### ISSUE TITLE
Assertion failing in PLNUnitTester

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#1004]
@sebastianruder - the latest update you made to test_rules_new.py is producing an error when the unit tests are ran on Buildbot, could you take a look at it?

[link](https://github.com/opencog/opencog/blob/1de2470fe2b5901869d9711dd589491be8ae310f/tests/python/test_pln/test_rules_new.py#L232)

```
test_all (test_rules_new.PLNUnitTester) ... FAIL
```

```
======================================================================
FAIL: test_all (test_rules_new.PLNUnitTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/opencog_master/build/tests/python/test_pln/test_rules_new.py", line 87, in test_all
    self.run_file(testFile)
  File "/buildbot/opencog_master/build/tests/python/test_pln/test_rules_new.py", line 253, in run_file
    self.verify_result()
  File "/buildbot/opencog_master/build/tests/python/test_pln/test_rules_new.py", line 232, in verify_result
    self.assertTrue(allPredictedItemsExist and allItemsWerePredicted)
AssertionError: False is not true
```

**Comment by inflector** [comment]
@cosmoharrigan I just updated this test for an issue with it failing with Linas, and it definitely passes on the buildbot. See: http://buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/277/steps/test/logs/stdio

So you can close this one, if you concur.

**Comment by cosmoharrigan** [comment]
Thanks @inflector.
