### ISSUE TITLE
Disk killing /tmp/pln.log

### ISSUE THREAD

**Issue by tpsjr7** [opencog/opencog#1082]
I was following the tutorial at http://wiki.opencog.org/w/Using_PLN_in_PyCharm

After a minute or so after running the command in the opencog shell

"agents-start deduction_agent.DeductionAgent"

Got a notification that my disk was going to fill up. I found /tmp/pln.log had grown to 5GB before I killed it.

**Comment by cosmoharrigan** [comment]
Closing: the referenced version is deprecated by the new rule engine version. Wiki page redirected also.
