### ISSUE TITLE
Deletion of Battery not communicated to Planner

### ISSUE THREAD

**Issue by Nemquae** [opencog/opencog#1096]
This is probably a clerical error on the Unity3D side like the other issues connecting to the planner, but since there's no more errors in the log or other indications as to the culprit, here's the output of the Planner after we finish the first plan to eat the battery:

OCPLANNER_DEBUG:Goalgame: EnergyDemandGoal

Debug planning step 1: Selected subgoal :State: EnergyDemandGoal ( (id_OAC_AGI_Robot,pet) ) = true
Debug planning step 1: Selected rule :eatFoodtoAchieveEnergyDemand
Debug: find ungrounded variable : ($entity_var0,undefined)
Debug: find ungrounded variable : ($entity_var0,undefined)
Debug: find ungrounded variable : ($entity_var0,undefined)
Debug: groundARuleNodeBySelectingNonNumericValues() is finding candidate groups...
CandidateGroup 1
($entity_var0,undefined)= (id_-4162076,object)
Fitness score = 200
Debug: groundARuleNodeBySelectingNonNumericValues() found candidate group number totally: 1
Debug planning step 1: All Variable bindings for rule :eatFoodtoAchieveEnergyDemand
($entity_var0,undefined)= (id_-4162076,object)
($entity_var1,undefined)= (id_OAC_AGI_Robot,pet)
Debug planning step 1: All effects for rule :eatFoodtoAchieveEnergyDemand
Effect  1: State: EnergyDemandGoal ( (id_OAC_AGI_Robot,pet) )
           [value changed]:  = false -> = true
Effect  2: State: holder ( (id_-4162076,object) )
           [value changed]:  = (id_OAC_AGI_Robot,pet) -> = (none,none)
Effect  3: State: exist ( (id_-4162076,object) )
           [value changed]:  = true -> = false
Debug planning step 1: All preconditions for rule :eatFoodtoAchieveEnergyDemand
Precondition  1: depth: 00 State: exist ( (id_-4162076,object) ) = true is satisfied :)
Precondition  2: depth: 01 State: is_edible ( (id_-4162076,object) ) = true is satisfied :)
Precondition  3: depth: 02 State: holder ( (id_-4162076,object) ) = (id_OAC_AGI_Robot,pet) is unsatisfied :(

Debug planning step 2: Selected subgoal :State: holder ( (id_-4162076,object) ) = (id_OAC_AGI_Robot,pet)
Debug planning step 2: Selected rule :pickupObjecttoHoldIt
Debug: groundARuleNodeBySelectingNonNumericValues() is finding candidate groups...
Debug: groundARuleNodeBySelectingNonNumericValues(): There is no non numeric variable in this rule. Doesn't need to be grounded!
Debug planning step 2: All Variable bindings for rule :pickupObjecttoHoldIt
($entity_var0,undefined)= (id_OAC_AGI_Robot,pet)
($entity_var1,undefined)= (id_-4162076,object)
Debug planning step 2: All effects for rule :pickupObjecttoHoldIt
Effect  1: State: holder ( (id_-4162076,object) )
           [value changed]:  = (none,avatar) -> = (id_OAC_AGI_Robot,pet)
Debug planning step 2: All preconditions for rule :pickupObjecttoHoldIt
Precondition  1: depth: 020 State: is_pickupable ( (id_-4162076,object) ) = true is satisfied :)
Precondition  2: depth: 021 State: Distance ( (id_OAC_AGI_Robot,pet), (id_-4162076,object) ) < 1.5 is satisfied :)

OCPlanner::Planning success! Total steps = 2, Cost time = 12ms

RuleNode:pickupObjecttoHoldIt Action:grab
 Rule node dept = 02
Step No.1: grab(id_-4162076,object)

RuleNode:eatFoodtoAchieveEnergyDemand Action:eat
 Rule node dept = 0
Step No.2: eat(id_-4162076,object)
OCPlanner found a plan: 1 for the selected demand goal:(EvaluationLink (stv 0.996929 0.001248)
  (PredicateNode "EnergyDemandGoal") ; [81]
) ; [82]

Something edible was reported!!

Debug: add None Block Entitye: id_-4254224
current action (ExecutionLink (stv 1.000000 1.000000)
  (GroundedSchemaNode "grab") ; [141]
  (ListLink (stv 1.000000 1.000000)
    (ObjectNode "id_-4162076") ; [14892]
  ) ; [18365]
) ; [18366]

... And then the next plan starts where the character attempts to grab and eat the non-existent battery.

Also, is the integrity (safety) demand goal active right now?  Plans to move toward the hearth never execute, even when no batteries are present...

**Comment by linas** [comment]
closing; this bug concerns obsolete code and is likely to never be fixed.
