### ISSUE TITLE
REST module can't get an updated content of the atomspace

### ISSUE THREAD

**Issue by misgeatgit** [opencog/opencog#1147]
If one starts the REST API and does http://localhost:5000/api/v1.1/atoms request,  The REST server returns the  content of the atomspace. However, any later modification made to the atomspace after starting the REST server is not being reflected in the subsequent http://localhost:5000/api/v1.1/atoms requests.

Note that the issue is generic to any other python modules and not particular to the REST server.Here https://github.com/misgeatgit/opencog/blob/restapi-bug-reproduce/opencog/python/web/api/restapi_bug_sscce.py is a simple python module with an http server to reproduce the bug without involving the REST API.You can use it by adding restapi_bug_sscce in your PYTHON_PRELOAD param in opencog.conf. or pulling https://github.com/misgeatgit/opencog/tree/restapi-bug-reproduce.

**Comment by misgeatgit** [comment]
Sorry, the problem was actually particular to the REST implementation. process forking seems to copy the atomspace. I have made a pull request to fix this problem but It recreates the problem addressed by commit 36d9c895353f71e9e50b9ad6ebae9e1c2f8eda9e.

**Comment by cosmoharrigan** [comment]
@misgeatgit What do you think happens during creation of a daemonic child process that causes that symptom, which doesn't occur using a thread? Is there anything about how the atomspace reference is passed in atomspace_details.pyx that you mention above that could be modified so that the daemonic child process would receive a reference to the correct atomspace?

**Comment by misgeatgit** [comment]
@cosmoharrigan  According to the discussion http://stackoverflow.com/questions/10721915/shared-memory-objects-in-python-multiprocessing supports my guess. The solution would be making the atomspace a shared object between the python processes(https://docs.python.org/2/library/multiprocessing.html#sharing-state-between-processes). I will do that.

**Comment by bgoertzel** [comment]
Ah... that sounds promising ...

On Sun, Jan 4, 2015 at 10:39 AM, Misgana Bayetta <notifications@github.com>
wrote:

> @cosmoharrigan <https://github.com/cosmoharrigan> According to the
> discussion
> http://stackoverflow.com/questions/10721915/shared-memory-objects-in-python-multiprocessing
> supports my guess. The solution would be making the atomspace a shared
> object between the python processes(
> https://docs.python.org/2/library/multiprocessing.html#sharing-state-between-processes).
> I will do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1147#issuecomment-68618409>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
Based on what I read in the various explanations, you can only share Value and Array, and not other objects.  Several of the stackoverflow posts point out that python shared memory IPC is very hard.  

Why not revert the commit that uses fork instead of threads?  What was wrong with using threads? If the only point of that commit was to honor the cogserver shutdown command, then it would surely be easier just to just figure out how to handle shutdown...

**Comment by linas** [comment]
@cosmoharrigan you may want to review the difference between forking and threading. In threads, memory is always shared. In forked processes, memory is never shared.  After a fork, you simply get a snapshot of what was, at the time of the fork.  In this case, after a fork, you simply get a snapshot of the atomspace, as it was, at that time. Whatever changes are made by either the parent or the child are completely isolated from each-other: these two atomspaces from then on evolve as completely independent entities, having no knowledge of each-other's existence.

**Comment by cosmoharrigan** [comment]
@misgeatgit #1176 merged; perhaps you want to try making the thread into a daemon thread? http://stackoverflow.com/questions/190010/daemon-threads-explanation

**Comment by linas** [comment]
Bingo. Daemon thread sounds like exactly the right thing to me.

**Comment by cosmoharrigan** [comment]
#1180 merged; now the REST API runs in a daemon thread, and the shutdown command works properly (and the same atomspace is shared, addressing the original topic of this issue).

@misgeatgit Thank you for identifying and fixing this issue!

**Comment by bgoertzel** [comment]
Woo hoo !! thanks Misgana

Cosmo, are there further urgent python bugs for Misgana to fix?   If not he
will go back to time-slicing between PLN and fixing other small python bugs

Misgana, does this fix the visualizer issues as well?   If not that remains
urgent...

thx
ben

On Tue, Jan 6, 2015 at 1:36 PM, Cosmo Harrigan <notifications@github.com>
wrote:

> #1180 <https://github.com/opencog/opencog/pull/1180> merged; now the REST
> API runs in a daemon thread, and the shutdown command works properly (and
> the same atomspace is shared, addressing the original topic of this issue).
>
> @misgeatgit <https://github.com/misgeatgit> Thank you for identifying and
> fixing this issue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1147#issuecomment-68910013>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by misgeatgit** [comment]
@bgoertzel the visualizers problem was caused by the REST API. It should work now.

**Comment by bgoertzel** [comment]
OK, great... let's obviously have someone test that to be sure

Tsega, can you please download the latest OPenCog version and see if it
fixes the visualizer issues?  Thanks!

On Tue, Jan 6, 2015 at 9:10 PM, Misgana Bayetta <notifications@github.com>
wrote:

> @bgoertzel <https://github.com/bgoertzel> the visualizers problem was
> caused by the REST API. It should work now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1147#issuecomment-68969119>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by cosmoharrigan** [comment]
> Cosmo, are there further urgent python bugs for Misgana to fix?   If not he
will go back to time-slicing between PLN and fixing other small python bugs

@bgoertzel None immediately come to mind that would be classified as "urgent". I'll let you know if any others come up when I talk with Jim.

**Comment by bgoertzel** [comment]
OK, thanks ;)

On Tue, Jan 6, 2015 at 9:16 PM, Cosmo Harrigan <notifications@github.com>
wrote:

> Cosmo, are there further urgent python bugs for Misgana to fix? If not he
> will go back to time-slicing between PLN and fixing other small python bugs
>
> @bgoertzel <https://github.com/bgoertzel> None immediately come to mind
> that would be classified as "urgent". I'll let you know if any others come
> up when I talk with Jim.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1147#issuecomment-68969633>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by misgeatgit** [comment]
>K, great... let's obviously have someone test that to be sure
@bgoertzel  it works on my machine.
