### ISSUE TITLE
Problem with coding AndRule in scm

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1159]
I'm having a problem coding the AndRule because the clauses in pattern are not connected.

To reproduce the problem you may do as follows::

```
guile> (load "../opencog/reasoning/RuleEngine/rules/pln/and.scm")
(load "../opencog/reasoning/RuleEngine/rules/pln/and.scm")
(ConceptNode "B" (stv 0.60000002 0.99999982))

guile> (cog-bind pln-rule-and)
(cog-bind pln-rule-and)
Backtrace:
In ice-9/boot-9.scm:
 157: 10 [catch #t #<catch-closure 33f18e0> ...]
In unknown file:
   ?: 9 [apply-smob/1 #<catch-closure 33f18e0>]
In ice-9/boot-9.scm:
 157: 8 [catch #t #<catch-closure 33f17c0> ...]
In unknown file:
   ?: 7 [apply-smob/1 #<catch-closure 33f17c0>]
   ?: 6 [call-with-input-string "(cog-bind pln-rule-and)\n" ...]
In ice-9/boot-9.scm:
2320: 5 [save-module-excursion #<procedure 3675120 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 4 [read-and-eval #<input: string 36110d0> #:lang ...]
  37: 3 [lp (cog-bind pln-rule-and)]
In unknown file:
   ?: 2 [opencog-extension cog-bind (#)]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 3643440 at ice-9/boot-9.scm:97:6 (thrown-k . args)> #{C++ exception}# ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 33f1780> #{C++ exception}# ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure cog-bind: Pattern is not connected! Found 2 components:
Connected component 0 consists of ----------------: 
(VariableNode "$A" (av 0 0 0) (stv 1.000000 0.000000)) ; [57]
Connected component 1 consists of ----------------: 
(VariableNode "$B" (av 0 0 0) (stv 1.000000 0.000000)) ; [58]
 (/home/nilg/OpenCog/opencog/opencog/query/VirtualMatch.cc:365)
ABORT: C++ exception
```

I don't know how to work around that. Do I need to hack the pattern matcher to support non connected clauses? Or does that mean I don't need the pattern matcher, but then how to integrate the rule in PLN which uses the pattern matcher?

**Comment by ngeiswei** [comment]
Well, it was definitely educational...

So what I've done is merely re-append all clauses in PatternMatch::validate_clauses, disable the _component.size() == 1 check, and disable the _virtuals.empty() case in PatternMatch::do_match, so it goes directly in the more general case handling virtual links.

It works fine, I'm just not yet entirely sure how to restore the old behavior for the default callback, and keep that one for the PLN callback.

What I suggest is to move PatternMatch::validate_clauses as a callback, so DefaultPatternMatchCB::validate_clause be the same old code and AttentionalFocusCB::validate_clauses would contain the new hack.

I'm confident it's gonna work, I'll go ahead and push it on my branch. However I'm just not sure it is the very best way, maybe you've got some better idea.

Thanks.

**Comment by ngeiswei** [comment]
Hmm, the validate_clauses CB would still have to return the _virtual and _nonvirtual lists, it's possible of course, but it's getting less elegant. I guess there's a better way. I need to meditate on that...

**Comment by ngeiswei** [comment]
I think I found the best compromise... I'm keeping PatternMatch::validate_clauses, still doing the job of splitting clauses into virtual and non virtual clauses, as well as doing what seems to be mandatory checking, then it calls the validate_clauses CB part for the rest. :+1:

**Comment by linas** [comment]
closing. This is fixed.  End note: the PM now explores all possible combinations. Under certain circumsances, it will print a warning if it seems that this is not what the user intended.
