### ISSUE TITLE
AllPythonModuleTest failing

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1162]
MathUTest and  AllPythonModuleTests failiing.

http://buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/56/steps/test/logs/stdio

Logs = http://buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/56/steps/test/logs/testlog

**Comment by inflector** [comment]
This was fixed with #1281
