### ISSUE TITLE
10 tests failed out of 142

### ISSUE THREAD

**Issue by beew** [opencog/opencog#1166]
Hi,

I tried to build opencog with the ocpkg script and make test failed for 10 tests

38:SCMExecutionUTest
61:SudokuUTest
63:RuleUTest
69:MathUTest
75:Cython
77:CythonGuile
79:CythonMoses
80:AllPythonModuleTests
85:HebbianCreationModuleUTest
108:NeighborSamplingUTest

The relevant sections of the build log is at https://gist.github.com/beew/c0c379474899df276b65

My OS is Ubuntu 14.04.1 64 bit

Please advise, thanks.

**Comment by beew** [comment]
Hi, Amen,

Sorry for being dense, I looked at your wiki entry but it is still not clear to me how to proceed after
"(sudo?) docker run --rm  -p 17001:17001 -p 5000:5000 -v $PWD:/home/opencog -it opencog"

Do you then cd into the docker subfolder and run cmake .. and proceed as usual?

After that how do you invoke the container for opencog?

**Comment by AmeBel** [comment]
Hi,
i have updated the wiki. Let me know if that is not clear .
Thanks, for pointing out the insufficient instruction on the wiki :-)

**Comment by beew** [comment]
Hi Amen,
Thanks for the update!
