### ISSUE TITLE
buildbot: Boost::math not installed.

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1178]
buildbot is not running NeighborSamplingUTest (see e.g. http://buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/70/steps/test/logs/stdio) normally this would be test number 109.

Its not run due to this: 
```
# requires boost::math; don't build if not found.
IF(Boost_MATH_C99_FOUND)
   ADD_CXXTEST(NeighborSamplingUTest)
   TARGET_LINK_LIBRARIES(NeighborSamplingUTest
      moses
      comboreduct
      cogutil
   )
ENDIF(Boost_MATH_C99_FOUND)
```

This is set in the main CMakefile if Boost::math is found.

**Comment by linas** [comment]
I just pushed a patch at adds boost-math.  It needs to be deployed to the buildbot ...

**Comment by AmeBel** [comment]
buildbot is running the test, but it is failing 

buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/84/steps/test/logs/stdio

**Comment by linas** [comment]
Passes for me, but on the buildbot, I see this:

In NeighborSamplingUTest::test_sample_from_neighborhood:
/home/buildslave/slave/opencog_master_trusty/build/tests/learning/moses/NeighborSamplingUTest.cxxtest:255: Error: Assertion failed: (sample_size == sampled_size) || (sample_size-1 == sampled_size) || (sample_size-2 == sampled_size)

need a sparate bug rport for this.
