### ISSUE TITLE
Can't run the cogserver in a debugger

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1179]
1) I compile OpenCog in Debug mode

2) launch the cogserver under gdb
```
cd build-debug/opencog/server
gdb cogserver
(gdb) r  -c ../../../lib/opencog.conf
```

3) Previously I've set a breakpoint at the first line of main's CogServerMain.cc, I step at each instruction till l.203
```
    cogserve.loadSCMModules(DEFAULT_MODULE_PATHS);
```
and get those errors
```
(gdb) 
[New Thread 0x7fffe7fff700 (LWP 18031)]
[New Thread 0x7fffe77ae700 (LWP 18032)]
(gdb) 
(gdb) 
Single stepping until exit from function GC_suspend_handler,
which has no line number information.
(gdb) 
Single stepping until exit from function __errno_location@plt,
which has no line number information.
(gdb) 
Cannot find bounds of current function
```

Any idea? Has anyone attempted to run cogserver under gdb and knows what to do?

**Comment by misgeatgit** [comment]
It works for me after  handling SIGPWR  and SIGXCPU signals as mentioned in this #471

**Comment by ngeiswei** [comment]
Excellent, thanks!
