### ISSUE TITLE
ExecutionLink should be ExecutionOutputLink in pattern matcher

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1181]
It's not a practical issue, just an inconsistence, but I'd rather fix it now than later before this inconsistence turns into something broken in practice.

According to

http://wiki.opencog.org/w/ExecutionLink
http://wiki.opencog.org/w/ExecutionOutputLink

the ExecutionLink should be ExecutionOutputLink in the expression passed to the pattern matcher. 

So for instance
```
    BindLink
        ListLink $A
        ImplicationLink
            $A
            ExecutionLink
                GroundedSchemaNode "scm: pln-formula-not"
                ListLink $A
```
should be
```
    BindLink
        ListLink $A
        ImplicationLink
            $A
            ExecutionOutputLink
                GroundedSchemaNode "scm: pln-formula-not"
                ListLink $A
```

As you may notice ExecutionLink is supposed to point to the output of the function (third argument in the outcoming set), unless it has no output, only side effect. Whereas ExecutionOutputLink denotes the output itself. I think in the case of the pattern matcher, it's really the output of the function that is denoted, so we should use ExecutionOutputLink.

If you agree this is right I can operate the change, just let me know we're in agreement.

**Comment by linas** [comment]
I have no clue what an ExecutionOutputLink is supposed to be --  the wiki page for it is utterly incomprehensible to me.  Seriously -- a return value ??  How can a link possibly have a "return value", or any kind of output at all?  I can imagine that maybe some sort of substitution could take place, but its not clear to me where or how that could happen.  We certainly don't have any code that does this.

In particular, the current code implements a pure side-effect.  We have no concept of "eval" in opencog.

**Comment by ngeiswei** [comment]
But the scheme code does not have a side effect it return an atom, exactly what ExecutionOutputLink expect.

The way I think of ExecutionOutputLink is

```
SimilarityLink <1>
    NumberNode 5
    ExecutionOutputLink
        +
        ListLink
            NumberNode 3
            NumberNode 2
```
where + takes 2 NumberNode and return the NumberNode corresponding to their sum.

**Comment by ngeiswei** [comment]
The notion of return value of a link only needs to exist at a semantic level, defined by the kind of hypergraph I give in example. Then, practically, an agent, like say the pattern matcher, might operate substitutions according to this semantics.

**Comment by linas** [comment]
OK, on closer review: You are saying that it should be the following:
```
   ExecutionLink
        Inputs
        Output
```
whereas
```
    ExecutionOutputLink
          Inputs
```
That is, the "output" for this second graph does not appear at all in its outgoing set, while for the first one it does.  I suppose that's reasonable.  The wiki is still as clear as mud...

A better name would be nice. I understand that ExecutionOutput has some historical precedent (and maybe its in the books, too?) but it seems strange that its the name of the link that doesn't actually have the output.  ExecutionFreeLink, maybe? ExecutionRumpLink ? ExecutionStumpLink?  ExecutionFunctionLink ?

**Comment by ngeiswei** [comment]
Yeah I also found the name confusing at first, but on second look, it is the link corresponding semantically to the output of the execution so maybe ExecutionOutputLink isn't so bad.

**Comment by ngeiswei** [comment]
I'm reviewing the code further in particular
```
ExecutionLink::do_execute
```
It really matches the semantics of an ExecutionOutputLink. So I'll proceed in renaming all that.

**Comment by ngeiswei** [comment]
Hmm, those ExecutionLinks are spread all over the code. I'm becoming hesitant to do the change. On the other hand, I'm almost sure this stuff is gonna bite us in the future, the earlier it's fixed, the better, I think.

I'm letting that aside for now, waiting for further feedback and having a better overview of the use of the ExecutionLink across the code.

**Comment by bgoertzel** [comment]
Nil,

The fact that, in the code, Linas used the name "ExecutionLink" for what my
books called "ExecutionOutputLink" has been known to me for a long time.

I will shortly put the text of all my OpenCog-related books on the wiki
site (so they can be linked with the more code-related docs and with the
code itself); Hruy is helping me wiki-fy them.   This will make the
confusion more apparent, I would say...

-- Ben

On Wed, Jan 7, 2015 at 4:55 AM, ngeiswei <notifications@github.com> wrote:

> Hmm, those ExecutionLinks are spread all over the code. I'm becoming
> hesitant to do the change. On the other hand, I'm almost sure this stuff is
> gonna bite us in the future, the earlier it's fixed, the better, I think.
>
> I'm letting that aside for now, waiting for further feedback and having a
> better overview of the use of the ExecutionLink across the code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1181#issuecomment-69000337>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
My attention span is ... well, its not short, but my patience is thin.  If I can't find clear, concise, accurate documentation for something (e.g. execution output links) in a few minutes, I'll just go my own way.   This is why I insist of clear, well-organized wikis and READMEs and text that gets to the point immediately ... I just don't have the patience to wade through mountains of material in search for a detail.  This is why ExecutionOutputLink is mis-named.

(I don't think I'm unique .. I love wikipedia because it caters to my impatient attention span.  Clearly, it hits the spot for many others, as well. Ergo, I'm not unique. ).

**Comment by ngeiswei** [comment]
I've submitted a pull request for that issue https://github.com/opencog/opencog/pull/1227
and updated the wikipages accordingly

http://wiki.opencog.org/w/ExecutionLink
http://wiki.opencog.org/w/GroundedSchemaNode
http://wiki.opencog.org/w/ExecutionOutputLink
