### ISSUE TITLE
Implement fuzzy subhypergraph matching

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1198]
Since the same (or very similar) information may be expressed in natural language in many different ways, question-answering must be able to handle the case where a NL query as entered by a dialogue partner, and the commonsensical answer to this query as “read” by OpenCog from some text source, have different syntactic expressions.

Ideally this would be dealt with via PLN or other reasoning that fully “understands” the content of the query and answer sentences. However, as a temporary means – and as a long-term mechanism for handling cases where the language involves is not fully understood – it will be useful for having a tool to handle query/answer matching based on “fuzzy Atom-subhypergraph matching.” Such a tool will also be useful more broadly for other applications requiring fuzzy matching of Atomspace hypergraphs.

A tool of this nature was implemented in the Novamente Cognition Engine in 2004-2005, using a Dynamic Programming based algorithm, but this is not necessarily the ideal algorithm to use going forward.

So what we want is a function of the conceptual form
``` 
float findApproximateMatches(Atom_subgraph A)
```

That is reasonably fast for Atom subgraphs with dozens of Atoms, plus a reasonably efficient algorithm that, given A, searches the Atomspace and finds B that are close matches to A. The process has to be fast enough to be used real-time within natural language dialogue, i.e. less than half a second or so.

An outline of one possible algorithm for this is given in: [Approximate Pattern Matching](http://wiki.opencog.org/w/Approximate_Pattern_Matching)

**Comment by linas** [comment]
I believe that this is doable using the existing pattern matcher.  Just implement callbacks that are suitably lenient in what they choose to match.  FWIW, the 'optional clause' utility should be useful for this.
