### ISSUE TITLE
Integration with game character control

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1205]
Tweaking the various speech act schema and associated hard-coded dialogue rules for appropriateness in the game context.

Subtle issues here would seem to be:
- Goals specific to the game world context, and their connection with speech acts
- Articulation of descriptions of things in the game world environment
- Articulation of events, processes and sequences in the game world

**Comment by linas** [comment]
This is almost a duplicate of #1204 ...

**Comment by linas** [comment]
closing as duplicate of #1204
