### ISSUE TITLE
 Getting some backing store working effectively

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1209]
This is not really an NLP task, but is listed here due to its importance for unsupervised language learning.
For unsupervised learning it will be very valuable to be able to rapidly load (small or large) pieces of a saved AtomSpace according to a flexible set of queries.

This could be done by extending the Postgres Backing Store's API, or by integrating some other backing store and writing an appropriate API for it and customizing it appropriately. 

This will include
- [ ] Remove the NLP_HACK from persist/sql/PersistModule.cc
- [x] Dockerizing the existing postgres implementation

**Comment by linas** [comment]
closing, this is incoherent, appears to be a automated script that went wild on a trello board.

**Comment by AmeBel** [comment]
@linas what is the nlp_hack for

**Comment by linas** [comment]
what it says here: https://github.com/opencog/opencog/blob/master/opencog/persist/sql/SQLPersistSCM.cc#L106  I don't know that I can say much more, than what it says there.

I'm guessing that there is some code that is sloppy about what it tries to save to the database.  I must have discovered this by accident, by looking at the database contents. I guess it must have been easier to write this 'hack' than to do something more elegant.

FWIW, the hack seems harmless: it seems very unlikely that you would ever want to store any of these atom types in the database, right? Or might PLN try to store bindlinks?

I plan to start helping Rohit a bit later in the year, and might then be able to find why these were needed.  if I `grep store-atom opencog/nlp/learn/*`  I see a bunch of uses,  But none of these are trying to store any of the unwanted types, so I'm not sure what is... if anything. Maybe nothing is...

**Comment by bgoertzel** [comment]
Saving BindLinks sounds useful to me...

For instance, "advanced queries" from the visualizer are formalized as
BindLinks for submission to the Pattern Matcher.   If we want visualizer
users to be able to save queries and then reload them for later use, they
should be save-able in the BackingStore...

Unless I misunderstand something...


On Thu, Mar 12, 2015 at 8:35 AM, Linas Vepštas <notifications@github.com>
wrote:

> what it says here:
> https://github.com/opencog/opencog/blob/master/opencog/persist/sql/SQLPersistSCM.cc#L106
> I don't know that I can say much more, than what it says there.
>
> I'm guessing that there is some code that is sloppy about what it tries to
> save to the database. I must have discovered this by accident, by looking
> at the database contents. I guess it must have been easier to write this
> 'hack' than to do something more elegant.
>
> FWIW, the hack seems harmless: it seems very unlikely that you would ever
> want to store any of these atom types in the database, right? Or might PLN
> try to store bindlinks?
>
> I plan to start helping Rohit a bit later in the year, and might then be
> able to find why these were needed. if I grep store-atom
> opencog/nlp/learn/* I see a bunch of uses, But none of these are trying
> to store any of the unwanted types, so I'm not sure what is... if anything.
> Maybe nothing is...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1209#issuecomment-78403082>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
If you really want to, just undef line 117  I don't think that will hurt anything, except maybe performance of gathering corpus statistics. I'd have to explore this later.

**Comment by linas** [comment]
Oh .. 

I am starting to remember...  The corpus-statistics-gathering code does NOT store any of these problem types, when it is running automatically. It just runs and stores what it needs to.  However, in early versions of the code, I think what I was doing was letting it run, and then manually storing *everything*, after a few hours or days of runtime.  I later discovered that I had saved a bunch of junk along with the real data.  The hack was to stop this from happening.

I think the long -term plan was this: create a new command called "store-absolutely-everything-except-these-types". I started writing the code for this, got bored, distracted, busy, decided the hack was easier.  So the task is really to finish implementing this command.  To be symmetric, perhaps there should be a "load-absolutely-everything-except-these-types" command.

**Comment by AmeBel** [comment]
thanks, will start on adding those commands

**Comment by linas** [comment]
Oh, wait .. that last comment is not entirely correct either. Actually its kind of wrong. So, as I look through the code, I see this:

https://github.com/opencog/opencog/blob/master/opencog/atomspace/AtomSpaceImpl.cc#L129
and this:
https://github.com/opencog/opencog/blob/master/opencog/atomspace/AtomSpaceImpl.cc#L106
and line 169 and line 198

So -- here is what is happening, here is the problem being solved.  When you go to add an atom to the atomspace, the atomspace thinks to itself "gee do I already have that atom in the database? If so, then I should fetch that atom". There are two reasons for doing this: to get at it's UUID (so that all identical atoms have identical UUID's) and to get its TV.  So .. this seems to make sense, right?

When parsing a document, one generates large quantities of WordInstanceNodes, which will be deleted seconds later.  However, for a few seconds, they live in the atomspace.  If the WordInstanceNode is not ignored, then the atomspace will look for it in the backend.  Of course, its not there -- but, in the meantime, it wastes some milliseconds waiting for the negative reply from the database.   

The optimization is obvious: if we know, a priori, that the  atom could never be there, then we shouldn't waste time looking for it.  I'm guessing that this has a large performance impact, simply because there are a lot of WordInstancenodes being constantly generated.

**Comment by linas** [comment]
Thus, this has nothing to do with bulk-save and bulk-restore.  So the  "store-absolutely-everything-except-these-types"  command is probably not needed. (I don't need it).

What is needed is a scheme function that will add a type to the ignore-list.  That way, before starting parsing, before starting R2L, or anything else that generates lots of temporary atoms, we could just set the ignore-list to the types of these temporary atoms.  

Just add code to here:
https://github.com/opencog/opencog/blob/master/opencog/persist/sql/SQLPersistSCM.cc#L155
say, call it `sql-ignore-atom-type`  and then add code to here

https://github.com/opencog/opencog/tree/master/opencog/nlp/learn

say, setup.scm  which they just has
```
(sql-ignore-atom-type 'WordInstanceNode)
(sql-ignore-atom-type 'ParseNode)
etc.
```

I could do this last part, as long as I don't forget.   We will have to tell Rohit to use this, too. He won't know.  I'll forget.

**Comment by linas** [comment]
To be clear: if you start using R2L with the database, then you will also want to ignore all of the temporary types, or suffer a slowdown.

Another possible policy is to always ignore everything.  That is, just disable https://github.com/opencog/opencog/blob/master/opencog/atomspace/AtomSpaceImpl.cc#L106 . Then every algorithm that wanted something out of the database would always have to explicitly ask for it.

I'd have to think about that. I can't tell is that is a good idea or a bad idea. We might need to adjust the API's to explicilty support this mode.

**Comment by AmeBel** [comment]
Closing, as the features had been implemented . Details [`(use-modules (opencog persist))`](https://github.com/opencog/atomspace/blob/2a33ae4c85161fa49a7f697ca76f6648f3ec14cd/opencog/scm/opencog/persist.scm)
