### ISSUE TITLE
node_match, link_match, etc have confusing name

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1220]
The naming DefaultPatternMatchCB::node_match, etc, is really confusing as it returns false when it actually matches and true when it doesn't.

I do understand that unix functions do historically return 0 when it does well and != 0 otherwise as a code error, but here we're dealing with C++ bool type, it's really counterintuitive to return false when it matches.

I suggest to either

1. rename them node_mismatch, link_mismatch, ...

2. return true when it matches, false when it doesn't.

3. do nothing.

I do understand that other functions like Implicator::grounding works the same way, return false when the grounding succeeds. It's also confusing but at least it doesn't blatently contradict the method name.

1. is gonna make the method names 3 char longer, I don't like that.

2. is opening the risk to introduce bugs, I don't like that.

3. the confusion still remains, I don't like that either.

Help me!

**Comment by williampma** [comment]
I agree.  I had to constantly remind myself of this fact when I was writing the callbacks in order to avoid making a mistake (and I still ended up making one mistake and returning the opposite value).

**Comment by ngeiswei** [comment]
OK, this makes me want to go with 2. It's a change that requires more care but the unity tests seem good enough. What I might do is mess up those functions (i.e. return true when it should return false) and see if the unit test can detect it, if it can then I'll do ahead and make the change. If it can't then I'll write more unit test.

Anyway, I won't do that today, but if you have any arguments against that, please speak out.

**Comment by linas** [comment]
Yes. Its a design flaw that seemed reasonable at the time ...
