### ISSUE TITLE
Too many open files (copied from unity3d-opencog-game)

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1240]
This is an issue copied from https://github.com/opencog/unity3d-opencog-game/issues/69 as it belongs on opencog.

Spydrouge commented on Dec 24:

After running the game for about any length of time, with or without batteries, the opencog back end will print out this:

```
Backtrace:
In ice-9/boot-9.scm:
157: 1 Exception thrown while printing backtrace:
ERROR: in procedure load-objcode: Too many open files

ERROR: in procedure apply-smob/1:
ERROR: in procedure pipe: Too many open files
scm_unprotect_object called on unprotected object
```
And promptly it will hang.

**Comment by ngeiswei** [comment]
I copy/paste a comment from brett79 as it relevant:

Preliminary investigation. Drop a battery, load the robot, watch the robot get the battery, drop another battery, watch the robot get the battery... repeat. The error seems to appear repeatedly around "cycle = 160".
Using the windows unity viewer, and ubuntu in a virtual machine. I 'paused' the unity viewer (alt-tab away from viewer), around 'Cycle=148'.
$ lsof > lsof.log

There seem to be over 10000 entries from 'oac':

$ grep -c oac lsof.log
13908
COMMAND    PID  TID       USER   FD      TYPE             DEVICE SIZE/OFF     NODE NAME
...
oac       3539 3549      bwolf  329w     FIFO                0,8      0t0    62263 pipe
oac       3539 3549      bwolf  330r     FIFO                0,8      0t0    62264 pipe
oac       3539 3549      bwolf  331w     FIFO                0,8      0t0    62264 pipe
oac       3539 3549      bwolf  332r     FIFO                0,8      0t0    62265 pipe
oac       3539 3549      bwolf  333w     FIFO                0,8      0t0    62265 pipe
oac       3539 3549      bwolf  334r     FIFO                0,8      0t0    62266 pipe
...

Just posting this here in case someone with a little more knowledge knows where this may be coming from. I don't believe it is a memory error, but rather 'Too many open files'.
Cheers, BW.

The other comments are irrelevant, IMO.

**Comment by ngeiswei** [comment]
Now my 2 cents: I thought it was related to commits

https://github.com/opencog/opencog/commit/d6cce6623dd5aa8a3cf22737e6887407a3ecde46
https://github.com/opencog/opencog/commit/c34494d755a12df6ce976b8111b51ef7d7868e79

so I reverted them locally, but still exactly the same problem.

**Comment by ngeiswei** [comment]
Now my 2 cents: I thought it was related to commits

https://github.com/opencog/opencog/commit/d6cce6623dd5aa8a3cf22737e6887407a3ecde46
https://github.com/opencog/opencog/commit/c34494d755a12df6ce976b8111b51ef7d7868e79

so I reverted them locally, but still exactly the same problem.

**Comment by linas** [comment]
I hope its not guile ... but just in case it is:  pipes are created near here: https://github.com/opencog/opencog/blob/master/opencog/guile/SchemeEval.cc#L50  and are closed here: https://github.com/opencog/opencog/blob/master/opencog/guile/SchemeEval.cc#L107  Pipes are documented here: http://www.gnu.org/software/guile/manual/html_node/Ports-and-File-Descriptors.html

The pipeno is an int and can be printed out as an int.  If it is at fault, then you will find it in /proc/<pid>/fdinfo and in /proc/<pid>/fd where pid is of course the pid of the cogserver.

**Comment by linas** [comment]
I just checked: `printf("duuude close pipeno: %d %d\n", _pipeno, scm_to_int(scm_fileno(_outport)));` prints plausible values for a plain-old cogserver w/o embodiment

**Comment by brett79** [comment]
Thanks Linas, that helped.
I've traced it to memory leaks in embodiement operational avatar controller. E.g. PsiActionSelectionAgent::executeAction() allocates "SchemeEval* evaluator = new SchemeEval(&atomSpace);" but there is no corresponding delete. Repeated calls were opening pipes, and they were not being closed because the object wasn't being destroyed. Eventually giving the 'too many files open' error.

I'm chainging the code to remove pointers for the local creation of an evaluator. This should help remove any further problems like this in the future. E.g. SchemeEval evaluator1(&atomSpace);

It appears to work. Just let me tidy it up and I'll submit a pull request.

**Comment by bgoertzel** [comment]
Thanks Brett!  This was a nasty and long-standing bug, I'm glad someone
finally chased it down ;)

On Sat, Jan 24, 2015 at 12:09 PM, Brett Ward <notifications@github.com>
wrote:

> Thanks Linas, that helped.
> I've traced it to memory leaks in embodiement operational avatar
> controller. E.g. PsiActionSelectionAgent::executeAction() allocates
> "SchemeEval* evaluator = new SchemeEval(&atomSpace);" but there is no
> corresponding delete. Repeated calls were opening pipes, and they were not
> being closed because the object wasn't being destroyed. Eventually giving
> the 'too many files open' error.
>
> I'm chainging the code to remove pointers for the local creation of an
> evaluator. This should help remove any further problems like this in the
> future. E.g. SchemeEval evaluator1(&atomSpace);
>
> It appears to work. Just let me tidy it up and I'll submit a pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1240#issuecomment-71299457>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
so can we close this bug report?

**Comment by ngeiswei** [comment]
I've tested it all works, thanks again Brett!

**Comment by WesagnDC** [comment]
Hi all, i'm getting the same bug till now.. i cant figure-out where the mess is happening. i'm new to this all and please, can anyone help me? find where is this happening inside embodiment and fix it! thanks!

Backtrace:
In ice-9/boot-9.scm:
157: 1 Exception thrown while printing backtrace:
ERROR: in procedure load-objcode: Too many open files

ERROR: in procedure apply-smob/1:
ERROR: in procedure pipe: Too many open files
scm_unprotect_object called on unprotected object![screenshot from 2015-02-23 16 46 07](https://cloud.githubusercontent.com/assets/9802182/6328742/8833a900-bb7b-11e4-9243-4326a38104d8.png)
