### ISSUE TITLE
guile module system

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1247]
The curent  guile implementation is almost ready to be converted into a module system.  The goal is to have the following work:
```
$ guile
guile> (use-modules (opencog opencog))
guile> (ConceptNode "asdf")
```
The above assumes that opencog has been installed in `/usr/local`.  If it hasn't been, then its a little more complicated:
```
$ export LTDL_LIBRARY_PATH= /build/opencog/guile
$ guile -L opencog/scm -L build
guile> (use-modules (opencog opencog))
guile> (ConceptNode "asdf")
```
To do this, need to create file `/opencog/scm/opencog/opencog.scm`  with contents somewhat like this:
```
(define-module (opencog opencog))
(load-extension "libsmob" "opencog_guile_init")   ;; this is why LTDL is needed.
```
Also needed is an '/opencog/scm/opencog/atomtypes.scm` with content similar to this:
```
(define-module (opencog atomstypes))
(load "opencog/learning/pln/pln_types.scm")
... etc....
(export ConceptNode)
(export ... etc)
```
Then, `make install` would install the above files to `/usr/local/share/opencog`  and some magic needed to put this into the guile search path...

**Comment by linas** [comment]
I think this can be done with 1 or 2 days of fiddling around and another 1-2 days of general cleanup and reorganization as needed.

**Comment by cosmoharrigan** [comment]
Wow.

**Comment by linas** [comment]
Never mind. Why do I bother. I did most of above in about an hour, and I just pushed it all out

**Comment by linas** [comment]
@cosmoharrigan  all that talk about "pythonic" made me think about "schematic" and I realized that by throwing the cogserver overboard, the above can be made to work.  fwiw, /examples/guile/basic.scm  should now work for you.

At some point in the future, I plan the following two "stupid computer tricks" : get the python prompt from scheme, ad get a scheme prompt from python.  One of the two should be possible by creating a modified version of /opencog/cython/opencog/PyScheme.cc to start the "shell", and vice-versa in the other direction.

**Comment by linas** [comment]
Just about everything described in the first comment is now done. So I could close this issue ... However, other modules are needed: probably a module for cog-bind being the highest priority, but also others.   So, for the moment, I leave this open as a to-do reminder to go farther, and modularize these other bits.

**Comment by williampma** [comment]
Should `opencog.scm` be loaded automatically in `opencog.conf`?  Right now the solution does not work for creating new modules within the cogserver scm shell, because `(opencog)` does not exist there.

Unless some of the C++ code changes in 1338aa02888875fa1f9e89baeba38a894d4e1c29 is undone.

**Comment by linas** [comment]
argh.

What you need to do is to touch all of the atom_types.script files, and
rebuild. Or just make clean and rebuilt.

The problem is that the old module stuff is still thee in the autogenerated
types.scm files in your build tree.

The CMakefile should have rebuilt these, but it doesn't.

--linas

**Comment by williampma** [comment]
No, I don't think that's it.  I have cleaned/rebuilt several times before.

What I wanted to do is, create a new file "test.scm":
```
(define-modules (newname stuff))
(cog-new-node 'ConceptNode "abc")
```
and then in the cogserver scheme shell do
```
(load "../path/to/test.scm")
```
this will complain because inside each scheme module, it does not know about the modules loaded outside.

My previous fixes allow me to do
```
(define-modules (newname stuff))
(use-modules (opencog))
(cog-new-node 'ConceptNode "abc")
```
but now that the `(opencog)` modules is not defined outside `opencog.scm` file, there's no way to load the opencog stuff back in.  ie. typing
```
(use-modules (opencog))
```
in the cogserver scheme shell (not standalone guile) is not recognized, because `opencog.scm` is not loaded by default.

... unless
```
; Another possibility: add stuff to your ~/.guile file, for example:
; (add-to-load-path "/home/yourname/opencog/build")
; (add-to-load-path "/home/yourname/opencog/opencog/scm")
;
```
is needed even for the cogserver scheme shell...

**Comment by linas** [comment]
I don't understand.  What do you mean by "it does not know about the modules loaded outside."?  If (newname stuff) needs ice-9 or srfi-1 whatever, then it should explicitly say so.  It cannot assume that they'd been previously loaded, and even if they were, I think it cannot use them. modules have to be self-contained, and provide for themselves everything they need.

The only thing that the (opencog) module is doing is loading the pre-defined atom types. You need this if there's no cogserver, but if there is a cogserver, then those atomtypes are there .... ohh wait ... 

I see .. you are saying that inside the (newname stuff), it looks like the atom types are not available to you?  Hmm. Weird, but maybe that's right.  In this case, yes, you would need to say (use-modules (opencog))  and so yes, I guess maybe opencog.scm should be loaded by opencog.conf.   Hmm. I have not tried that. I guess it should work.  There might be weird interactions ...

**Comment by linas** [comment]
closing. Essentially everything wanted here is done. And I think t mostly all works too.  

Demos in the /examples/guile directory.
