### ISSUE TITLE
Weird pattern not connected exception

### ISSUE THREAD

**Issue by misgeatgit** [opencog/opencog#1255]
I'm having the ff error which I wasn't able t comprehend after struggling for a while. My observation is that whenever a BindLink is passed to a global instance of a pattern matcher **more than once** it throws pattern mot connected exception. Below is my debug print

RULE

    (BindLink
       (ListLink
          (VariableNode "$A5")
          (VariableNode "$B5")
          (VariableNode "$C5")
       )
       (ImplicationLink
         (InheritanceLink
             (AndLink
                (VariableNode "$A5")
                (VariableNode "$C5")
             )
             (AndLink
                (VariableNode "$B5")
                (VariableNode "$C5")
             )
          )
         (ExecutionOutputLink````
             (GroundedSchemaNode "scm: pln-formula-context")
             (ListLink
                (ContextLink
                   (VariableNode "$C5")
                   (InheritanceLink
                      (VariableNode "$A5")
                      (VariableNode "$B5")
                   )
                )
                (InheritanceLink
                   (AndLink
                      (VariableNode "$A5")
                      (VariableNode "$C5")
                   )
                   (AndLink
                      (VariableNode "$B5")
                      (VariableNode "$C5")
                   )
                )
             )
          )
       )
    )

VALIDATION FAILED:
Pattern is not connected! Found 2 components:
Connected component 0 consists of ----------------: 
(InheritanceLink (av 0 0 0) (stv 1.000000 0.000000)
  (AndLink (av 0 0 0) (stv 1.000000 0.000000)
    (VariableNode "$A5" (av 0 0 0) (``stv 1.000000 0.000000)) ; [94]
    (VariableNode "$C5" (av 0 0 0) (stv 1.000000 0.000000)) ; [96]
  ) ; [98]
  (AndLink (av 0 0 0) (stv 1.000000 0.000000)
    (VariableNode "$B5" (av 0 0 0) (stv 1.000000 0.000000)) ; [95]
    (VariableNode "$C5" (av 0 0 0) (stv 1.000000 0.000000)) ; [96]
  ) ; [99]
) ; [100]
Connected component 1 consists of ----------------: 
(InheritanceLink (av 0 0 0) (stv 1.000000 0.000000)
  (AndLink (av 0 0 0) (stv 1.000000 0.000000)
    (VariableNode "$A5" (av 0 0 0) (stv 1.000000 0.000000)) ; [94]
    (VariableNode "$C5" (av 0 0 0) (stv 1.000000 0.000000)) ; [96]
  ) ; [98]
  (AndLink (av 0 0 0) (stv 1.000000 0.000000)
    (VariableNode "$B5" (av 0 0 0) (stv 1.000000 0.000000)) ; [95]
    (VariableNode "$C5" (av 0 0 0) (stv 1.000000 0.000000)) ; [96]
  ) ; [99]``
) ; [100]
(InheritanceLink (av 0 0 0) (stv 1.000000 0.000000)
  (AndLink (av 0 0 0) (stv 1.000000 0.000000)
    (VariableNode "$A5" (av 0 0 0) (stv 1.000000 0.000000)) ; [94]
    (VariableNode "$C5" (av 0 0 0) (stv 1.000000 0.000000)) ; [96]
  ) ; [98]
  (AndLink (av 0 0 0) (stv 1.000000 0.000000)
    (VariableNode "$B5" (av 0 0 0) (stv 1.000000 0.000000)) ; [95]
    (VariableNode "$C5" (av 0 0 0) (stv 1.000000 0.000000)) ; [96]
  ) ; [99]
) ; [100]

**Comment by linas** [comment]
Ugh.  You cannot not use a single global instance. Create a new one each time. 

Single global instances are not thread-safe: if two threads try to use it, it will crash.  The PatternMatch class has all sorts of internal state, and there is no way to clear that state.  You would need to clear it before each use. 

The best way to use the PatternMatch class is on the stack: do not new/delete it.  Creating it on stack is almost surely faster than creating a routine that would clear the internal state, so that you could reuse it.

**Comment by linas** [comment]
Closing, cause I think you found a "feature" not a "bug".
