### ISSUE TITLE
remove OAC shell script

### ISSUE THREAD

**Issue by arc1388** [opencog/opencog#1260]
So it took me a while to get everything together...  First, I used virtual machine, but the free version had a data limit of 8gb so testing got fucked (even with dynamic memory).  Then I couldn't get bridge connection to work on VMware, so I eventually just went with shared IP.  Finally got to making the tests again.  96% in and I got the following failure:

Scanning dependencies of target DistributeOACStuff
Project Directory from here = ../..
Build Directory = ../../build
Putting distribution files into ../../build/dist/Embodiment
cp: cannot stat ‘../../build/opencog/query/libQueryModule.so’: No such file or directory
    while executing
"exec cp -rf $file $distDir"
    ("foreach" body line 2)
    invoked from within
"foreach file $flist {
    exec cp -rf $file $distDir
}"
    (file "./make_distribution" line 139)
make[3]: *** [tests/embodiment/Control/OperationalAvatarController/CMakeFiles/DistributeOACStuff] Error 1
make[2]: *** [tests/embodiment/Control/OperationalAvatarController/CMakeFiles/DistributeOACStuff.dir/all] Error 2
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2

Needless to say, I'm frustrated, but not completely demoralized.  I have a job that focuses on decision support tool philosophy and I occasionally have free time because of the particular nature of this job.  I want to contribute but, hell, tonight I'm fed up.  

Seriously, thanks for any kind of help!  I'm off for the night for obvious reasons.
(Anything I should send?  You'll likely have to give specific code to speed things up.)

**Comment by arc1388** [comment]
So I got through two more tests because I had to change:
Libbuiltinreqs from libserver
Libquerymodule from libquery

but now 
cp: cannot stat ‘../../build/opencog/shell/libscheme-shell.so’: No such file or directory
and no file makes sense to change.

**Comment by arc1388** [comment]
Had to move over libscheme-shell.so over to the right place

moving the embodiment folder  to OperationalAvatarController

But ^ didnt work so Im stuck with

[ 96%] Built target combo_shell
Project Directory from here = ../..
Build Directory = ../../build
Putting distribution files into ../../build/dist/Embodiment
Using config file ../../opencog/embodiment/dev_embodiment.conf.default
Error copying directory from "/home/ai/opencog/src/build/dist/Embodiment" to "/home/ai/opencog/src/build/tests/embodiment/Control/OperationalAvatarController".
make[3]: *** [tests/embodiment/Control/OperationalAvatarController/CMakeFiles/DistributeOACStuff] Error 1
make[2]: *** [tests/embodiment/Control/OperationalAvatarController/CMakeFiles/DistributeOACStuff.dir/all] Error 2
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2

**Comment by linas** [comment]
I don't think any of use here know why a shell script is even needed to copy files around, and the wisdom of having this has been questioned before.  I think it was mutually agreed that somehow, that shell script should be eliminated. But, somehow, things work for the rest of us, so we've let the sleeping dog lie.

But it woke you up, so maybe a good task would be to simply remove it. Unless @lake or @shujingke knows why its needed ... or maybe @ngeiswei

**Comment by arc1388** [comment]
Thanks @linas I appreciate the response.  I've been out of country on work for a month and have been unable to look back into this (frustrating) issue until now.  Could you possibly point me in the right direction as to where I can find the OAC shell script I should try to delete? I've been deleting and renewing files for a while based on my incorrect intuition. Is there a makelist where I should be deleting the callout for the oac test?

**Comment by linas** [comment]
I have no idea. You'd have to study the makefiles.

**Comment by arc1388** [comment]
Ahh OK good that's what Im doing.  Just wanted to make sure I was on the right path.  Thanks again!

**Comment by linas** [comment]
closing OAC is gone, bug no longer applicable
