### ISSUE TITLE
Python Tests were Failing - Some Tests Disabled

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1280]
AllPythonUnitsTests was failing. So I'm submitting a Pull Request that temporarily disables two tests for test_anaphora.py and one scheme test for test_pln.py

This issue is to remind us that these tests are incomplete and should be reenabled once someone with domain experience fixes the tests so they pass (modeled after issue #442).

The tests which are skipped from: tests/python/test_anaphora/test_anaphora.py 
    test_bfs
    test_propose

From tests/python/test_pln/test_rules_new.py
    InductionRule_InheritanceLink.scm

Comments in Pull Request (will) refer to this issue.

**Comment by cosmoharrigan** [comment]
I guess one of these 3 tests can be removed from this issue description?

**Comment by linas** [comment]
closing, pull request #1798 undoes this.
