### ISSUE TITLE
Truth Value Sanity Check Breaks TruthValueUTest

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1282]
This checkin:

https://github.com/opencog/opencog/commit/9b48ab40071cbfb726c5453dd05e891ef85952f4

breaks the TruthValueUTest unit test.

From the test log at: 

http://buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/217/steps/test/logs/testlog

Excerpt from test/logs/testlog follows:
------------------------------------------

19/147 Testing: TruthValueUTest
19/147 Test: TruthValueUTest
Command: "/home/buildslave/slave/opencog_master_trusty/build/bin/tests/atomspace/TruthValueUTest"
From the buildbot test log:

Directory: /home/buildslave/slave/opencog_master_trusty/build/bin/tests/atomspace
"TruthValueUTest" start time: Feb 19 05:22 UTC
Output:
----------------------------------------------------------
terminate called after throwing an instance of 'opencog::RuntimeException'
  what():  Don't know how to merge N7opencog20IndefiniteTruthValueE into a SimpleTruthValue (/home/buildslave/slave/opencog_master_trusty/build/opencog/atomspace/SimpleTruthValue.cc:78)
Running cxxtest tests (2 tests)
<end of output>
Test time =   0.12 sec
----------------------------------------------------------
Test Failed.
"TruthValueUTest" end time: Feb 19 05:22 UTC
"TruthValueUTest" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by linas** [comment]
sorry. fixed
