### ISSUE TITLE
Psi Tests were Failing - Some Tests Disabled

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1283]
Four Psi unit tests were failing. So I'm submitting a Pull Request that temporarily disables these four tests.

This issue is to remind us that these tests should be reenabled once someone with domain experience fixes the tests so they pass (modeled after issue #442).

The following tests FAILED:
	129 - PsiDemandUpdaterAgentUTest (SEGFAULT)
	130 - PsiModulatorUpdaterAgentUTest (SEGFAULT)
	131 - PsiFeelingUpdaterAgentUTest (SEGFAULT)
	132 - PsiActionSelectionAgentUTest (SEGFAULT)

Comments in Pull Request (will) refer to this issue.

**Comment by linas** [comment]
Closing -- psi is gone. This bug report no longer applicable.
