### ISSUE TITLE
NeighborSamplingUTest Failing Intermittently

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1288]
I've seen this on my VM and it just showed up on the builtbot. Sometimes NeighborSamplingUTest passes, and other times it fails.

Without changing any code that should affect testing, I've had NeighborSamplingUTest fail where it was succeeding before. Just now, the buildbot's tests succeeded when the build just prior failed.

This is likely a problem that only shows up for some random sequences or due to an uninitialized variable.

From the buildbot test log at:
http://buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/220/steps/test/logs/testlog

---------------------------

109/147 Testing: NeighborSamplingUTest
109/147 Test: NeighborSamplingUTest
Command: "/home/buildslave/slave/opencog_master_trusty/build/bin/tests/learning/moses/NeighborSamplingUTest"
Directory: /home/buildslave/slave/opencog_master_trusty/build/bin/tests/learning/moses
"NeighborSamplingUTest" start time: Feb 19 23:15 UTC
Output:
----------------------------------------------------------
Running cxxtest tests (7 tests)before generate:[00000000111101001212000002000000]
after generate:[00000000111101001212101002000000]
new distance: 2
.fs.pack_width = 2 bpp = 64

test 1 -- sample_size: 10 sampled_size: 10 max_distance: 2 min_distance:2
fs.pack_width = 1 bpp = 64
the initial randomized contin_spec instance: [01000100020002000100]
fs.pack_width = 1 bpp = 64

test 3 -- sample_size:10 sampled_size:7 max_distance:2 min_distance:1

In NeighborSamplingUTest::test_sample_from_neighborhood:
/home/buildslave/slave/opencog_master_trusty/build/tests/learning/moses/NeighborSamplingUTest.cxxtest:255: Error: Assertion failed: (sample_size == sampled_size) || (sample_size-1 == sampled_size) || (sample_size-2 == sampled_size)
fs.pack_width = 1 bpp = 64
total_size :490
generated_size :490
.fs.pack_width = 1 bpp = 64
total_size :40
generated_size :40
.fs.pack_width = 1 bpp = 64
total_size :18
generated_size :18
.bits : [0000000000000000000000000000000000000000]
fs.pack_width = 1 bpp = 64
total_size :40
generated_size :40
.bits : [0000000000000000000000000000000000000000]
fs.pack_width = 1 bpp = 64
.
Failed 1 and Skipped 0 of 7 tests
Success rate: 85%
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"NeighborSamplingUTest" end time: Feb 19 23:15 UTC
"NeighborSamplingUTest" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by linas** [comment]
Its been doing that for a while. I thought we already had a bug report for this, but it seems we don't.   This is an issue for Nil, he was the last to touch the code, and that;'s when it started.  (well, I've also been one to monkey with this, but Nil is the regular user of it)

**Comment by bgoertzel** [comment]
This is for Nil to fix, I'd say, yea...

On Fri, Feb 20, 2015 at 10:41 AM, Linas Vepštas <notifications@github.com>
wrote:

> Its been doing that for a while. I thought we already had a bug report for
> this, but it seems we don't. This is an issue for Nil, he was the last to
> touch the code, and that;'s when it started. (well, I've also been one to
> monkey with this, but Nil is the regular user of it)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1288#issuecomment-75180892>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by ngeiswei** [comment]
Thanks for the report, I'll take of it.

**Comment by linas** [comment]
Ahem.  Nil,
 4/153 Test   #4: lazy_selectorUTest ....................***Failed

**Comment by ngeiswei** [comment]
Hallelujah.
