### ISSUE TITLE
Removing InverseHebbianLinks

### ISSUE THREAD

**Issue by bgoertzel** [opencog/opencog#1293]
I think it may be possible to remove InverseHebbianLink, thus simplifying the HebbianLink module, by changing the way the math of HebbianLinks is done...

Where AF = the AttentionalFocus, perhaps we may consider

HebbianLink A B <s>

s= s_hebbAB = P( B in AF at time $T | A in AF at time $T)

We can then also look at

InverseHebbianLink A B <s1>

s1= s_invHebbAB = P( B *not* in AF at time $T | A in AF at time $T)

But in this case s_invHebbAB = 1 - s_hebbAB

so I am unsure why we need InverseHebbianLink at all...

We can also look at the expected probability of being in the AF,

s_AF = P(Atom $x is in AF at time $T)

i.e. the percentage of Atoms in the AF at a random time

Only if

s_HebbAB >> s_AF

is s_HebbAB interesting; only if

s_invHebbAB << s_AF

is s_invHebbAB interesting...

Perhaps, rather than having HebbianLinks and InverseHebbianLinks, we
just need to make sure we boost the LTI of HebbianLinks whose
strengths are either surprisingly large or surprisingly small?  (or am
I overlooking something?)

**Comment by moikle** [comment]
Hmmm -- this might be a bit trickier than we thought. Combining s_invHebbAB = 1 - s_HebbAB with s_invHebbAB << s_AF gives s_HebbAB >> 1-s_AF. I don't think we want to boost STI values whenever s_HebbAB >> min(s_AF, 1-s_AF). 

Instead, I propose that we institute an interval of values for being outside the AF. That is, boost STI values whenever s_HebbAB << s_AF_inv or s_HebbAB >> s_AF. Now this clearly only works, though, if s_AF_inv < s_AF. Otherwise we would be boosting STI values for all links! 

I think this mimics, in essence at least, the old design where we had a de facto value of s_AF_inv = 0.

**Comment by bgoertzel** [comment]
Matt -- yes, you are right, this is a good correction....

There should be a comment in the code warning people about the s_AF_inv <
s_AF constraint...

-- Ben


On Fri, Feb 27, 2015 at 12:42 PM, moikle <notifications@github.com> wrote:

> Hmmm -- this might be a bit trickier than we thought. Combining
> s_invHebbAB = 1 - s_HebbAB with s_invHebbAB << s_AF gives s_HebbAB >>
> 1-s_AF. I don't think we want to boost STI values whenever s_HebbAB >>
> min(s_AF, 1-s_AF).
>
> Instead, I propose that we institute an interval of values for being
> outside the AF. That is, boost STI values whenever s_HebbAB << s_AF_inv or
> s_HebbAB >> s_AF. Now this clearly only works, though, if s_AF_inv < s_AF.
> Otherwise we would be boosting STI values for all links!
>
> I think this mimics, in essence at least, the old design where we had a de
> facto value of s_AF_inv = 0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1293#issuecomment-76329961>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by moikle** [comment]
I’ve already logged it as an issue. I'm working out all the dynamics and math of the “simplified approach” just to ensure all is correct.

—matt

**Comment by moikle** [comment]
Rethinking some more with additional simplification. I think that the "connection matrix" (even though we are not using this approach now) values c_ij in themselves are enough to play the role of Hebbian versus InverseHebbian links. Correct me if I'm wrong, but "large" c_ij values will tend to bring s_j into the AF if s_i is in the AF, while "small" c_ij values will tend to do the opposite. No need for inverse Hebbian links nor my earlier notion of an invAF. Pretty straightforward math -- I think the original idea of the inverse links only served to complicate everything, but then perhaps I am overlooking something incredibly obvious.

**Comment by bgoertzel** [comment]
Yes.  The connection matrix values are simply conditional probabilities,
which are Hebbian if high and inverse Hebbian if low

-- ben

On Mon, Mar 2, 2015 at 3:59 PM, moikle <notifications@github.com> wrote:

> Rethinking some more with additional simplification. I think that the
> "connection matrix" (even though we are not using this approach now) values
> c_ij in themselves are enough to play the role of Hebbian versus
> InverseHebbian links. Correct me if I'm wrong, but "large" c_ij values will
> tend to bring s_j into the AF if s_i is in the AF, while "small" c_ij
> values will tend to do the opposite. No need for inverse Hebbian links nor
> my earlier notion of an invAF. Pretty straightforward math -- I think the
> original idea of the inverse links only served to complicate everything,
> but then perhaps I am overlooking something incredibly obvious.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1293#issuecomment-76671267>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by misgeatgit** [comment]
@bgoertzel and @moikle  you may also close this issue.
