### ISSUE TITLE
Implement flexible merging mechanism for TruthValues

### ISSUE THREAD

**Issue by bgoertzel** [opencog/opencog#1295]
What do we do when merging a TV of type X into a TV of type Y?    This is hairier...

I think it should be fair to assume, for the time being, that two TV types being assigned to the same Atom type, should be mutually interconvertible (perhaps with some loss of information).   If we assume this, then when merging a TV tv1 of type X into a TV tv2 of type Y, we can assume there exist methods to cast tv1 into type Y, or to cast tv2 into type X

So, suppose we have an Atom A with a TV tv1 of type X.  Suppose we want to merge a new TV tv2 of type Y into A's truth value....  So we are calling some method like

tv1.merge(tv2)

One way to look at this is

tv1.merge(tv2, typeoption = old | new | default | stronger | weaker)

If typeoption=old, then the type of the resulting TV is tv1

If typeoption=new, then the type of the resulting TV is tv2

If typeoption=dominant, then the type of the resulting TV is whatever is specified in the merge code as the default for merging a TV of type X and a TV of type Y (this is going to be either X or Y)

For instance, for merging a SimpleTV with an IndefiniteTV, the default might be IndefiniteTV

If typeoption=stronger then the type of the resulting TV is whichever of X or Y is specified as stronger

If typeoption=weaker then the type of the resulting TV is whichever of X or Y is specified as weaker

What I mean by "stronger vs. weaker" here is e.g., SimpleProbabilisticTV is weaker than IndefiniteTV, because an IndefiniteTV can exactly specify a SimpleProbabilisticTV, but a Simple ProbabilisticTV only specified an IndefiniteTV with a lot of heuristic fudging.

...

This kind of approach would require specifying somewhere or other, the strength ordering and default ordering of each pair of commensurable TV types (where "commensurable" means that the two TV types are applicable to the same Atom types)...

It seems to me this would give enough flexibility for different cognitive processes to do what they wish with TV types....   And if someone doesn't want to worry about it, they can call

tv1.merge(tv2) =tv1.merge(tv2, typeoption=default)

and then magic will happen and hopefully the default choices won't cause any egregious stupidity ;p

I'm not sure we want to require that all TruthValues partake in this merge-option mechanism.  But all PLN truth values should, as should CountTruthValue.

**Comment by linas** [comment]
This work was completed in pull request #1312
