### ISSUE TITLE
AllPythonModuleTests fails

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1308]
Open a distinct bug for this, continuing from #1306.

**Comment by linas** [comment]
I get this:
```
$  nosetests -vs ./tests/python/
Testing the bfs function ... SKIP: Unit test disabled, see: https://github.com/opencog/opencog/issues/1280
test_conjunctions (test_anaphora.AnaphoraUnitTester) ... ok
Testing the getWords function ... ok
test_pleonastic_if (test_anaphora.AnaphoraUnitTester) ... ok
Testing the propose function ... SKIP: Unit test disabled, see: https://github.com/opencog/opencog/issues/1280
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
test_all (test_rules_new.PLNUnitTester) ... ERROR
Failure: SkipTest (ImportError exception: make sure the required dependencies are installed.) ... SKIP: ImportError exception: make sure the required dependencies are installed.

======================================================================
ERROR: test_all (test_rules_new.PLNUnitTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opencog-git/tests/python/test_pln/test_rules_new.py", line 31, in setUp
    self.addTestFile("AndRule_new.scm")
  File "/opencog-git/tests/python/test_pln/test_rules_new.py", line 97, in addTestFile
    ruleFolder = os.getenv("PROJECT_SOURCE_DIR") + "/tests/python/test_pln/new_scm_tests/"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

----------------------------------------------------------------------
Ran 10 tests in 3.650s

FAILED (SKIP=6, errors=1)
```

**Comment by inflector** [comment]
I'm not getting that error. What happens when you run `make test`? Same thing?

Perhaps `PROJECT_SOURCE_DIR` is not defined so `os.getenv("PROJECT_SOURCE_DIR")` returns `NoneType`?

It's also possible that this behavior is different for different versions of Python. What version of Python are you running?

**Comment by linas** [comment]
$ python --version
Python 2.7.6


No clue about PROJECT_SOURCE_DIR -- that should be fixed.

**Comment by inflector** [comment]
What are you getting in your build/tests/python/CTestTestfile.cmake file?

At lines 7 and 8, which come from source at:
https://github.com/opencog/opencog/blob/master/tests/python/CMakeLists.txt#L8

I have: 

`ADD_TEST(AllPythonModuleTests "/usr/local/bin/nosetests" "-vs" "--with-doctest" "/home/opencog/src/opencog/tests/python/")
SET_TESTS_PROPERTIES(AllPythonModuleTests PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/opencog/src/opencog/build/opencog/cython:/home/opencog/src/opencog/opencog/python:/home/opencog/src/opencog/opencog/python/opencog:/home/opencog/src/opencog/opencog/nlp;PROJECT_SOURCE_DIR=/home/opencog/src/opencog;PROJECT_BINARY_DIR=/home/opencog/src/opencog/build")`

Which sets PROJECT_SOURCE_DIR and I'm not getting the error you show. Is PROJECT_SOURCE_DIR present in your build/tests/python/CTestTestfile.cmake?

**Comment by inflector** [comment]
Oh, I see you are calling nosetests directly from the command line above. That will fail if you don't set the ENVIRONMENT variable first, however, `make test` should be setting it through the above mechanism.

**Comment by linas** [comment]
It fails when I say 'make test'  It fails when I run it by hand.   PROJECT_SOURCE_DIR is not set in my env.    I don't see what  PROJECT_SOURCE_DIR has to do with anything: the test should not depend on env variables -- I have 100 different terminal windows that I bounce between -- I cannot start monkeying with the env in each different term that I have open.

**Comment by linas** [comment]
my current env is this:
```
XDG_VTNR=2
XDG_SESSION_ID=c2
TERM=xterm
SHELL=/bin/bash
ROS_ROOT=/opt/ros/indigo/share/ros
XDG_SESSION_COOKIE=4464da00797efbf61ba9be4b517969c3-1425074343.875805-97113977
ROS_PACKAGE_PATH=/home/linas/hanson/src/catkin/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks
ROS_MASTER_URI=http://localhost:11311
WINDOWID=46149374
HUSHLOGIN=FALSE
OLDPWD=/home/linas/src/opencog-git
USER=linas
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
LD_LIBRARY_PATH=/home/linas/hanson/src/catkin/devel/lib/x86_64-linux-gnu:/opt/ros/indigo/lib/x86_64-linux-gnu:/home/linas/hanson/src/catkin/devel/lib:/opt/ros/indigo/lib
SSH_AUTH_SOCK=/tmp/ssh-57VEs50uAIRa/agent.7356
CATKIN_TEST_RESULTS_DIR=/home/linas/hanson/src/catkin/build/test_results
CPATH=/home/linas/hanson/src/catkin/devel/include:/opt/ros/indigo/include
ROS_TEST_RESULTS_DIR=/home/linas/hanson/src/catkin/build/test_results
PATH=/home/linas/hanson/src/catkin/devel/bin:/opt/ros/indigo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
MAIL=/var/mail/linas
PWD=/home/linas/src/opencog-git/build
LTDL_LIBRARY_PATH=build/opencog/guile:build/opencog/query:build/opencog/nlp/lg-dict:build/opencog/nlp/sureal
LANG=en_US.UTF-8
ROSLISP_PACKAGE_DIRECTORIES=/home/linas/hanson/src/catkin/devel/share/common-lisp
XDG_SEAT=seat0
HOME=/home/linas
SHLVL=2
ROS_DISTRO=indigo
LOGNAME=linas
PYTHONPATH=/home/linas/hanson/src/catkin/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages
VISUAL=/usr/bin/vi
CVS_RSH=/usr/bin/ssh
PKG_CONFIG_PATH=/home/linas/hanson/src/catkin/devel/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/home/linas/hanson/src/catkin/devel/lib/pkgconfig:/opt/ros/indigo/lib/pkgconfig
XDG_RUNTIME_DIR=/run/user/500
CMAKE_PREFIX_PATH=/home/linas/hanson/src/catkin/devel:/opt/ros/indigo
DISPLAY=:0.0
ROS_ETC_DIR=/opt/ros/indigo/etc/ros
COLORTERM=mate-terminal
_=/usr/bin/env
```

I am guessing that perhaps CMAKE_PREFIX_PATH or PYTHONPATH or LTDL_LIBRARY_PATH or LD_LIBRARY_PATH is causing the failure

**Comment by inflector** [comment]
"the test should not depend on env variables" 

Yep, that's true, I'll fix that.

**Comment by inflector** [comment]
I fixed the test test_rules_new.py so that it doesn't rely on any environment variables except PYTHONPATH. Those fixes are included in pull request #1349

The Python tests, and OpenCog Python access, require setting PYTHONPATH to include:
```
/home/USER/opencog/opencog/python/
/home/USER/opencog/opencog/nlp/
/home/USER/opencog/build/opencog/cython/
```
I noticed that yours does not include the above. We could alter the tests so they fix up sys.path at the top of the test, but we're telling people they need to set it in:

http://wiki.opencog.org/w/Python#Setting_up

so that seemed beyond the scope of this issue, until I hear otherwise. If you want me to make the changes so there is no requirement for setting PYTHONPATH, just let me know.

In bash, I entered.
```
export PYTHONPATH="${HOME}/src/opencog/build/opencog/cython:${HOME}/src/opencog/opencog/python::${HOME}/src/opencog/opencog/nlp"
```
and then ran:
```
nosetests -vs ./tests/python/
``` 
and all the tests now pass with the changes in #1349.

**Comment by linas** [comment]
I can't think of a particularly good solution off the top of my head.  Bare guile has similar issues.  Both of these used to be solved, for better of for worse, bu the opencog.conf file, and the path-search and file loading mechanism there.  That is why I suggested one possible solution is to rip the confg-file stuff out of the cogserver, move it to its own directory,  and write a python wrapper for it. That way you could configure search path load paths, port numbers, etc. 

The only other thing I can think of is to do what ROS does: when you say "make" it automatically creates a build/setup.sh file, and all users are told to source it before doing anything.  And/or source it after each build ... its not elegant either, but it works.

**Comment by linas** [comment]
It now passes for me. Thanks!
