### ISSUE TITLE
Add support for Python evaluation in EvaluationLink

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1319]
The code in EvaluationLink::do_evaluate only supports Scheme execution despite the comment in the first line below. There is an exception thrown that Python execution is "not implemented".  This was added because the call to PythonEval::instance was crashing.

https://github.com/opencog/opencog/blob/master/opencog/execution/EvaluationLink.cc#L150-L184

Add back the support and test to make sure the crash no longer happens.

**Comment by linas** [comment]
fwiw python_eval should also take atomspace as an argument somewhere, so that it acts on the correct atomspace.

**Comment by inflector** [comment]
@linas It looks like this should work now based on your commit https://github.com/opencog/opencog/commit/c86f9ef751fddc72d98a3488e78faaf93230137b. 

What do I need to run in guile to test it? I'm not sure of the format expected by EvaluationLink in order to invoke `EvaluationLink::do_evaluate`.

**Comment by linas** [comment]
Same format as ExecutionLink.  The only difference is that EvaluationLinks use GroundedPredicateNodes instead of GroundedSchemaNodes and the result of the invocation is not another atom, but a truth value.  But the input arguments are the same.   I do not recall if cog-execute! can take EvaluationLinks or not.  If not, then maybe a cog-evaluate! should be created.  Having a distinct name would lessen confusion,

**Comment by linas** [comment]
Here's a simple, if bogus test case:  write a python function, taking two atoms, and returning a TV.  Call it "bogus_tv".   For example:

```
def bogus_tv(atom_a, atom_b) :
    return TruthValue(0.6, 0.234)
```
Something more "realistic" might calculate the mean of the tv on A and B, or some other formula.

Then try this at the scheme shell:
```
(cog-evaluate! 
   (EvaluationLink
       (GroundedPredicateNode "py: bogus_tv")
       (ListLink
            (ConceptNode "asdf")
            (ConceptNode "qert")
      )
   )
)
```

The above should return the TV that "bogus_tv" returns.

As should be clear: the above is how you write a "function" in the atomspace, taking two arguments, and how you call that function.  Instead of using cog-evaluate, the pattern matcher will also evaluate such expressions.

**Comment by inflector** [comment]
Thanks Linas, the function calling semantics are what I thought they'd be, and match ExecutionOutputLink for parameter handling, that's good. So the PythonEval code will be largely the same, just need to convert the returned PyObject* into a TV.

**Comment by linas** [comment]
Yes.

**Comment by inflector** [comment]
Well it looks like you implemented cog-evaluate just in time. I just submitted pull request #1363 which I got to successfully return a TruthValuePtr to the cog-execute function I wrote so I could work on this. I was crashing after that and just about to ask you what the guts of that was supposed to do. And when I pulled upstream/master you magically had already written it.

I had `tvp->clone()` where you wrote `tvp->rawclone()`. But I was just guessing.

You've got to add the module to the function `test_functions.bogus_tv` to get it to work. So this works now:
```
(cog-evaluate! 
   (EvaluationLink
       (GroundedPredicateNode "py: test_functions.bogus_tv")
       (ListLink
            (ConceptNode "asdf")
            (ConceptNode "qert")
      )
   )
)
```
The one oddity is that this results in a print of:
```
(stv 0.60000002 0.00029241448)
```
when the TruthValue from the bogus_tv Python function is initialized with:
```
TruthValue(0.6, 0.234)
```
The `0.6` matches but '0.00029241448` is not `0.234`. I don't recall seeing any bugs about TruthValue not being initialized properly in Python but I'll look into it.

**Comment by inflector** [comment]
Ah, there's a `countToConfidence` function being called in `to_string()` for `SimpleTruthValue` that does:

```
confidence = count / (count + 800.0)
```

which when applied to 0.234 gives `0.000292414468768`

So I'm closing this issue.

**Comment by bgoertzel** [comment]
BTW, that value 800 should be a parameter, adjustable at runtime...
traditionally called
"k" but it could be called "confidence_personality_parameter" or whatever
...

On Fri, Mar 6, 2015 at 9:44 AM, Curtis Faith <notifications@github.com>
wrote:

> Ah, there's a countToConfidence function being called in to_string() for
> SimpleTruthValue that does:
>
> confidence = count / (count + 800.0)
>
> which when applied to 0.234 gives 0.000292414468768
>
> So I'm closing this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1319#issuecomment-77491498>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by inflector** [comment]
In the code, it's actually a constant: 
```
#define KKK 800.0f
```
I'm not sure whoever wrote that knows the U.S. connotation of KKK.

It definitely seems like something that ought to be a tunable parameter, absolutely.
