### ISSUE TITLE
Buildbot: LinkGrammar not installed

### ISSUE THREAD

**Issue by williampma** [opencog/opencog#1334]
Apparently LG is not installed on the buildbot, so some of the NLP unit tests are not being run.

```
-- link-grammar( >= 4.7.12) was not found. Make sure LINK_GRAMMAR_LIBRARY, LINK_GRAMMAR_INCLUDE_DIR and LINK_GRAMMAR_DATA_DIR are set.
-- Link Grammar missing: needed for the Viterbi parser.
```

So maybe LG should be installed?

**Comment by AmeBel** [comment]
how many tests do you get on your machine?

**Comment by williampma** [comment]
152

I probably should be getting 153 since there are 3 NLP related tests right now that depends on LG, and the buildbot is now at 150.

**Comment by AmeBel** [comment]
i have updated the docker images. Check and close if resolved.

**Comment by williampma** [comment]
Cool.  I see the tests on buildbot now.  Thanks!
