### ISSUE TITLE
Unable to build opencog because "PythonEval" is not declared

### ISSUE THREAD

**Issue by ZhangYou0122** [opencog/opencog#1337]
Hi, I'm trying to build opencog on ubuntu 14.04, after installing all the prerequisites and excuting
```
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```
which is not successful, the compiler complains:
```
[ 63%] Building CXX object opencog/server/CMakeFiles/server.dir/CogServer.cc.o
/home/zhangyou/git/opencog/opencog/server/CogServer.cc: In destructor ‘virtual opencog::CogServer::~CogServer()’:
/home/zhangyou/git/opencog/opencog/server/CogServer.cc:110:5: error: ‘PythonEval’ has not been declared
     PythonEval::delete_singleton_instance();
     ^
/home/zhangyou/git/opencog/opencog/server/CogServer.cc:113:28: error: ‘global_python_finalize’ was not declared in this scope
     global_python_finalize();
                            ^
make[2]: *** [opencog/server/CMakeFiles/server.dir/CogServer.cc.o] Error 1
make[1]: *** [opencog/server/CMakeFiles/server.dir/all] Error 2
make: *** [all] Error 2
```

My python --version shows `Python 2.7.6`

**Comment by inflector** [comment]
PythonEval definitely has `global_python_finalize();` See:

https://github.com/opencog/opencog/blob/master/opencog/cython/PythonEval.h#L168

so there must be something else going on. Does your code match the current master branch?

What directory are you running make from?

**Comment by inflector** [comment]
And did you try a:

`make clean` 

first or was there no `build` directory when you started because this was a fresh install?

**Comment by inflector** [comment]
Does this line compile without a warning or error:

https://github.com/opencog/opencog/blob/master/opencog/server/CogServer.cc#L39 ?

**Comment by linas** [comment]
Zhang does not haver python-dev or cython installed.  The CogServer isn't using HAVE_CYTHON protecting those lines.  I just pushed a fix for the second part.

This is a very leet bug, by the  way. I want a letter jacket with my number 1337 on it.

**Comment by ZhangYou0122** [comment]
Thank you! I didn't expect this question would be answered so quickly, and in such detail!

> Does your code match the current master branch?

Yes, the command I used: `git clone https://github.com/opencog/opencog`


>And did you try a:

>make clean

>first or was there no build directory when you started because this was a fresh install?

I created a "build" directory under the project's root dir. And that's where `make` was run.


>Does this line compile without a warning or error:

>https://github.com/opencog/opencog/blob/master/opencog/server/CogServer.cc#L39 ?

Yes, no error on this line. I pasted all error info on this issue.


>The CogServer isn't using HAVE_CYTHON protecting those lines. I just pushed a fix for the second part.


This bug fix worked!  
Now I'm struggling with another compile error, but I wanna see if I can get around it myself...

**Comment by inflector** [comment]
@ZhangYou0122 How is that compile error going? Did you ever get it fixed?

**Comment by ZhangYou0122** [comment]
>How is that compile error going? Did you ever get it fixed?

Yes, it turn out that guile is not installed correctly, "make" command went without error.

**Comment by inflector** [comment]
@ZhangYou0122 Good to hear. Would you please close this issue if your problem is resolved. Thanks

**Comment by ZhangYou0122** [comment]
Of course, thanks again.
