### ISSUE TITLE
orFormula

### ISSUE THREAD

**Issue by moikle** [opencog/opencog#1365]
The or formula in formulas.py does not make sense to me.

**Comment by AmeBel** [comment]
If orFormula is the general form of union then it doesn't account for all the possible intersections

**Comment by moikle** [comment]
True but it seems to me that the code written always gives a truth value of 1? Or am I reading the Python incorrectly?

—matt

**Comment by AmeBel** [comment]
I got that impression at first too, but andAB is the intersection of all tv.means, i don't know what total_s is but is greater than 1 with the exception of all tv-means being 1

**Comment by moikle** [comment]
That may be what is supposed to happen in which case it may make sense but I just ran the code through python in a couple of random examples for input truth values and ended up with total_s =1 each time. Unless, that is, I am missing something in terms of what is happening in the calculations of the means.

—matt

**Comment by AmeBel** [comment]
that is because the default tv for a new atom is (1, 0)

**Comment by moikle** [comment]
I was testing just the function itself, using arbitrary values in the array tvs.

**Comment by AmeBel** [comment]
i got the same result at first. Solution https://stackoverflow.com/questions/21768286/using-integer-division-in-python

**Comment by moikle** [comment]
Two problems with this:

1) I was inputing float values;
2) More fundamentally, mathematically the loop _should_ always output 1.

With exact values, we initialize total_s = 1, so the first time through the loop andAB = total_s * tv.mean = tv.mean.
Next, total_s = total_s + tv.mean - andAB = total_s + tv.mean - tv.mean = total_s = 1.

At each step in the loop, total_s begins at 1 so that it should, barring round-off, end at 1 which still makes no sense to me. Nothing I tried made sense to me as I tried initializing with different total_s values as well. Now total_s does change, but not in a sensible manner.

—matt

**Comment by AmeBel** [comment]
yap you are right.

**Comment by moikle** [comment]
OK -- I think I have figured out the problem. We just need to initialize total_s = tv[0] rather than to total_s = 1.0.

**Comment by moikle** [comment]
tvs[0]

**Comment by AmeBel** [comment]
with few other changes then it would be effectively be [binaryOrFormula](https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/formulas.py#L212) but it is still not a general union formula

**Comment by moikle** [comment]
Yes -- for two truth values it is exactly the same as binaryOrFormula but it can be used for lists of longer truth values as well -- though it does assume independence and uses inclusion/exclusion -- I'm unsure what this orFormula is supposed to calculate otherwise -- is it meant to assume non-independence? -- or is it supposed to be a general formula for more than 2 tvs? -- if so then what I just gave should work -- if it is to assume non-independence then we should add a new formula to the list and determine what the formula should then be.

**Comment by moikle** [comment]
Initialization should definitely be total_s = tvs[0]. The orFormula would then be the correct generalized independence-based union formula. We may need to think through a non-independence based formula/program for generalized unions but have not done so yet.

**Comment by linas** [comment]
this bug references code that has been removed from the repository, closing.
