### ISSUE TITLE
inheritance formula

### ISSUE THREAD

**Issue by moikle** [opencog/opencog#1366]
inheritance formula in formulas.py is not a duplicate and should be included in the code -- it appears to me to be implementing mixed Inheritance

**Comment by AmeBel** [comment]
do you mean https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/formulas.py#L240

**Comment by moikle** [comment]
yes

—matt

**Comment by AmeBel** [comment]
i couldn't get any particular formula on the books, only a mention of that the weighted average of IntenstionalInheritanceLink and SubsetLink implys an InheritanceLink, so it seems the commented out is the correct one.

**Comment by moikle** [comment]
Yes — but I believe we actually want both formulas. They are not duplicates. The first formula is a conversion from extensionalInheritance to (mixed) Inheritance, and the commented out formula is a formula for Inheritance given both inthensionalInheritance and extensionalInheritance.

—matt

**Comment by AmeBel** [comment]
so [this](https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/inheritance_rules.py#L233) rule should be using the commented-out one .

what is mixed inheritance? Can't find anything on it.

**Comment by moikle** [comment]
OK — I was trying to find the relevant page online but didn’t find it yet, but on page 27 of the PLN book there are three relationships representing first-order conditional probabilities:

1) Subset (extensional)
2) Inheritance, which is thought of as mixed intensional/extensional
3) IntensionalInheritance (intensional)

We also have three symmetrized first-order conditional probabilities

1) ExtensionalSimilarity (extensional)
2) Similarity (mixed)
3) IntensionalSimilarity (intensional)

with similar distinctions also for higher-order Implication and Equivalence links.

—matt

**Comment by bgoertzel** [comment]
mixed inheritance is just inheritance (as a combination of intensional and
extensional inheritance)

On Fri, Mar 6, 2015 at 2:50 PM, Amen Belayneh <notifications@github.com>
wrote:

> so this
> <https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/inheritance_rules.py#L233>
> rule should be using the commented-out one .
>
> what is mixed inheritance? Can't find anything on it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1366#issuecomment-77514971>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by AmeBel** [comment]
well then [this](https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/formulas.py#L240) is the correct one, assuming a weight of one is ok(page 262 PLNBook provides one option for determining the weight). 

So, [the in use](https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/formulas.py#L169 ) formula is wrong or there are cases where in [makeUpCount](https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/formulas.py#L32) should be used?

**Comment by moikle** [comment]
Ah -- I had missed the prior formula in the file. I think we can leave the formula as is. No change needed.

**Comment by AmeBel** [comment]
@moikle not clear which of the two should't change

**Comment by moikle** [comment]
The code is fine as it is -- with the one formula commented out as duplicate.
