### ISSUE TITLE
build/reasoning folder

### ISSUE THREAD

**Issue by williampma** [opencog/opencog#1367]
Hello, 

Is there any particular reason files are being copied to `build/reasoning` folder, instead of `build/opencog/reasoning` folder?

Would anyone object if those files are changed to be copied to `build/opencog/reasoning` instead?

**Comment by williampma** [comment]
And maybe those files do not even have to be copied at all?  Why not just use the files from the `opencog/reasoning` folder?  They are just scheme files.

**Comment by misgeatgit** [comment]
I followed the trend that @cosmoharrigan started and at the time I didn't ask him why. Besides the path modifications needed in the test code, I don't see any harm of doing it. May be @cosmoharrigan has a solid reason for doing that.

**Comment by williampma** [comment]
> They loaded at runtime. So we need to copy them to the build folder.

I don't get it.  Scheme files have been loaded at runtime from the source folder without problem before.

**Comment by misgeatgit** [comment]
Absolute path makes it hard. for example  my build directory is side by side to the main opencog repository. other may have in built and so on. In these non standard situation absolute path can't be used. Or did I miss sth here?

**Comment by williampma** [comment]
I think by default (at least for those stuff defined in opencog.conf), both the source folder and the binary folder are searched (in addition to a whole bunch of others).  They are listed at https://github.com/opencog/opencog/blob/master/opencog/util/files.cc

I am not sure where the path specified in the json file should be based (I think there's where the scheme files are loaded?).  Maybe the same set of paths, or maybe different.

**Comment by linas** [comment]
I'm not sure, but sometimes unit tests fail if the copy is not made,  Not sure, but it has been an issue in the past with buildbot and/or OSX and other non-standard situations.

For python files, python will litter .pyc files into the source tree, which is either annoying, or broken if the source tree is marked read-only (e.g. on the buildbot).

**Comment by cosmoharrigan** [comment]
It seems like there are 2 *separate* questions here, as originally described by @williampma:
> Is there any particular reason files are being copied to build/reasoning folder, instead of build/opencog/reasoning folder?

For this, this doesn't make sense and should be eliminated, right? There's no reason to have both of these folders:
build/opencog/reasoning
build/reasoning

> And maybe those files do not even have to be copied at all? Why not just use the files from the opencog/reasoning folder? They are just scheme files.

I am not sure of the answer to this one.
