### ISSUE TITLE
Trigger compile, utest and code style checking on pull request

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1383]
It would be really cool if every time someone does a pull request the builtbot is automatically triggered to 

1. Clone the branch corresponding to the pull request
2. Compile it
3. Run the unit tests
4. Perform some code style checking
5. Send the report back to the list

This would help us to assess the quality of a pull request before merging it.

**Comment by williampma** [comment]
Like Travis CI?

**Comment by AmeBel** [comment]
i have tried that but wasn't able to make it work, https://github.com/AmeBel/opencog/tree/travis-ci-new
may be you guys could try to configure it  on your forks. If you can't find a means of implementing i will go ahead with the adding that feature to the buildbot.

@githart any suggestions? drone.io didn't work for me as well

**Comment by linas** [comment]
clsoing I think this is done. If not, please open a new bug report indicating remaining work.
