### ISSUE TITLE
Testing Distributed atomspace 

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1394]
Steps to take for the test were initial outlined  [here](https://github.com/opencog/docker/pull/29#issuecomment-78401615)
1. start two containers, both connected to one database.
2. write a guile script so that one of them pushes atoms into the database, the other pulls them out.
3. To verify that data is moving, you have to actually look at truth values. So one would create atoms with e.g. low truth values, the other would verify the values. Maybe make them large and push them back again. Ping-pong around. Or you could look at incoming sets ... see below.

Notes:
- The push and pull commands are in scheme, called fetch-atom fetch-incoming-set store-atom all of which take a single atom as an argument.
- `load-atoms-of-type` takes a single type as an argument
- `barrier` takes no arguments; its supposed to make sure all stores are finished before any loads start. (if you try to store 100K atoms, it might take a while. Barrier is supposed to block until they are all stored.).
- atom UUID's should be preserved, i.e., they should be the same in both atomspaces.

**Comment by linas** [comment]
Closing. I think the `MultiUserUTest.cxxtest` and the `MultiPersistUTest.cxxtest` unit tests in the atomspace test this.  Anyway, this code is not in the opencog repo any more.
