### ISSUE TITLE
PLN deduction formula

### ISSUE THREAD

**Issue by moikle** [opencog/opencog#1401]
At some point, the independence-based deduction rule should be corrected to include the consistency conditions. 

IF: 0 <= sAB-max((sA+sB-1)/sA, 0) <= min(1, sB/sA) -max((sA+sB-1)/sA, 0)
AND 0 <=  sBC-max((sB+sC-1)/sB, 0) <= min(1, sC/sB)-max((sB+sC-1)/sB, 0)
   sAC = [sAB.sBC + ((1-sAB)(sC - sBsBC))/(1-sB)] 
ELSE:
   sAC = 0
END

The trickiest part about the corrected formula is that the truth value sAC now depends upon five independent variables sA, sB, sC, sAB, and sBC, rather than only four. This change will need to be propagated through all rules that depend upon deduction so as to include the appropriate conditional requirements.

**Comment by AmeBel** [comment]
What do you mean by " This change will need to be propagated through all
rules"?

**Comment by moikle** [comment]
I will provide the corresponding conditionals for the other rules :-) But generally what I mean is that deduction is used to calculate induction, abduction, transitive similarity, evaluationImplication, etc. 

Now there two forms for the conditions and these can be put into "helper" functions -- then the only thing that changes are the inputs into those functions.

**Comment by moikle** [comment]
So, for example, we can form the functions

consistency1(A, B, AB) = A*B-max((A+B-1)/A, 0) and
consistency2(A, B) = min(1, B/A).

For deduction we then have 

IF consistency1(A, B, AB) >=0 and consistency1(A, B, AB) <= consistency2(A, B)
    and consistency1(B, C, BC) >=0 and consistency1(B, C, BC) <= consistency2(B, C)
THEN AC = [AB.BC + ((1-AB)(C - B*BC))/(1-B)] 
ELSE AC=0

I just worked out the case for induction. The conditions need to be
IF consistency1(B, A, BA) >=0 and consistency1(B, A, BA) <= consistency2(B, A)
    and consistency1(B, C, BC) >=0 and consistency1(B, C, BC) <= consistency2(B, C)
If this is the case then we can simply apply
THEN AB = inversionFormula(BA, B, A)
    AC = deduction(A, B, C, AB, BC) 
ELSE AC=0

What works out very nicely, as I verified, is that the conditional statements for induction end up equivalent for the conditional for deduction applied to (A, B, inversion(BA)) and to (B, C, BC). What that means is that after correcting the deduction formula to include the conditionals, induction can be found via

AB = inversionFormula(BA, A, B)
AC = deduction(A, B, C, AB, BC)

That is, we can simply apply the inversion rule to BA first. The required conditionals are then included in the deduction formula.

Since abduction is analogous to induction except with inversion on the second pair instead of on the first, abduction can be found via

BC = inversion(CB, B, C)
AC = deduction(A, B, C, AB, BC)

My guess is that all the other required conditionals will also be included in the single set of inequalities included in deduction, but I will verify this.

**Comment by moikle** [comment]
transitive similarity is correct in the python code using the new corrected deduction formula applied to (A, B, C, T1, T2) and to (A, B, C, T3, T4)

2inh2sim may need to be rewritten in terms of the deduction rule as it is used twice in the derivation.

**Comment by moikle** [comment]
OK -- for 2inh2sim, while we used the deduction rule twice in the PLN book, these steps were not necessary. The formula does, however, need to include the following consistency conditions,

consistency1(A, C, AC)>= 0
consistency1(C, A, CA)>=0
consistency2(A, C, AC)>=0
consistency2(C, A, CA)>=0

Since we can eliminate the deduction rule in the proof of the 2inh2sim rule, we need no conditions involving B and we will need to invoke the consistency conditions within the 2inh2sim rule itself.

**Comment by moikle** [comment]
inh2sim requires only three inputs (A, C, AC) and hence only requires the consistency conditions 

consistency1(A, C, AC)>= 0
consistency2(A, C, AC)>=0

**Comment by moikle** [comment]
sim2inh requires the three inputs (A, B, and simAB). Assuming I did the calculations correctly, the consistency conditions are always satisfied when each of the three inputs are non-negative, which should always be the case.

**Comment by moikle** [comment]
Working out this last case (sim2inh) made me realize that since, by default, sA, SB, sC, sAB, sAC are all probability values in [0, 1], then the consistency conditions can be simplified (though we still need to ensure all the values are in [0,1].

Since each of the inputs into the deduction rule should be between 0 and 1, we can eliminate the max and min cutoff functions. The new consistency functions can be rewritten in the simpler form

consistency1: sAB >= (sA+sB-1)/sA (we don't need the max function since sAB should be >=0 by default.)
consistency2: sB/sA >= sAB (again, sAB should be <=1 by default.)

Of course we can leave the cutoff functions to ensure that each of the probabilities remains a probability so

consistency1: sAB >= max(0, (sA+sB-1)/sA)
consistency2: min(1, sB/sA) >= sAB

Either way, as indicated in the thread above, we do need to implement some sort of these consistency functions so as to ensure that all the values we calculate using the PLN formulas make sense.

**Comment by moikle** [comment]
Consistency conditions also need to be used in:

Concept Geometry Deduction: consistency1(A, B, AB): sAB >= max(0, (sA+sB-1)/sA), and consistency 2: min(1, sB/sA) >= sAB; and both conditions again for the triple (B, C, BC)

Modus Ponens: consistency1(A, B, AB): sAB >= max(0, (sA+sB-1)/sA), and consistency 2: min(1, sB/sA) >= sAB

The inputs to Symmetric modus ponens are the same as for sim2inh so we again need:
simAB >= sA+sB-1 and simAB <= sB/sA.

Bayes' inversion uses sA, sB, sAB so these three need to be consistent:
sAB >= max(0, (sA+sB-1)/sA)

All these changes were implicit in the PLN book but only made explicit for the independence-based deduction rule. I will write all these explicit formula changes into the wiki this week.

**Comment by AmeBel** [comment]
@moikle deduction is applicable to only ImplicationLink and InheritanceLink right?

**Comment by moikle** [comment]
Deduction definitely applies to those two link types. I cannot think of any other link types to which it would apply, but I may be overlooking something.

—matt

**Comment by moikle** [comment]
Also applies to SubsetLink and PartOfLink

—matt

**Comment by AmeBel** [comment]
what is IndependenceAssumptionDiscount in http://wiki.opencog.org/w/Independence_Based_Deduction_Formula

**Comment by bgoertzel** [comment]
It reflects the notion that some error exists in a truth value produced by
the deduction formula, due to the approximate nature of the deduction
formula (which includes an independence assumption that is approximate
rather than exact).  Due to this error, the confidence of a conclusion
produced by the deduction formula is less than it would be if the formula
were exact...

-- Ben

On Wed, Mar 18, 2015 at 7:14 PM, Amen Belayneh <notifications@github.com>
wrote:

> what is IndependenceAssumptionDiscount in
> http://wiki.opencog.org/w/Independence_Based_Deduction_Formula
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1401#issuecomment-82907499>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by AmeBel** [comment]
how should the IndependenceAssumptionDiscount be derived?

@moikle what is min_count in the formula for nAC? And is nAC confidence or count?

**Comment by bgoertzel** [comment]
Assuming a random universe we can derive it from the variance of the
hypergeometric distribution (see the proof of the deduction formula ) ...

Alternate derivations could be made based on more realistic models of the
universe

Since this is lot of work we just make up a number now ;-)

On Wednesday, March 18, 2015, Amen Belayneh <notifications@github.com>
wrote:

> how should the IndependenceAssumptionDiscount be derived?
>
> @moikle <https://github.com/moikle> what is min_count in the formula for
> nAC? And is nAC confidence or count?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1401#issuecomment-82916173>.
>


-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by AmeBel** [comment]
and the luck number is ?

**Comment by bgoertzel** [comment]
.987654321

On Wednesday, March 18, 2015, Amen Belayneh <notifications@github.com>
wrote:

> and the luck number is ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1401#issuecomment-82926261>.
>


-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by AmeBel** [comment]
haha :-D

**Comment by linas** [comment]
Eh?

4 8 15 16 23 42

**Comment by AmeBel** [comment]
with the exception of nAC the consistency conditions are implemented in #1515

**Comment by linas** [comment]
is this still an issue?

**Comment by AmeBel** [comment]
@ngeiswei any comment?

**Comment by ngeiswei** [comment]
All these corrections have been applied, closing.
