### ISSUE TITLE
why is libmoses being built static, not shared?

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1421]
Nil,

The moses Cmakefile says: `ADD_LIBRARY (moses SHARED STATIC`  can I get rid of STATIC? it seems to mostly pointlessly burn up disk space.

**Comment by ngeiswei** [comment]
Linas,

the static part has been used to package binaries of standalone moses. I do not know if that is still being used but I think we can remove it, we'll see, likely nobody is gonna complain.

**Comment by ngeiswei** [comment]
Ahah, it's funny how the mind can create a narrative to justify its actions (although I do really recall trying to set linking as much static as possible in a standalone build of moses, so what I've said wasn't entirely BS).

```
-- Configuring done
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "moses" of type STATIC_LIBRARY
    depends on "feature_selection" (weak)
  "feature_selection" of type SHARED_LIBRARY
    depends on "moses" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
```

*That* is the real reason behind the STATIC keyword.

**Comment by linas** [comment]
ah.  Right. I knew that.  Properly speaking, circular dependencies are always a bug, but I could not think of any quick and easy bug fix for it.  

The problem with static is that each of the binaries (the examples) is now huge, because each includes a full static copy of moses.  and siince there are maybe a dozen examples, this all adds up.

**Comment by linas** [comment]
closing
