### ISSUE TITLE
EvaluationToMemberRule output choice

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1424]
@bgoertzel  @moikle
Let us assume we have 
```
(EvaluationLink
    (PredicateNode "eat")
    (ListLink
         (ConceptNode "dog")
         (ConcpetNode "dragon")
))
```
There are two possible outputs for EvaluationToMember Rule

```
(MemberLink
	(ConceptNode "dog")
	(SatisfyingSetLink
		(VariableNode "$X")
		(EvaluationLink
			(PredicateNode "eat")
			(ListLink
				(VariableNode "$X")
				(ConceptNode "dragon")))))

(MemberLink
	(ConceptNode "dragon")
	(SatisfyingSetLink
		(VariableNode "$X")
		(EvaluationLink
			(PredicateNode "eat")
			(ListLink
				(ConceptNode "dog")
				(VariableNode "$X")))))
```

How should the chaining be performed? and what is the formula associated with it?

**Comment by moikle** [comment]
Amen,

Good question as both approaches make sense to me. It seems to me that the original EvaluationLink contains more information than either of your two suggestions by themselves. Instead the original EvaluationLink provides the information for constructing both of your outputs.

In terms of handling the chaining, I just don’t know. Do we wish to create both outputs since they provide different senses, or do we wish to merge the two TVs?

Ben?

—matt

**Comment by bgoertzel** [comment]
The rule should produce both outputs IMO.   The chainer can then choose
which one to use via whatever heuristics it wants, e.g. by which one has
nodes with higher STI in a more prominent position...

On Tue, Mar 17, 2015 at 1:54 PM, moikle <notifications@github.com> wrote:

> Amen,
>
> Good question as both approaches make sense to me. It seems to me that the
> original EvaluationLink contains more information than either of your two
> suggestions by themselves. Instead the original EvaluationLink provides the
> information for constructing both of your outputs.
>
> In terms of handling the chaining, I just don’t know. Do we wish to create
> both outputs since they provide different senses, or do we wish to merge
> the two TVs?
>
> Ben?
>
> —matt
>
> > On Mar 17, 2015, at 1:07 PM, Amen Belayneh <notifications@github.com>
> wrote:
> >
> > @bgoertzel <https://github.com/bgoertzel> @moikle <
> https://github.com/moikle>
>
> > Let us assume we have
> >
> > (EvaluationLink
> > (PredicateNode "eat")
> > (ListLink
> > (ConceptNode "dog")
> > (ConcpetNode "dragon")
> > ))
> > There are two possible outputs for EvaluationToMember Rule
> >
> > (MemberLink
> > (ConceptNode "dog")
> > (SatisfyingSetLink
> > (VariableNode "$X")
> > (EvaluationLink
> > (VariableNode "eat")
> > (ListLink
> > (VariableNode "$X")
> > (ConceptNode "dragon")))))
> >
> > (MemberLink
> > (ConceptNode "dragon")
> > (SatisfyingSetLink
> > (VariableNode "$X")
> > (EvaluationLink
> > (VariableNode "eat")
> > (ListLink
> > (ConceptNode "dog")
> > (VariableNode "$X")))))
> > How should the chaining be performed? and what is the formula associated
> with it?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/opencog/opencog/issues/1424>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1424#issuecomment-82124602>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by ngeiswei** [comment]
Sorry to be so strict but according to the PLN book, p.35, the SatisfyingSet link takes only one argument, a predicate, so it should be

```
(MemberLink
    (ConceptNode "dog")
    (SatisfyingSetLink
        (EvaluationLink
            (VariableNode "eat")
            (ListLink
                (VariableNode "$X")
                (ConceptNode "dragon")))))
```

(given that EvaluationLink P X corresponds to a Predicate as Ben has suggested).

**Comment by ngeiswei** [comment]
Oh, I see it contradicts the wiki...

http://wiki.opencog.org/w/SatisfyingSetLink

**Comment by ngeiswei** [comment]
Yeah, the reason is because as defined in the page SatifyingSetLink acts as a lambda

http://wiki.opencog.org/w/SatisfyingSetLink#Truth_values

except that if we assume

```
EvaluationLink
    P
    $X
```

also implicitly acts as a lambda, then no need of having SatifyingSet acts as a lambda again.

I think it would be simpler if we had a LambdaLink (better name than BindLink) and never assumes anything acts implicitly as a lambda. Of course that's at the price of clobbering the hypergraphs with LambdaLink all over the place. I am more fearful of inconsistency than verbosity, that is why I would favor a LambdaLink only, no implicit lambda. It's still a judgment call though.

**Comment by ngeiswei** [comment]
BTW, I don't know the context of the question so forgive my perhaps irrelevant suggestion but why the EvaluationToMember Rule wouldn't simply turn

```
(EvaluationLink
    (PredicateNode "eat")
    (ListLink
         (ConceptNode "dog")
         (ConcpetNode "dragon")
))
```
into

```
(MemberLink
    (ListLink
         (ConceptNode "dog")
         (ConcpetNode "dragon")
    (SatisfyingSetLink (PredicateNode "eat")))
```
?

**Comment by AmeBel** [comment]
As far as i know
```
(MemberLink
    (ConceptNode "dog")
    (SatisfyingSetLink
        (VariableNode "$X")
        (EvaluationLink
            (VariableNode "eat")
            (ListLink
                (VariableNode "$X")
                (ConceptNode "dragon")))))
```
mean dog is the member of the set that eat dragon

what does 

```
(MemberLink
    (ListLink
         (ConceptNode "dog")
         (ConcpetNode "dragon")
    (SatisfyingSetLink (PredicateNode "eat")))
```
mean?

**Comment by ngeiswei** [comment]
It means that ("dog", "dragon") is a member of the concept of pairs of things that eat other things.

**Comment by AmeBel** [comment]
replace dragon with pizza :-)

**Comment by ngeiswei** [comment]
Yes, sure, putting TV in consideration we'd have

```
(MemberLink (stv 0 0.9)
    (ListLink
         (ConceptNode "dog")
         (ConcpetNode "dragon")
    (SatisfyingSetLink (PredicateNode "eat")))
```

```
(MemberLink (stv 0.6 0.9)
    (ListLink
         (ConceptNode "dog")
         (ConcpetNode "pizza")
    (SatisfyingSetLink (PredicateNode "eat")))
```

**Comment by AmeBel** [comment]
I am not getting how the pair 'dog and pizza ' have higher probability of being the member of the set of things that eat. Maybe it is a lambda calculus thing, i live this to the experts

**Comment by ngeiswei** [comment]
I don't mean "the set things that eat", I mean "the set of pairs (X, Y), so that X eats Y"

**Comment by AmeBel** [comment]
well that makes sense

**Comment by bgoertzel** [comment]
I think implicit BindLinks are OK so long as the documentation is clear and
consistent with good working examples (not currently the case)

On Tue, Mar 17, 2015 at 5:08 PM, ngeiswei <notifications@github.com> wrote:

> Yeah, the reason is because as defined in the page SatifyingSetLink acts
> as a lambda
>
> http://wiki.opencog.org/w/SatisfyingSetLink#Truth_values
>
> except that if we assume
>
> EvaluationLink
>     P
>     $X
>
> also implicitly acts as a lambda, then no need of having SatifyingSet acts
> as a lambda again.
>
> I think it would be simpler if we had a LambdaLink (better name than
> BindLink) and never assumes anything acts implicitly as a lambda. Of course
> that's at the price of clobbering the hypergraphs with LambdaLink all over
> the place. I am more fearful of inconsistency than verbosity, that is why I
> would favor a LambdaLink only, no implicit lambda. It's still a judgment
> call though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1424#issuecomment-82220155>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by ngeiswei** [comment]
OK, first I suggest we remove variable binding from SatisfyingSet.

I found SatisfyingSetLink uses in
```
python/pln/examples/relex2logic/syllogisms/disjunctive-syllogism.scm
python/pln/examples/relex2logic/syllogisms/conditional-syllogism.scm
```
The version of SatisfyingSetLink they use do *not* incorporate variable binding.

However there is one use of SatisfyingSetLink that incorporates binding
```
python/pln/rules/direct_evaluation_rules.py
```
but we don't care since this code is going obsolete anyway.

So I think we all agree that the wiki page should be corrected accordingly (to remove the first argument for binding).

I'll wait for Linas feedback since he is the main contributor of that page...

**Comment by ngeiswei** [comment]
Oh! Actually they're all from the obsolete python PLN version!

But there's another use in
```
nlp/relex2logic/rule-helpers.scm
```
and withing the same file I can find SatifyingSetLink with binding and without binding!!!

Well, maybe the binding could be made optional, but what for? If EvaluationLink automatically binds its free variables with a lambda, then no need of that extra binding. And if it doesn't, no need of that extra binding either (cause then it's better to have an explicit BindLink or LambdaLink anyway!)

**Comment by AmeBel** [comment]
what do you mean by "... within the same file I can find SatifyingSetLink with binding and without binding!!!"?

**Comment by ngeiswei** [comment]
I mean that within the file rule-helpers.scm you find things like:

```
			(SatisfyingSetLink df-link-stv
				(VariableNode var_name) 	
				(EvaluationLink df-link-stv (PredicateNode verb_instance df-node-stv)
					(ListLink df-link-stv
						(ConceptNode subj_instance df-node-stv)
						(VariableNode var_name df-node-stv)
					)
				)
			)
```
and things like
```
(SatisfyingSetLink (PredicateNode instance df-node-stv) df-link-stv)
```
Note that the first use of SatisfyingSetLink has 2 arguments (a VariableNode and an EvaluationLink), while the second has only one argument (a PredicateNode).

**Comment by linas** [comment]
Perhaps we could support both implicit and explicit forms. so -- 

Implicit declaration is OK, although the code that actually does things, under the covers, typically needs the explicit declaration. It can obtain this by searching for all VariableNodes; this is not hard to do, but its one more minor step.

But surely there are expressions that might involve multiple VariableNodes, only one of which is bound?   consider: the set of things that can eat something, and the set of things that can be eaten by someone.  The first is naturally
```
SatisfyingSetLink
     VariableNode "$eater"
     EvaluationLink
       PredicateNode "eat"
       ListLink
         VariableNode "$eater"
         VariableNode "$food"
```

Is there a way of saying the above, without having to use two VariableNodes in it?  Keep in min that we cannot assume that a predicate always has two places:  there can also be three-place predicates:  for example "X criticizes Y for Z" which is not really reducible to a bunch of two-place predicates.

**Comment by ngeiswei** [comment]
I can think of 3 reasons not to use implicit BindLink/LambdaLink:

1. It make introduce ambiguities, for instance in
```
    ImplicationLink
        EvaluationLink
            PredicateNode "eat"
            ListLink
                VariableNode $X
                VariableNode $Y
        EvaluationLink
            PredicateNode "big"
            VariableNode $X
```
you may want to say 
```
BindLink
    $Y
    ImplicationLink
        BindLink
            $X
            EvaluationLink
                PredicateNode "eat"
                ListLink
                    VariableNode $X
                    VariableNode $Y
            EvaluationLink
                PredicateNode "big"
                    VariableNode $X
```
which corresponds to a predicate (due to the last BindLink)

or

```
    ImplicationLink
        BindLink
            ListLink
$X
            EvaluationLink
                PredicateNode "eat"
                ListLink
                    VariableNode $X
                    VariableNode $Y
            EvaluationLink
                PredicateNode "big"
                    VariableNode $X
```

**Comment by ngeiswei** [comment]
Damn, I sent inadvertently too fast... let me edit what is above.

**Comment by ngeiswei** [comment]
4. And once we use BindLink explicitly, then no need to have binding attached to SatisfyingSet.

**Comment by ngeiswei** [comment]
Now for the benefits of using implicit BindLink:

1. Save some RAM (although we don't know how much till we measure)
2. Backward compatibility with the good old (or should I say bad old) ambiguous notations.

**Comment by ngeiswei** [comment]
Oh, and here's another one, how to determine the order in which the variables are bound? According to the order of how the variables are encountered while parsing the hypergraph?

Consider the following example
```
EquivalenceLink
    EvaluationLink
        PredicateNode "eat"
        ListLink
            $X
            $Y
    EvaluationLink
        PredicateNode "is_eaten_by"
        ListLink
            $Y
            $X
```
Do you mean
```
EquivalenceLink
    BindLink
        ListLink
            $X
            $Y
        EvaluationLink
            PredicateNode "eat"
            ListLink
                $X
                $Y
    BindLink
        ListLink
            $X
            $Y
        EvaluationLink
            PredicateNode "is_eaten_by"
            ListLink
                $Y
                $X
```
or
EquivalenceLink
    BindLink
        ListLink
            $X
            $Y
        EvaluationLink
            PredicateNode "eat"
            ListLink
                $X
                $Y
    BindLink
        ListLink
            $Y
            $X
        EvaluationLink
            PredicateNode "is_eaten_by"
            ListLink
                $Y
                $X
```
That makes quite a difference. And of course here you could use the fact that $X and $Y are used in both predicates, but what if the variables are different.

Just this morning I wasn't completely sure, but the more I think about it the more I believe implicit binding is troublesome.

**Comment by linas** [comment]
Can we close this? I think all of the conceptual issues here have been resolved.

**Comment by linas** [comment]
Can we close this? I think all of the conceptual issues here have been resolved, and I don't see any outstanding work items that arise from this.

**Comment by ngeiswei** [comment]
This issue has been utterly hijacked by myself and looks terribly confusing. We're passed this debate anyway, let's close.
