### ISSUE TITLE
BackwardChainer: Rule selection problem

### ISSUE THREAD

**Issue by williampma** [opencog/opencog#1441]
It seems there is going to be some problem with rule selection.  Looking at the old PLN, the new PLN, and the PLN design at http://wiki.opencog.org/w/New_PLN_Chainer_Design#Overall_Backward_Chaining_Process  it seems the chainer chooses rules by matching the "output" (implicand of an ImplicationLink).

However, as rules become more complex (like some current on-going discussion), it becomes impossible to tell what the rule "output" will be by just looking, as the output could be wrapped inside another function that does some processing first, and spit out different results.

Is this a problem?

**Comment by bgoertzel** [comment]
That would be a big problem for the whole backward chaining methodology...

On Fri, Mar 20, 2015 at 5:57 PM, William Ma <notifications@github.com>
wrote:

> It seems there is going to be some problem with rule selection. Looking at
> the old PLN, the new PLN, and the PLN design at
> http://wiki.opencog.org/w/New_PLN_Chainer_Design#Overall_Backward_Chaining_Process
> it seems the chainer chooses rules by matching the "output" (implicand of
> an ImplicationLink).
>
> However, as rules become more complex (like some current on-going
> discussion), it becomes impossible to tell what the rule "output" will be
> by just looking, as the output could be wrapped inside another function
> that does some processing first, and spit out different results.
>
> Is this a problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1441>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by misgeatgit** [comment]
I see two  solution here:
   1.Enforcing a standard where always the first or some position in the argument list of ExecutionOutputLink to be the output.But we need a validation mechanism here.
   2.Introducing a new type of Link that wraps around the output and used as a marker

**Comment by bgoertzel** [comment]
On Fri, Mar 20, 2015 at 7:13 PM, Misgana Bayetta <notifications@github.com>
wrote:

>
> 2.Introducing a new type of Link that wraps around the output and used as
> a marker
>

I think we can use ExecutionLink for this purpose (ExecutionLink wrapped in
a LambaLink, with the pre and post condition expressed involving
variables)....  William and Amen and I discussed this a bit, I'll write
something on it late tonight or on Saturday morning...



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1441#issuecomment-83987770>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
has this been fixed? Can it be closed?

**Comment by williampma** [comment]
Has deep type been implemented in the recent months?  If not, then I think it is not fixed.

**Comment by ngeiswei** [comment]
To the best of my knowledge it hasn't been fixed.

**Comment by ngeiswei** [comment]
This has been fixed. The adopted solution is to describe the conclusion pattern as first argument of the rule formula, as explained https://wiki.opencog.org/w/URE_Configuration_Format#Defining_Rules
