### ISSUE TITLE
pattern match: Implement SatisfactionLink

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1445]
Many current uses of the pattern matcher do NOT require an ImplicationLink too be present.  Thus, the patther matcher should be able to accept the following form:
```
SatisfactionLink
    VariableDecls
    Expression
```
That is, called cog-bind on the above would cause the pattern matcher to find all groundings (all members of the satisfying set) and calling all callbacks, etc. but that is all. Perhaps we should create a new function (cog-satisfy) that does nothing but the above.  This is pursuant to the discussion in pull request #1440

A SatisfactionLink should be a kind of LambdaLink that is "true" when the expression is satisfiable. Thus, SatsifactionLink is maybe almost identical to a SatisfyingSetLink, except that ti requires explicit variable binding...!?

**Comment by linas** [comment]
Nil,

To be clear: I pickeck the name "SatisfcationLink" which is confusingly  similar to SatsifyingSetLink because I am confused about the difference between the two, if any. !?

 I'm proposing this, as well:
```
LAMBDA_LINK <- ORDERED_LINK
BIND_LINK <- LAMBDA_LINK    # for backwards compat
SATISFACTION_LINK <- LAMBDA_LINK  
FOR_ALL_LINK <-LAMBDA_LINK
EXIST_LINK <- LAMBDA_LINK
AVERAGE_LINK <- LAMBDA_LINK
```

So the last five things are all special cases of a lambda.  I am less clear about their types.  I guess they are all functions returning TV's ???

So a SatisfactionLink is "true" if the pattern matcher can find something in the atomspace that is a grounding for its bound variables.  i.e. if there is a pattern in the atomspace that satsifies it. Thus, a SatsifactionLink is kind-of-like a ThereExistsLink -- its true if the thing exists...

However, a SatisfactionLink is also kind-of-like a SatisfyingSetLink because the pattern matcher by default, can find *everything* that satisfies it.

**Comment by bgoertzel** [comment]
The SatisfyingSetLink is intended as a symbol denoting the set of all x
that fulfill the specified criteria...

It's not intended to be true iff the set of all x that fulfill the
specified criteria is nonempty ...

So in a way it's more like an ExecutionOutputLink.  The ExecutionOutputLink
is a symbol for the output of running a certain procedure.   The
SatisfyingSetLink is a symbol for the output of finding all x that fulfill
certain criteria...

Is this the same as your SatisfactionLink?

-- Ben

On Tue, Mar 24, 2015 at 4:26 AM, Linas Vepštas <notifications@github.com>
wrote:

> Nil,
>
> To be clear: I pickeck the name "SatisfcationLink" which is confusingly
> similar to SatsifyingSetLink because I am confused about the difference
> between the two, if any. !?
>
> I'm proposing this, as well:
>
> LAMBDA_LINK <- ORDERED_LINK
> BIND_LINK <- LAMBDA_LINK    # for backwards compat
> SATISFACTION_LINK <- LAMBDA_LINK
> FOR_ALL_LINK <-LAMBDA_LINK
> EXIST_LINK <- LAMBDA_LINK
> AVERAGE_LINK <- LAMBDA_LINK
>
> So the last five things are all special cases of a lambda. I am less clear
> about their types. I guess they are all functions returning TV's ???
>
> So a SatisfactionLink is "true" if the pattern matcher can find something
> in the atomspace that is a grounding for its bound variables. i.e. if there
> is a pattern in the atomspace that satsifies it. Thus, a SatsifactionLink
> is kind-of-like a ThereExistsLink -- its true if the thing exists...
>
> However, a SatisfactionLink is also kind-of-like a SatisfyingSetLink
> because the pattern matcher by default, can find *everything* that
> satisfies it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1445#issuecomment-85179509>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
SatisficationLink is intended to specify a pattern that the pattern matcher can look for. I meant to say: "a SatisfactionLink could be (for example) set "true" if the pattern matcher can find something".

There is a new scheme function, cog-satisfy, that takes a SatisfactionLink, and returns a truth value. The actual truth value that is returned ... is computed in a callback. Stupidly at the present time.

Mostly, I wanted something that works a lot like the BindLink, but does not require the ImplicationLink that BindLink does, the ImplicationLink makes things awkward something I want to do.

I'm sot-of feeling my way around here, I have a clear vision for what I want to do, but a fuzziy idea of the best way to fit that into the "grand scheme of things"

**Comment by bgoertzel** [comment]
Linas,

What I think would be useful could be

cog-find-satisfiers

or whatever, that takes a SatisfactionLink, and returns a SetLink
with MemberLinks to the Atoms found to satisfy the pattern indicated
by the SatisfactionLink.

In this case the SatisfactionLink would be acting exactly like I
was envisioning a SatisfyingSetLink to work --- that is, the
SatisfyingSetLink
is a symbol for the set of entities satisfying the pattern indicated...

I don't see a reason for SatisfactionLink to be different from
SatisfyingSetLink,
it seems to me we only need one.   Then PLN (and potentially other inference
methods can manipulate SatisfyingSetLinks, and the pattern matcher can
evaluate them, and all will be well in the world...)

-- Ben



On Sun, Mar 29, 2015 at 12:35 PM, Linas Vepštas <notifications@github.com>
wrote:

> SatisficationLink is intended to specify a pattern that the pattern
> matcher can look for. I meant to say: "a SatisfactionLink could be (for
> example) set "true" if the pattern matcher can find something".
>
> There is a new scheme function, cog-satisfy, that takes a
> SatisfactionLink, and returns a truth value. The actual truth value that is
> returned ... is computed in a callback. Stupidly at the present time.
>
> Mostly, I wanted something that works a lot like the BindLink, but does
> not require the ImplicationLink that BindLink does, the ImplicationLink
> makes things awkward something I want to do.
>
> I'm sot-of feeling my way around here, I have a clear vision for what I
> want to do, but a fuzziy idea of the best way to fit that into the "grand
> scheme of things"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1445#issuecomment-87357259>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by AmeBel** [comment]
if a,b,c satisfy the SatisfySet(x), then the returned will be
```
SetLink
  MemberLink
      a, b, c...
      SatisfySet(x)
```
or did you mean to say,

```
MemberLink
  SetLink
      a, b, c...
      SatisfySet(x)
```
? and if you meant the second one, then is SetLink a singleton set or not [(previous comment on SetLink)](https://github.com/opencog/opencog/pull/1422#issuecomment-83647609)?

**Comment by AmeBel** [comment]
updated the indentation on the second one
```
MemberLink
  SetLink
      a, b, c...
 SatisfySet(x)
```

**Comment by bgoertzel** [comment]
If we have

L :=
SatisfyingSetLink
    $X
    Pattern($X)


and a, b, c match Pattern($X), then the return of

cog-find-satisfiers L

would be

SetLink
    a
    b
    c


... at least that was my proposal...

ben




On Mon, Mar 30, 2015 at 5:47 PM, Amen Belayneh <notifications@github.com>
wrote:

> if a,b,c satisfy the SatisfySet(x), then the returned will be
>
> SetLink
>   MemberLink
>       a, b, c...
>       SatisfySet(x)
>
> or did you mean to say,
>
> MemberLink
>   SetLink
>       a, b, c...
>       SatisfySet(x)
>
> ? and if you meant the second one, then is SetLink a singleton set or not (previous
> comment on SetLink)
> <https://github.com/opencog/opencog/pull/1422#issuecomment-83647609>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1445#issuecomment-87617283>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by ngeiswei** [comment]
A decision really needs to be made!

Do we want SatisfyingSet to be
```
    SatisfyingSetLink
        <variables>
        <predicate expression>
```
or
```
    SatisfyingSetLink
        <predicate>
```

In the second version it uses a predicate already, that already encapsulates the variable bindings (with a lambdaLink for instance). While the first version uses a predicate expression that requires bindings by its parents.

I prefer the second version because it is in accordance with the PLN book and I believe is simpler.

**Comment by ngeiswei** [comment]
A decision really needs to be made!

Do we want SatisfyingSet to be
```
     SatisfyingSetLink
         <variables>
         <predicate expression>
```
or
```
     SatisfyingSetLink
         <predicate>
```

The second version uses a predicate that already encapsulates the 
variable bindings (with a lambdaLink for instance). While the first 
version uses a predicate expression that requires bindings by its parents.

I prefer the second version because it is in accordance with the PLN 
book and I perceive it as simpler.

Nil

**Comment by ngeiswei** [comment]
"I believe it", "I perceive it", words, words, words, informal words, arggg....

**Comment by ngeiswei** [comment]
I can't way for the day I can use a Handle pointing to the grand planetary AtomSpace rather than a word!

**Comment by bgoertzel** [comment]
I suppose the second is better as it enables a functional style as well as
a style with explicit variables..

On Mon, Mar 30, 2015 at 6:03 PM, ngeiswei <notifications@github.com> wrote:

> A decision really needs to be made!
>
> Do we want SatisfyingSet to be
>
>     SatisfyingSetLink
>         <variables>
>         <predicate expression>
>
> or
>
>     SatisfyingSetLink
>         <predicate>
>
> In the second version it uses a predicate already, that already
> encapsulates the variable bindings (with a lambdaLink for instance). While
> the first version uses a predicate expression that requires bindings by its
> parents.
>
> I prefer the second version because it is in accordance with the PLN book
> and I believe is simpler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1445#issuecomment-87619933>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by AmeBel** [comment]
in the second case how will the argument numbers be specified? Or that doesn't matter in the greater scheme?

**Comment by bgoertzel** [comment]
A list is a single argument ;)

**Comment by AmeBel** [comment]
@bgoertzel nice one :-)

**Comment by linas** [comment]
@ngeiswei if there are no binds, then all variables are free.  and that's OK, that's a valid expression, I guess.  But you yourself pointed out the problems that occur when some variables are bound and others are not.  Have you forgotten your doubts?  Solved them somehow?  

Also: the old wiki page for the satisfying set link he some long worked examples. The new wiki page is incomprehensible (to me) I have no clue what it is or how it works. You need to put the examples in there, and show how they actually work, with your version of the proposal.

**Comment by linas** [comment]
@bgoertzel , the pattern matcher already returns the set of atoms that satisfy it; its been doing that for 5 years now. It just stuffs them into a ListLink .  It is trivially changed to stuff them into some other link.

The satisfactionLink is meant to be completely different: it returns nothing!  That is because a variety of things simply don't need the returned set.

**Comment by linas** [comment]
Ben,  right now, here is what happens. Compare it to what you wrote
```
L :=
BindLink
    $X
    Pattern($X)
```
and a, b, c match Pattern($X), then the return of
```
cog-bind L
```
is
```
ListLink
    a
    b
    c
```

I can change the ListLink to be SetLink.

**Comment by linas** [comment]
Actually, what I just wrote is not correct. What happens today is this:
```
L :=
BindLink
    $X $Y $Z
    ImplicationLink
        Pattern($X,$Y,$Z)
        f($X,$Y,$Z)
```
and (a,k,s),   (b,l,t), (c,m,u) match Pattern($X,$Y,$Z), then the return of
```
cog-bind L
```
is

ListLink
    f(a,k,s)
    f(b,l,t)
    f(c,m,u)
```

So if you change it to just use only one variable, and use f($X) to be just $X, then you get your desired behavior (except that its not called SatsisfyingSetLink .. we could change that too .. so that SatisfyingSetLink is recognozed by the pattern matcher, and  it will throw an error if more than one variable is used!?)

**Comment by bgoertzel** [comment]
yeah, getting rid of the need for the ImplicationLink in the use of the
pattern matcher, basically makes it easy to use the BindLink as if it were
(what I used to call a) SatisfyingSetLink ...

I guess having a ListLink instead of a SetLink really does no harm,
although I'm not sure how much the order in the ListLInk actually means? ...

There are various things to be clarified here, but Nil is trying to get
some PLN stuff by done by April 3 and then goes on vacation for a few
days.... So I guess we should all three confer on this after Easter and
make some collective decisions about the various pending matters regarding
types, variables etc.


ben

On Tue, Mar 31, 2015 at 12:11 AM, Linas Vepštas <notifications@github.com>
wrote:

> Ben, right now, here is what happens. Compare it to what you wrote
>
> L :=
> BindLink
>     $X
>     Pattern($X)
>
> and a, b, c match Pattern($X), then the return of
>
> cog-bind L
>
> is
>
> ListLink
>     a
>     b
>     c
>
> I can change the ListLink to be SetLink.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1445#issuecomment-87737720>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by bgoertzel** [comment]
Well there's no fundamental difference between a list of variables and a
list-valued variable... so I don't see a problem with the way it works now
where there can be multiple variables involved

I am inclined to like Nil's idea of LambdaLink ...

But I guess we should wait a week and sort this out when Nil has spare
cycles to come to his own considered conclusions and fully join the
discussion...

On Tue, Mar 31, 2015 at 12:17 AM, Linas Vepštas <notifications@github.com>
wrote:

> Actually, what I just wrote is not correct. What happens today is this:
>
> L :=
> BindLink
>     $X $Y $Z
>     ImplicationLink
>         Pattern($X,$Y,$Z)
>         f($X,$Y,$Z)
>
> and (a,k,s), (b,l,t), (c,m,u) match Pattern($X,$Y,$Z), then the return of
>
> cog-bind L
>
> is
>
> ListLink
> f(a,k,s)
> f(b,l,t)
> f(c,m,u)
>
>
> So if you change it to just use only one variable, and use f($X) to be just $X, then you get your desired behavior (except that its not called SatsisfyingSetLink .. we could change that too .. so that SatisfyingSetLink is recognozed by the pattern matcher, and  it will throw an error if more than one variable is used!?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1445#issuecomment-87739785>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
I just changed the ListLink to SetLink: it is a single line of code. .. except for the three unit tests that expected List.   I made this change now because it seems like the right thing to do, anyway.

**Comment by inflector** [comment]
These recent changes broke the atomspace_bm benchmark since it generates random types and the new validation code doesn't like random nodes attached to validated atoms. I've updated the benchmark so that it doesn't generate random types of type BIND_LINK, SATISFACTION_LINK or LAMBDA_LINK. 

The benchmark is currently not included in any tests so there's no way for anyone to know that a change they made broke it unless they happen to run the benchmark. Most of the benchmark code is already abstracted into a class, so I'm going to add a unit test that will run a very low iteration, five- or ten-second version of the benchmark class's test all.

**Comment by bgoertzel** [comment]
I noticed the addition to the bindings of cog-satisfy and an attempt to 
port satisfy_link in the Cython bindings that was commented out. 

I fixed the Cython code so the binding now works, but I need an example 
usage to add it to my test. In this case, there is no C++ test for 
satisfy_link that I can copy from.

Linas or Ben, can you give an example of how you'd like this to work in 
scheme and I'll port it to the Python bindings test.

- Curtis

**Comment by cosmoharrigan** [comment]
Note: I posted a reply to that last question from @inflector on the mailing list.

**Comment by inflector** [comment]
The satisfaction_link Python binding now has a unit test after #1541 is merged.

**Comment by linas** [comment]
I'm closing this, because the core work has been cmpleted over the course of the last thre weeks; with #1557 being the last of that series.

The theoretical discussions still need to happen; just lets not do it here...

I'm guessing that SatisfactionLink is probably the same thing as SatisfyingSetLink, but I'm keeping the name separate until we're comfortable w/ this.  I also renamed LambdaLink to ScopeLink which I think is almost the same thing, but I wanted to avoid confusion during debate of the theory of things.

Note also: there is now the concept of ExecutionOuputLinks that are "built-in" i.e. do not need a GSN to say what to do.  GSN's are now treated as "black box", the built-in's are "clear box"

```
// Same idea as the VirtualLink, but for ExecutionOutputLinks.
// Again, the only reason that this link types exists is so that the
// pattern matcher can find them and treat them as needed.
FUNCTION_LINK <- EXECUTION_OUTPUT_LINK

// Basic arithmetic operators
PLUS_LINK <- FUNCTION_LINK
TIMES_LINK <- FUNCTION_LINK
```

Ditto: run-time evaluatable built-in links returning TV:

```
// A VirtualLink is equivalent to an EvaluationLink, with a
// GroundedPredicateNode in it, except that the GPN is "built in".
// So, for example, GreaterThanLink is equivalent to an EvaluationLink
// with a GroundedPredicateNode "c++:greater_than". The built-in
// evaluation links have better performance, since they don't need
// to make a call to external scheme or python code to get evaluated.
//
// The VirtuaLink designation is needed by the pattern matcher,
// in order to be able to find and treat these terms correctly.
//
// VirtualLinks only need to be used for those GPN's that take 2 or
// more arguments. If they take only one, then there is no reason
// for them to be delcared as virtual (at least, as far as the pattern
// matcher is concerned, with, right now, is the unly user of this
// link type.)
VIRTUAL_LINK <- EVALUATION_LINK
GREATER_THAN_LINK <- VIRTUAL_LINK
EQUAL_LINK <- VIRTUAL_LINK
```
