### ISSUE TITLE
Pattern match: implement cut operator

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1457]
Implement the cut operator for the pattern matcher.

http://en.wikipedia.org/wiki/Cut_%28logic_programming%29

This would be a CutNode.  it would appear in a clause all by itself. If it is encountered, then the system would not back-track past it to search for additional solutions.

This is an interesting idea, but there does not seem to be any immediate, pressing use for it.

**Comment by bgoertzel** [comment]
Egads!!!  OpenCog on Prolog !!!! ;o

On Thu, Mar 26, 2015 at 1:34 AM, Linas Vepštas <notifications@github.com>
wrote:

> Implement the cut operator for the pattern matcher.
>
> http://en.wikipedia.org/wiki/Cut_%28logic_programming%29
>
> This would be a CutNode. it would appear in a clause all by itself. If it
> is encountered, then the system would not back-track past it to search for
> additional solutions.
>
> This is an interesting idea, but there does not seem to be any immediate,
> pressing use for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1457>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
You mean "ProLog on OpenCog".  After implementing this, and resolving #1458 #1460 #1432, you should be able to take any prolog program, convert it in a fairly straightforward fashion, into atoms, and run it in the pattern matcher. 

As a side effect, I think it also means that you could convert STRIPS programs, and other similar things, and have those run as well.  Performance would be horrid: probably a factor of 100x or 1000x slower than modern-day systems, but the capability would be there.

**Comment by linas** [comment]
Closing; premature suggestion.
