### ISSUE TITLE
Recursion/Forward-chaining in the pattern matcher.

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1458]
Currently, forward-chaining is being developed as part of PLN.  A version of it, however, could be done in the pattern matcher, itself.  In many ways, the pattern matcher resembles the ProLog programming language, in terms of what it does.  Patterns are like ProLog programs.  The most significant missing feature is recursion (aka forward-chaining).

To support recursion, two link types are needed: DefineLink and MatchLink.  DefineLink is used to give a pattern a name:
```
DefineLink
     NameNode  "some name"
     BindLink
        ... etc.
```
while the MatchLink is use to "call" the previously defined pattern: i.e.
```
BindLink
       variable decls ...
       AndLink
             stuff.
             MatchLink
                  more stuff
```

The "more stuff" passed to the match link would need to correspond to the signature declared in the DefineLink.

Every time a MatchLink is encountered, the sub-pattern it asks for would need to be explored and grounded.

**Comment by bgoertzel** [comment]
This would be a useful feature ;-)

On Thu, Mar 26, 2015 at 1:55 AM, Linas Vepštas <notifications@github.com>
wrote:

> Currently, forward-chaining is being developed as part of PLN. A version
> of it, however, could be done in the pattern matcher, itself. In many ways,
> the pattern matcher resembles the ProLog programming language, in terms of
> what it does. Patterns are like ProLog programs. The most significant
> missing feature is recursion (aka forward-chaining).
>
> To support recursion, two link types are needed: DefineLink and MatchLink.
> DefineLink is used to give a pattern a name:
>
> DefineLink
>      NameNode  "some name"
>      BindLink
>         ... etc.
>
> while the MatchLink is use to "call" the previously defined pattern: i.e.
>
> BindLink
>        variable decls ...
>        AndLink
>              stuff.
>              MatchLink
>                   more stuff
>
> The "more stuff" passed to the match link would need to correspond to the
> signature declared in the DefineLink.
>
> Every time a MatchLink is encountered, the sub-pattern it asks for would
> need to be explored and grounded.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1458>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
Status: this is partly implemented and sort-of-ish works in some simple cases. There are a few theoretical issues I haven't yet resolved, that prevent forward progress.

The next step is to support ExecutionOutputLink in the *body* of the pattern, so that, while pattern-matching, if there is an ExecutionOutputLink in the pattern, then it is executed on the spot, and matching continues with whatever it is that it returned as the new pattern. 

There's some preliminary support for this now, but its not actually done yet.

**Comment by linas** [comment]
Closing. Things have changed a lot since this oringianl report. Much of the work has been done or is being done within the scope of https://github.com/opencog/atomspace/issues/74

**Comment by linas** [comment]
Note the above MatchLink is now called PutLink. Some notes on recursion can be found here: 

http://wiki.opencog.org/wikihome/index.php/PutLink#Recursion
