### ISSUE TITLE
Pattern match: Implement SignatureLink

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1460]
The signature link is an easy, compact way to specify atom types.  The wiki page http://wiki.opencog.org/w/SignatureLink described what a SignatureLink is, and how to convert it into an equivalent BindLink.  The http://wiki.opencog.org/w/Type_checker wiki page describes how to use the SignatureLink to perform type checking.

Implementation (including unit tests) should take no more than a few days, perhaps a week for someone unfamiliar with the atomspace.

**Comment by AmeBel** [comment]
* on TypeChoiceLink, how about when one wants to express an arbitrary length for a ListLink?For example the predicate eat could have an arity 0-2 in Englisht, AFAIK. What if a predicate x from language/perception/system/model y has n arguments? 

* on Typechecking, where does the TruthValue types fit in? For example, should PLN filter out the atom types based on the type of TVs after PatternMatching on type and structure, and other agents like wise, or should TV-type checking be part of the default implementation? [python PLN input-output list](https://docs.google.com/spreadsheets/d/1iSXwM2qSBuIXqRXzrORYM-eiI0mdUuiIE0RH3J5VTzw/edit#gid=0)

**Comment by linas** [comment]
I don't quite understand the questions. 

*The basic TypeChoic, (which takes a set of TypeNode's) has been implemented since forever, although I just changed the name today. There's a unit test for it.
* I also changed VariableTypeLink to TypeLink earlier today.
* If you want an arbitrary-length ListLink, you would just use TypeNode, for example, I beleive the following will work today
```
TypedVariableLink
   VariableNode "$i-am-a-list-link-var"
   TypeNode "ListLink"
```
and that way, VariableNode "$i-am-a-list-link-var" will match only ListLinks (of arbitrary length 0,1,2,3,4,5 ...). I suspect that there is no unit test for this, so it might be buggy.

* the proposal does not include any checks for TV types, and I don't want to add that right now, at least, not without a lot of additional discussion and thought.  Here's why: (1) if you really want to reject one TV type and accept another, you can do that today with a custom callback. But nno one does this. (2) there are several places in the pattern matcher where truth values have to be taken as crisp-logic: i..e. do one thing if the TV strength>0.5, and another if not. This shows up in the NotLink, and also in the EvaluationLink with a GroundedPedicateNode. Currently, a match is accepted only if the GPN returns a TV>0.5  (3) So it would be really cool if one could say "accept this match only if the TV is of type X, and the TV values is formula Y, and the AF is Z."  But figuring out how say that nicely and cleanly is ... not something I'm ready to think about, yet.  It would not be hard to code up: the hard part is how to describe the accept/reject criteria using nothing but atoms.  We could/should cover this via separate issue and/or wiki page.

**Comment by williampma** [comment]
I think what @AmeBel wanted for point 1:

Matching a ListLink of arbitrary length, and somehow, for everything under this ListLink, dynamically generate variables for each.  ie, dynamically generate variables bases on the arbitrary length ListLink...

Not sure if that is even possible.

**Comment by linas** [comment]
William, you seem to bee talking about that other issue (the one where I said "maybe you could use a QuoteLink") I did not really understand what was going on there at all; something about GSN scm:func returning unknown, arbitrary links with maybe-variables in them, but I did not understand the problem that needs to be solved. Perhaps you could start all over again, and explain that problem (in a new issue)?  Viz, what the input is, where the pattern matcher fits in, and what you would like the output to be, if anything was possible.  But I'm pretty sure that problem is unrelated to this proposal, which is pretty narrow and specific, and related to Nil's type-checking work.

**Comment by linas** [comment]
BTW .. implementing the type checker as a bindlink would be easy, but perhaps slow and wasteful of cpu resources ... it would be straightforward to just do a simple, direct comparison... after all, typechecking is a guaranteeed hlating problem :-)

**Comment by linas** [comment]
There are two ways to think about type-checking. If all types are constants, then a type-checking algorithm is a simple tree walk, and using the pattern matcher is complete overkill for that. Tree walks are guaranteed to always halt in finite time. However, if there are type variables and type equations, where we say "we want node A to be the same type as node B", or if we say "we want link B to be a subtype of link A", then the full pattern matcher is needed, as a simple tree walk is insufficent to solve type equations and type inequalities.

**Comment by linas** [comment]
Idea: have fuzzy matching be like a loose form of type checking.  This is the current course I'm pursuing for adding fine-grained fuzzy to the pattern matcher  (the current fuzzy matcher is all or nothing; I want to instead have a match where some parts are mandatory and precise, and some parts are fuzzy)

**Comment by linas** [comment]
This pull req https://github.com/opencog/atomspace/pull/551 should cover everything discussed here. Will close shortly.
