### ISSUE TITLE
PLNTest Failed

### ISSUE THREAD

**Issue by aurelien-rainone** [opencog/opencog#1476]
as seen on the build bot, since some days, this test is always failing
<pre>
95/161 Testing: AllPythonModuleTests
95/161 Test: AllPythonModuleTests
Command: "/usr/local/bin/nosetests" "-vs" "--with-doctest" "/home/buildslave/slave/opencog_master_trusty/source/tests/python/"
Directory: /home/buildslave/slave/opencog_master_trusty/source/build/tests/python
"AllPythonModuleTests" start time: Mar 29 02:29 UTC
Output:
----------------------------------------------------------
Testing the bfs function ... SKIP: Unit test disabled, see: https://github.com/opencog/opencog/issues/1280
test_conjunctions (test_anaphora.AnaphoraUnitTester) ... ;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/build/opencog/reasoning/pln/pln_types.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/build/opencog/reasoning/pln/pln_types.scm.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/build/opencog/reasoning/pln/pln_types.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/build/opencog/reasoning/pln/pln_types.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getChildren.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getChildren.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getChildren.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getChildren.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_WordInstanceNode.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_WordInstanceNode.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_WordInstanceNode.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_WordInstanceNode.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_ParseNode.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_ParseNode.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_ParseNode.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getNumberNode_ParseNode.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/connectRootsToParseNodes.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/connectRootsToParseNodes.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/connectRootsToParseNodes.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/connectRootsToParseNodes.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllNumberNodes.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllNumberNodes.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllNumberNodes.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllNumberNodes.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllParseNodes.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllParseNodes.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllParseNodes.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getAllParseNodes.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getConjunction.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getConjunction.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getConjunction.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getConjunction.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getParseNode.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getParseNode.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getParseNode.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getParseNode.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getWords.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getWords.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getWords.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/getWords.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/isIt.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/isIt.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/isIt.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/isIt.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#1.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#1.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#1.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#1.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#2.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#2.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#2.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#2.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#3.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#3.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#3.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#3.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#4.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#4.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#4.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#4.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#5.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#5.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#5.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#5.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#6.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#6.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#6.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#6.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#7.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#7.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#7.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#7.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#8.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#8.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#8.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#8.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#9.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#9.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#9.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#9.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#10.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#10.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#10.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#10.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#11.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#11.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#11.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#11.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#12.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#12.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#12.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#12.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#13.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#13.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#13.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#13.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#14.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#14.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#14.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#14.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#15.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#15.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#15.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#15.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#16.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#16.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#16.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#16.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#17.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#17.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#17.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#17.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#18.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#18.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#18.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslavok
Testing the getWords function ... ok
test_pleonastic_if (test_anaphora.AnaphoraUnitTester) ... ok
Testing the propose function ... SKIP: Unit test disabled, see: https://github.com/opencog/opencog/issues/1280
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
test_all (test_rules_new.PLNUnitTester) ... FAIL
test_restapi.TestRESTApi.test_delete_link ... ok
test_restapi.TestRESTApi.test_delete_node ... ok
test_restapi.TestRESTApi.test_dot_export ... ok
test_restapi.TestRESTApi.test_get_atoms_by_av ... ok
test_restapi.TestRESTApi.test_get_types ... ok
test_restapi.TestRESTApi.test_include_incoming_outgoing ... ok
test_restapi.TestRESTApi.test_post_and_get_link ... ok
test_restapi.TestRESTApi.test_post_and_get_node ... ok
test_restapi.TestRESTApi.test_post_revise_existing_link ... ok
test_restapi.TestRESTApi.test_post_revise_existing_node ... ok
test_restapi.TestRESTApi.test_put_and_get_tv_av_link ... ok
test_restapi.TestRESTApi.test_put_and_get_tv_av_node ... ok
test_restapi.TestRESTApi.test_scheme_command ... ok
test_restapi.TestRESTApi.test_tv_filter ... ok

======================================================================
FAIL: test_all (test_rules_new.PLNUnitTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/slave/opencog_master_trusty/source/tests/python/test_pln/test_rules_new.py", line 96, in test_all
    self.run_file(testFile)
  File "/home/buildslave/slave/opencog_master_trusty/source/tests/python/test_pln/test_rules_new.py", line 268, in run_file
    self.verify_result()
  File "/home/buildslave/slave/opencog_master_trusty/source/tests/python/test_pln/test_rules_new.py", line 247, in verify_result
    self.assertTrue(allPredictedItemsExist and allItemsWerePredicted)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 23 tests in 2.731s

FAILED (SKIP=5, failures=1)
Testing file: /home/buildslave/slave/opencog_master_trusty/source/tests/python/test_pln/new_scm_tests/AndRule_new.scm
Checking if all predicted items were created:
Unable to find 
(AndLink (av 0 0 0) (stv 0.160000 0.650000)
  (ConceptNode "A" (av 0 0 0) (stv 0.800000 0.800000)) ; 
  (ConceptNode "B" (av 0 0 0) (stv 0.200000 0.650000)) ; 
) ; 

  No, not all predicted items were created (see above for details)
Checking if all created items were predicted:
Unable to find 
(AndLink (av 0 0 0) (stv 0.640000 0.800000)
  (ConceptNode "A" (av 0 0 0) (stv 0.800000 0.800000)) ; 
  (ConceptNode "A" (av 0 0 0) (stv 0.800000 0.800000)) ; 
) ; 

  No, some created items were not predicted (see above for details)
e/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/filters/filter-#18.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#1.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#1.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#1.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#1.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#2.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#2.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#2.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#2.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#3.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#3.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#3.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pre-process/pre-process-#3.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#1.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#1.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#1.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#1.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#2.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#2.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#2.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#2.scm.go
;;; note: source file /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#3.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#3.scm.go
;;; compiling /home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#3.scm
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/buildslave/slave/opencog_master_trusty/source/opencog/nlp/anaphora/rules/pleonastic-it/pleonastic-it-#3.scm.go
<end of output>
Test time =   2.87 sec
----------------------------------------------------------
Test Failed.
"AllPythonModuleTests" end time: Mar 29 02:29 UTC
"AllPythonModuleTests" time elapsed: 00:00:02
----------------------------------------------------------

</pre>

**Comment by inflector** [comment]
Aurelien, can you change the title to PLNTest Failed since I recently separated out all the Python tests into their own unit tests so names were more instructive.

**Comment by aurelien-rainone** [comment]
done!

**Comment by ngeiswei** [comment]
If that PLNUTest refers to the Python version of PLN, it would be better if it is renamed PythonPLNUTest, right?

**Comment by aurelien-rainone** [comment]
i'll let @inflector answer here. Siince i created the issue, i didn't follow the refactoring of the python tests.
Just tell me and i'll rename it

**Comment by ngeiswei** [comment]
Yeah, I'm just saying cause the python version of PLN is going obsolete, so it would be less confusing.

**Comment by inflector** [comment]
@ngeiswei Since it is going away, is anyone going to fix the breakage in the PLNTest written in Python? If so, I'll rename it. If not, then I'll remove it.

**Comment by inflector** [comment]
I just submitted a pull request with the name change. Still, I'm curious if you aren't going to fix the problem (in the test or the Python PLN), it might be better to remove the test.

**Comment by ngeiswei** [comment]
I think it's OK to disable that test. Then eventually python PLN should be completely removed as well.

**Comment by inflector** [comment]
@ngeiswei Okay, I just submitted a pull request that skips this test so it passes with the note in the test log that Python PLN is deprecated. Please merge that request and close this issue when you have done so. Thanks
