### ISSUE TITLE
Build error triggered by #1516

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#1518]
@inflector this issue is to track the build error triggered by #1516 as noted here: https://github.com/opencog/opencog/pull/1516#issuecomment-91679842

**Comment by inflector** [comment]
Hey Cosmo, I won't be able to get to this for a while. Can you easily rollback the changes. I think I see what I missed. Doesn't show up for make only for make -j >1

**Comment by linas** [comment]
doesn't show up for make -janything for me ...

**Comment by cosmoharrigan** [comment]
It builds successfully for me on my machine as well. Hence, I'm not sure that it's necessary to revert the change immediately. Rather, when you are back perhaps you can check what might be the cause of it not building on Buildbot. Thanks.

**Comment by linas** [comment]
It might be a race condition in the dependencies .. with -j6, it could
happen that the thing being used has not yet been built.  You'd need to
tweak some cmakefile somwhere, and add the dependency

**Comment by inflector** [comment]
Just submitted a pull request, #1523 which should fix this problem.

The generated files are now going to the build directory and type_constructors.pyx just includes them.

**Comment by cosmoharrigan** [comment]
Thanks. 'make' succeeds now on Buildbot, but 'make tests' fails. However, I can't tell whether that failure is related to this or not, can you? http://buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/451/steps/compile_2/logs/stdio

**Comment by inflector** [comment]
It's possible but I didn't touch the scheme type generation code. At least not intentionally.

**Comment by inflector** [comment]
That test builds on my machine just fine, as well.

**Comment by inflector** [comment]
@AmeBel Do you have access to the buildbot machine?

**Comment by inflector** [comment]
Actually, that isn't a test that's a distribution script. It doesn't build as a target for me. Perhaps because I am missing some of the cmake dependencies for embodiment?

Nevertheless, I have the file in the place it is expecting to find it, as that's the main core_types.scm file for atomspace.

So that's probably not an error I caused, but I'm still a bit suspicious since it is one of the generated files and I most definitely was in the code for auto-generation of types.

Hopefull, @AmeBel can get more information about the missing file.

**Comment by AmeBel** [comment]
The core_types.scm is not being created. To reproduce, run in build directory
```
$ rm -rf *
$ cmake ..
$ make -j$(nproc)
$ make test
```

**Comment by inflector** [comment]
Yep, I somehow typed a 'd' over the 'm' in 'core_types.scm' in the OPENCOG_ADD_ATOM_TYPES macro. This is fixed in pull request #1527.

**Comment by inflector** [comment]
@cosmoharrigan This shows fixed on buildbot now after #1527 was merged.

**Comment by cosmoharrigan** [comment]
Thanks.
