### ISSUE TITLE
Hardwired build path in type_constructors.pyx

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1525]
In file
```
opencog/cython/opencog/type_constructors.pyx
```
the includes
```
include "../../../build/opencog/atomspace/core_types.pyx"
include "../../../build/opencog/embodiment/AtomSpaceExtensions/embodiment_types.pyx"
include "../../../build/opencog/nlp/types/nlp_types.pyx"
include "../../../build/opencog/reasoning/pln/pln_types.pyx"
include "../../../build/opencog/spacetime/spacetime_types.pyx"
include "../../../build/opencog/dynamics/attention/attention_types.pyx"
```
are hardwired, I can't compile it under build-debug for instance.

I tried to hack the path with PROJECT_BINARY_DIR without success. Given I don't know much about Cython I prefer to let it to the expert.

**Comment by inflector** [comment]
Sorry, I didn't know that others were using different build directories. I'm fairly new to linux builds and CMake. Spent far too much time in Mac and Windows land.

@ngeiswei Pull request #1527 fixes this issue.

**Comment by ngeiswei** [comment]
It fixes the issue as far as I can tell, so I'm closing.
