### ISSUE TITLE
Clean obsolete PLN code and documentation

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1539]
The obsolete C++ and Python versions of PLN are still documented on the wiki

wiki.opencog.org/w/Category:PLN-Obsolete
http://wiki.opencog.org/w/New_PLN_Design,_2013
etc...

I don't think keeping everything and putting under the obsolete category is a good idea, we need to simplify as much as possible. I don't see any point keeping those pages unless they contain some really interesting material, and in such a case then should be moved to a better place.

The obsolete Python version of PLN is still in the repo, both code and documentation

opencog/reasoning/RuleEngine/README.md (that one is really confusing!!!!)
opencog/python/pln

under python/pln/examples there are still used and usable scheme code. Either I can let that in here and rename pln by pln_obsolete. Or move the scheme code under say

opencog/reasoning/scm

Let me know if you have any feedback before I start butchering all that.

**Comment by AmeBel** [comment]
On the python PLN, i think it is best to keep it untill the new PLN is working cosistently and we have resolved the representation issues so as to port all the rules, examples and unit tests before butchering it.

**Comment by AmeBel** [comment]
For me, it would be great if 
* the scheme-binding to URE/PLN works
* a python binding is added, for making mind agents
* the way to use the control policy is clearly documented. 
* the difference between URE and PLN is clearly documented. At present it is not clear how the PLN implementation is different/similar from URE,  at least for those of us who are not C++ gurus.

**Comment by ngeiswei** [comment]
@AmeBel I agree on both points, so

1. I'll rename python/pln by python/pln_old for now

we may decide to remove it entirely once the port is complete

2. I'll strive toward making the difference between URE and PLN clear (it's not really clear to myself either BTW).

Thanks for the feedback.

**Comment by williampma** [comment]
The "pln" folder under "rule-engine-src" really shouldn't be named so, as it's just rule engine code.  The "pln" folder under "reasoning" however, I have no idea what that is.  I think maybe it should have been "pln-type" or something.

In fact, it would be great to change "rule-engine-src" to something else.  It always bugged me there is a "src" folder when the whole opencog folder is already for source.

I am also not sure why "RuleEngine" is under "reasoning".  What would be "reasoning" without "RuleEngine"?  Is the whole "reasoning" already about the "RuleEngine"?  If so, "RuleEngine" stuff might need to move one folder up.

Maybe this structure like this would be better?

```
reasoning\pln-type
reasoning\rules
reasoning\engine
reasoning\engine\forwardchainer
reasoning\engine\backwardchainer
```

**Comment by AmeBel** [comment]
At high level, my understanding was that the universal/unified rule engine is more generic and the default implementation will have functionality some what similar to a [decision engine](http://en.m.wikipedia.org/wiki/Business_rules_engine) and PLN is a specialized form differentiated with its approach of choosing atoms while forward chaining in addition to it being capable of backward chaining. Maybe @linas's FSM merge is more like the decision engine ?????

**Comment by AmeBel** [comment]
By the way the immediate use case for URE is for porting relex2logic from the java implementation, regardless of r2l's redesign.

**Comment by cosmoharrigan** [comment]
@AmeBel following up on your link to the "Business rules engine" Wikipedia article, for fun, here are some more relevant Wikipedia articles to describe the URE concept:
http://en.wikipedia.org/wiki/Production_system
http://en.wikipedia.org/wiki/Inference_engine
http://en.wikipedia.org/wiki/Rewriting#Term_rewriting_systems
http://en.wikipedia.org/wiki/Abstract_rewriting_system
http://en.wikipedia.org/wiki/Formal_grammar
http://en.wikipedia.org/wiki/Rete_algorithm

**Comment by ngeiswei** [comment]
I've added the PLN subcategory "Atom PLN Semantics"

http://wiki.opencog.org/w/Category:Atom_PLN_Semantics

The idea is to add for every relevant atom type a section "PLN Semantics" plus
```
[[Category:Atom PLN Semantics]]
```
at the end of the page.

I've already added many atoms, more needs to be added.

**Comment by ngeiswei** [comment]
Continuing on William suggestion to re-organize the folder tree structure, I suggest the following
```
reasoning/engine
reasoning/engine/backwardchainer
reasoning/engine/forwardchainer
reasoning/pln
reasoning/pln/rules
reasoning/p2l
reasoning/p2l/rules
```
I've remove pln-types as those atom types definitions have been moved to spacetime and atomspace atom type scripts.

I'm still not sure whether I should have
```
reasoning/rules/pln
reasoning/rules/p2l
```
or
```
reasoning/pln/rules
reasoning/p2l/rules
```

**Comment by linas** [comment]
The finite-state-machine demo was not meant to compete with URE.  Although
FSM state transitions "rules" are kind-of-like URE rules, I've been
assuming that the URE is much more than just an FSM.

The FSM is meant for scripting robot behaviors (e.g. if someone smiled at
you, then smile back, else frown.) and its a demo showing how this could be
done.

The markov chain demo is more interesting, because its like an FSM, but
with different probabilities for transitioning to different states.

There are some very interesting questions about where probabilities could
be computed and updated, but that is a different discussion. (I noticed
that there is a certain part of the pattern matcher callback, the
"evaluation callback", where it would be "natural" to implement different
kinds of TV update rules.  This might be a good place to put PLN TV
computations. The default evaluation rules implemented there are
crisp-logic boolean rules)

**Comment by ngeiswei** [comment]
Sorry I don't understand what the FSM demo has to do with that. I'm merely trying to get a more structure ruleEngine/PLN/R2L code. Rapidly trying to search the string "fsm", I got a hit in the nlp folder, maybe that is where the confusion occured, nlp vs pln?

**Comment by linas** [comment]
Amen made a reference to my recent addition of a "finite state machine"
(FSM) demo. It is in the /examples/pattern-matcher folder. There are
actually three demos: a simple FSM, a generic FSM, and a Markov chain
(probabilistic FSM).  The state-transition rules are just some very simple
evaluation links.

For the markov chain rules I used ContextLinks to encode the conditional
probabilities of the state transitions.

I am toying with the idea of creating a simple pattern matcher callback
that would handle generic Bayesian probability via the TV's on
ContextLinks.  It would "generalize" the current default callback, which
just uses true/false TV's on AndLink OrLink, NotLink, Thus, with the
probabilistic callback, AndLink becomes P(A and B)  OrLink becomes P(A or
B), NotLink becomes P(not A) and ImplicationLink becomes the conditional
probability P(B|A)

I think it would be a "neat trick"; it could be a compliment to the
stronger PLN, giving a simple way of doing "Bayesian reasoning".  I dunno.
its a half-finished idea.

**Comment by ngeiswei** [comment]
I believe this has been sorted for now. I'm closing the issue.
