### ISSUE TITLE
broken sudo make install

### ISSUE THREAD

**Issue by artifacer** [opencog/opencog#1546]
Compiled master smoothly on fedora 20 after minor modification:

$ git diff
diff --git a/lib/zmq/zhelpers.hpp b/lib/zmq/zhelpers.hpp
index 5aaeeb8..be09d3f 100644
--- a/lib/zmq/zhelpers.hpp
+++ b/lib/zmq/zhelpers.hpp
@@ -26,8 +26,8 @@

 //  Include a bunch of headers that we will need in the examples

-#include <zmq.hpp>
-//#include <lib/zmq/zmq.hpp>
+//#include <zmq.hpp>
+#include <lib/zmq/zmq.hpp>
 // todo: package updated zmq.hpp

 #include <iostream>

But then, sudo make install gives:
[..]
-- Installing: /usr/local/lib64/opencog/libdimensionalembedding.so
-- Set runtime path of
"/usr/local/lib64/opencog/libdimensionalembedding.so" to
"/usr/local/lib/opencog"
-- Up-to-date: /usr/local/include/opencog/pleasure/generation.hpp
-- Up-to-date: /usr/local/include/opencog/pleasure/generation_table.hpp
-- Up-to-date: /usr/local/include/opencog/pleasure/node_list.hpp
-- Up-to-date: /usr/local/include/opencog/pleasure/population.hpp
-- Up-to-date: /usr/local/include/opencog/PatternMiner/Pattern.h
-- Up-to-date: /usr/local/include/opencog/PatternMiner/HTree.h
-- Up-to-date: /usr/local/include/opencog/PatternMiner/PatternMiner.h
-- Up-to-date:
/usr/local/include/opencog/reasoning/RuleEngine/rule-engine-src/ForwardChainer.h
CMake Error at
opencog/reasoning/RuleEngine/rule-engine-src/cmake_install.cmake:36
(FILE):
  file INSTALL cannot find

"/home/user/github/opencog/opencog/opencog/reasoning/RuleEngine/rule-engine-src/pln/Chainer.h".
Call Stack (most recent call first):
  opencog/reasoning/RuleEngine/cmake_install.cmake:37 (INCLUDE)
  opencog/reasoning/cmake_install.cmake:38 (INCLUDE)
  opencog/cmake_install.cmake:40 (INCLUDE)
  cmake_install.cmake:38 (INCLUDE)

make: *** [install] Error 1

The file is indeed not in that directory:
$ ls
/home/user/github/opencog/opencog/opencog/reasoning/RuleEngine/rule-engine-src/pln/
BCPatternMatch.cc   DefaultForwardChainerCB.cc
ForwardChainInputMatchCB.cc    ForwardChainer.cc         PLNCommons.h
BCPatternMatch.h    DefaultForwardChainerCB.h
ForwardChainInputMatchCB.h     ForwardChainer.h          PLNModule.cc
BackwardChainer.cc  FCMemory.cc
ForwardChainPatternMatchCB.cc  ForwardChainerCallBack.h  PLNModule.h
BackwardChainer.h   FCMemory.h
ForwardChainPatternMatchCB.h   PLNCommons.cc

currently I am on commit 7898adfc5886c33428f4364acb0fbb142edadcf7
(Date:   Fri Apr 17 18:17:36 2015 +0800), but I have tried it with few
older versions from the last few days, and I got the same result.

Maybe cmake output is relevant:
$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Build type: Release
-- Found libbfd: /usr/lib64/libbfd.so
-- Binutils found.
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105400 found.
-- Found Boost::program_options
-- Found Boost::math
-- GHC was found.
-- GSL found.
-- Guile (2.0.11 >= 2.0.0) was found.
-- HyperTable was not found. Make sure HYPERTABLE_LIBRARY and HYPERTABLE_INCLUDE_DIR are set.
-- Hypertable not found; the experimental distributed persistence DB needs it.
-- Found libiberty: /usr/lib64/libiberty.a
-- Libiberty found.
-- A library with BLAS API not found. Please specify library location.
-- LAPACK requires BLAS
-- A library with LAPACK API not found. Please specify library location.
-- LAPACK missing: needed for blopex-based clustering.
-- link-grammar( >= 4.7.12) was not found. Make sure LINK_GRAMMAR_LIBRARY, LINK_GRAMMAR_INCLUDE_DIR and LINK_GRAMMAR_DATA_DIR are set.
-- Link Grammar missing: needed for the Viterbi parser.
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
-- MPI missing: needed for MPI-MOSES.
-- OpenGL was found.
-- Protobuf was not found. Make sure PROTOBUF_LIBRARY and PROTOBUF_INCLUDE_DIR are set.
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Protobuf was not found; the new message decoding functions would not work.
   To over-ride, make sure PROTOBUF_LIBRARIES and PROTOBUF_INCLUDE_DIRS are set.
-- Python libs found.
-- Cython ( 0.21.1 >= 0.19.0) found.
-- Python destination dir found: /usr/lib/python2.7/site-packages
-- SDL was found.
-- SDL_gfx was found
-- Found Intel TBB
-- 
-- Could NOT find TCL (missing:  TCL_INCLUDE_PATH) 
-- Could NOT find TCLTK (missing:  TCL_INCLUDE_PATH TK_LIBRARY TK_INCLUDE_PATH) 
-- Could NOT find TK (missing:  TK_LIBRARY TK_INCLUDE_PATH) 
-- TCL shell was found here: /bin/tclsh
-- UnixODBC was found.
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- VALGRIND missing: needed for thread debugging.
-- Found Xerces 3.1.1 -- /usr/lib64/libxerces-c.so
-- Found ZeroMQ library: /usr/lib64/libzmq.so
-- Detected ZeroMQ version number: 3.2.4
-- ZeroMQ was found.
CMake Warning at tests/persist/sql/CMakeLists.txt:51 (MESSAGE):
  SQL database not configured for unit tests! See the README!

The following components will be built:
-----------------------------------------------
   AtomSpace          - A weighted and typed hypergraph database.
   Attention          - Agents for attention allocation dynamics.
   ComboReduct        - Library for reduction of combo program trees.
   Cython bindings    - Cython (python) bindings.
   Dim. Embedding     - Compute dimensional embedding of the AtomSpace.
   Doxygen            - Code documentation.
   Embodiment         - Architecture for embodiment.
   Feature selection  - MOSES based feature selection tool.
   GTK Visualizer     - GTK3-based Atomspace Visualizer.
   MOSES              - Meta-Optimizing Semantic Evolutionary Search.
   Python tests       - Python bindings nose tests.
   Scheme bindings    - Scheme bindings and shell.
   Server             - The CogServer.
   Spatial            - Vizualisation of the 3D spacemap.
   SQL persistance    - Save/Restore of AtomSpace to database.
   StackPrint         - Pretty printing of stack traces.
   Ubigraph           - Visualisation of the AtomSpace.
   Unit tests         - Unit tests.
   Util               - General utility library.
   ZMQ                - ZMQ-based OAC GUI reports, AtomSpace publisher module.
   TBB                - Intel TBB (Threaded Building Blocks) for multithreading.

The following components WILL NOT be built:
-----------------------------------------------
   Blopex             - BLOPEX block eigenvalue solver.
   Hypertable         - HyperTable for scalable persistance (experimental).
   Viterbi            - Viterbi Parser for Link Grammar.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/github/opencog/opencog/build

**Comment by cosmoharrigan** [comment]
Note: this was previously reported in issue #239

**Comment by artifacer** [comment]
Thanks for the heads up regarding #239
I am not sure it is the same issue, and I didn't see there any
directions for a solution.

My problem: I just see a missing Chainer.h file (there are
BackwardChainer.h and ForwardChainer.h though).

Being a noob with this codebase - I am not sure how to continue.
I have seen no clues on wiki.opencog.org/w/Make_install
Is it safe to just skip the installation of that file?

Does the problem have to do with using fedora 20 distribution?
My python version is 2.7.5
Is there any recommended distribution where this this issue doesn't happen?

**Comment by AmeBel** [comment]
@cosmoharrigan  refered #239 because make install has been broken for a while. You don't need to install to run opencog. Refer to http://wiki.opencog.org/w/Building_OpenCog on how to build.

For fedora dependencies refer to https://github.com/AmeBel/opencog/blob/install-scripts/scripts/install-fedora-dependencies.sh . It has been tested for build but is failing for tests, on fedora 21 docker image. It is still a work in progress.

**Comment by linas** [comment]
I believe I've fixed all (or most of) the issues.  see #239 

The installed cogserver runs, and with an appropriate opencog.conf file, cogserver-module loading works, scheme module loading works, python works from the cogserver telnet interface. ptython module loading might still be broken, will test and fix this soon.

**Comment by linas** [comment]
closing; this is a stale report with no recent action and I think this is fixed.
