### ISSUE TITLE
python/pln/example/deduction/deduction_example.py doesn't work

### ISSUE THREAD

**Issue by 020794** [opencog/opencog#1552]
the script output is: 
$ python deduction_example.py 
--- History:
set([])

the content of pln_log.txt is:
; Number of atoms in atomspace after inference: 17
(ConceptNode "Peter") ; [13]

(ConceptNode "Being") ; [6]

(ConceptNode "Animal") ; [5]

(ConceptNode "Slimy") ; [4]

(ConceptNode "Intelligent") ; [3]

(ConceptNode "Frog") ; [2]

(VariableNode "$standardize_apart_") ; [17]

(VariableNode "$pln_var_") ; [15]

(InheritanceLink (stv 1.000000 0.000000)
  (VariableNode "$standardize_apart_") ; [17]
  (VariableNode "$standardize_apart_") ; [17]
) ; [18]

(InheritanceLink (stv 0.900000 0.111111)
  (ConceptNode "Peter") ; [13]
  (ConceptNode "Frog") ; [2]
) ; [14]

(InheritanceLink (stv 1.000000 0.000000)
  (VariableNode "$pln_var_") ; [15]
  (VariableNode "$pln_var_") ; [15]
) ; [16]

(InheritanceLink (stv 0.900000 0.111111)
  (ConceptNode "Animal") ; [5]
  (PredicateNode "Moves") ; [7]
) ; [12]

(InheritanceLink (stv 0.900000 0.111111)
  (ConceptNode "Animal") ; [5]
  (ConceptNode "Being") ; [6]
) ; [11]

(InheritanceLink (stv 0.900000 0.111111)
  (ConceptNode "Frog") ; [2]
  (ConceptNode "Animal") ; [5]
) ; [10]

(InheritanceLink (stv 0.500000 0.111111)
  (ConceptNode "Frog") ; [2]
  (ConceptNode "Slimy") ; [4]
) ; [9]

(InheritanceLink (stv 0.200000 0.111111)
  (ConceptNode "Frog") ; [2]
  (ConceptNode "Intelligent") ; [3]
) ; [8]

(PredicateNode "Moves") ; [7]

**Comment by AmeBel** [comment]
The python PLN is deprecated, we are still in the process of moving all the rules and examples to the new implementation @ https://github.com/opencog/opencog/tree/master/opencog/reasoning/RuleEngine/rule-engine-src/pln . 

But, there seems to be a bug or the code base is out of sync with the recent python binding changes. @inflector would you comment on this?

**Comment by 020794** [comment]
It seems to be caused by get_atoms_in_attentional_focus(in atomspace_detail.pyx) always returns None.

**Comment by inflector** [comment]
I didn't change the bindings for get_atoms_in_attentional_focus at all. They're the same as they've always been unless you call the x version xget_atoms_in_attentional_focus which uses the new Python generator / yield semantics to avoid creating and copying a Python List.

I don't see how get_atoms_in_attentional_focus would ever return a None.

@020794 How are you determining that get_atoms_in_attentional_focus always returns None?

**Comment by inflector** [comment]
Are you sure it is not just returning an empty list?

@AmeBel What do you suggest I look at to determine whether or not this is a bug in the bindings? I'm not sure what potential "bug" you are pointing to.

**Comment by AmeBel** [comment]
@inflector the example used to run, a few months ago. Since no changes have been made to the python pln, i made an assumption that the recent python changes may have touched something. I haven't tried to find the failing point.

**Comment by linas** [comment]
But python-pln is obsolete; can we close this bug?

**Comment by ngeiswei** [comment]
I took the freedom to close it.
