### ISSUE TITLE
SudokuUTest failing on make test

### ISSUE THREAD

**Issue by sigkill** [opencog/opencog#1556]
Hello,

I see that the pattern matcher notes on SudokuUTest seem to state that the more complex portion of the test is currently broken - is this expected to cause a failure of the entire make test?

Out of all tests this is the only one failing on my system and I'm curious if I should poke at it more or if the failure is expected for now?

Thanks!

**Comment by AmeBel** [comment]
It is expected, refer to http://buildbot.opencog.org:8010/

But this won't prevent you from running opencog

**Comment by inflector** [comment]
@sigkill Specific failures in tests are fairly common in OpenCog as it is still a research platform and in flux more than a finished product might be. The failures tend to get fixed fairly quickly, generally in a day or two.

What I do when I notice a failure during my testing is check the waterfall on buildbot to see if the failure shows up there, and if it does, I assume I didn't cause it with my own changes.

**Comment by linas** [comment]
Fixed in commit #1557  I broke Sudoku during a major re-write, and was eager to commit code at that point. I should now work fine.

**Comment by linas** [comment]
closing I assume this now works for everyone.
