### ISSUE TITLE
unbound variable TypeNode in R2l scheme rules

### ISSUE THREAD

**Issue by anitzkin** [opencog/opencog#1576]
Linas, I wrote some more of the r2l rules, following your templates closely.  When i loaded them, the shell gave me the error, unbound variable: TypeNode.

**Comment by linas** [comment]
when is the last time you pulled? I believe that TypeNode is a recent renaming from VariableTypeNode, maybe a month ago.   If VariableTypeNode works that's your answer.

Sorry for the disruptions, there will be one more major shakeup in the next few days, and then that will be it.

**Comment by linas** [comment]
If you decide to pull todays version, you will have to first clone and build cogutils

**Comment by anitzkin** [comment]
I cloned cogutils earlier today.  I pulled a couple of days ago I think . .
. but I will try it again.

**Comment by anitzkin** [comment]
I cloned cogutils earlier, but I don't think I built it. How do I build it?

**Comment by AmeBel** [comment]
https://github.com/opencog/cogutils/blob/master/README.md#building-cogutils

**Comment by anitzkin** [comment]
Okay . . . obviously I already have an opencog/build directory; I went
there and ran cmake -DCMAKE_BUILD_TYPE=Release .. and got the error about
Cogutil missing except that I've cloned it successfully twice now. ?

**Comment by linas** [comment]
You build it in the cogutils/build directory because you are building cogutils, not opencog.

**Comment by linas** [comment]
Closing, I think this bug is stale.
