### ISSUE TITLE
Python Module: print output going to wrong location.

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1596]
The cogserver python module redirects some output, but not all print output:  for example:  start cogserver, `telnet localhost 17001` and say `print "hello"` and the output comes back by telnet session.

But, if instead, you call some python library, and it has print statements in it, then those prints end up on the cogserver console, instead of the telnet console.  I'm not sure under what circumstances this happens; for me, it happens when I call (for example)
```
      rospy.Subscriber("/blender_api/available_gestures",
             AvailableGestures, self.get_gestures_cb)
```
and the `get_gestures_cb` has print statements.  The problem here is that  `rospy.Subscriber` is listening for messages asynchornoulsy, thus .. well, I don't know. It might explain it if this is not easily reproducible.

**Comment by linas** [comment]
I have hacked around this in some recent pull request.  Its a hack .... its a part of pull request #2025 and is located here:  
https://github.com/opencog/opencog/commit/3e6896b537b1e99519b2dfee7712bc2a06353cf8#diff-3356f5f6465ff136fe4e302c9702c0a1
 This is also a duplicate of  opencog/atomspace/issues/629

Although the solution seems to be kind-of hacky, it kind-of works. Thus I am closing this, for now. 

@inflector  if you understand this issue, and can think of a better solution, let me know.

**Comment by inflector** [comment]
@linas I'll look into solving this "the right way", but it's not an area I'm already familiar with so I don't yet know what that means.

**Comment by linas** [comment]
Thanks. I'm not sure what priority this needs to be, but my solution did seem to be a work-around, rather than a fix.
