### ISSUE TITLE
Python Module: signals are disabled

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1597]
When running the cogserver, before any python code is run (i.e. if there are no python preloads) then the cogsever can be ctrl-c'ed from the console. After running python, then ctrl-C no longer works.  Not a big deal, but annoying during development.

**Comment by SadhanaSrinivasan** [comment]
@linas Hi, I'm planning to solve this issue by implementing a python signal handler that executes 'quit()' on ctrl-c.

**Comment by linas** [comment]
thanks, sounds reasonable.

**Comment by linas** [comment]
See also issue opencog/atomspace #656

**Comment by inflector** [comment]
@SadhanaSrinivasan Are you still working on this signal handler?

**Comment by linas** [comment]
FYI, all of my ros code now works without a cogserver. Which means we can also start removing the cogserver from other popular scripts and what-not, making it optional and possibly even deprecated, since it really .. does nothing useful, anyway.

**Comment by linas** [comment]
Closing ... this is no longer an issue. Don't know why, but it now works for me.
