### ISSUE TITLE
REST API /api/v1.1/atoms returns 500 Internal Server Error

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/opencog#1608]
$ wget localhost:5000/api/v1.1/atoms
--2015-05-09 19:18:15--  http://localhost:5000/api/v1.1/atoms
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 500 INTERNAL SERVER ERROR
2015-05-09 19:18:15 ERROR 500: INTERNAL SERVER ERROR.

/types command works fine though:
$ wget localhost:5000/api/v1.1/types
--2015-05-09 19:18:22--  http://localhost:5000/api/v1.1/types
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1137 (1.1K) [application/json]
Saving to: ‘types.1’

console output:
REST API is now running in a separate daemon thread.
 \* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [09/May/2015 19:18:15] "GET /api/v1.1/atoms HTTP/1.1" 500 -
127.0.0.1 - - [09/May/2015 19:18:22] "GET /api/v1.1/types HTTP/1.1" 200 -

cogserver.log doesn't have anything to say about it:
[2015-05-09 19:17:09:830] [INFO] Starting CogServer loop.
[2015-05-09 19:17:40:581] [INFO] Creating python request restapi.Start
[2015-05-09 19:17:40:582] [INFO] Created python request restapi.Start

**Comment by cosmoharrigan** [comment]
@eddiemonroe What needs to be done upon a fresh install to get opencog to recognize the module? Right now, after a fresh install, it's not loaded:
```
opencog> restapi.Start
command "restapi.Start" not found
```
I know you and Linas were talking about this on the list, so I am wondering if you have any suggestions.

**Comment by linas** [comment]
Try doing an `import restapi` by hand.  I notice that restapi is autmoatically pre-loaded by the opencog.conf file, and the cogserver starts without errors ... so it should be loaded. ... but whenever I try to specify a preload of my stuff, the cogserver crashes.  So maybe it is silently failing for you?

**Comment by eddiemonroe** [comment]
@cosmoharrigan Are you using the latest from both atomspace and opencog? The issue Linas and I were talking about had to do with the cython "opencog" package in particular, so don't think it would impact the restapi, but I'm not positive about that.

@linas, I tried removing restapi from PYTHON_PRELOAD and doing an import restapi by hand--got the same 500 error result.

**Comment by eddiemonroe** [comment]
@linas, just to confirm we're talking about the same thing, what i did was `opencog> loadpy restapi`

**Comment by cosmoharrigan** [comment]
Ok, I fixed my issue by installing a missing dependency. Now the module loads, and I am at the same place as @eddiemonroe.

**Comment by cosmoharrigan** [comment]
I think a good start to figure out what's going on is to try to get the unit tests to pass again after all the recent changes:

```
> cd ~/opencog/tests/python/restapi
> python2.7 -m nose test_restapi.py
```

**Comment by cosmoharrigan** [comment]
Or, to get rid of the cluttered logging,
```
> cd ~/opencog/tests/python/restapi
> python2.7 -m nose test_restapi.py --nologcapture
```

**Comment by linas** [comment]
On Sat, May 9, 2015 at 6:08 PM, Cosmo Harrigan <notifications@github.com>
wrote:

> python2.7 -m nose test_restapi.py --nologcapture


? Passes for me.

**Comment by cosmoharrigan** [comment]
@linas it doesn't pass for me. Are you sure it's actually running the tests? If you don't have all the dependencies it will skip the test.

```
try:
    from web.api.apimain import RESTAPI
except ImportError:
    import unittest
    raise unittest.SkipTest("ImportError exception: make sure the required "
                            "dependencies are installed.")
```

**Comment by linas** [comment]
No exceptions, no  errors it prints OK at the end.
```
python2.7 -m nose test_restapi.py
S
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK (SKIP=1)
```

unless SKIP means something?

**Comment by cosmoharrigan** [comment]
Indeed, it indicates that the tests were skipped, because the required python packages were not found. (https://github.com/opencog/opencog/blob/master/opencog/python/requirements.txt)

**Comment by fredyvilla** [comment]
Hello All,

I'm new to the community but I have started looking at open issues to see where I can contribute.
The atoms rest call is working for me. Has this issue been fixed?

vagrant@cogbox:~$ wget localhost:5000/api/v1.1/atoms
--2015-08-16 05:37:10--  http://localhost:5000/api/v1.1/atoms
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14138 (14K) [application/json]
Saving to: âatoms.2â

100%[======================================>] 14,138      --.-K/s   in 0s

2015-08-16 05:37:10 (35.8 MB/s) - âatoms.2â saved [14138/14138]

vagrant@cogbox:~$ wc atoms
    0  1530 14138 atoms
vagrant@cogbox:~$

Console Log:
REST API is now running in a separate daemon thread.
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [16/Aug/2015 05:34:45] "GET /api/v1.1/atoms HTTP/1.1" 200 -




I started with a clean install and did the following:
1) update PYTHONPATH in .bashrc and Dependencies.
2) Remove restapi from the opencog.conf predloaded modules
3) Updated PYTHON_EXTENSION_DIRS  = ../opencog/python,../opencog/python/web/api (I was not able to loadpy restapi until I did this)
4) manually loadpy restapi

The unit test still fails:
python -m nose test_restapi
terminate called after throwing an instance of 'opencog::AssertionException'
  what():  Accidentally called the base class!
To fix this bug, be sure to make the following call in your code:
   server(MyServer::MyCreateInstance);
So, for example:
   server(OAC::createInstance);
or maybe this:
   server(CogServer::createInstance);
depending on which you want.  You only need to do this once,
early during the initialization of your program.
 (/vagrant/opencog/opencog/server/BaseServer.cc:48)
Aborted (core dumped)

Please let me know how you want me to proceed.

**Comment by AmeBel** [comment]
Hi @fredyvilla , welcome to the community

what did you add to your PYTHONPATH?

**Comment by fredyvilla** [comment]
Thanks Amen.

This is what I have:
echo $PYTHONPATH
:/usr/local/share/opencog/python:/home/vagrant/open/opencog/opencog/python:/home/vagrant/open/opencog/build/opencog/cython

**Comment by AmeBel** [comment]
Closing b/c issue is outdated. For examples, on how to use the RESTAPI, see https://github.com/opencog/opencog/tree/master/examples/restapi
