### ISSUE TITLE
CogUtil not linked correctly in pull?

### ISSUE THREAD

**Issue by mmreilly** [opencog/opencog#1621]
Trying to 'build' and install OpenCog using the instructions here (http://wiki.opencog.org/w/Installing_OpenCog_for_Noobs#How_to_Install_OpenCog_and_its_dependencies_in_a_nutshell)

The setup here seems to not link the CogUtil libraries.

There error message in the terminal is: 
  include could not find load file:

    lib/Summary.cmake

-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Build type: Release
CMake Error at CMakeLists.txt:134 (FIND_PACKAGE):
  By not providing "FindCogUtil.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CogUtil", but
  CMake did not find one.

  Could not find a package configuration file provided by "CogUtil"
  (requested version 2.0.1) with any of the following names:

    CogUtilConfig.cmake
    cogutil-config.cmake

  Add the installation prefix of "CogUtil" to CMAKE_PREFIX_PATH or set
  "CogUtil_DIR" to a directory containing one of the above files.  If
  "CogUtil" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by AmeBel** [comment]
Hi, follow these steps
http://wiki.opencog.org/w/Installing_OpenCog_for_Noobs#First_Steps_for_.2A.2Aexpert.2A.2A_users:_those_familiar_with_git.2C_Github.2C_and_Linux

please close these issue on success

**Comment by mmreilly** [comment]
That link you provide are the instructions I followed. The above post are the resulting errors from these instructions. I use Ubuntu 14.10 LTS Utopic.

**Comment by AmeBel** [comment]
My mistake, i forgot to mention that i updated the section in the link above. So, run the steps for updating dependencies.

**Comment by mmreilly** [comment]
Hi AmeBel, I assume you mean you updated the 'expert user' section? 

From the terminal: 

1. I first git cloned:  https://github.com/opencog/opencog.git
2. cd to opencog-master
3. run ln -s ocpkg setup.sh 
4. run chmod ugo+rx setup.sh 

step 4. outputs:  "chmod: cannot operate on dangling symlink ‘setup.sh’ "

What about using the noob section? Does this section, to your knowledge, pull/contain/link the necessary dependencies? I've tried both sections, and had issues with 'cogutil' -- my first post regarding errors (above) referred to the command in the noob section: "wget https://raw.githubusercontent.com/opencog/opencog/master/scripts/ocpkg && chmod ugo+rx ocpkg && ./ocpkg -v" 

Thanks

**Comment by AmeBel** [comment]
run the following commands, after step 2
```
cd scripts
run ln -s ocpkg setup.sh
run chmod ugo+rx setup.sh
```

ocpkg is the same one but you have to symlink to setup.sh or rename it to setup.sh

**Comment by AmeBel** [comment]
thanks for the feedback i updated the section

**Comment by mmreilly** [comment]
Yes --  understood that point after browsing around, thanks. Anyhow, I just ran it exactly as you have there, and...it *almost* worked, here's the point at which it failed, the errors: 


make[2]: Entering directory '/tmp/link-grammar-5.2.5/build/link-grammar/minisat'
make[3]: Entering directory '/tmp/link-grammar-5.2.5/build/link-grammar/minisat'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libminisat.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libminisat.so.2.0.0 /usr/local/lib/libminisat.so.2.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libminisat.so.2.0.0': Permission denied
Makefile:425: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/tmp/link-grammar-5.2.5/build/link-grammar/minisat'
Makefile:595: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/tmp/link-grammar-5.2.5/build/link-grammar/minisat'
Makefile:764: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/tmp/link-grammar-5.2.5/build/link-grammar'
Makefile:532: recipe for target 'install-recursive' failed

**Comment by mmreilly** [comment]
I couldn't brute force ( i.e. perhaps the failed libraries aren't strictly needed) and build over it, as there is no 'build' folder in the project at this point.

That is, in the docs :    cd opencog/'build'

**Comment by AmeBel** [comment]
if you are not going to try out sureal or work with language processing then you don't need link-grammar.

**Comment by mmreilly** [comment]
OK -  there doesn't seem to be a build folder. Should I just cd to the opencog-master/opencog directory and run your build instructions from there?  'opencog-master/opencog'  contains a CMakeLists.txt which 'cmake' needs (athough I am not confident it's the correct CMakeList.txt to build).    Thanks again for the advice.

**Comment by AmeBel** [comment]
```
cd opencog-master
mkdir build
cmake ..
make -j$(nproc)
```

**Comment by mmreilly** [comment]
AmeBel, this community rocks -- thank you for all your work on this documentation --  one more thing before I close the account. The final line 'opencog/server/cogserver -c lib/opencog.conf'  results in several warnings. Do you have any thoughts/concerns on these? 

;;; /home/michele/opencog-master/build/..//opencog/nlp/relex2logic/rule-helpers.scm:1245:8: warning: possibly unbound variable `TruthValueGreaterThanLink'
;;; compiled /home/michele/.cache/guile/ccache/2.0-LE-8-2.0/home/michele/opencog-master/opencog/nlp/relex2logic/rule-helpers.scm.go
;;; compiling /home/michele/opencog-master/build/..//opencog/nlp/relex2logic/post-processing.scm
;;; compiled /home/michele/.cache/guile/ccache/2.0-LE-8-2.0/home/michele/opencog-master/opencog/nlp/relex2logic/post-processing.scm.go
;;; compiling /home/michele/opencog-master/build/..//opencog/nlp/lg-dict/utilities.scm
;;; /home/michele/opencog-master/build/..//opencog/nlp/lg-dict/utilities.scm:17:8: warning: possibly unbound variable `lg-get-dict-entry'
;;; /home/michele/opencog-master/build/..//opencog/nlp/lg-dict/utilities.scm:18:8: warning: possibly unbound variable `lg-get-dict-entry'
;;; compiled /home/michele/.cache/guile/ccache/2.0-LE-8-2.0/home/michele/opencog-master/opencog/nlp/lg-dict/utilities.scm.go
;;; compiling /home/michele/opencog-master/build/..//opencog/nlp/sureal/surface-realization.scm
;;; /home/michele/opencog-master/build/..//opencog/nlp/sureal/surface-realization.scm:100:4: warning: possibly unbound variable `lg-get-dict-entry'
;;; /home/michele/opencog-master/build/..//opencog/nlp/sureal/surface-realization.scm:116:20: warning: possibly unbound variable `sureal-match'
;;; compiled /home/michele/.cache/guile/ccache/2.0-LE-8-2.0/home/michele/opencog-master/opencog/nlp/sureal/surface-realization.scm.go
Listening on port 17001

**Comment by AmeBel** [comment]
don't close the account, just the issue :smile:


just run ` opencog/server/cogserver `

**Comment by mmreilly** [comment]
OK, will do. :) That terminal froze. Upon opening a new terminal and cd'ing back into 'opencog-master/opencog/build'     I run: 'opencog/server/cogserver' and get the following as output.  

Using default config at lib/opencog.conf
Using default config at ../lib/opencog.conf
ImportError: No module named agent_finder
Listening on port 17001

I understand we are calling the server. Are we using a file or script in the 'build' directory? Which file in 'build' are we using? Just want a better understanding here, if possible.

(Note:    The files in the 'build' directory are: CMakeCache.txt, cmake_install.cmake, CPackSourceConfig.cmake, examples, Makefile, opencog.log, CMakeFiles, CPackConfig.cmake, doc, lib, opencog, tests)

**Comment by AmeBel** [comment]
cogserver is using `opencog-master/build/lib/opencog.conf`

in another terminal type `telnet localhost 17001` to access the shell.

**Comment by mmreilly** [comment]
In directory opencog-master typing telnet localhost 17001 gives 

Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

In a brand new terminal it gives:

telnet: could not resolve localhost17001/telnet: Name or service not known

**Comment by mmreilly** [comment]
I just installed 'sudo apt-get install xinetd telnetd ' and ran 'telnet localhost 17001' and received the same error message as above

**Comment by AmeBel** [comment]
i don't know what that is, you have to google it and find a fix, or try `nc localhost 17001`.

**Comment by linas** [comment]
telnetd and xinetd have nothing to do with it.  You should probably remove those.

you need to have a space between localhost and 17001
