### ISSUE TITLE
Error while loading deduction.scm and abduction.scm

### ISSUE THREAD

**Issue by misgeatgit** [opencog/opencog#1623]
guile> (load-scm-from-file "../opencog/opencog/reasoning/pln/rules/deduction.scm")
and 
    guile> (load-scm-from-file "../opencog/opencog/reasoning/pln/rules/abduction.scm")

throws error message with following summary
In ice-9/boot-9.scm:
2320: 13 [save-module-excursion #<procedure 36029f0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 12 [read-and-eval #<input: string 1e930d0> #:lang ...]
  37: 11 [lp (include "formulas.scm")]
In ice-9/eval.scm:
 505: 10 [#<procedure 1b11620 at ice-9/eval.scm:499:4 (exp)> #]
In ice-9/psyntax.scm:
1091: 9 [expand-top-sequence ((include "formulas.scm")) () ...]
 974: 8 [scan ((include "formulas.scm")) () ...]
1198: 7 [syntax-type (include "formulas.scm") () ...]
1407: 6 [expand-macro #<procedure 1bb9a20 at ice-9/psyntax.scm:2945:2 (x)> # () ...]
2971: 5 [#<procedure 363ef90 (k filename)> # #]
2951: 4 [read-file "formulas.scm" {#f} ...]
In ice-9/boot-9.scm:
1605: 3 [in-vicinity {#f} "formulas.scm"]
In unknown file:
   ?: 2 [string-length {#f}]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 358ff80 at ice-9/boot-9.scm:97:6 (thrown-k . args)> wrong-type-arg ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 379a120> wrong-type-arg ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure string-length: Wrong type argument in position 1 (expecting string): #

**Comment by linas** [comment]
My guess: replace (include "formulas.scm")  by (load-from-path "formulas.scm")

**Comment by misgeatgit** [comment]
Got a different error message with your suggestion:
In procedure primitive-load-path: Unable to find file "formulas.scm" in load path

**Comment by linas** [comment]
two ways. On way is to `(add-to-load-path "/usr/local/share/opencog/scm")`

But if the file is in an opencog directory, then use (load-scm-from-file"formulas.scm"), because load-scm-from-file searches the usual opencog source and build directories.

In the long run, maybe we could have a tool to automatically do `add-to-load-path` for all teh opencog build and source directories.

**Comment by misgeatgit** [comment]
Thanks! load-scm-from-file works.

**Comment by linas** [comment]
You should complain to Eddie Monroe, he added the (include) instead of (load-from-path) I assumed that he had tested his code, but I guess he did not.

**Comment by misgeatgit** [comment]
:+1:

**Comment by eddiemonroe** [comment]
Yeah, I did add the (include) to the Deduction rule, which wasn't loading, to match the same (include) already in a few of the other rules, which allowed Deduction to be loaded in the forward chainer like the others.
