### ISSUE TITLE
Default SimpleTruthValue in NLP

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#1629]
As from the rule-helpers.scm, there are "df-link-stv" and "df-node-stv":

https://github.com/leungmanhin/opencog/blob/e1464555469ca0ae9cde00ced607c573db84178f/opencog/nlp/relex2logic/rule-helpers.scm#L4-L14

defining default simple truth values for nodes and links created via R2L, is there any reason why we are using different default values for R2L-atoms than the others (which are using TruthValue::DEFAULT_TV() as defined in TruthValue.cc)?

**Comment by AmeBel** [comment]
actually that should become a function that checks for the count(and the associated tv) of any atom that already exist in the atomspace and adjust it accordingly. If it the first time entry then set the count to 1 and calculate the tv.

@bgoertzel comments?

**Comment by williampma** [comment]
For the NLP pipeline node count is implemented quite awhile back https://github.com/opencog/opencog/pull/1318.

The only reason it doesn't run is that the two lines of code @leungmanhin mentioned is interfering with it.

**Comment by AmeBel** [comment]
I didn't know that. Thanks @williampma . @leungmanhin  best to remove those variables and their usage, then. And update comment @ https://github.com/opencog/opencog/blob/master/opencog/nlp/scm/processing-utils.scm#L314

**Comment by leungmanhin** [comment]
Yes I'll do it.

I was also wondering, as from the rule-helpers comment:

; (Note: Without assigning this value, the default stv is (stv 1.0 0.0);
; PLN doesn't work on these as it requires links to have non-zero confidence
; values. Furthermore, some rules (e.g. AbductionRule) require a strength value
; smaller than 1.0. as -- conceptually -- this makes the Node equivalent to
; the entire universe.)

Should we also update the default truth values for all atoms, or would it cause any problem?
https://github.com/opencog/atomspace/blob/master/opencog/atomspace/TruthValue.cc#L52-L57

**Comment by AmeBel** [comment]
that was for the python PLN, it doesn't matter now. I don't think the PM/URE take account of the TV, with the exceptions of evaluation of GroundedPredicateNodes and some links like AbsentLink, EqualLink

**Comment by linas** [comment]
> Should we also update the default truth values for all atoms, or would it
> cause any problem?
>
> https://github.com/opencog/atomspace/blob/master/opencog/atomspace/TruthValue.cc#L52-L57
>

No, please don't change that., it would cause all sorts of problems.

**Comment by leungmanhin** [comment]
I see, thanks. That remains unchanged.

**Comment by leungmanhin** [comment]
Closed #1631
