### ISSUE TITLE
Building oac failed

### ISSUE THREAD

**Issue by chenesan** [opencog/opencog#1635]
I git pull the project recently, and I'm sure the cogutil/, atomspace/, opencog/ is up-to-date. I had already "make" and "sudo make install" the cogutil and atomsapce.
When I built the opencog/ I got failed:

[ 84%] Building CXX object opencog/embodiment/Control/OperationalAvatarController/CMakeFiles/oac.dir/Inquery.cc.o
/home/opencog/src/myrepo/opencog/opencog/embodiment/Control/OperationalAvatarController/Inquery.cc:40:36: fatal error: opencog/query/BindLink.h: No such file or directory
 #include <opencog/query/BindLink.h>

I ls the atomspace/query/ and I only found BindLinkAPI.h...

**Comment by linas** [comment]
Fixed in 5c8c56654b683ebcd533e011a272497ed08ee36f  sorry it wasn't caught earlier

**Comment by chenesan** [comment]
That works. Thanks!
