### ISSUE TITLE
Is it possible to provide the rest-api bindings of pattern match besides guile

### ISSUE THREAD

**Issue by 020794** [opencog/opencog#1645]
The current bindings of pattern-match is c++ and guile. It can not be used in client server mode.

Is it possible to provide the rest-api bindings of pattern match besides guile.

**Comment by linas** [comment]
It can be used in client-server mode, very easily.  Just use netcat.

For example, just say `echo (cog-bind blah-blah) | netcat localhost 17001` and you'll get an answer back. That's how I do all my stuff.  That's how link-grammar and relex talk to opencog.  You can have this stuff all on different machines.  You can have multiple copies all churning away at computations.

**Comment by 020794** [comment]
Thank you
