### ISSUE TITLE
Recent changes in BindLink syntax causing some error . . . 

### ISSUE THREAD

**Issue by anitzkin** [opencog/opencog#1648]
I just wrote a bunch of R2L rules, and I went to test them, and I kept getting the same error on every rule, and then I tested one of the ones we already merged that definitely worked before ngeiswei did some changes in the BindLink, and those rules get the same error now also, which is . . . .

 In procedure cog-new-link: Expecting an outgoing set size of at most two, got 3 (/tmp/atomspace-master/opencog/atoms/bind/ConcreteLink.cc:168)

**Comment by ngeiswei** [comment]
@anitzkin I think I know where is the problem. Please write a unit test that reproduces the bug and I'll fix it.

**Comment by williampma** [comment]
Actually, `/opencog/atoms/bind/ConcreteLink.cc` was removed quite awhile ago I think?  So the solution is......... update your local source~

**Comment by ngeiswei** [comment]
good we have William around to pay attention ;-)

**Comment by anitzkin** [comment]
Mmm. Updated this morning. WIll again.

**Comment by anitzkin** [comment]
I says I'm already up-to-date.

**Comment by anitzkin** [comment]
As far as a unit test goes, just try to load one of the scheme R2L rules.

**Comment by linas** [comment]
It may help to run 'make cl;ean', so that old binaries are removed --
leftovers can sometimes manifest as bizarre bugs.

**Comment by anitzkin** [comment]
I ran "make clean" and it deleted my cogserver from opencog/server, so I ran cmake and make again and it's still gone,
and then I rebased and ran cmake and make again, and its still gone! 

Arggghh.  I am so not right for this work.  You know I'm leaving in two weeks, right?
--------------------------------------------
On Wed, 6/17/15, Linas Vepštas <notifications@github.com> wrote:

 Subject: Re: [opencog] Recent changes in BindLink syntax causing some error . . .  (#1648)
 To: "opencog/opencog" <opencog@noreply.github.com>
 Cc: "anitzkin" <a_nitzkin@yahoo.com>
 Date: Wednesday, June 17, 2015, 7:29 AM
 
 It may help to run 'make
 cl;ean', so that old binaries are removed --
 
 leftovers can sometimes manifest as bizarre bugs.
 
 
 
 On 6/16/15, anitzkin <notifications@github.com>
 wrote:
 
 > As far as a unit test goes, just try to load one of the
 scheme R2L rules.
 
 >
 
 > On Tue, Jun 16, 2015 at 4:09 PM, Aaron Nitzkin
 <a_nitzkin@yahoo.com> wrote:
 
 >
 
 >> I says I'm already up-to-date.
 
 >>
 
 >> On Tue, Jun 16, 2015 at 4:08 PM, Aaron Nitzkin
 <a_nitzkin@yahoo.com>
 
 >> wrote:
 
 >>
 
 >>> Mmm. Updated this morning. WIll again.
 
 >>>
 
 >>> On Tue, Jun 16, 2015 at 3:57 PM, ngeiswei
 <notifications@github.com>
 
 >>> wrote:
 
 >>>
 
 >>>> good we have William around to pay
 attention ;-)
 
 >>>>
 
 >>>> —
 
 >>>> Reply to this email directly or view it on
 GitHub
 
 >>>>
 <https://github.com/opencog/opencog/issues/1648#issuecomment-112325128>.
 
 >>>>
 
 >>>
 
 >>>
 
 >>
 
 >
 
 >
 
 > ---
 
 > Reply to this email directly or view it on GitHub:
 
 >
 https://github.com/opencog/opencog/issues/1648#issuecomment-112338402
 
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by anitzkin** [comment]
Alright, Amen ran his new setup file, got everything all set to rights . . .

--------------------------------------------
On Wed, 6/17/15, Linas Vepštas <notifications@github.com> wrote:

 Subject: Re: [opencog] Recent changes in BindLink syntax causing some error . . .  (#1648)
 To: "opencog/opencog" <opencog@noreply.github.com>
 Cc: "anitzkin" <a_nitzkin@yahoo.com>
 Date: Wednesday, June 17, 2015, 7:29 AM
 
 It may help to run 'make
 cl;ean', so that old binaries are removed --
 
 leftovers can sometimes manifest as bizarre bugs.
 
 
 
 On 6/16/15, anitzkin <notifications@github.com>
 wrote:
 
 > As far as a unit test goes, just try to load one of the
 scheme R2L rules.
 
 >
 
 > On Tue, Jun 16, 2015 at 4:09 PM, Aaron Nitzkin
 <a_nitzkin@yahoo.com> wrote:
 
 >
 
 >> I says I'm already up-to-date.
 
 >>
 
 >> On Tue, Jun 16, 2015 at 4:08 PM, Aaron Nitzkin
 <a_nitzkin@yahoo.com>
 
 >> wrote:
 
 >>
 
 >>> Mmm. Updated this morning. WIll again.
 
 >>>
 
 >>> On Tue, Jun 16, 2015 at 3:57 PM, ngeiswei
 <notifications@github.com>
 
 >>> wrote:
 
 >>>
 
 >>>> good we have William around to pay
 attention ;-)
 
 >>>>
 
 >>>> —
 
 >>>> Reply to this email directly or view it on
 GitHub
 
 >>>>
 <https://github.com/opencog/opencog/issues/1648#issuecomment-112325128>.
 
 >>>>
 
 >>>
 
 >>>
 
 >>
 
 >
 
 >
 
 > ---
 
 > Reply to this email directly or view it on GitHub:
 
 >
 https://github.com/opencog/opencog/issues/1648#issuecomment-112338402
 
 
 
 —
 Reply to this email directly or view
 it on GitHub.
