### ISSUE TITLE
fatal error: PsiModulatorUpdaterAgent.h: No such file or directory

### ISSUE THREAD

**Issue by Allend575** [opencog/opencog#1661]
I have searched for an answer and simply can't find it. The compiler crashes here on every build. I don't know if this is an issue or something I am doing. 

[ 86%] Building CXX object opencog/embodiment/Control/OperationalAvatarController/CMakeFiles/oac.dir/Pet.cc.o
In file included from /home/drcicom-admin/opencog-project/opencog/opencog/embodiment/Control/OperationalAvatarController/Pet.cc:53:0:
/home/drcicom-admin/opencog-project/opencog/opencog/embodiment/Control/OperationalAvatarController/OAC.h:64:38: fatal error: PsiModulatorUpdaterAgent.h: No such file or directory
 #include "PsiModulatorUpdaterAgent.h"
                                      ^
compilation terminated.
make[2]: *** [opencog/embodiment/Control/OperationalAvatarController/CMakeFiles/oac.dir/Pet.cc.o] Error 1
make[1]: *** [opencog/embodiment/Control/OperationalAvatarController/CMakeFiles/oac.dir/all] Error 2
make: *** [all] Error 2
21:22:52: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project opencog (kit: Desktop)
When executing step 'Make'

**Comment by suriyadeepan** [comment]
This happens only when you try building with MOSES (HAVE_MOSES). If not, OAC module is not built and compilation works fine. I tried adding OpenPsi shared lib in CMakeList on OAC folder but I get undefined reference error while linking. Someone please look into this.

**Comment by suriyadeepan** [comment]
check out https://github.com/opencog/opencog/pull/1649

comment from @AmeBel 
"Please note that this changes will break the OAC . Refer to https://github.com/opencog/opencog/blob/master/opencog/embodiment/Control/OperationalAvatarController/OAC.h#L64"

**Comment by AmeBel** [comment]
Just merged a fix. Test and close if satisfied with solution. :smile:

**Comment by pennachin** [comment]
@AmeBel I ran into the same issue over the weekend. This fixes the build, but make test still needs a similar update, I guess:

    [ 97%] Built target pbTest
    make[3]: *** No rule to make target `opencog/embodiment/Control/OperationalAvatarController/oac-exec', needed by     `tests/embodiment/Control/OperationalAvatarController/CMakeFiles/DistributeOACStuff'.  Stop.
    make[2]: *** [tests/embodiment/Control/OperationalAvatarController/CMakeFiles/DistributeOACStuff.dir/all] Error 2
    make[1]: *** [CMakeFiles/test.dir/rule] Error 2
    make: *** [test] Error 2

**Comment by AmeBel** [comment]
@pennachin disabled

**Comment by pennachin** [comment]
Thanks @AmeBel
