### ISSUE TITLE
Trying to integrate with ros

### ISSUE THREAD

**Issue by yantrabuddhi** [opencog/opencog#1669]
Hi @linas ,
 I wrote a agent modified from agent example. This is supposed to be put inside ros workspace for compilation and in the CMakeLists.txt "opencog_src_dir" is to be specified for your system.
Cogserver at first try says unable to load module and in second attempt crashes on running
`loadmodule /home/mandeep/cogros_ws/devel/lib/libAgentROS.so` from opencog telnet shell
Here are logs from /tmp/cogserver.log
```
[2015-07-03 10:59:32:149] [INFO] Starting CogServer loop.
[2015-07-03 11:00:18:086] [INFO] Loading module "/home/mandeep/cogros_ws/devel/lib/libAgentROS.so"
[2015-07-03 11:00:18:087] [WARN] Unable to load module "/home/mandeep/cogros_ws/devel/lib/libAgentROS.so": /home/mandeep/cogros_ws/devel/lib/libAgentROS.so: undefined symbol: _ZN3ros7console13g_initializedE
[2015-07-03 11:00:19:688] [INFO] Loading module "/home/mandeep/cogros_ws/devel/lib/libAgentROS.so"
```
My source code is available in below link
https://github.com/yantrabuddhi/opencog/tree/dev/examples/AgentROS

**Comment by yantrabuddhi** [comment]
issue is solved, needed to allow link libraries and set the variable scopes correctly

**Comment by yantrabuddhi** [comment]
Hi @linas ,
 Can you please review my code, there are some problems i know of but I need to know how to best do it. The code has hard-coded path in AgentROS for cogserver as I can't access argc argv from plugin, also because I wouldn't like any other things to go in these parameters i guess.

**Comment by linas** [comment]
Well, I would really like to get away from using opencog agents, and using cogserver modules.

The problem is that both the agents, and the cogserver modules, are not very flexible and don't offer much utility for all the effort they require to set up and use.

You can use opencog directly from the python shell (or from the guile shell), and this seems like the best way  to use opencog and the cogserver.

**Comment by linas** [comment]
To put it differently: we should not be creating new agent and module examples, I don't think...
