### ISSUE TITLE
All implemented pln rules throwing C++ Exception

### ISSUE THREAD

**Issue by prateeksaxena2809** [opencog/opencog#1704]
while running [the pln inversion rule](https://gist.github.com/prateeksaxena2809/9cb2ac239db5d942fd86), the cogserver gives a c++ exception with the following error. Also the basic [or-creation-rule](https://gist.github.com/prateeksaxena2809/1c1f811dfc35cdf8d773) is giving the same error. I have tried the solution provided in issue #1648 but its not working. Please suggest

**Comment by linas** [comment]
what error?

**Comment by ngeiswei** [comment]
Those 2 rules have in common that they don't have explicit output, this is tied to issue https://github.com/opencog/atomspace/issues/119. I plan to work on that soon, but I have other things on my plate ATM.

**Comment by SadhanaSrinivasan** [comment]
Hi @linas @ngeiswei,

I'm planning on working on this, any pointers?

**Comment by ngeiswei** [comment]
@prateeksaxena2809 can you provide more information, I don't know how to reproduce this error.

**Comment by prateeksaxena2809** [comment]
The primary issue here is with backward chaining. The backward chainer is
supposed to look at the output of the rule ( primarily in Execution Output
Link) and return the source Links and Nodes. When the rules consist of a
definite number of nodes, this is easy. But, whenever we encounter rules
with ListLinks as arguments, this was not possible because links had to be
extracted from the input using methods like(gar, gdr) and thus Regexing the
input to a definite node seemed tough. A few suggestions to tackle the
issue was introduction of Deep Type and Signature Links. As far as I know,
a short term robust solution is in place with different rules for 0,1,2 and
3 member rules.

**Comment by ngeiswei** [comment]
Thanks @prateeksaxena2809 . @SadhanaSrinivasan I should mention that the rule format might change soon, so it's probably not the best issue for a beginner, so I invite you to try to find another issue to work on.

**Comment by SadhanaSrinivasan** [comment]
@ngeiswei Could you please let me know when the format has changed, so that I can work on this? Meanwhile, I'll start on beginner issues. I found #1597, please let me know of other beginner issues.

**Comment by ngeiswei** [comment]
@SadhanaSrinivasan I think it's probably take a few weeks. #1597 sounds like a great issue for a beginner. Have fun!

**Comment by linas** [comment]
closing, this seems to be stale.
