### ISSUE TITLE
Haskell missing stack package: Error installing OpenCog in Vagrant Virtual box

### ISSUE THREAD

**Issue by dbl001** [opencog/opencog#1753]
David-Laxers-MacBook-Pro:opencog davidlaxer$ vagrant ssh
/Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.3/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /Developer/NVIDIA/CUDA-6.5/bin in PATH, mode 040777
/Applications/Vagrant/embedded/gems/gems/bundler-1.6.2/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /Developer/NVIDIA/CUDA-6.5/bin in PATH, mode 040777
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-49-generic i686)

 * Documentation:  https://help.ubuntu.com/

  System information as of Mon Aug 31 19:05:47 UTC 2015

  System load:  0.0               Processes:           72
  Usage of /:   2.7% of 39.34GB   Users logged in:     0
  Memory usage: 3%                IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.50.2

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

123 packages can be updated.
51 updates are security updates.

Last login: Mon Aug 31 19:05:54 2015 from 10.0.2.2
vagrant@cogbox:~$ wget http://raw.github.com/opencog/ocpkg/master/ocpkg -O octool && chmod +rx octool && ./octool -rdpcal
--2015-08-31 19:10:28--  http://raw.github.com/opencog/ocpkg/master/ocpkg
Resolving raw.github.com (raw.github.com)... 199.27.79.133, 199.27.79.133
Connecting to raw.github.com (raw.github.com)|199.27.79.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.github.com/opencog/ocpkg/master/ocpkg [following]
--2015-08-31 19:10:28--  https://raw.github.com/opencog/ocpkg/master/ocpkg
Connecting to raw.github.com (raw.github.com)|199.27.79.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/opencog/ocpkg/master/ocpkg [following]
--2015-08-31 19:10:28--  https://raw.githubusercontent.com/opencog/ocpkg/master/ocpkg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.79.133, 199.27.79.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.79.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32080 (31K) [text/plain]
Saving to: ‘octool’

100%[======================================>] 32,080      --.-K/s   in 0.002s  

2015-08-31 19:10:29 (14.3 MB/s) - ‘octool’ saved [32080/32080]

[octool] Adding software repositories...
OK
deb http://download.fpcomplete.com/ubuntu/trusty stable main
gpg: keyring `/tmp/tmpnlggxm92/secring.gpg' created
gpg: keyring `/tmp/tmpnlggxm92/pubring.gpg' created
gpg: requesting key 9AADBE7B from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpnlggxm92/trustdb.gpg: trustdb created
gpg: key 9AADBE7B: public key "Launchpad PPA for OpenCog Developers" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
gpg: keyring `/tmp/tmp0587o8dx/secring.gpg' created
gpg: keyring `/tmp/tmp0587o8dx/pubring.gpg' created
gpg: requesting key F6F88286 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp0587o8dx/trustdb.gpg: trustdb created
gpg: key F6F88286: public key "Launchpad PPA for Herbert V. Riedel" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
[octool] Installing OpenCog build dependencies....
E: Unable to locate package stack
vagrant@cogbox:~$

**Comment by linas** [comment]
'stack' is a recently-added tool used to build the haskell bindings.  The haskell bindings were only added this summer, nothing uses them yet. You can work around this for now by commenting out the line that needs stack..

Meanwhile, the haskell people should take a look at this.

**Comment by linas** [comment]
@MarcosPividori @ngeiswei @AmeBel another haskell stack bug ...

**Comment by MarcosPividori** [comment]
Hi,
Are you running this on: *Ubuntu Linux 14.04 "Trusty Tahr"* according to: https://github.com/opencog/ocpkg/blob/master/ocpkg#L8 ?
Thanks,
Marcos

**Comment by dbl001** [comment]
Yes.

**Comment by MarcosPividori** [comment]
Hi, it looks like the problem is you are running the script on a i686 32bit machine. I will update the script.

**Comment by linas** [comment]
I think we decided long ago that opencog-on-32 bit is not supported. You'll have more 32-bit issues down the line.  Maybe we should add a kill switch when this config is detected.

**Comment by dbl001** [comment]
I used these instructions:

http://wiki.opencog.org/w/Installing_OpenCog_for_Noobs <http://wiki.opencog.org/w/Installing_OpenCog_for_Noobs>

git clone https://github.com/opencog/opencog.git <https://github.com/opencog/opencog.git>
wget http://raw.github.com/opencog/ocpkg/master/ocpkg <http://raw.github.com/opencog/ocpkg/master/ocpkg> -O octool && chmod +rx octool && ./octool -rdpcal

vagrant@cogbox:~/opencog/build$ uname -a
Linux cogbox 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:14:51 UTC 2015 i686 i686 i686 GNU/Linux


I wasn’t intentionally chosing 32bit.  How do I get 64bit Ubuntu virtual box?

**Comment by AmeBel** [comment]
The issue as you pointed out could be related to the absence of ocpkg script in the opencog repo. I am updating & the Vagrantfile now.

@dbl001 sorry for lack of quality on our wiki page, we are working on it,  please use the command in http://wiki.opencog.org/wikihome/index.php/Ocpkg instead

**Comment by dbl001** [comment]
Thanks!  Please let me know when to do the ‘pull’ to get the update Vagrant file.

**Comment by dbl001** [comment]
btw - with the 32 bit Ubuntu version here’s the results of $ make test

91% tests passed, 3 tests failed out of 34

Total Test time (real) = 179.88 sec

The following tests FAILED:
	 11 - AnaphoraTest (Failed)
	 17 - PythonModuleUTest (Failed)
	 21 - RestApiTest (OTHER_FAULT)
Errors while running CTest
make[3]: *** [CMakeFiles/test] Error 8
make[2]: *** [CMakeFiles/test.dir/all] Error 2
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2

**Comment by linas** [comment]
at this time, those failures are "normal" - someone who is good at python needs to fix them.

**Comment by dbl001** [comment]
Did I mis-interpret your comments about 32bit unsupported?  The Vagrant file specifies a 32bit architecture.
  # 64-bit machine caused a fatal issue: http://stackoverflow.com/a/22575302/1695962
  config.vm.box = "trusty32"
  config.vm.box_url = "http://files.vagrantup.com/trusty32.box"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box"

**Comment by AmeBel** [comment]
opencog does run on 32 bit system, as recently as 9 month ago. I believe that was a misunderstanding, or things have changed more recently. I will confirm to you soon.

**Comment by AmeBel** [comment]
@MarcosPividori updated Vagrantfile, thus closing the issue. If it still persists don't hesitate to open it.

Have fun :smile:

**Comment by dbl001** [comment]
Any thoughts on trying to convert the Vagrant virtual box to 64 bits?

**Comment by AmeBel** [comment]
it should work seemlessely, if you edit it to trusty64. You can also try
https://github.com/opencog/docker/tree/master/opencog as docker only works
on 64bit systems, and that is actively maintained.

**Comment by linas** [comment]
Oh, I thought we had a "lets not do 32-bits anymore" many years ago now. I guess if it works, that's OK too. The interesting apps seem to blow out 4GB ram very quickly, though.

**Comment by dbl001** [comment]
I got this error trying to launch ‘Opencog-Dev’ from Docker Kitematic.
OpenCog seems to be ok.
Open an issue?

**Comment by AmeBel** [comment]
What error?

**Comment by dbl001** [comment]
Tag latest not found in repository docker.io/opencog/opencog-dev

Relevant?
https://github.com/docker/docker-registry/issues/637 <https://github.com/docker/docker-registry/issues/637>

**Comment by AmeBel** [comment]
the tag is `cli`
```
docker pull opencog/opencog-dev:cli
```
