### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by chris-hawley** [opencog/opencog#1778]
I've been banging my head against google for a few days and haven't been able to find solution to this problem. 

I have 2 errors which may or may not be related

error 1: 
my /usr/local/share/opencog/python/opencog only contains bindlick.so and atomspace.so. As a result those are the only modules i can import in python. Naturally, i looked back in the documentation to see if there was anything I missed and i came across error 2.

error 2:
in my ~/OPENCOG/opencog/build dir i ran `sudo make install` and i got the following error

    CMake Error at opencog/nlp/relex2logic/cmake_install.cmake:60 (FILE):
      file INSTALL cannot find
      "/home/chrishawley/OPENCOG/opencog/opencog/nlp/relex2logic/IMPERATIVE.scm".
    Call Stack (most recent call first):
      opencog/nlp/cmake_install.cmake:39 (INCLUDE)
      opencog/cmake_install.cmake:38 (INCLUDE)
      cmake_install.cmake:38 (INCLUDE)

any thoughts?

**Comment by linas** [comment]
It was a badly capitalized filename.  I just fixed it in pull req #1779

**Comment by chris-hawley** [comment]
Thank you. the install completed successfully. Python is not finding Pymoses. However, everything else appears to be working.

**Comment by linas** [comment]
you have to fork the opencog/moses repo, and build and install that, to get moses.

**Comment by chris-hawley** [comment]
Thank you. I feel stupid for not thinking of that.

**Comment by linas** [comment]
Nah, its OK, moses is a very different part; its for stand-alone machine learning ...
