### ISSUE TITLE
xmlrpc dependency

### ISSUE THREAD

**Issue by sanuj** [opencog/opencog#1788]
`libxmlrpc-c-dev` is not available for debian which is an optional prerequisite for opencog. The following libxmlrpc packages exist:
``` 
libxmlrpc-c++8             libxmlrpc-core-c3-dev      libxmlrpc-epi-dev
libxmlrpc-c++8-dev         libxmlrpc-epi0             libxmlrpc-light-ocaml-dev
libxmlrpc-core-c3          libxmlrpc-epi0-dbg         libxmlrpc-lite-perl
```
will any alternative work? I can update the README file with the new alternative.

**Comment by AmeBel** [comment]
The installation script for ubuntu 14.04 and above can be found @ https://github.com/opencog/ocpkg/blob/master/ocpkg. For debian you can find the script is @ https://github.com/opencog/opencog/blob/master/scripts/install-debian-dependencies.sh .So it would be best if you update the debian script if anything is missing. 

Unless it affects the reference environment, which is Ubuntu 14.04(at this time), then updating the README isn't required. That being said, any updates to the debian script, is highly appreciated. Thanks

**Comment by linas** [comment]
do we even have any code left that uses xml ?  I thought tht Nil deleted
all of it.

--linas

**Comment by AmeBel** [comment]
do not konw. @ngeiswei comments?

**Comment by ngeiswei** [comment]
According to the root CMakeList.txt, xmlrpc is used by ubigraph. Ubigraph is still in the OpenCog repo, I don't know if it's actually being used by anyone.

**Comment by linas** [comment]
Unigraph appears to have died in 2008 -- that was the last time that new binaries were posted, or that there was any activity on the website. I'm guessing that those binaries are not even compatible with modern systems.   We should probably remove ubi entirely.

**Comment by linas** [comment]
Newest version for ubuntu is 8.04 -- seven years old.
 http://ubietylab.net/ubigraph/content/Downloads/

debian 4.0 aka debian etch ended-of-lifed in 2010

suse 10.3 end-of-lifed in 2009  (suse 10 started in 2005 o 10 is not the year)

I'm removing ubi now ...

**Comment by linas** [comment]
Pull req #1792
