### ISSUE TITLE
AnaphoraTest fails: 

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1796]
The present cause of failure for AnaphoraTest seems to be related to python not being able to load the nlp-types.
#### Issue
How does one import new types declared outside of the libatomspace into python, without using the `type_constructors` python module?
#### Test Output
```python

11/29 Testing: AnaphoraTest
11/29 Test: AnaphoraTest
Command: "/usr/local/bin/nosetests" "-vs" "/opencog/tests/nlp/anaphora"
Directory: /opencog/build/tests/nlp
"AnaphoraTest" start time: Oct 07 11:31 UTC
Output:
----------------------------------------------------------
Failure: AttributeError (type object 'atom_types' has no attribute 'WordInstanceNode') ... ERROR

======================================================================
ERROR: Failure: AttributeError (type object 'atom_types' has no attribute 'WordInstanceNode')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/opencog/tests/nlp/anaphora/test_anaphora.py", line 23, in <module>
    class AnaphoraUnitTester(TestCase):
  File "/opencog/tests/nlp/anaphora/test_anaphora.py", line 60, in AnaphoraUnitTester
    def getWord(self,name,type=types.WordInstanceNode):
AttributeError: type object 'atom_types' has no attribute 'WordInstanceNode'

----------------------------------------------------------------------
Ran 1 test in 0.015s

FAILED (errors=1)
<end of output>
Test time =   0.13 sec
----------------------------------------------------------
Test Failed.
"AnaphoraTest" end time: Oct 07 11:31 UTC
"AnaphoraTest" time elapsed: 00:00:00
----------------------------------------------------------
```
`libnlp-types.so ` is found in `opencog/build/opencog/nlp/types` .

**Comment by linas** [comment]
No clue how to fix this; requires elbow grease to figure out how types work in python.

**Comment by pennachin** [comment]
@linas I think you mentioned not long ago that this test passes on your machine when run manually?

**Comment by linas** [comment]
Last time we had this conversation I ran it, it worked... isn't this the
case for you too?

**Comment by pennachin** [comment]
No, I have never been able to get this test to pass, and I believe neither has Amen.

**Comment by linas** [comment]
Hmm. I just tried it, and its now failing in the same way as reported up top.  If I look at `tests/nlp/anaphora/test_anaphora.py` it seems like it never explicitly imports the nlp types.  This suggests that, in the past, python used to automatically search for and find all atom types; now it doesn't do that any more ... looking.

**Comment by linas** [comment]
whoops; I just did a git pull to get the latest, and now the error has changed:  
```
from agents.hobbs import HobbsAgent
```
!???

**Comment by AmeBel** [comment]
That could be a pythonpath issue fixed in https://github.com/opencog/opencog/pull/1795/files. You might have to add `/opencog/opencog/nlp/anaphora` to PYTHONPATH

**Comment by linas** [comment]
yep, OK, makes sense

**Comment by linas** [comment]
OK, I'm hacking on this now.  If I change WordInstanceNode to ConceptNode, then the test fails in scheme code invoked from python.  This is a partial work-around:

```
scheme_eval(self.atomspace, "(setenv \"LTDL_LIBRARY_PATH\" \"/usr/local/lib/opencog:/usr/local/lib/opencog/modules\")")
scheme_eval(self.atomspace, "(add-to-load-path \"/usr/local/share/opencog/scm\")")
```

which suggests that python is not setting up library search paths correctly.

**Comment by linas** [comment]
Seems like `cogserver_type_constructors.pyx` should call `get_refreshed_types()`  but that does not seem to work ...

**Comment by linas** [comment]
#1798 includes multiple fixes for this.

**Comment by AmeBel** [comment]
https://github.com/opencog/opencog/pull/1839 fixes the failure due to configuration issue. But know, we their is failure in logic (a guess). Don't know the code to fix it .

**Comment by linas** [comment]
It still always fails for me, with error:
```
Testing filter #11...
accepted antecedent
Testing filter #12...
accepted antecedent
Testing filter #13...
Too many root sets
Aborted
```

**Comment by linas** [comment]
Never mind, this fixes it:
```
https://github.com/ivmai/bdwgc/blob/master/mark_rts.c#L245
if (n_root_sets == MAX_ROOT_SETS) {
        ABORT("Too many root sets");
    }

https://github.com/ivmai/bdwgc/blob/master/include/private/gc_priv.h#L1037
#   define MAX_ROOT_SETS 8192

want LARGE_CONFIG

--enable-large-config

./configure --enable-cplusplus --enable-large-config
```

**Comment by AmeBel** [comment]
Set `PYTHONPATH=/usr/local/share/opencog/python:/opencog/opencog/python/:/opencog/build/opencog/cython:/opencog/opencog/nlp/anaphora `
If you are using opencog/opencog-dev:cli docker image, or its equivalent on your system

**Comment by AmeBel** [comment]
I guess it is a different issue

**Comment by linas** [comment]
Now works for me, although I did trip over this one, first:  https://github.com/ivmai/bdwgc/issues/83
