### ISSUE TITLE
fedora: cmake error atomspace lib not found (already installed)

### ISSUE THREAD

**Issue by kendricktan** [opencog/opencog#1840]
Upon cmake, it throws up with error:

	CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
	Please set them or make sure they are set and tested correctly in the CMake files:
	ATOMSPACE_PythonEval_LIBRARY
	    linked by target "server" in directory /home/kendricktan/Downloads/opencog/opencog/server
	ATOMSPACE_persist-sql_LIBRARY
	    linked by target "attention" in directory /home/kendricktan/Downloads/opencog/opencog/dynamics/attention
	    linked by target "RuleEngineModule" in directory /home/kendricktan/Downloads/opencog/opencog/modules
	    linked by target "PersistModule" in directory /home/kendricktan/Downloads/opencog/opencog/modules
	    linked by target "QueryModule" in directory /home/kendricktan/Downloads/opencog/opencog/modules
	    linked by target "PythonModule" in directory /home/kendricktan/Downloads/opencog/opencog/modules/python
	    linked by target "server" in directory /home/kendricktan/Downloads/opencog/opencog/server
	    linked by target "server" in directory /home/kendricktan/Downloads/opencog/opencog/server
	    linked by target "cogserver_type_constructors" in directory /home/kendricktan/Downloads/opencog/opencog/cython/opencog
	    linked by target "cogserver_cython" in directory /home/kendricktan/Downloads/opencog/opencog/cython/opencog
	    linked by target "agent_finder" in directory /home/kendricktan/Downloads/opencog/opencog/cython/opencog
	    linked by target "spacetime" in directory /home/kendricktan/Downloads/opencog/opencog/spacetime
	    linked by target "AtomSpacePublisherModuleUTest" in directory /home/kendricktan/Downloads/opencog/tests/persist/zmq/events
	    linked by target "PLNRulesUTest" in directory /home/kendricktan/Downloads/opencog/tests/reasoning
	    linked by target "PyEvalUTest" in directory /home/kendricktan/Downloads/opencog/tests/cython
	    linked by target "PythonModuleUTest" in directory /home/kendricktan/Downloads/opencog/tests/cython

Again, I've already installed the newly patched atomspace for fedora, and i don't know why its throwing up these errors.

OS: Fedora 22
cmake: 3.3.2
GNU make 4.0

** Also if this continues, would the devs here recommend me running it through docker? **

**Comment by AmeBel** [comment]
I am getting this error on build
```
[ 54%] Building CXX object opencog/modules/events/CMakeFiles/atomspacepublishermodule.dir/AtomSpacePublisherModule.cc.o
In file included from /opencog/opencog/modules/events/AtomSpacePublisherModule.h:36:0,
                 from /opencog/opencog/modules/events/AtomSpacePublisherModule.cc:25:
/opencog/lib/zmq/zhelpers.hpp:29:19: fatal error: zmq.hpp: No such file or directory
compilation terminated.
opencog/modules/events/CMakeFiles/atomspacepublishermodule.dir/build.make:62: recipe for target 'opencog/modules/events/CMakeFiles/atomspacepublishermodule.dir/AtomSpacePublisherModule.cc.o' failed
make[2]: *** [opencog/modules/events/CMakeFiles/atomspacepublishermodule.dir/AtomSpacePublisherModule.cc.o] Error 1
CMakeFiles/Makefile2:1764: recipe for target 'opencog/modules/events/CMakeFiles/atomspacepublishermodule.dir/all' failed
make[1]: *** [opencog/modules/events/CMakeFiles/atomspacepublishermodule.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
Did you get such an error before the one you reported above?

**Comment by kendricktan** [comment]
@AmeBel thanks for the quick reply, but no, i wasn't even able to get pass the cmake steps

**Comment by hedayat** [comment]
@AmeBel You need to install cppzmq-devel package for zmq.hpp
@kendricktan I've successfully built this in Fedora. Surprisingly, it seems that it has failed to find pythoneval and persist-sql libraries. What is the output of: `ls /usr/lib*/opencog /usr/local/lib*/opencog/`?

**Comment by AmeBel** [comment]
@hedayat thanks, was able to build and run. 

Just updated the installation script for fedora https://github.com/opencog/ocpkg/pull/39

**Comment by linas** [comment]
IS this fixed? can it be closed?

**Comment by AmeBel** [comment]
yes, fixed. A dockerfile have been added to test the fedora installation script @ https://github.com/opencog/docker/tree/master/packaging/fedora
