### ISSUE TITLE
fedora: docker scripts/.gdbinit not found

### ISSUE THREAD

**Issue by kendricktan** [opencog/opencog#1841]
After the failed attempt to install opencog on fedora 22, i turned to docker.
However, the DockerFile wasn't able to initialize properly

    Step 6 : RUN chmod 755 /tmp/octool && /tmp/octool -rdpcalv
	 ---> Using cache
	 ---> 7545fc1932a9
	Step 7 : COPY scripts/.gdbinit ~/.gdbinit
	scripts/.gdbinit: no such file or directory

My understanding is that the DockerFile isn't configured properly, however since i'm not familiar with this project (nor docker) itself i don't really know how to fix it :\

Steps to reproduce:

    cd [DockerFile dir]
    sudo docker build -t $USER/opencog .

OS: Fedora 22
Docker version 1.8.2-fc22, build cb216be/1.8.2

**Comment by AmeBel** [comment]
it is best you use the dockerfiles at https://github.com/opencog/docker/tree/master/opencog follow the README.md

**Comment by AmeBel** [comment]
I have just updated the dockerfiel in this repo https://github.com/opencog/opencog/pull/1842, but still is better you use https://github.com/opencog/docker/tree/master/opencog as that enables you to use the nlp-piepline and moses.

**Comment by kendricktan** [comment]
@ambel, thanks for the fast reply, I've successfully built it on docker, time to start playing with it! (finally)

however funny thing is that I tried building Moses on fedora and it compiled and installed successfully, however upon running the binary file it gives an

    libmoses_exec.so library not found )or smthg similar) I'll update soon, on my phone atm

**Comment by AmeBel** [comment]
on moses: I got the same error on fedora 22. There seems to be a lot of cmake related fixes needed for the different repos once we start the packaging drive. But for now,  you can continue, by installing moses in an ubuntu docker-image, details can be found @ https://github.com/opencog/docker/tree/master/opencog/moses
