### ISSUE TITLE
cannot start cogserver because of loading libPersistZmqModule.so error

### ISSUE THREAD

**Issue by shujingke** [opencog/opencog#1843]
I pulled the lastest Atomspace, cogutil, and opencog, and built. And then when I start cogserver. I got this error:

./opencog/server/cogserver: symbol lookup error: ./opencog/modules/libPersistZmqModule.so: undefined symbol: _ZN7opencog13ZMQPersistSCMC1EPNS_9AtomSpaceE

It looks like similar to this issue: 
https://github.com/opencog/opencog/commit/0b790cae26cf2ba825446740e77290be2e2dbd9f

Suggest to comment out the load ./opencog/modules/libPersistZmqModule.so in the config file first before anyone fix this.

**Comment by issacnitin** [comment]
Have the same problem. fixed yet?

**Comment by scourge101** [comment]
I have the same problem and I'm not sure if it helps but [this](https://groups.google.com/forum/?fromgroups#!topic/opencog/-lZO6xQDkMs) topic addresses the same error from two weeks ago.

**Comment by AmeBel** [comment]
Fixed by https://github.com/opencog/opencog/pull/1858

**Comment by issacnitin** [comment]
Thanks a lot!
