### ISSUE TITLE
DockerFile 'text file busy' error

### ISSUE THREAD

**Issue by lefredj** [opencog/opencog#1854]
I was following instructions on http://wiki.opencog.org/wikihome/index.php/BuildingOpenCog for building opencog using docker, and I had a "text file busy" error while trying:
docker build -t $USER/opencog .

I managed to pass through by changing line 21 of DockerFile to
RUN chmod 755 /tmp/octool; sync; /tmp/octool -rdpcalv

regards

**Comment by AmeBel** [comment]
better if you create a pull-request.

**Comment by AmeBel** [comment]
FYI, just included your suggestion through https://github.com/opencog/docker/pull/56 to the main docker-library repo for opencog projects.

**Comment by AmeBel** [comment]
Thanks :smile:
