### ISSUE TITLE
Minecraft OpenCog code.

### ISSUE THREAD

**Issue by rTreutlein** [opencog/opencog#1887]
The opencog-to-minecraft repository contains a bunch of code that should probably be merged with into the opencog repo. Currently you have to copy paste it over the opencog repo before you build it.

Was there some reason to why it hasn't been merged yet ,other then that it broke the old-embodiment code? (no longer an issue as that is gone)

If there is non then ill make a pull request to merge it into the 3DSpaceMap branch.

Why is there an extra branch for the 3DSpaceMap, what are the plans for that?

**Comment by linas** [comment]
yeah minecraft should be merged;  Someone should review it carefully.  

The conflict was not with embodiment, I think the conflict was with 3D spacemap or something like that.

**Comment by rTreutlein** [comment]
I am pretty sure the code in the opencog-to-minecraft repo is outdated and since the 3DSpaceMap code has now been merge this can be closed.

**Comment by linas** [comment]
Are you saying that the code here: https://github.com/opencog/opencog-to-minecraft/opencog is outdated?  There seemed to be some ways in which it seemed it was newer, I thought.  Or at least different-and-not-obviously-older.

So, if you delete the above folder, and build the rest of the minecraft bridge, does it work?  Elsewhere, you had said it doesn't suggesting that the above branch still contains something useful.

I'm going to re-open this, just to keep track until this is resolved. I just don't have the time to do this myself, just right now.

**Comment by rTreutlein** [comment]
The opencog-to-minecraft currently only works with the code that is in opencog-to-minecraft/opencog. But it contains classes that have been removed from the 3DSpaceMap code that is in opencog right now. So it seems to the code in the minecraft repo is out of date.

Then i would have to update the minecraft binings to use the new API.

@chenesan You wrote this code, so whats the most up to date code according to you?

**Comment by chenesan** [comment]
Hi @rTreutlein 
Sorry that I have been a long time out of the work here..
The code in opencog-to-minecraft/opencog is the code for Minecraft embodiment.
And the code that I pull to opencog/opencog, including some refactoring work, is newer than that. But I haven't used them in the Minecraft embodiment.
Because it seems nobody needed the code at that time (about Sep. ~ Oct.) and I'm busy in other school work so I stopped the development and integration in Minecraft embodiment.
I think I can try to fix this in the next 1~2 weeks.

**Comment by rTreutlein** [comment]
@chenesan No problem just needed to know whats the most up to date code. And would be great if you could update it, if you can't for some reason just tell me an ill do it. The Main Repo is now in the OpenCog Organization.

**Comment by chenesan** [comment]
OK, I will fix that in the next 1~2 weeks.

**Comment by AmeBel** [comment]
closing because this is resolved by various pull-requests
