### ISSUE TITLE
Microplanning fail

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1903]
I am currently debugging what appears to be a microplanning fail.  I believe that the following should generate output, but it doesn't:
```
$ guile
scheme@(guile-user)>
(use-modules (opencog) (opencog nlp) (opencog nlp microplanning))
(init-trace "/tmp/micro")

(define lap
(SequentialAndLink
   (InheritanceLink
      (ConceptNode "Linas@862d2b73-dc84-4fc1-bc87-896476ba6541")
      (ConceptNode "Linas"))
   (EvaluationLink
      (DefinedLinguisticPredicateNode "definite")
      (ListLink
         (ConceptNode "Linas@862d2b73-dc84-4fc1-bc87-896476ba6541")))
   (ImplicationLink
      (PredicateNode "ate@37537945-4593-4136-bc70-236f4c86c43c")
      (PredicateNode "eat"))
   (InheritanceLink
      (ConceptNode "apple@5409a01f-f0d1-4665-af02-5811c9806b0e")
      (ConceptNode "apple"))
   (EvaluationLink
      (PredicateNode "ate@37537945-4593-4136-bc70-236f4c86c43c")
      (ListLink
         (ConceptNode "Linas@862d2b73-dc84-4fc1-bc87-896476ba6541")
         (ConceptNode "apple@5409a01f-f0d1-4665-af02-5811c9806b0e")))
   (InheritanceLink
      (SpecificEntityNode "Linas@862d2b73-dc84-4fc1-bc87-896476ba6541")
      (DefinedLinguisticConceptNode "male"))
   (InheritanceLink
      (SpecificEntityNode "Linas@862d2b73-dc84-4fc1-bc87-896476ba6541")
      (ConceptNode "Linas"))
))

(microplanning lap "declarative" *default_chunks_option* #f)
```

Note that everything is being run from the guile repl, and the cogserver has not been started.
Another way to reproduce this is below; however, it requires a running relex server:
```
$ guile -l ../opencog/nlp/chatbot/run-chatbot.scm
scheme@(guile-user)> (process-query 'luser "Linas ate an apple.")
scheme@(guile-user)> (process-query 'luser "Who ate an apple?")
```

which replies 
```
You made an Interrogative SpeechAct
Fuzzy match is finished.
$1 = "Sorry, I don't know the answer."
```

I'm going to continue debugging this, but thought maybe someone else can find the bug faster than me.  I've put debug prints in teh code -- trace-msg which prints to /tmp/chattty to try to narrow things down.  Remove/add the debug prints as desired.

**Comment by leungmanhin** [comment]
I think it's because the speech act is missing for the sentence you parsed (Linas ate an apple.)

**Comment by leungmanhin** [comment]
I mean, we need to tell microplanner the speech act of the sentences it is going to generate (pass that as one of the arguments), and microplanner will start constructing queries, with the speech act attached, and send them one by one to sureal to see if any of them can be used to generate a sentence. So if the sentences we have in the atomspace do not have any speech act, pattern matcher will return nothing, sureal will think it can't be used to generate sentences, microplanner will think it is bad and as a result it returns false.

**Comment by leungmanhin** [comment]
Btw I tried to run the above steps, but then I got this error:
```
scheme@(guile-user)> (microplanning lap "declarative" *default_chunks_option* #f)
guile: symbol lookup error: /usr/local/lib/opencog/libsureal.so: undefined symbol: _ZN7opencog3nlp16lg_conn_linkableERKNS_6HandleES3_
```
Do you know how can I fix this?

**Comment by linas** [comment]
`lg_conn_linkable` is provided by lg-dict and sureal failed to link to lg-dict.  I'll push a fix for this shortly.

**Comment by linas** [comment]
Ugh, well, I do say `(microplanning lap "declarative" *default_chunks_option* #f)` but I guess that "declarative" is not enough.   So why is that argument even needed? I'll try to get rid of it shortly.

**Comment by linas** [comment]
Oh I see what you mean. But when I say `(cog-incoming-set (DefinedLinguisticConceptNode "DeclarativeSpeechAct"))`  I see lots of sentences, and I know that one of them talks about eating apples, and the rest talk about other people eating other things.

**Comment by leungmanhin** [comment]
I see... strange, looks like currently the speech act is generated but not included as part of the r2l outputs, I think that's the reason

**Comment by linas** [comment]
Can you explain what you mean by "not included as part of the r2l outputs"?  Its there -- the chatbot looks it up using  `sentence-get-utterance-type` in NLP utils.  That does a simple chase : `SentenceNode-> ParseLink->ParseNode->InterpretationLink->InterpretationNode->InheritanceLink->DefinedLinguisticConceptNode->BlahBlaSpeechAct`  

I'm guessing maybe microplanning isn't using the InterpretationLink? or maybe the BlaSpeechAct is capitalized differently? Something like that?

**Comment by leungmanhin** [comment]
I mean it seems that the speech act is generated but is not in this SetLink:
https://github.com/opencog/opencog/blob/master/opencog/nlp/chatbot/chat-utils.scm#L76

Normally the r2l stuffs are wrapped in this SetLink, with an InterpretationNode as its neighbor linked together by a ReferenceLink (#L79 of the same file). Currently sureal assumes the speech act is there.

For example, a query generated by microplanner may look something like this:
```
(SetLink
   (EvaluationLink
      (PredicateNode "is@123")
      (ListLink
         (ConceptNode "name@234")
         (ConceptNode "Tom@345")
      )
   )
   (InheritanceLink
      (InterpretationNode "MicroplanningNewSentence")
      (DefinedLinguisticConceptNode "DeclarativeSpeechAct")
   )
)
```
This query will be sent to sureal, which in turn will extract the clauses and send them to the pattern matcher:
https://github.com/opencog/opencog/blob/master/opencog/nlp/sureal/SuRealSCM.cc#L159

One of the things sureal will check is to see if the groundings have the above link-structure, e.g.:
https://github.com/opencog/opencog/blob/master/opencog/nlp/sureal/SuRealPMCB.cc#L121

So if the speech act (which is part of the pattern created by microplanner) does not satisfy this, sureal will reject the grounding. I guess that may be the reason.

**Comment by linas** [comment]
This is a duplicate of #1912 -- since that is fixed, so is this. Closing
