### ISSUE TITLE
Cogserver crashes while attempting to process request after starting all ECAN agents

### ISSUE THREAD

**Issue by misgeatgit** [opencog/opencog#1920]
I have observed that cogserver is unable to process requests after running ECAN mind agents and keeping them busy by creating and stimulating atoms on some cycle interval via another mind agents. As the agents take more CPU time while updating importance parameters of atoms and spreading attention , the server takes more time to process other requests to the point where it finally crashes. My experimental branch and work is found [here] (https://github.com/misgeatgit/opencog/tree/ecan-wbench/opencog/dynamics/experiment) which might be helpful for reproducing the crash.

**Comment by linas** [comment]
Can you provide a stack trace?

If I remember correctly, all agents share a single thread that is time-sliced; the shell request processor runs in a different thread and its response time should not be affected by the first thread.

Is it possible that you are running out of memory, or running out of stack? what does top show?

**Comment by misgeatgit** [comment]
Just saw the stack trace and the issue seems to be related with wrong way of setting parameters in the ECAN agents so Its not really related with threading.
