### ISSUE TITLE
Opencog build failed

### ISSUE THREAD

**Issue by wenwei-dev** [opencog/opencog#1972]
The latest opencog (2015 Dec 28) build failed. There are some errors in the compiling phase.

`[ 48%] Building CXX object opencog/cython/opencog/CMakeFiles/agent_finder.dir/agent_finder.cpp.o
/home/ben/Development/hansonrobotics/opencog/opencog/build/opencog/cython/opencog/agent_finder.cpp:362:40: fatal error: opencog/cython/CythonUtils.h: No such file or directory
 #include "opencog/cython/CythonUtils.h"
                                        ^
compilation terminated.
make[2]: *** [opencog/cython/opencog/CMakeFiles/agent_finder.dir/agent_finder.cpp.o] Error 1
make[1]: *** [opencog/cython/opencog/CMakeFiles/agent_finder.dir/all] Error 2
make: *** [all] Error 2`

`[ 48%] Building CXX object opencog/dynamics/attention/CMakeFiles/attention.dir/SimpleImportanceDiffusionAgent.cc.o
/home/ben/Development/hansonrobotics/opencog/opencog/opencog/dynamics/attention/SimpleImportanceDiffusionAgent.cc:28:41: fatal error: opencog/atomutils/AtomUtils.h: No such file or directory
 #include <opencog/atomutils/AtomUtils.h>`

The these revisions seem to work.
opencog: [bf282b1](https://github.com/opencog/opencog/commit/bf282b1a79decc0fb66ed6f5f20ac08ec810b342)
atomspace: [3a0776](https://github.com/opencog/atomspace/commit/3a07767a89868a5d3b7234e3a1e9cde55efae6ee)

**Comment by AmeBel** [comment]
It is building now.

**Comment by linas** [comment]
Sorry, my fault; I got busy removing what looked like ugly and obsolete code in the atomspace, then merged the changes, before realizing that .. hey hey hey .. there were still users in the opencog repo depending on this code.

It should all work now,  I'm closing this; if its still an issue, please re-open.
