### ISSUE TITLE
libPythonEval.dylib not found for architecture x86_64 Mac OS X

### ISSUE THREAD

**Issue by abhinavmoudgil95** [opencog/opencog#2006]
I have successfully built atomspace, cogutils and moses on **OS X 10.11.3 with gcc 5.1.0 and boost 1.60.**

All the dependencies were installed using Homebrew package manager. 
While building OpenCog, I get the following error: 

```
Scanning dependencies of target blopex
[  1%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/fortran_matrix.c.o
[  2%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/lobpcg.c.o
[  3%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/multivector.c.o
[  4%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/temp_multivector.c.o
Linking C shared library libblopex.dylib
[  4%] Built target blopex
Scanning dependencies of target serial_driver
[  5%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/multi_vector.c.o
[  6%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/pcg_multi.c.o
[  8%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/serial_driver.c.o
Linking C executable serial_driver
[  8%] Built target serial_driver
Scanning dependencies of target dimensionalembedding
[  9%] Building CXX object opencog/learning/dimensionalembedding/CMakeFiles/dimensionalembedding.dir/DimEmbedModule.cc.o
Linking CXX shared library libdimensionalembedding.dylib
ld: file not found: libPythonEval.dylib for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [opencog/learning/dimensionalembedding/libdimensionalembedding.dylib] Error 1
make[1]: *** [opencog/learning/dimensionalembedding/CMakeFiles/dimensionalembedding.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by pennachin** [comment]
Did you "sudo make install" the atomspace build? That should install this library in /usr/local/lib/opencog or wherever it is you're installing...

**Comment by abhinavmoudgil95** [comment]
Yes. I did 'make && sudo make install' while building atomspace.

**Comment by pennachin** [comment]
And is libPythonEval.dylib built and installed by the atomspace build?

**Comment by abhinavmoudgil95** [comment]
I don't know exactly the way to make sure that libPythonEval.dylib is built and installed. 
But yes, the file is present in atomspace/build/opencog/cython/ folder.

**Comment by AmeBel** [comment]
See in  `build/opencog/cython/`. If it isn't built it is likely that you haven't installed `python-dev` or its equivalent on mac

**Comment by abhinavmoudgil95** [comment]
`libPythonEval.dylib` is present in `atomspace/build/opencog/cython/ ` directory too.

**Comment by AmeBel** [comment]
Your PYTHONPATH should atleast be `PYTHONPATH=/usr/local/share/opencog/python:/opencog/opencog/python/:/opencog/build/opencog/cython:/opencog/opencog/nlp/anaphora`

**Comment by abhinavmoudgil95** [comment]
Apparently my PYTHONPATH is not set. When I run the command `echo $PYTHONPATH`, I get a blank line as output. Should I set my PYTHONPATH as mentioned above?

**Comment by AmeBel** [comment]
yes, and then rebuild

**Comment by abhinavmoudgil95** [comment]
I rebuilt all the repositories again (atomspace, cogutils, moses and opencog) but it didn't work. I am getting same error while building opencog.

**Comment by AmeBel** [comment]
I don't know what I was thinking with the PYTHONPATH, the error is a c++ link error not a python run error. Sorry about that 

It seems to be a linking eroror. 
```
export LD_LIBRARY_PATH="/usr/local/lib/opencog/modules:/usr/local/lib/opencog/"
```
and you don't need to rebuild everything, just rebuild opencog repo

**Comment by abhinavmoudgil95** [comment]
Still getting the same error. I get couple of warnings when I run `cmake ..` for building opencog. See[ here](http://pastebin.com/WKRZTYXe), if there is any library or path I missed?

**Comment by AmeBel** [comment]
it seems the equivalent of  `LD_LIBRARY_PATH` on mac is `DYLD_LIBRARY_PATH` and the more "sane one" being `DYLD_FALLBACK_LIBRARY_PATH` (see [here](https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s) for more). So, try again after replacing with either of those

**Comment by abhinavmoudgil95** [comment]
Sorry, neither of these work.

**Comment by abhinavmoudgil95** [comment]
I came to know from [here](https://github.com/oracle/node-oracledb/issues/231) that `DYLD_LIBRARY_PATH` doesn't work in Mac OS X El Capitan unless SIP is turned off. I turned the SIP off but still it doesn't work.

**Comment by abhinavmoudgil95** [comment]
Okay, so I copied this file` libPythonEval.dylib` from` /usr/local/lib/opencog/`to `/usr/local/lib`. 
Build process proceeded further but I get the following error later. 

```
Abhinavs-MBP:build abhinavmoudgil95$ make 
Scanning dependencies of target blopex
[  1%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/fortran_matrix.c.o
[  2%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/lobpcg.c.o
[  3%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/multivector.c.o
[  4%] Building C object opencog/learning/clustering/blopex/CMakeFiles/blopex.dir/temp_multivector.c.o
Linking C shared library libblopex.dylib
[  4%] Built target blopex
Scanning dependencies of target serial_driver
[  5%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/multi_vector.c.o
[  6%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/pcg_multi.c.o
[  8%] Building C object opencog/learning/clustering/blopex-demo/CMakeFiles/serial_driver.dir/serial_driver.c.o
Linking C executable serial_driver
[  8%] Built target serial_driver
Scanning dependencies of target dimensionalembedding
[  9%] Building CXX object opencog/learning/dimensionalembedding/CMakeFiles/dimensionalembedding.dir/DimEmbedModule.cc.o
Linking CXX shared library libdimensionalembedding.dylib
[  9%] Built target dimensionalembedding
Scanning dependencies of target statistics
[ 10%] Building CXX object opencog/learning/statistics/CMakeFiles/statistics.dir/InteractionInformation.cc.o
Linking CXX shared library libstatistics.dylib
[ 10%] Built target statistics
Scanning dependencies of target cogita
[ 11%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/CogitaConfig.cc.o
[ 12%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/IRC.cc.o
/Users/abhinavmoudgil95/opencog/opencog/opencog/nlp/irc/IRC.cc: In member function 'int IRC::start(const char*, int, const char*, const char*, const char*, const char*)':
/Users/abhinavmoudgil95/opencog/opencog/opencog/nlp/irc/IRC.cc:155:41: error: 'TCP_KEEPIDLE' was not declared in this scope
  rc=setsockopt(irc_socket, IPPROTO_TCP, TCP_KEEPIDLE, &optval, optlen);
                                         ^
make[2]: *** [opencog/nlp/irc/CMakeFiles/cogita.dir/IRC.cc.o] Error 1
make[1]: *** [opencog/nlp/irc/CMakeFiles/cogita.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by linas** [comment]
http://stackoverflow.com/questions/15860127/how-to-configure-tcp-keepalive-under-mac-os-x

**Comment by linas** [comment]
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man4/tcp.4.html

**Comment by linas** [comment]
the code needs something like 
```
#ifdef ICP_KEEP_IDLE
  the current code
#else
  whatever is needed to get MacOS to work right
#endif
```

Its pretty low priority -- IRC sometimes disconnects clients, and this just helps avoid disconnection. Its unlike you will run the chatbot on osx anyway so this is low priority

**Comment by abhinavmoudgil95** [comment]
Thanks linas. I fixed it yesterday by editing the corresponding file. Now I am trying to resolve [this](http://pastebin.com/dfLay3bW) error which occurred when 74% building was complete. Exactly same error while building opencog was reported earlier [here](https://trac.macports.org/ticket/44274) on macports official forum but I don't know whether it is fixed yet.

**Comment by linas** [comment]
Perhaps we should be using clang on macos, instead of gcc ... after all, Apple is a major investor in llvm, supplying almost half the budget, last I heard, while giving nothing at all to gcc ...

**Comment by abhinavmoudgil95** [comment]
I tried to build cogutils and other repositories using clang compiler earlier but got a cmake error: `Only the gcc compiler is supported at this time` That's why I thought it would be wise to shift to gcc rather than making changes to `CMakeLists.txt` or other files of repositories. I'll try to resolve this error as soon as possible otherwise we can think to shift to clang.

**Comment by linas** [comment]
The reason that "only gcc is supported" is because none of the active developers have access to a MacOS platform.  In the world of open source software, nothing is actually free -- someone has to roll up their sleeves and actually do the needed work. I don't believe that there are any fundamental issues (for osx, unlike windows where there are fundamental issues)  but there may be an endless litany of irritating annoyances, like the ones you've hit.

**Comment by abhinavmoudgil95** [comment]
True that. I am happy to contribute my part.

**Comment by abhinavmoudgil95** [comment]
### Finally built all the four opencog repositories from source in Mac OS X El Capitan. 

Following are the fixes: 
- For [error: macro "toupper" passed 2 arguments, but takes just 1](http://pastebin.com/dfLay3bW) error, add `#include <Python.h>` to file `PyMindAgent.cc`

- I encountered another error after resolving above error. It stated [error: destructor priorities are not supported](http://pastebin.com/3Zz8sf4h). 
Fix: Modify line 38 `#if __GNUC__ ` in PyMindAgent.cc to `#if __GNUC__ && INIT_PRIORITY && ((GCC_VERSION >= 40300) || (CLANG_VERSION >= 20900))`

- The original issue `ld: file not found: libPythonEval.dylib for architecture x86_64 ` was resolved by a small temporary hack i.e. `cp /usr/local/lib/opencog/* /usr/local/lib/` because dynamic linking using environment variable `DYLD_LIBRARY_PATH ` was not working as stated in comment above.

**Comment by AmeBel** [comment]
@abhinavmoudgil95 it would be very helpful if you would add the steps required for the build @ http://wiki.opencog.org/wikihome/index.php/Building_OpenCog.

**Comment by AmeBel** [comment]
even better would be a script that does the setting up. You could make the pr @ https://github.com/opencog/ocpkg

**Comment by abhinavmoudgil95** [comment]
Yes, I'm writing a script now. I'll get back soon.

**Comment by inflector** [comment]
>The reason that "only gcc is supported" is because none of the active developers have access to a MacOS platform. - linas

Or those that do have decided they'd rather spend their time adding features to OpenCog as it's relatively easy to setup a Docker container / VirtualBox VM on OS X that runs the standard OpenCog OS Ubuntu 14.04 LTS without having to do any other work. Docker or a VM running Linux happens to be a very common setup for doing any sort of web development back-end work. So many Mac owning developers are accustomed to Docker or VirtualBox running the same code as their server's Linux systems. And, as all the OpenCog tools are known to just work on Ubuntu 14.04, I know if something is broke, it's likely on my end.

Still, I, for one, would rather be debugging and editing C++ in Xcode. Editing with Sublime Text and gcc / gdb via a terminal command line bash shell works but is hardly the most productive. Especially when you are trying to figure out a new and complicated source base. And for Python, I'd rather be running PyCharm as my IDE.

Writing code with gcc / gdb and Linux in a shell is so 1975. Yup, command line Unix has been around that long.

I should note that even Xcode is only 1995. The real question is: Why is development in 2016, even at its best, so much worse than it was in 1995 in many respects? Seriously, the most productive environment I've ever used was Microsoft Visual C++ 20 years ago. Even Xcode with all of Apple's relatively recent thrust with Chris Lattner (aka Mr. LLVM) running Developer Tools is barely catching up to Microsoft's tools of 20 years ago. What's with that? And I hate Microsoft, in general, so I'm not just saying this because I'm a Windows junkie. I'm not.

And don't even get me started with the fragmentation and complication of the typical open source project. 200 different parts, each with specialized (and generally non-current) versions of tools and libraries and back end software, most written by someone only partially familiar with the code as most of the developers are new to the system, many are new to programming etc. I'm thinking of the reddit source especially here (not OpenCog). Open source is wonderful in many ways, but open source volunteer labor is a really bad way to build a large-scale system if you have any other choice (also known as lots of money to fund a full-time development team).

I digress. ;-)

If you do get things building on OS X, I'd be happy to help improve the OS X build system so Xcode development works well.

**Comment by inflector** [comment]
@abhinavmoudgil95 I saw you got it compiling while I was writing my mini-diatribe. Nice job!

**Comment by abhinavmoudgil95** [comment]
@inflector Thanks!

**Comment by linas** [comment]
@abhinavmoudgil95 could you please submit a pull request that adds makes the two PyMindAgent.cc files? Or maybe @inflector can make these changes?

Re: GUI's: Yes, I tried using PyCharm Its a train wreck; I can't imagine why people even begin to consider it as an acceptable coding environment!  I used Visual C++ back in the day, and hated every second of it.  I ran away from that smoldering heap of slag as fast as I could; its how I became a Linux user in the first place. Then there was that IDE for Java, Eclipse, which seemed to require more than 4GB RAM for anything more than "hello world".  Back in the early 2000's, and 32-bit CPU's, more 4GB was hard to come by. Basically, I've never actually seen an IDE that was anything more than a colorful way to distract you with blinkenlights and slow down productivity to a painful crawl. In short IDE's suck, and 20-30 years later, essentially zero progress has been made on improving the IDE's. They still suck. In the same timeframe, there has been a revolution in software.. so really, the question is, why do IDE's still suck?  Why has there been no progress?
