### ISSUE TITLE
AtomSpace not found

### ISSUE THREAD

**Issue by shubhamG9** [opencog/opencog#2045]
shubham@ubuntu:~/Mytest/opencog/build$ cmake ..
-- Build type: Release
-- Found CogUtil version 2.0.1 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- AtomSpace not found
CMake Error at CMakeLists.txt:150 (MESSAGE):
  AtomSpace missing: it is needed for everything!

-- Configuring incomplete, errors occurred!
See also "/home/shubham/Mytest/opencog/build/CMakeFiles/CMakeOutput.log".
See also "/home/shubham/Mytest/opencog/build/CMakeFiles/CMakeError.log".

I followed all the steps mentioned for installing OpenCog

**Comment by AmeBel** [comment]
Would you point me where the instructions you used are at.

**Comment by shubhamG9** [comment]
http://wiki.opencog.org/wikihome/index.php/Installing_OpenCog_for_Noobs

It was all mentioned here

**Comment by AmeBel** [comment]
That is an obsolete page see http://wiki.opencog.org/wikihome/index.php/Building_OpenCog

**Comment by shubhamG9** [comment]
okay.Thanks

**Comment by shubhamG9** [comment]
shubham@ubuntu:~/Mytest/atomspace/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Build type: Release
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
-- Boost version 105400 found.
-- Looking for include file opencog/util/cogutil.h
-- Looking for include file opencog/util/cogutil.h - found
-- Found CogUtil version 2.0.1 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- CxxTest found.
-- Gearman found.
-- Guile (2.0.9 >= 2.0.9) was found.
-- HyperTable was not found. Make sure HYPERTABLE_LIBRARY and HYPERTABLE_INCLUDE_DIR are set.
-- Hypertable not found; the experimental distributed persistence DB needs it.
-- Found these protobuf libs: /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Protobuf was found.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7") 
-- Python libs found.
-- Found Cython: /usr/bin/cython (Required is at least version "0.19.0") 
-- Cython ( 0.20.1 >= 0.19.0) found.
-- Python destination dir found: /usr/lib/python2.7/dist-packages


while building atomspace it's stuck .

**Comment by AmeBel** [comment]
clean your build directory and restart

**Comment by linas** [comment]
closing seems to be stale bug
