### ISSUE TITLE
LG dictionary is represented incorrectly (SQL bug opencog/atomspace#650)

### ISSUE THREAD

**Issue by linas** [opencog/opencog#2050]
The current design for representing LG disjuncts is incorrect, for several reasons, explained below. The most urgent of these is that it results in bug opencog/atomspace#650, and SQL table overflow bug. 

To see the issue, do this:

```
(use-modules (opencog) (opencog nlp lg-dict))
(cog-arity (gdr (gar (lg-get-dict-entry (WordNode "drink")))))
```

which reports a link with an outgoing set with 8210 members in it.  It looks like this, if you print it out:

```
(SetLink
   (LgWordCset
      (WordNode "drink")
      (LgOr
         (LgConnector
            (LgConnectorNode "XXXGIVEN")
            (LgConnDirNode "+")
         )
         (LgConnector
            (LgConnectorNode "A")
            (LgConnDirNode "-")
            (LgConnMultiNode "@")
         )
         (LgAnd ... ; ... 8208 more entries ....
```

Besides the SQL bug, there are two other problems, one of which is extremely serious:   first, imagine an agent that is trying to learn a language.  This requires learning new disjuncts, and adding them to the set; and possibly removing others.  For the above, that requires deleting the 8210-element of the LgOr and replacing with with another one that is 8211 or 8209 or whatever.  Yuck!

Yucky, but there is also a show-stopper here: the above format makes it completely impossible to track  disjunct usage statistics!  For example, suppose we want to know how often the connector A- is used with "drink". Where can we store this count?  Not in the A- connector, because it is used in many, many different words.  And not in the  `LgWordCset`  because that doesn't tell you which disjunct is being used.  Thus, the above representation must be replaced. I propose the below ...

```
   (LgDisjunct
      (WordNode "drink")
      (LgConnector
         (LgConnectorNode "XXXGIVEN")
         (LgConnDirNode "+") ))

   (LgDisjunct
      (WordNode "drink")
      (LgConnector
         (LgConnectorNode "A")
         (LgConnDirNode "-")
         (LgConnMultiNode "@") ))

   (LgDisjunct
      (WordNode "drink")
      (LgAnd ...))

; ... 8207 more entries ....
```

This avoids the huge outgoing set.  Adding and removing new disjuncts is trivial.  And finally, there is a perfect place to store per-disjunct statistics.   (Side comment: it also illustrates why a fast `cog-fetch-incoming-set` is important: to fetch the above from SQL, one would  `(cog-fetch-incoming-set (WordNode "drink"))` and get the 8210 entries back.)

Also a different problem: I'm guessing that each and every use of the `LgOr` link type is probably wrong.  First, it should have been called `LgChoice` because its not a logical-OR, its a choice. Next, to be usable, the choices need to be in  "disjunctive normal form" (DNF) and, philosophically speaking, the atomspace is a "DNF engine" -- every top-level link is a DNF of all other links. Its what the atomspace is all about. That's a more abstract argument as to why `LdDisjunct` is "correct", while `LgOr` is "wrong".

**Comment by williampma** [comment]
This seems like a good idea, although it would also require changing SuReal to accommodate.

Changing from `LgOr` to `LgDisjunct` would be fine, since it's just naming.  As far as I remember, each entry inside the original topmost `LgOr` is already in DNF, so there shouldn't be any changes required there.

**Comment by linas** [comment]
Well, its not "just naming", it also means that `LgWordCset` is removed as a link-type, and not used any more.  Yes, this requires changes to sureal.  But you are right -- its not a big, complicated change -- it should be fairly easy, I think (a zillion times easier than redesiging the SQL backend)

**Comment by leungmanhin** [comment]
PR #2052 updated the representation, it now generates LgDisjuncts for a WordNode

**Comment by linas** [comment]
seems to be fixed. 
```
(cog-arity (lg-get-dict-entry (WordNode "drink")))
```

shows 15282 but that's because everything was jammed into a `SetLink`  I'm not sure that its a good idea to wrap everything in a SetLink like this -- it seems like an abuse, but .. whatever. Maybe OK for now.

closing
