### ISSUE TITLE
Sureal doesn't generate answers anymore

### ISSUE THREAD

**Issue by talkhaldi** [opencog/opencog#2057]
Hi, 

So I had this working before but since I pulled all the new code today, it stopped answering anything..

```
guile> (process-query "Tareq" "John threw a ball.")
Hello Tareq, you said: "John threw a ball."
You made a Declarative SpeechAct

guile> (process-query "Tareq" "Who threw a ball?")
Hello Tareq, you said: "Who threw a ball?"
You made an Interrogative SpeechAct
Sorry, I don't know the answer.
guile> (process-query "Tareq" "Tom eats apples.")
Hello Tareq, you said: "Tom eats apples."
You made a Declarative SpeechAct

guile> (process-query "Tareq" "What does Tom eat?")
Hello Tareq, you said: "What does Tom eat?"
You made an Interrogative SpeechAct
Sorry, I don't know the answer.
```

 
after this:

```
guile> (define s (car (nlp-parse "Who threw the ball?")))

guile> (define r2l-set (get-r2l-set-of-sent s))

guile> (define fzset (nlp-fuzzy-match r2l-set 'SetLink (list (DefinedLinguisticConceptNode "InterrogativeSpeechAct"))))
```

fzset does have results, but

`(define reply (gen-sentences (cog-outgoing-set fzset)))`

always gives an empty set. Can anyone else confirm this issue?

**Comment by leungmanhin** [comment]
The R2L output looks different than it used to be, it now contains some left-over wrapper SetLink/ListLink from R2L rules, that may confuses sureal as sureal takes the format into account. Perhaps this is related to the recent FC updates, I'll take a deeper look

**Comment by linas** [comment]
@leungmanhin it would also be good if the expected output of r2l was documented, and it the format that sureal expects was documented. That would make it easier for others to debug.

**Comment by leungmanhin** [comment]
@linas ok I'll also documented what format that sureal expects, for r2l, I'll try to find the document or create one if I couldn't, that should also be useful toward creating a unit test for r2l as well

**Comment by leungmanhin** [comment]
FC now returns a SetLink instead of a ListLink, so updating the `cog-delete-parent` to handle this as in PR #2059 should fix this problem
