### ISSUE TITLE
Invoking python from scheme in opencog

### ISSUE THREAD

**Issue by yenat** [opencog/opencog#2109]
Here is the place where the convae code is placed (https://github.com/yenat/opencog/tree/master/opencog/python/preload_functions) and when running the scheme code which invokes convae.conv from (https://github.com/yenat/opencog/blob/master/ex.scm) it will display python module for convae_destin_1.py not found.This python function calls other functions from different directories which in turn may be related to others. My question is how and where can I place all the functions when wanting to invoke python code from scheme like the above case.

~Regards

**Comment by linas** [comment]
Just place the directory into your PYTHONPATH environment variable: for example:
```
export PYTHONPATH=/opt/ros/indigo/lib/python2.7/dist-packages:/usr/local/share/opencog/python:/home/yenat/convae/opencog/python/preload_functions
```
That should do the trick.  Well, you have to also import the python code. There are several ways to do this.  One way is this:
```
(use-modules (opencog) (opencog python))
(python-eval "
# import assorted opencog stuff, modify as needed.
from opencog.atomspace import types
# import convae stuff, modify as needed:
import convae
")
```
You can put any kind of python code into the (python-eval "...") clause, as long as its properly indented as python normally is, and has appropriate newlines, etc.

Another way is to power up the cogserver, and then
```
echo "py\n# import assorted opencog stuff\nfrom opencog.atomspace import types\n# import convae stuff, modify as needed:\nimport convae\n" | netcat localhost 17001
```
If you run the cogserver, set the PYTHONPATH before you start the cogsrever

**Comment by bgoertzel** [comment]
Yenat,

If you're still stuck after trying Linas's suggestions,  let's see if
Selameab can make it work -- he's been fighting with various other
python/OpenCog issues lately, related to the visualizer..

And if Selameab gets stuck on it too, we can invoke the Mighty Curtis...

;)
ben

On Tue, Apr 5, 2016 at 2:52 AM, Linas Vepštas <notifications@github.com>
wrote:

> Just place the directory into your PYTHONPATH environment variable: for
> example:
>
> export PYTHONPATH=/opt/ros/indigo/lib/python2.7/dist-packages:/usr/local/share/opencog/python:/home/yenat/convae/opencog/python/preload_functions
>
> That should do the trick. Well, you have to also import the python code.
> There are several ways to do this. One way is this:
>
> (use-modules (opencog) (opencog python))
> (python-eval "
> # import assorted opencog stuff, modify as needed.
> from opencog.atomspace import types
> # import convae stuff, modify as needed:
> import convae
> ")
>
> You can put any kind of python code into the (python-eval "...") clause,
> as long as its properly indented as python normally is, and has appropriate
> newlines, etc.
>
> Another way is to power up the cogserver, and then
>
> echo "py\n# import assorted opencog stuff\nfrom opencog.atomspace import types\n# import convae stuff, modify as needed:\nimport convae\n" | netcat localhost 17001
>
> If you run the cogserver, set the PYTHONPATH before you start the cogsrever
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/2109#issuecomment-205445628>
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by Selameab** [comment]
Try adding the lines below to the end of ~/.bashrc
```
PYTHONPATH="$PYTHONPATH:/home/yenat/opencog/opencog/python/preload_functions/scripts:/home/yenat/opencog/opencog/python/preload_functions/scae_destin"
export PYTHONPATH
```
The two paths should be changed to the absolute location of scripts and scae_destin on your machine.

**Comment by yenat** [comment]
OK, thanks Selameab.

**Comment by linas** [comment]
I assume that this is no longer an issue.
