### ISSUE TITLE
failed to connect to rest api

### ISSUE THREAD

**Issue by chris-hawley** [opencog/opencog#2208]
steps to I took:
1. install latest version 
2. start opencog client 
3. start rest api using python code in rest api documentation

```
import web.api.restapi
web.api.restapi.Start().run(None, ATOMSPACE)
```

4. test using the exampleclient.py file provided. 

the error returned is 
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1.1/atoms (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
```

**Comment by AmeBel** [comment]
Just tested and was not able to reproduce your error. I also updated the wiki and moved the examples to https://github.com/opencog/opencog/tree/master//examples/restapi

**Comment by AmeBel** [comment]
@chris-hawley if you are not having any more problems please close this issue, thanks.

**Comment by chris-hawley** [comment]
I figured it out. Documentation needs to be more complete on what's available with the RESTapi
