### ISSUE TITLE
new error using (nlp-parse ...)

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2232]
(nlp-parse ... ) worked for me last week but not now.  the relex server works correctly but in the current opencog commit `f00e9f1b` i'm getting the following error:

````
scheme@(guile-user)> (use-modules (opencog)
...              (opencog nlp)
...              (opencog nlp sureal)
...              (opencog nlp chatbot) ; the chatbot defines nlp-parse
... )
link-grammar: Info: Dictionary found at /usr/local/share/link-grammar/en/4.0.dict
scheme@(guile-user)> (nlp-parse "get the ball")
ERROR: In procedure opencog-extension:
````
``ERROR: Throw to key `C++-EXCEPTION' with args `("cog-fc" "Backtrace:\nIn ice-9/boot-9.scm:\n1645: 19 [%start-stack #t #<procedure 3963e00 at system/repl/repl.scm:149:33 ()>]\n1650: 18 [#<procedure 39cc480 ()>]\nIn ice-9/eval.scm:\n 432: 17 [eval # #]\nIn srfi/srfi-1.scm:\n 578: 16 [map #<procedure 3a74f90 at ice-9/eval.scm:416:20 (a)> (#)]\nIn ice-9/eval.scm:\n 411: 15 [eval # #]\n 387: 14 [eval # #]\n 387: 13 [eval # #]\n 432: 12 [eval # #]\n 436: 11 [eval # #]\n 387: 10 [eval # #]\nIn unknown file:\n   ?: 9 [opencog-extension cog-fc (# # #)]\nIn ice-9/boot-9.scm:\n 157: 8 [catch #t #<catch-closure 39d0c00> ...]\nIn unknown file:\n   ?: 7 [apply-smob/1 #<catch-closure 39d0c00>]\nIn ice-9/boot-9.scm:\n 157: 6 [catch #t #<catch-closure 39d0ae0> ...]\nIn unknown file:\n   ?: 5 [apply-smob/1 #<catch-closure 39d0ae0>]\nIn ice-9/eval.scm:\n 386: 4 [eval #<memoized (r2l-check-name (quote (WordNode \"ball\")\n))> ()]\n 393: 3 [eval #<memoized r2l-check-name> ()]\nIn unknown file:\n   ?: 2 [memoize-variable-access! #<memoized r2l-check-name> #<directory # 2615c60>]\nIn ice-9/boot-9.scm:\n 102: 1 [#<procedure 396d840 at ice-9/boot-9.scm:97:6 (thrown-k . args)> unbound-variable ...]\nIn unknown file:\n   ?: 0 [apply-smob/1 #<catch-closure 39d0aa0> unbound-variable ...]\n\nERROR: In procedure apply-smob/1:\nERROR: Unbound variable: r2l-check-name\nABORT: unbound-variable\n (/home/biocog/hansonrobotics/opencog/atomspace/opencog/guile/SchemeEval.cc:1147)")'.
``

**Comment by leungmanhin** [comment]
`r2l-check-name` is currently defined in one of the r2l rule, loading `(opencog nlp relex2logic)` module would solve this problem

**Comment by mjsduncan** [comment]
thanks!  for some reason guile couldn't find relex2logic by just appending `(opencog nlp relex2logic)` to the above list of modules, i had to use `opencog/opencog/nlp/relex2logic/run-r2l.scm` to load the module.

**Comment by linas** [comment]
the rr2l-check-name function was renamed recently; its possible that the root cause was that you have not done a `make install` since that time.
