### ISSUE TITLE
AIML chat enhancement

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2264]
Sometimes aiml chatbot is not giving anything... it may be because of the rules themselves, for example
```
scheme@(guile-user)> (aiml-get-response-wl (List (Word "yes")))
perform srai recursion
(ListLink
   (WordNode "personality")
   (WordNode "test")
   (WordNode "question" (stv 0.01242236 0.0024937657))
)

srai result is
(ListLink
)

$16 = (ListLink
)
```

or giving something that cannot be verbalize
```
scheme@(guile-user)> (aiml-get-response-wl (List (Word "hi")))
perform srai recursion
(ListLink
   (WordNode "hello")
)

srai result is
(ListLink
   (WordNode "!")
)

$19 = (ListLink
   (WordNode "!")
)
```

or similarly 
```
scheme@(guile-user)> (aiml-get-response-wl (List (Word "how") (Word "are") (Word "you")))
$57 = (ListLink
   (WordNode "?" (stv 0.16901408 0.1416309))
)
```

Is there any quick fix to these problems?

**Comment by linas** [comment]
The srai "PERSONALITY TEST QUESTION" is handled in https://github.com/hansonrobotics/HEAD/src/chatbot/aiml/generic/personality.aiml line  32.  It makes use of the <condition> tag, which is not one of the tag types that get converted.  It's use is fairly rare, and it seems to be used as one of the mechanisms for storing facts gleaned from the conversation (e.g. the personality type of the speaker)

**Comment by linas** [comment]
Hello and Hi seem to be arranged in an infinite loop:
https://github.com/hansonrobotics/HEAD/tree/master/src/chatbot/aiml/generic/reduction2.safe.aiml#L1047
and
https://github.com/hansonrobotics/HEAD/tree/master/src/chatbot/aiml/generic/salutations.aiml#L304

I'm not sure where the lone exclamation mark is coming from.

**Comment by linas** [comment]
pull req #2268 fixes some of the punctuation issues.

**Comment by linas** [comment]
pull req #2269 provides some additional cleanup

**Comment by linas** [comment]
In order to avoid the srai "PERSONALITY TEST QUESTION", the only quick/easy solution that I see is to  not load the file https://github.com/hansonrobotics/HEAD/tree/master/src/chatbot/aiml/generic/personality.aiml into the system.

**Comment by bgoertzel** [comment]
Fair enough, we don't need that file anyway...

On Tue, Jul 12, 2016 at 7:46 AM, Linas Vepštas <notifications@github.com>
wrote:

> In order to avoid the srai "PERSONALITY TEST QUESTION", the only
> quick/easy solution that I see is to not load the file
> https://github.com/hansonrobotics/HEAD/tree/master/src/chatbot/aiml/generic/personality.aiml
> into the system.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opencog/opencog/issues/2264#issuecomment-231898657>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFolXEnrxXSVeW4rmJ4yhBmX46PNwRNUks5qUtXNgaJpZM4JJP5B>
> .
>



-- 
Ben Goertzel, PhD
http://goertzel.org

Super-benevolent super-intelligence is the thought the Global Brain is
currently struggling to form...

**Comment by linas** [comment]
I think I'm done, I don't see anything else in particular that is worth doing.

I left exclamation marks and question marks at the end of words, perhaps the text-to-speech system can do something with these?   If they cause a problem, I can remove them as well.  For example:
```
(aiml-get-response-wl (List (Word "glad") (Word "to")(Word "hear")(Word "it")))
$7 = (ListLink
   (WordNode "what's")
   (WordNode "new")
   (WordNode "with")
   (WordNode "you?")
)
```

notice the punctuation in "what's" I assume that the TTS can handle that.

**Comment by leungmanhin** [comment]
seems that the TTS we are using in HEAD does not do anything for exclamation marks and question marks... but keeping them there is fine, don't seem to cause any problem. I'll also skip the "PERSONALITY TEST QUESTION", thanks for the fixes
