### ISSUE TITLE
foreach.h:14:34: error: declaration of namespace ‘boost::BOOST_FOREACH’ conflicts...

### ISSUE THREAD

**Issue by githart** [opencog/opencog#23]
[  0%] Building CXX object opencog/util/CMakeFiles/util.dir/lazy_selector.cc.o
In file included from /home/dhart/opencog/opencog/util/lazy_selector.cc:28:0:
/home/dhart/opencog/opencog/util/foreach.h:14:34: error: declaration of namespace ‘boost::BOOST_FOREACH’ conflicts with
In file included from /usr/include/boost/multi_index/hashed_index.hpp:22:0,
                 from /home/dhart/opencog/opencog/util/lazy_selector.h:30,
                 from /home/dhart/opencog/opencog/util/lazy_selector.cc:25:
/usr/include/boost/foreach_fwd.hpp:56:1: error: previous declaration of namespace ‘boost::BOOST_FOREACH’ here
make[3]: **\* [opencog/util/CMakeFiles/util.dir/lazy_selector.cc.o] Error 1
make[2]: **\* [opencog/util/CMakeFiles/util.dir/all] Error 2
make[1]: **\* [opencog/learning/moses/CMakeFiles/moses.dir/rule] Error 2
make: **\* [moses] Error 2
(beefymiracle-virgin)dhart@opencog-aristotle:~/opencog_build$

**Comment by wvxvw** [comment]
With newer boos  105300 as is my case, the problem persists.  Had to add one more `(BOOST_VERSION/100 != 1053)` to the list.

**Comment by ngeiswei** [comment]
we could replace all foreach by C++11 range for loop and get rid of foreach.h (there are still dozens though).

**Comment by ngeiswei** [comment]
Using some regex magic I managed to replace most foreach by C++11 loop (over 300), about 5 remains that require a bit more thinking. If you still can't solve this problem let me know, I'll take care of them and we can get rid boost foreach entirely.

**Comment by linas** [comment]
Wow.

**Comment by ngeiswei** [comment]
I removed the last few foreach and deleted foreach.h
