### ISSUE TITLE
Creating a thread via AgentThreadRunner class hangs the guile shell thread

### ISSUE THREAD

**Issue by misgeatgit** [opencog/opencog#2301]
@hedayat,@linas et al. Here are the steps to reproduce this situation: 

- build and load the [this](https://gist.github.com/misgeatgit/4c9cced9b6ba071917d71a7c73fd8edd) module.
- open guile shell via telnet and start inserting random atoms and queries.

After few seconds both the AgentRunnerThread and guile shell hang. Subsequent opening of other guile shells will also result in an immediate hanging. Furthermore, if the python REST server has been run, starts hanging right after guile shell hanging. Seems a deadlock to me.

**Comment by linas** [comment]
so where is the deadlock?

start gdb, wait till it deadlocks, then say `info threads` and `thread 42` and `bt` to gather the backtraces.

my guess is that the agent code is deadlocking -- last time I looked at the agent code in the cogserver, it was in terrible shape, and very buggy -- it probably needs to be completely thrown away and re-written.

**Comment by hedayat** [comment]
@linas You're welcome! I don't remember you pointing to any bugs however. You complained a lot though!
@misgeatgit I'll try to re-produce. But if you can find the bug, it'd be better.

**Comment by misgeatgit** [comment]
I did some debugging and the lock waiting is happening here https://github.com/opencog/opencog/blob/master/opencog/cogserver/shell/GenericShell.cc#L166 and https://github.com/opencog/opencog/blob/master/opencog/cogserver/shell/GenericShell.cc#L193 .

I put the two sections in one lock_guard and the problem was solved. @linas, Since I am not sure that this a cleaner fix, it would be good if you can take this as a hint and fix it.

**Comment by linas** [comment]
you state that the deadlock is located at those two locks, but do not provide any evidence of this. What is the actual cause of the deadlock? Both of those locks protect a very short segment of code, and are released in microseconds, and make no recursive calls. How can they possibly deadlock? What am I missing?

**Comment by misgeatgit** [comment]
@linas, my usage of deadlock might be incorrect but the problem mimics that situation. Anyways, here is the backtrace.

````
(gdb) info threads
  Id   Target Id         Frame 
  17   Thread 0x7fffe4ff9700 (LWP 30395) "cogserver" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  12   Thread 0x7fffe57fa700 (LWP 30329) "cogserver" 0x00007ffff6d1c6cd in read () at ../sysdeps/unix/syscall-template.S:81
  10   Thread 0x7fffe67fc700 (LWP 30322) "cogserver" 0x00007ffff6d1c72d in write () at ../sysdeps/unix/syscall-template.S:81
  9    Thread 0x7fffe6ffd700 (LWP 30311) "cogserver" __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:95
  8    Thread 0x7fffe77fe700 (LWP 30308) "cogserver" 0x00007ffff6d2c0ed in accept () at ../sysdeps/unix/syscall-template.S:81
  7    Thread 0x7fffe7fff700 (LWP 30307) "cogserver" 0x00007ffff6cf1dfd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7fffedbaa700 (LWP 30305) "cogserver" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7fffee3ab700 (LWP 30304) "cogserver" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7fffeebac700 (LWP 30303) "cogserver" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7fffef3ad700 (LWP 30302) "cogserver" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7ffff05bd700 (LWP 30301) "cogserver" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7ffff7faf840 (LWP 30297) "cogserver" 0x00007ffff6cf1dfd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
(gdb) thread 17
[Switching to thread 17 (Thread 0x7fffe4ff9700 (LWP 30395))]
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135	../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) bt
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff5b2f649 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff5b2f470 in __GI___pthread_mutex_lock (mutex=0x7fffecb47320 <_stdout_redirect_mutex>) at ../nptl/pthread_mutex_lock.c:79
#3  0x00007fffec9416b7 in __gthread_mutex_lock (__mutex=0x7fffecb47320 <_stdout_redirect_mutex>) at /usr/include/x86_64-linux-gnu/c++/4.8/bits/gthr-default.h:748
#4  lock (this=0x7fffecb47320 <_stdout_redirect_mutex>) at /usr/include/c++/4.8/mutex:134
#5  lock_guard (__m=..., this=<synthetic pointer>) at /usr/include/c++/4.8/mutex:414
#6  opencog::GenericShell::eval (this=0x7fffd4029570, expr="(Node \"zdd\")", s=<optimized out>)
    at /home/misgana/OPENCOG/opencog/opencog/cogserver/shell/GenericShell.cc:166
#7  0x00007ffff7bc27d9 in opencog::ConsoleSocket::OnLine (this=0x7fffd8000d00, line="(Node \"zdd\")")
    at /home/misgana/OPENCOG/opencog/opencog/cogserver/server/ConsoleSocket.cc:141
#8  0x00007ffff7bc065e in opencog::ServerSocket::handle_connection (this=0x7fffd8000d00) at /home/misgana/OPENCOG/opencog/opencog/cogserver/server/ServerSocket.cc:144
#9  0x00007ffff72bda60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff5b2d184 in start_thread (arg=0x7fffe4ff9700) at pthread_create.c:312
#11 0x00007ffff6d2b37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by misgeatgit** [comment]
Another hint, what actually exposes this problem is this line of code from https://gist.github.com/misgeatgit/4c9cced9b6ba071917d71a7c73fd8edd#file-deadlocktestmodule-cc-L63 . As the agents thread keeps printing on the cogserver shell, the generic shell gets busier redirecting that to the scheme shell.... if I comment out  this printing, all seems to work.

**Comment by linas** [comment]
OK, so thread 9 is also blocked, waiting for the lock. That means that some third thread, not 17 and not 9, is holding the lock.  I am giuessing that it is thread 122, and I am guessing that thread 12 is blocked at either line 208 or 218  of GenericShell.  The reason for this is probably because the agent thread never closes stdout -- that is, when you create the thread, stdout remains open, while thread 12 is waiting for the stdout port to close, and it never does, because the new agent thread never exits.

The way to fix this is to have all agent threads close the redirect pipe, so that the read loop exits, instead of blocking.

In order to avoid the loss of print output for agents, one could either redirect stdout to some file, .. maybe the cogserver log file.  Another possibility is to redirect the pipe output to the cogservers stdou ... this might make debugging hard, if the cog-server does not have a controlling terminal (which is the normal situation -- you 'd have to start the cogserver from the bash shell to get a controlling terminal).

**Comment by AmeBel** [comment]
The hanging can be reproduced as described in https://github.com/opencog/ros-behavior-scripting/issues/74#issuecomment-234214682

**Comment by linas** [comment]
I assume that pull request #2311 fixes this?

**Comment by linas** [comment]
There are other agent bugs, I opened #2314 to track those, but I assume those bugs are not affecting the current problem?

**Comment by misgeatgit** [comment]
It partially fixes it.  But when I start the REST server from the python shell together with nlp-parse , Unless I disable those continuous prints from the agents it will hang or gets very slow.

**Comment by linas** [comment]
OK, I think that is due to bug #2315 -- python printing is broken, right now.  Can we close this bug, and continue with that bug?

**Comment by misgeatgit** [comment]
OK.

**Comment by linas** [comment]
The pull request opencog/atomspace#837 should partially fix the python printing problems -- all prints will go to the cogserver stdout.

I'm now working on code to send those prints to the telnet shell.

**Comment by linas** [comment]
anyway, the point is -- printing in python should now work, and something should appear instantly.
