### ISSUE TITLE
ERROR: In procedure dynamic-link: file: "libPythonSCM", message: "file not found"

### ISSUE THREAD

**Issue by vishnuu** [opencog/opencog#2361]
Hallo all,

I am trying for opencog chatbot demo. But when I run run-chatbot.scm, it fails.  

These errors are thrown:

`guile -l ../opencog/nlp/chatbot/run-chatbot.scm`
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/vishnu/Documents/opencog_relatedPackages/opencog/build/../opencog/nlp/chatbot/run-chatbot.scm
;;; compiling /usr/local/share/opencog/scm/opencog/nlp/chatbot/chat-utils.scm
link-grammar: Info: Dictionary found at /usr/local/share/link-grammar/en/4.0.dict
;;; WARNING: compilation of /usr/local/share/opencog/scm/opencog/nlp/chatbot/chat-utils.scm failed:
;;; ERROR: In procedure dynamic-link: file: "libPythonSCM", message: "file not found"
;;; WARNING: compilation of /home/vishnu/Documents/opencog_relatedPackages/opencog/build/../opencog/nlp/chatbot/run-chatbot.scm failed:
;;; ERROR: Unbound variable: python-eval
Listening on port 17004

Any help is welcome.

**Comment by linas** [comment]
I'm guessing that the atomspace was built without python support ...

**Comment by vishnuu** [comment]
yes thanks. I installed cython and that solved the problem.
