### ISSUE TITLE
unbound-variable: process query

### ISSUE THREAD

**Issue by vishnuu** [opencog/opencog#2364]
Hello, 

I am trying to run opencog chatbot.  I have started relex and opencog server.  when i made a sniff test, it said "unbound-variable" . 

 opencog>    (process-query "luser" "Are you a bot?")
Entering scheme shell; use ^D or a single . on a line by itself to exit.
guile> Backtrace:
In ice-9/boot-9.scm:
 157: 12 [catch #t #<catch-closure 3431f00> ...]
In unknown file:
   ?: 11 [apply-smob/1 #<catch-closure 3431f00>]
In ice-9/boot-9.scm:
 157: 10 [catch #t #<catch-closure 3431a20> ...]
In unknown file:
   ?: 9 [apply-smob/1 #<catch-closure 3431a20>]
   ?: 8 [call-with-input-string "   (process-query \"luser\" \"Are you a bot?\")\n" ...]
In ice-9/boot-9.scm:
2401: 7 [save-module-excursion #<procedure 34534b0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 6 [read-and-eval #<input: string 3193a90> #:lang ...]
  37: 5 [lp (process-query "luser" "Are you a bot?")]
In ice-9/eval.scm:
 386: 4 [eval # ()]
 393: 3 [eval #<memoized process-query> ()]
In unknown file:
   ?: 2 [memoize-variable-access! #<memoized process-query> #<directory # 19acc60>]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 3261cc0 at ice-9/boot-9.scm:97:6 (thrown-k . args)> unbound-variable ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 34319e0> unbound-variable ...]

ERROR: In procedure apply-smob/1:
ERROR: Unbound variable: process-query
ABORT: unbound-variable

I have also  these lines in the .guile :

use-modules (ice-9 readline)) (activate-readline)
(add-to-load-path "/usr/local/share/opencog/scm")
(add-to-load-path ".")
(use-modules (opencog))
(use-modules (opencog query))
(use-modules (opencog exec))
(load-from-path "opencog.scm")

What can i do now? any help is welcome. 
Thanks in advance.

**Comment by leungmanhin** [comment]
Hi, you will have to load the chatbot module also, i.e.
```
(use-modules (opencog nlp chatbot))
```

**Comment by vishnuu** [comment]
Thanks :) It is working now!

**Comment by vishnuu** [comment]
@leungmanhin  when i typed (process-query "luser" "Are you a bot?") 
it replied  "Sorry, I don't understand it "

Then I started the bot from my build directory
 opencog/nlp/irc/cogita 

and in the freenode.net i started a conversion
[11:20] <vishnuu> hello
[11:20] <cogita-bot> [0;32mopencog[1;32m> [0m

It does not reply. what should i  probably do now?

**Comment by leungmanhin** [comment]
Please make sure you have the relex installed and have the relex server started beforehand https://github.com/opencog/relex/blob/master/opencog-server.sh

and you will also have to give some "knowledge" to the system by parsing them via `nlp-parse`, e.g.
```
(nlp-parse "the sky is beautiful")
```

On the other hand, I recommend you to use this chatbot instead (https://github.com/opencog/opencog/tree/master/opencog/nlp/chatbot-psi), which is newer and is more robust. And it is recommended to run it with HEAD (https://github.com/hansonrobotics/HEAD/). The `hrtool` in HEAD will set up everything for you, you can refer to the README file in HEAD for details.

**Comment by vishnuu** [comment]
@leungmanhin Thank you very much for the reply. 

1.  I tried running  hanson robotics head on linux minut 17.3 (based on ubuntu trusty) and on linux mint 18.  But it threw an error saying :
[ERROR] Error: Only Ubuntu 14.04 (trusty) is supported
will it not run on Linux mint?

2. I have also tried giving some knowledge
guile> (nlp-parse "the sky is beautiful")
guile> (process-query "vishnu" "what is beautiful?")
(relex server is also running) 

It throws the following error saying 'basic_sentiment_analysis' is not defined. :
Backtrace:
In ice-9/boot-9.scm:
 157: 11 [catch #t #<catch-closure 22b36e0> ...]
In unknown file:
   ?: 10 [apply-smob/1 #<catch-closure 22b36e0>]
In ice-9/boot-9.scm:
 157: 9 [catch #t #<catch-closure 22b3000> ...]
In unknown file:
   ?: 8 [apply-smob/1 #<catch-closure 22b3000>]
   ?: 7 [call-with-input-string "(nlp-parse \"the sky is beautiful\")\n(process-query \"priya\" \"what is beautiful?\")\n" ...]
In ice-9/boot-9.scm:
2401: 6 [save-module-excursion #<procedure 3d3c510 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 5 [read-and-eval #<input: string 3d3a4e0> #:lang ...]
  37: 4 [lp (nlp-parse "the sky is beautiful")]
In opencog/nlp/chatbot/chat-utils.scm:
 272: 3 [nlp-parse "the sky is beautiful"]
In unknown file:
   ?: 2 [opencog-extension cog-evaluate! (#)]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 3d43d80 at ice-9/boot-9.scm:97:6 (thrown-k . args)> C++-EXCEPTION ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 229eae0> C++-EXCEPTION ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure cog-evaluate!: Python error in call_sentiment_parse: global name 'basic_sentiment_analysis' is not defined. (/home/vishnu/Documents/opencog_relatedPackages/atomspace/opencog/cython/PythonEval.cc:812)
ABORT: C++-EXCEPTION

Any suggestions?

**Comment by leungmanhin** [comment]
yes https://github.com/opencog/opencog/issues/2366#issuecomment-239933147 was the reason
