### ISSUE TITLE
opencog chatbot error 'basic_sentiment_analysis' is not defined

### ISSUE THREAD

**Issue by vishnuu** [opencog/opencog#2366]
I have tried giving some knowledge for running opencog chatbot 
`guile> (nlp-parse "the sky is beautiful")`

(relex server is also running)

It throws the following error saying 'basic_sentiment_analysis' is not defined. :
Backtrace:
In ice-9/boot-9.scm:
157: 11 [catch #t # ...]
In unknown file:
?: 10 [apply-smob/1 #]
In ice-9/boot-9.scm:
157: 9 [catch #t # ...]
In unknown file:
?: 8 [apply-smob/1 #]
?: 7 [call-with-input-string "(nlp-parse \"the sky is beautiful\")\n(process-query \"priya\" \"what is beautiful?\")\n" ...]
In ice-9/boot-9.scm:
2401: 6 [save-module-excursion #]
In ice-9/eval-string.scm:
44: 5 [read-and-eval # #:lang ...]
37: 4 [lp (nlp-parse "the sky is beautiful")]
In opencog/nlp/chatbot/chat-utils.scm:
272: 3 [nlp-parse "the sky is beautiful"]
In unknown file:
?: 2 [opencog-extension cog-evaluate! (#)]
In ice-9/boot-9.scm:
102: 1 [# C++-EXCEPTION ...]
In unknown file:
?: 0 [apply-smob/1 # C++-EXCEPTION ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure cog-evaluate!: Python error in call_sentiment_parse: global name 'basic_sentiment_analysis' is not defined. (/home/vishnu/Documents/opencog_relatedPackages/atomspace/opencog/cython/PythonEval.cc:812)
ABORT: C++-EXCEPTION

Any suggestions?
Any help is welcome.

**Comment by vishnuu** [comment]
I followed this [link](https://github.com/opencog/opencog/issues/2285).  

Installed following things. It worked!!!
`sudo pip install pyyaml`
`sudo pip install -U pyyaml nltk 
sudo python -m nltk.downloader -d /usr/local/share/nltk_data punkt averaged_perceptron_tagger`

**Comment by linas** [comment]
opencog needs to be fixed so that it still works, even if NLTK is not installed.

The sentiment analysis code probably does not belong in this project, but should be a separate project.

**Comment by linas** [comment]
I believe that pull req #2401 should fix this.  I'm closing this issue for now, let me know if there are any further issues.
