### ISSUE TITLE
Problems in running opencog/nlp/chatbot-psi with imported AIML rules

### ISSUE THREAD

**Issue by bryantclc** [opencog/opencog#2368]
Hi, everyone. 
I have some problems when I run chatbot-psi with imported AIML rules.
I describe the steps I take to make use AIML rules in chatbot-psi of OpenCog, and to show the detailed problems we faced:
(1)I get some AIML rules from hansonrobotics/HEAD: https://github.com/hansonrobotics/HEAD/tree/master/src/chatbot/scripts/aiml/generic 
(2)I translate one AIML file into Openpsi rule use aiml2psi.pl script in “nlp/aiml/import” dir, and it can get aiml-rules.scm successfully: 
# ./aiml2psi.pl --dir /home/chenlicheng/robot/opencog/opencog-master/build/aiml

(3)Start the relex server with default port 4444: # /home/chenlicheng/robot/opencog/relex-master/opencog-server.sh
(4)In another shell window, start cogserver with default configuration: # /home/chenlicheng/robot/opencog/opencog-master/build/ opencog/cogserver/server/cogserver
(5)In another shell window, connect to the cogserver with telnet: # rlwrap telnet localhost 17001
(6)Entering into scheme shell (in (5) client window): # opencog> scm
(7)Add the load path of chatbot-psi: # guile> (add-to-load-path "/home/chenlicheng/robot/opencog/opencog-master/opencog/nlp/chatbot-psi")
(8)Load the main.scm of chatbot-psi as shown in README.md: guile> (load-from-path "main.scm")
(9)For convenient, we copy the aiml-rules.scm file into the chatbot-psi directory and then load it : # guile> (load-from-path "aiml-rules.scm")
(10)     Then we can chat with the robot-psi, such as this question: # guile> (chat "what is ai")  
Please Note: “what is ai” is the exact question in the AIML and aiml-rules.scm file
(11)     In Cogserver window, we can see it can generate the right answer, as shown with Eva says
Using default config at lib/opencog.conf
Using default config at ../lib/opencog.conf
Using default config at /usr/local/etc/opencog.conf
Listening on port 17001
;;; note: source file /home/chenlicheng/robot/opencog/opencog-master/opencog/nlp/chatbot-psi/main.scm
;;;       newer than compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/chenlicheng/robot/opencog/opencog-master/opencog/nlp/chatbot-psi/main.scm.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/chenlicheng/robot/opencog/opencog-master/opencog/nlp/chatbot-psi/main.scm
link-grammar: Info: Dictionary found at /usr/local/share/link-grammar/en/4.0.dict
;;; main.scm:45:4: warning: possibly unbound variable `reset-all-chatbot-states'
;;; main.scm:50:8: warning: possibly unbound variable`input-utterance'
;;; main.scm:53:8: warning: possibly unbound variable `input-utterance-sentence'
;;; main.scm:54:8: warning: possibly unbound variable`input-utterance-text'
;;; main.scm:55:8: warning: possibly unbound variable `input-utterance-words'
;;; main.scm:55:37: warning: possibly unbound variable`get-word-list'
;;; compiled /root/.cache/guile/ccache/2.0-LE-8-2.0/home/chenlicheng/robot/opencog/opencog-master/opencog/nlp/chatbot-psi/main.scm.go
WARNING: (guile-user): `nlp-parse' imported from both (opencog nlp chatbot) and (opencog nlp chatbot-eva)
WARNING: (opencog nlp chatbot-eva):`r2l-rules' imported from both (opencog nlp relex2logic) and (opencog nlp chatbot-psi)
(Eva says:  artificial intelligence is the branch of engineering and science devoted to constructing machines that think )

(12)     However, in the client window, we do not get the answer immediately.
(13)     Then I ask another question in client window: guile> (chat "who created aiml")  /// this is also the exact question in the AIML rule
(14)     Now that the client window get the answer of the first question (“what is ai”): 
artificial intelligence is the branch of engineering and science devoted to constructing machines that think
(15)     But in the cogserver window, it get the right answer :
(Eva says:  artificial intelligence is the branch of engineering and science devoted to constructing machines that think )
(Eva says:  Dr Richard S Wallace created AIML )
(16)     Then if I ask the third question in client window, it will return the answer of the second question, and so on.
(17)    In conclusion, the problem is that the client can not get the answer immediately, and it will get the answer of the previous question. But the cogserver works normally.

Next I will list two problems we have faced which will result in the cogserver crushed:
(1) When we want to ask the question with some word different of AIML rule, the cogserver will be crushed, for example, in AIML, the exact question is “what is ai”, however, when we ask that “what is the ai” , the cogserver throws exception and crushed as following:

(Eva says:  artificial intelligence is the branch of engineering and science devoted to constructing machines that think )
(Eva says:  Dr Richard S Wallace created AIML )
Backtrace:
In ice-9/boot-9.scm:
157: 2 [catch #t #<catch-closure 1804ea0> ...]
In unknown file:
   ?: 1 [apply-smob/1 #<catch-closure 1804ea0>]
   ?: 0 [opencog-extension cog-evaluate! ((DefinedPredicateNode "OpenPsi: loop")
)]

ERROR: In procedure opencog-extension:
ERROR: Throw to key `C++-EXCEPTION' with args`("cog-evaluate!" "Backtrace:\nIn ice-9/boot-9.scm:\n 157: 13 [catch #t #<catch-closure 1804ea0> ...]\nIn unknown file:\n   ?: 12 [apply-smob/1 #<catch-closure 1804ea0>]\n   ?: 11 [opencog-extension cog-evaluate! ((DefinedPredicateNode \"OpenPsi: loop\")\n)]\nIn ice-9/boot-9.scm:\n 157: 10 [catch #t #<catch-closure 47e7a80> ...]\nIn unknown file:\n   ?: 9 [apply-smob/1 #<catch-closure 47e7a80>]\nIn ice-9/boot-9.scm:\n 157: 8 [catch #t #<catch-closure 47e7960> ...]\nIn unknown file:\n   ?: 7 [apply-smob/1 #<catch-closure 47e7960>]\nIn opencog/openpsi/main.scm:\n  90: 6 [psi-step]\nIn srfi/srfi-1.scm:\n 578: 5 [map #<procedure ffe7c0 at opencog/openpsi/main.scm:91:8 (d)> (#)]\n 578: 4 [map #<procedure act-and-evaluate (rule)> (#)]\nIn opencog/openpsi/main.scm:\n  80: 3 [act-and-evaluate #]\nIn unknown file:\n   ?: 2 [opencog-extension cog-execute! (#)]\nIn ice-9/boot-9.scm:\n 102: 1 [#<procedure 47b7a80 at ice-9/boot-9.scm:97:6 (thrown-k . args)> C++-EXCEPTION ...]\nIn unknown file:\n   ?: 0 [apply-smob/1 #<catch-closure 47e7920> C++-EXCEPTION ...]\n\nERROR: In procedure apply-smob/1:\nERROR: In procedure cog-execute!: Failed evaluation; see logfile for stack trace. (/home/chenlicheng/robot/opencog/atomspace-master/opencog/atoms/execution/ExecutionOutputLink.cc:159)\nABORT: C++-EXCEPTION\n (/home/chenlicheng/robot/opencog/atomspace-master/opencog/guile/SchemeEval.cc:1147)")'.

> > We think in opencog, it will adopt fuzzy matching and PLN reasoning, so this question should be handled correctly if we remove the stop word of “the”. And even if it can not be matched with AIML rules, it should output something like “Sorry, I can not answer the question” but not to be crushed.

(2) When we ask exactly the same question twice, the cogserver will also be crushed:
In client: 
# guile> (chat "what is ai")
# guile> (chat "what is ai") #

   In cogserver, it throws exception:
    (Eva says:  artificial intelligence is the branch of engineering and science devoted to constructing machines that think )
Backtrace:
In ice-9/boot-9.scm:
157: 2 [catch #t #<catch-closure 2001d40> ...]
In unknown file:
   ?: 1 [apply-smob/1 #<catch-closure 2001d40>]
   ?: 0 [opencog-extension cog-evaluate! ((DefinedPredicateNode "OpenPsi: loop")
)]

ERROR: In procedure opencog-extension:
ERROR: Throw to key `C++-EXCEPTION' with args`("cog-evaluate!" "Backtrace:\nIn ice-9/boot-9.scm:\n 157: 13 [catch #t #<catch-closure 2001d40> ...]\nIn unknown file:\n   ?: 12 [apply-smob/1 #<catch-closure 2001d40>]\n   ?: 11 [opencog-extension cog-evaluate! ((DefinedPredicateNode \"OpenPsi: loop\")\n)]\nIn ice-9/boot-9.scm:\n 157: 10 [catch #t #<catch-closure 1adc920> ...]\nIn unknown file:\n   ?: 9 [apply-smob/1 #<catch-closure 1adc920>]\nIn ice-9/boot-9.scm:\n 157: 8 [catch #t #<catch-closure 1adc800> ...]\nIn unknown file:\n   ?: 7 [apply-smob/1 #<catch-closure 1adc800>]\nIn opencog/openpsi/main.scm:\n  90: 6 [psi-step]\nIn srfi/srfi-1.scm:\n 578: 5 [map #<procedure 17c3580 at opencog/openpsi/main.scm:91:8 (d)> (#)]\n 578: 4 [map #<procedure act-and-evaluate (rule)> (#)]\nIn opencog/openpsi/main.scm:\n  80: 3 [act-and-evaluate #]\nIn unknown file:\n   ?: 2 [opencog-extension cog-execute! (#)]\nIn ice-9/boot-9.scm:\n 102: 1 [#<procedure 1d5d540 at ice-9/boot-9.scm:97:6 (thrown-k . args)> C++-EXCEPTION ...]\nIn unknown file:\n   ?: 0 [apply-smob/1 #<catch-closure 1adc7c0> C++-EXCEPTION ...]\n\nERROR: In procedure apply-smob/1:\nERROR: In procedure cog-execute!: Failed evaluation; see logfile for stack trace. (/home/chenlicheng/robot/opencog/atomspace-master/opencog/atoms/execution/ExecutionOutputLink.cc:159)\nABORT: C++-EXCEPTION\n (/home/chenlicheng/robot/opencog/atomspace-master/opencog/guile/SchemeEval.cc:1147)")'.

> > we can not understand that why cogserver will be crushed if it is asked with the same question twice.

Can someone help us to figure out why these problems happened and how to fix it?
Thanks very much!

**Comment by leungmanhin** [comment]
Hi, could you try again running it with HEAD (https://github.com/hansonrobotics/HEAD) altogether? Because it will launch a web interface and you are recommended to interact with it via that web interface instead.

**Comment by bryantclc** [comment]
Hi leungmanhin, thanks for your help.
I will try to run opencog with HEAD altogether

**Comment by bryantclc** [comment]
Hi, I find in the HEAD  (https://github.com/hansonrobotics/HEAD) , it also uses chatbot-psi module to run OpenCog based chatbot and behavior tree, in which it also import AIML rules. 

But it needs some more steps to make it work well, as shown in the HEAD/scripts/load_scm.exp:


send "(use-modules (opencog logger))\n"
send "(cog-logger-set-level! \"$OC_LOG_LEVEL\")\n"

send "(load \"$HR_WORKSPACE/opencog/opencog/opencog/nlp/chatbot-psi/main.scm\")\n"

**send "(markov-setup \"$MARKY_MARKOV_DIR/bin\" \"$HR_MODELS/markov_modeling\")\n"**

send "(psi-halt)\n"
**send "(load \"$OC_AIML_FILE\")\n"**
send "(if (not (psi-running?)) (psi-run))\n"


Note that:
(1) We need to download the AIML rules from here:  https://github.com/opencog/test-datasets/releases/download/current/aiml-current.tar.gz.
And it contains the "load-all.scm" script file to help us to load AIML rules into OpenCog
(2)We also need to install the marky_markov and setup markov in OpenCog: https://github.com/hansonrobotics/marky_markov.git
The markov_modeling can be download from: https://github.com/opencog/test-datasets/releases/download/current/markov_modeling.tar.gz 


After setup markov and load-all.scm, the chatbot-psi wouldn't be crushed:
(1) It wouldn't be crushed if it is asked with some unknown question, e.g. "what is the ai", instead, it will return some random answer, such as "(Eva says:  can vegetarians eat animal crackers ? )"
(2) It wouldn't be crushed if it is asked with the some question twice. However, it will also return some random answer for the second same question (the first one is the right answer):

Questions:
#what is ai
#what is ai
#what is ai

Answers:
(Eva says:  artificial intelligence is the branch of engineering and science devoted to constructing machines that think )
(Eva says:  why isn't 11 pronounced onety one ? )
(Eva says:  why is ' abbreviated' such a long word ? )

**Comment by leungmanhin** [comment]
hi @bryantclc, good to see it's working for you, these steps can be run automatically by `scripts/dev.sh --oc`

**Comment by linas** [comment]
based on the last comment, sounds like this is no longer an issue. Closing.
