### ISSUE TITLE
error: no code for module (opencog-eva-model) when running chatbot-psi

### ISSUE THREAD

**Issue by vishnuu** [opencog/opencog#2371]
Hello all,

I am trying to run opencog chatbot-psi.  
(My relex and cog server also running)

when i tried loading "main.scm", it said "no code for module (opencog-eva-model)"

`guile> (add-to-load-path "/home/vishnu/Documents/opencog_relatedPackages/opencog/opencog/nlp/chatbot-psi")`
`guile> (load-from-path "main.scm")`

Throws the folllowing error:
Backtrace:
In ice-9/boot-9.scm:
1724: 19 [%start-stack load-stack #<procedure 300f9c0 at ice-9/boot-9.scm:1745:2 ()>]
1729: 18 [#<procedure 2d51930 ()>]
In unknown file:
   ?: 17 [primitive-load-path "main.scm"]
In main.scm:
  21: 16 [#<procedure 31dbfa0 ()>]
In ice-9/boot-9.scm:
2401: 15 [save-module-excursion #<procedure 33aff40 at ice-9/boot-9.scm:4045:3 ()>]
4054: 14 [#<procedure 33aff40 at ice-9/boot-9.scm:4045:3 ()>]
1724: 13 [%start-stack load-stack #<procedure 321e700 at ice-9/boot-9.scm:1745:2 ()>]
1729: 12 [#<procedure 2f557e0 ()>]
In unknown file:
   ?: 11 [primitive-load-path "./actions.scm"]
In ice-9/eval.scm:
 505: 10 [#<procedure 21e8580 at ice-9/eval.scm:499:4 (exp)> (use-modules #)]
In ice-9/psyntax.scm:
1106: 9 [expand-top-sequence ((use-modules (opencog eva-model))) () ...]
 989: 8 [scan ((use-modules (opencog eva-model))) () ...]
 279: 7 [scan ((# #) #(syntax-object *unspecified* # #)) () (()) ...]
In ice-9/boot-9.scm:
3597: 6 [process-use-modules (((opencog eva-model)))]
 702: 5 [map #<procedure 2284160 at ice-9/boot-9.scm:3597:25 (mif-args)> ((#))]
3598: 4 [#<procedure 2284160 at ice-9/boot-9.scm:3597:25 (mif-args)> (#)]
2867: 3 [resolve-interface (opencog eva-model) #:select ...]
In unknown file:
   ?: 2 [scm-error misc-error #f ...]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 3005b80 at ice-9/boot-9.scm:97:6 (thrown-k . args)> misc-error ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 300fd60> misc-error ...]

ERROR: In procedure apply-smob/1:
ERROR: no code for module (opencog eva-model)
ABORT: misc-error

what can i do now ?

**Comment by AmeBel** [comment]
Do this
```bash
git clone https://github.com/opencog/ros-behavior-scripting
cd ros-behavior-scripting-master/
mkdir build
cd build/
cmake ..
sudo make install
```

**Comment by leungmanhin** [comment]
Yes, or run it with HEAD (https://github.com/hansonrobotics/HEAD/)

**Comment by vishnuu** [comment]
thanks @AmeBel @leungmanhin  yeah i did.  But when i query it says  "wrong-typ-arg"

`(aiml-get-response-wl (token-seq-of-sent "what is ai?"))`

ERROR: In procedure apply-smob/1:
ERROR: In procedure cog-type: Wrong type argument in position 1 (expecting opencog atom): "what is ai?"
ABORT: wrong-type-arg
