### ISSUE TITLE
make install fails 

### ISSUE THREAD

**Issue by noskill** [opencog/opencog#239]
[ 15%] Built target tree_gen
[ 15%] Generating opencog/cogserver.cpp
Scanning dependencies of target cogserver_cython
[ 15%] Building CXX object opencog/cython/CMakeFiles/cogserver_cython.dir/opencog/cogserver.cpp.o
In file included from /home/leron/projects/devsources/opencog/build/opencog/cython/opencog/cogserver.cpp:322:0:
/home/leron/projects/devsources/opencog/opencog/atomspace/ClassServer.h:35:42: fatal error: opencog/atomspace/atom_types.h: No such file or directory
compilation terminated.
make[2]: *** [opencog/cython/CMakeFiles/cogserver_cython.dir/opencog/cogserver.cpp.o] Error 1
make[1]: *** [opencog/cython/CMakeFiles/cogserver_cython.dir/all] Error 2
make: *** [all] Error 2

**Comment by linas** [comment]
Closing.  I pushed a string of fixes for this, earlier today. They are the fixes in between commit 47b066d5aad125940f0643b833094a90234399bd and 19d4bafb8a2ba7c3c9e8e305d4ffe16b05b458b2

Sorry I did not lump them into a pull request: I thought there would be only one fix, then only two, then only three ... it took 8 patches to get this to work.

p.s. after this, a suitabley-modified opencog.conf will: 
* load cogserver modules
* load scm scripts.

I have not tried python script loading yet, ts probably still broken.

I am closing this, based on above ..
