### ISSUE TITLE
REST API in examples

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#2398]
I'm running Ubuntu 16.04 x64. To the best of my ability, I've made sure I've installed opencog correctly.
When I tried to run `python ~/opencog/examples/restapi/start_restapi.py`, I got an error 

> Traceback (most recent call last):
>   File "start_restapi.py", line 1, in <module>
>     from web.api.apimain import RESTAPI
> ImportError: No module named web.api.apimain

Then I did `sudo pip install flask`, and now the same code returns

> /usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
>   .format(x=modname), ExtDeprecationWarning
> Traceback (most recent call last):
>   File "start_restapi.py", line 1, in <module>
>     from web.api.apimain import RESTAPI
>   File "/home/enoch/opencog/opencog/python/web/api/apimain.py", line 4, in <module>
>     from flask.ext.restful import Api
>   File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 110, in load_module
>     raise ImportError('No module named %s' % fullname)
> ImportError: No module named flask.ext.restful

When I tried to replace `flask.ext.restful` with `flask_restful `in `start_restapi.py`, I got

> Traceback (most recent call last):
>   File "start_restapi.py", line 1, in <module>
>     from web.api.apimain import RESTAPI
>   File "/home/enoch/opencog/opencog/python/web/api/apimain.py", line 4, in <module>
>     from flask_restful import Api
> ImportError: No module named flask_restful

What am I doing wrong?

**Comment by StrangeTcy** [comment]
Ok, I followed the advice from [here](http://stackoverflow.com/questions/27899911/no-module-named-flask-ext-restful), and now I'm getting 

> Traceback (most recent call last):
>   File "start_restapi.py", line 1, in <module>
>     from web.api.apimain import RESTAPI
>   File "/home/enoch/opencog/opencog/python/web/api/apimain.py", line 5, in <module>
>     from flask.ext.cors import CORS
>   File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 110, in load_module
>     raise ImportError('No module named %s' % fullname)
> ImportError: No module named flask.ext.cors

**Comment by StrangeTcy** [comment]
Ok, `sudo pip install`ing anything python complains about not finding did the trick. Guess I'm just new to python.

**Comment by linas** [comment]
there may be bugs in the rest api. It is not regularly used, and may have bit-rotted.
