### ISSUE TITLE
Chatbot and the Error: wrong type argument  

### ISSUE THREAD

**Issue by vishnuu** [opencog/opencog#2400]
Hello all,

I tried chatbot demonstration and I got the Error "wrong type argument". 

I did the following:
1. Run relex server with default port 4444.
2. Connect cogserver to telnet 17004.
    then typed (process-query "vishnu" "are you a bot?")
    It said like this, "I can't process truth query for now"
3.Then in the guile,  I gave some knowledge and in turn questioned the chatbot.
`guile>(nlp-parse "john is generous")`
`guile> (process-query "Priya" "who is generous?")`
Hello Priya, you said: "who is generous?"
You made an Interrogative SpeechAct
wrong-type-arg
(display Wrong type argument in position ~A: ~S (2 0) (0))
Sorry, I don't understand it

My .guile file is as follows:
`(use-modules (ice-9 readline)) (activate-readline)`
`(add-to-load-path "/usr/local/share/opencog/scm")`
`(add-to-load-path ".")`
`(use-modules (opencog))`
`(use-modules (opencog nlp chatbot))`
`(use-modules (opencog query))`
`(use-modules (opencog exec))`
`(load-from-path "opencog.scm")`

-----------------------------------------------------------------------------------------------------------------------
I also tried chatbot-psi. 

1. I converted one of the AIML files into scm and kept in .tmp.
`import/aiml2psi.pl --dir /where/the/aiml/files/are`
 `cp aiml-rules.scm /tmp`

2. started relex and cog server.i in 17001. Then in the guile 
`(use-modules (opencog) (opencog nlp) (opencog nlp aiml) (opencog openpsi))`
`(primitive-load "/tmp/aiml-rules.scm")`
` (aiml-get-response-wl (token-seq-of-sent "what is ai ?"))`

Backtrace:
In ice-9/boot-9.scm:
 157: 14 [catch #t #<catch-closure 15b8d20> ...]
In unknown file:
   ?: 13 [apply-smob/1 #<catch-closure 15b8d20>]
In ice-9/boot-9.scm:
 157: 12 [catch #t #<catch-closure 15b8680> ...]
In unknown file:
   ?: 11 [apply-smob/1 #<catch-closure 15b8680>]
   ?: 10 [call-with-input-string "(aiml-get-response-wl (token-seq-of-sent \"what is ai?\"))\n" ...]
In ice-9/boot-9.scm:
2401: 9 [save-module-excursion #<procedure 2e8d9f0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 8 [read-and-eval #<input: string 242e0d0> #:lang ...]
  37: 7 [lp (aiml-get-response-wl (token-seq-of-sent {"what is ai?"}))]
In ice-9/eval.scm:
 387: 6 [eval # ()]
In opencog/nlp/aiml.scm:
  60: 5 [token-seq-of-sent {"what is ai?"}]
In utilities.scm:
 545: 4 [cog-chase-link-chk ParseLink ParseNode {"what is ai?"} SentenceNode]
 662: 3 [cog-map-chase-links-chk ParseLink ParseNode ...]
In unknown file:
   ?: 2 [cog-type {"what is ai?"}]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 2e7fc80 at ice-9/boot-9.scm:97:6 (thrown-k . args)> wrong-type-arg ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 15b8640> wrong-type-arg ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure cog-type: Wrong type argument in position 1 (expecting opencog atom): "what is ai?"
ABORT: wrong-type-arg

I also tried like this:
`(aiml-get-response-wl (string-words "what is ai?"))`
Backtrace:
In ice-9/boot-9.scm:
 157: 13 [catch #t #<catch-closure 3811d40> ...]
In unknown file:
   ?: 12 [apply-smob/1 #<catch-closure 3811d40>]
In ice-9/boot-9.scm:
 157: 11 [catch #t #<catch-closure 3811680> ...]
In unknown file:
   ?: 10 [apply-smob/1 #<catch-closure 3811680>]
   ?: 9 [call-with-input-string "(aiml-get-response-wl (string-words \"what is ai?\"))\n" ...]
In ice-9/boot-9.scm:
2401: 8 [save-module-excursion #<procedure 39e5ab0 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 7 [read-and-eval #<input: string 3011c30> #:lang ...]
  37: 6 [lp (aiml-get-response-wl (string-words "what is ai?"))]
In ice-9/eval.scm:
 387: 5 [eval # ()]
 386: 4 [eval #<memoized (string-words (quote "what is ai?"))> ()]
 393: 3 [eval #<memoized string-words> ()]
In unknown file:
   ?: 2 [memoize-variable-access! #<memoized string-words> #<directory # 101ac60>]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 37b7dc0 at ice-9/boot-9.scm:97:6 (thrown-k . args)> unbound-variable ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 3811640> unbound-variable ...]

ERROR: In procedure apply-smob/1:
ERROR: Unbound variable: string-words
ABORT: unbound-variable

Am i missing anything here?  Any kind of help would be very helpful for me.

Thanks in advance.
-Vishnu

**Comment by linas** [comment]
Bad usage; Try doing this:
```
(relex-parse "what is ai ?")
(token-seq-of-sent (car (get-new-parsed-sentences)))
```

However, I'm sure that AIML will interact badly with relex -- AIML does not care for parsed sentences in which words have been converted into lemmas. What you seem to want to do is this:
```
aiml-get-response-wl (string-words "what is ai ?"))
```
assuming that you have previously defined this:
```
(define (string-words SENT-STR)
   (ListLink (map
      (lambda (w) (Word w))
      (string-tokenize SENT-STR)))
)
```

**Comment by linas** [comment]
The other bug you reported here,
```
guile> (process-query "Priya" "who is generous?")
Hello Priya, you said: "who is generous?"
You made an Interrogative SpeechAct
wrong-type-arg
(display Wrong type argument in position ~A: ~S (2 0) (0))
```
I cannot reproduce this bug. Please verify that this is still an issue.

**Comment by vishnuu** [comment]
Thanks linas for your reply!  Yeah this error still exists. Initially I got the following error.

`Hello Priya, you said: "who is generous?"
You made an Interrogative SpeechAct
Sorry, I don't understand it`
