### ISSUE TITLE
Guile returns "no code for module"

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#2411]
I'm trying to go to `~/opencog/opencog/nlp/chatbot` and run `sudo guile run-chatbot.scm`, and it doesn't work as expected and the traceback ends with 

> ERROR: In procedure scm-error:
> ERROR: no code for module (opencog cogserver)

I'm no guile expert (yet), but I'd like to get an idea where guile is looking for modules so that I can put some there for it to find.

**Comment by ngeiswei** [comment]
I believe you need to install opencog `sudo make install` under the build directory.

**Comment by ngeiswei** [comment]
Oh, you don't need to run guile with `sudo`, only the installation.

**Comment by StrangeTcy** [comment]
I've done it a long time ago, and recently I've re`install`ed it hoping it'd help.

As for using `sudo` with `guile`, I know, but I doubt that's the cause of my problem :-)

**Comment by leungmanhin** [comment]
I guess `-l` is missing, could you try again with `guile -l run-chatbot.scm`?

**Comment by StrangeTcy** [comment]
As I understand it, `-l` loads modules from paths stated in `~/.guile`. And it would seem that in my case they neccessary modules aren't there.

**Comment by StrangeTcy** [comment]
Ok, it turns out that `guile` has a useful `%load-path` command which shows you exactly what I wished to know.
Now to `cp` all the modules that for some reason didn't get copied there in the first place.

**Comment by StrangeTcy** [comment]
That's what I was looking for. Which closes the issue.
