### ISSUE TITLE
Can't make fuzzySCM

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#2428]
I'm trying to rebuild opencog, and while `cmake ..` seems to report no problems, `make` starts to report errors after 
```
[ 26%] Building CXX object opencog/nlp/fuzzy/CMakeFiles/nlpfz.dir/FuzzySCM.cc.o
/home/myname/opencog/opencog/nlp/fuzzy/FuzzySCM.cc: In member function ‘void opencog::nlp::FuzzySCM::init()’:
/home/myname/opencog/opencog/nlp/fuzzy/FuzzySCM.cc:76:46: error: no matching function for call to ‘define_scheme_primitive(const char [16], opencog::Handle (opencog::nlp::FuzzySCM::*)(opencog::Handle, opencog::Type, const HandleSeq&, bool), opencog::nlp::FuzzySCM*, const char [10])’
                             this, "nlp fuzzy");
                                              ^
```
See attached files for details
[make_opencog.txt](https://github.com/opencog/opencog/files/465512/make_opencog.txt)

**Comment by linas** [comment]
Did you build and install the atomspace first?

**Comment by StrangeTcy** [comment]
Yes, but that was a long time ago. Reinstalling it now, to make sure.

**Comment by linas** [comment]
The atomspace is frequently updated with opencog itself.  If "a long time ago" is more than a few months, you will also need to update cogutils, before you do the atomspace.

**Comment by StrangeTcy** [comment]
Ok, I've tried re`make`ing opecnog, and to make that I  tried to `make && make install` atomspace, and to do _that_, I installed a lot of other stuff.
Now the making of opencog went on rather smoothly, but then it failed:
```
[ 67%] Building CXX object opencog/spatial/CMakeFiles/SpaceMap.dir/MovableEntity.cc.o
[ 67%] Building CXX object opencog/spatial/CMakeFiles/SpaceMap.dir/Block.cc.o
[ 68%] Building CXX object opencog/spatial/CMakeFiles/SpaceMap.dir/3DSpaceMap/SpaceMapUtil.cc.o
In file included from /home/myname/opencog/opencog/spatial/3DSpaceMap/SpaceMapUtil.h:8:0,
                 from /home/myname/opencog/opencog/spatial/3DSpaceMap/SpaceMapUtil.cc:8:
/home/myname/opencog/opencog/spatial/3DSpaceMap/OctomapOcTree.h: In member function ‘opencog::spatial::OctomapOcTreeNode* opencog::spatial::OctomapOcTreeNode::getChild(unsigned int)’:
/home/myname/opencog/opencog/spatial/3DSpaceMap/OctomapOcTree.h:73:57: error: ‘getChild’ is not a member of ‘octomap::OcTreeNode’
                 return static_cast<OctomapOcTreeNode*> (OcTreeNode::getChi
                                                         ^
/home/myname/opencog/opencog/spatial/3DSpaceMap/OctomapOcTree.h: In member function ‘const opencog::spatial::OctomapOcTreeNode* opencog::spatial::OctomapOcTreeNode::getChild(unsigned int) const’:
/home/myname/opencog/opencog/spatial/3DSpaceMap/OctomapOcTree.h:77:63: error: ‘getChild’ is not a member of ‘octomap::OcTreeNode’
                 return static_cast<const OctomapOcTreeNode*> (OcTreeNode::
                                                               ^
opencog/spatial/CMakeFiles/SpaceMap.dir/build.make:422: recipe for target 'opencog/spatial/CMakeFiles/SpaceMap.dir/3DSpaceMap/SpaceMapUtil.cc.o' failed
make[2]: *** [opencog/spatial/CMakeFiles/SpaceMap.dir/3DSpaceMap/SpaceMapUtil.cc.o] Error 1
CMakeFiles/Makefile2:3115: recipe for target 'opencog/spatial/CMakeFiles/SpaceMap.dir/all' failed
make[1]: *** [opencog/spatial/CMakeFiles/SpaceMap.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by linas** [comment]
where did octomap come from? what version do you have installed?  What does dpkg -l ros-indigo-octomap say? Perhaps you installed a different version?

**Comment by linas** [comment]
when you run cmake it should print something like this:
```
-- Find octomap lib /opt/ros/indigo/lib/liboctomap.so
-- Find octomath lib /opt/ros/indigo/lib/liboctomath.so
-- -- Found Octomap at /opt/ros/indigo/lib/liboctomap.so
```

does it say that, or something different?

**Comment by linas** [comment]
I just updated the cmake messages, so that they also print he include directory that is found. You can then check yourself, whether or not getChild is there.

**Comment by StrangeTcy** [comment]
Just pulled it, and now `cmake ..` outputs
```
-- Find octomap lib /usr/local/lib/liboctomap.so
-- Find octomath lib /usr/local/lib/liboctomath.so
```

As for my octomap, I cloned it from [their repo](https://github.com/octomap/octomap/releases) and followed their instructions.

**Comment by StrangeTcy** [comment]
Oh. I'm beginning to see my error. Sorry.

**Comment by StrangeTcy** [comment]
Okay, now that I've installed `ros-kinetic`, my  system has a file called `liboctomap.so` in both `/usr/local/lib/` and `/opt/ros/indigo/lib`.
A search aslo shows that I have files called `liboctomap.so.1.6`, `liboctomap.so1.8` and so on.
The latest cmake still shows only
```
-- Find octomap lib /usr/local/lib/liboctomap.so
-- Find octomath lib /usr/local/lib/liboctomath.so
-- Found octomap headers at /usr/local/include

```

**Comment by StrangeTcy** [comment]
`dpkg -l ros-indigo-octomap `
shows 
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                            Version              Architecture         Description
+++-===============================-====================-====================-====================================================================
ii  ros-indigo-octomap              1.6.9-0trusty-201603 amd64                The OctoMap library implements a 3D occupancy grid mapping approach,

```

My guess is I'm trying to `make` opencog using octomap 1.8, while it expects to be made with octomap 1.6. There were probably some code differences, which are affecting the making.

**Comment by linas** [comment]
You should probably use either one, or the other octomap.  It might be possible to have both installed, but that is just asking for confusion and trouble.  

Likewise, you should install either kinetic or indigo, but not both. 

Please note that some of te vision and audio code assumes indigo, and will not compile with kinetic.  (that code is not in this repository, so if you are not using robot HEAD, then it won't affect you)

**Comment by StrangeTcy** [comment]
Well, if I try `make` with the old `octomap` from `/usr/local/lib`, it still doesn't work.
Is there a way to explicitly command `make` to use files from `/ros/indigo/lib`?

**Comment by linas** [comment]
You would have to explicitly specify the include file search path. Its easier to just remove the wrong copy, isn't it?

**Comment by StrangeTcy** [comment]
Probably. Either way, I'll try removing it and then I'll either report success or a new portion of problems :-)

**Comment by StrangeTcy** [comment]
Some deletion was required, but it finally made most things okay.
