### ISSUE TITLE
Question about max allowed disjunct cost in LG

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2434]
This sentence happens to cause `nlp-parse` to crash:

```
About English... There is no egg in the eggplant. No ham in the hamburger. And neither pine nor apple in the pineapple. English muffins were not invented in England and French fries were not invented in France.
```

it was because no parse was found by the link parser, and when I tried it on link parser on the command line it suggested me to use `!cost-max` to lower the max allowed disjunct cost and try again.

In this case what would be the ideal value of it? and should I change it or do something else for this kind of situations?

**Comment by linas** [comment]
The short answer is to bust up that long paragraph into individual sentences, then you won't have the combinatoric explosion.

A bigger issue is that "No ham in the hamburger" is not a grammatically valid English sentence.  That is, the original author should have used commas, not periods -- however, they used periods for dramatic effect, and that breaks the naive assumptions about grammaticality.

The problem of combinatoric explosion is also an old, important problem, but there is no easy solution for it, and fiddling with cost-max is unlikely to fix anything.

**Comment by linas** [comment]
I just now fixed a bug in link-grammar, where
"There is no ham in the hamburger, and neither pine nor apple in the pineapple."
was not parsing correctly. It parsed, just that the answer you got back was incorrect.

**Comment by linas** [comment]
Closing.  There does not seem to be anything to do, here.
