### ISSUE TITLE
Octomap code does not compile.

### ISSUE THREAD

**Issue by linas** [opencog/opencog#2478]
Turns out, I never had installed octomap before. After installing it, opencog does not compile:
```
/opencog-git/opencog/timeoctomap/AtomOcTreeNode.h: In member function ‘octomap::AtomOcTreeNode* octomap::AtomOcTreeNode::getChild(unsigned int)’:
/opencog-git/opencog/timeoctomap/AtomOcTreeNode.h:60:46: error: ‘getChild’ is not a member of ‘octomap::OcTreeNode’
         return static_cast<AtomOcTreeNode*> (OcTreeNode::getChild(i));
                                              ^~~~~~~~~~
```

**Comment by linas** [comment]
Sigh. And after removing octomap, so that I could get a working system back, its still broken:
```
make clean
cmake ..
```
does not fix it. Cmake says
```
-- Find octomap lib /usr/lib/liboctomap.so
-- Find octomath lib /usr/lib/liboctomath.so
```
but compiling says:
```
/opencog-git/opencog/timeoctomap/AtomOcTreeNode.h:36:32: fatal error: octomap/OcTreeNode.h: No such file or directory
 #include <octomap/OcTreeNode.h>
compilation terminated.
```
so basically, the cmake check for octomap is broken, it is not verifying to see if the header files are installed.

**Comment by AmeBel** [comment]
Did you install `ros-indigo-octomap` package or something else?

**Comment by AmeBel** [comment]
For the apt repository that serve `ros-indigo-octomap`, see https://github.com/opencog/ocpkg/blob/master/ocpkg#L557-L560

**Comment by linas** [comment]
No, I installed liboctomap and liboctomap-dev -- there's no ROS code in here, is there?  We should limit ROS to ros-behavior-scripting; it should not worm its way into this subsystem

**Comment by AmeBel** [comment]
There is no ros-code we are using the octomap library from ros.

**Comment by AmeBel** [comment]
It is the same library but is not packaged for ubuntu:14.04 http://packages.ubuntu.com/search?keywords=liboctomap&searchon=names.

**Comment by linas** [comment]
Closing. I believe I fixed this so that it no longer requires ros-indigo-octomap. The ROS version was outdated, and there were cut-n-paste bugs in our octompa that pasted in the obsolete functions.

Or at least, I think I fixed this. I cannot find the pull req, at the moment.
