### ISSUE TITLE
cogserver executable fails linking with libatmocore.so

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2492]
with current pulls installed:
`cogutils/build$ git branch -v`         * master f387d1a Move spec file to proper location
`atomspace/build$ git branch -v`    * master e79c989 Merge pull request #1010 from ngeiswei/more-BC-fix
`opencog/build$ git branch -v`        * master ad8aa03 Merge pull request #2491 from linas/cix

i'm getting this fail during make:
````
Linking CXX executable cogserver
libserver.so: undefined reference to `opencog::hash_value(opencog::Handle const&)'
libserver.so: undefined reference to `opencog::content_eq(opencog::Handle const&, opencog::Handle const&)'
/usr/local/lib/opencog/libatomcore.so: undefined reference to `opencog::TypeCheckException::TypeCheckException()'
collect2: error: ld returned 1 exit status
make[2]: *** [opencog/cogserver/server/cogserver] Error 1
make[1]: *** [opencog/cogserver/server/CMakeFiles/cogserver.dir/all] Error 2
make: *** [all] Error 2
````
any suggestions?

**Comment by linas** [comment]
closing - I assume this problem fixed itself.
