### ISSUE TITLE
forward-chainer: C++ exception when running chatbot-psi

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2508]
Not sure how to reliably reproduce this yet, but it appeared after starting the chatbot-psi for a while (even if I was not actively chatting with it). This exception caused the pln-reasoner to crash
```
scheme@(guile-user)> In thread:
uncaught throw to C++-EXCEPTION: (cog-fc The variable (VariableNode "__EXECUTION_OUTPUT_VAR__") ; [6495469486552467932][NULL]
 does not appear (unquoted) in any clause! (/home/manhin/hansonrobotics/opencog/atomspace/opencog/atoms/pattern/PatternLink.cc:469)
Function args:
((SetLink
)
 (ConceptNode "rb3")
 (SetLink
)
))
```

**Comment by leungmanhin** [comment]
just an update, this is still happening from time to time, looks like all I need is to load the `chatbot-psi/main.scm` in a guile shell and this error will show up after a while even if there is no interactions... suspecting it may be somehow related to the pln-reasoner loop

**Comment by leungmanhin** [comment]
now the error message becomes:
```
scheme@(guile-user)> In thread:
ERROR: In procedure cog-fc: Error while printing exception.
```
:)

**Comment by linas** [comment]
The messsage "Error while printing exception." is now fixed; the exception message should now be more useful in locating the error.

**Comment by leungmanhin** [comment]
Updated the exception message, I'll look into this issue

**Comment by linas** [comment]
you should talk to Nil about the forward chainer. He mumbled something about re-working it when he is done with the backward-chainer.

**Comment by ngeiswei** [comment]
Oh, I had not noticed that one, is it giving you trouble? Is it urgent to fix?

**Comment by leungmanhin** [comment]
This issue is not urgent

**Comment by linas** [comment]
Closing, I'm assuming that this one "fixed itself"
