### ISSUE TITLE
PLNRulesUTest is failing

### ISSUE THREAD

**Issue by linas** [opencog/opencog#2546]
It was working just yesterday:
```
ERROR: In procedure apply-smob/1:
ERROR: Unbound variable: deduction-inheritance-rule
ABORT: unbound-variable

```

**Comment by ngeiswei** [comment]
If it's not urgent I'll look into it next year.

**Comment by linas** [comment]
not urgent. It might be something specific to my system.

**Comment by pennachin** [comment]
Just tested, it's working on my machine.

**Comment by linas** [comment]
I dunno, I still get this error.

**Comment by linas** [comment]
It seems to be passing these days. Closing.

**Comment by linas** [comment]
well, actually it was failing just this morning, and now its passing this evening.  Not sure why it should be so unpredicatable.

**Comment by ngeiswei** [comment]
Failing for me too, I'm looking at it.

**Comment by ngeiswei** [comment]
@linas I'm having `Unbound variable: cog-tv-merge-hi-conf`, maybe it relates to your recent changes?

**Comment by ngeiswei** [comment]
Actually I just had to re-install the atomspace. It passes now.
