### ISSUE TITLE
TBB not found

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#2561]
What are the details of `cmake` looking for Intel's Threading Building Blocks? 
The output said that it couldn't find any on my system, so I followed the advice provided and downloaded the source code from [here]( https://www.threadingbuildingblocks.org/download) and compiled it (the exact line I used was `sudo make all`).
`cmake` couldn't find it, but I noticed that it 
```
-- Looked for Threading Building Blocks in /opt/intel/tbb;/usr/local/include;/usr/include
-- Intel TBB (Threaded Building Blocks) was not found;
```
So I got back to the tbb source root directory and tried `sudo make all tbb_build_dir=/opt/intel/tbb`. `cmake` still couldn't find tbb. I tried `sudo make all tbb_build_dir=/usr/local/include`. Didn't help.
I tried setting some variables as suggested by [this guy](https://stackoverflow.com/questions/10726537/how-to-install-tbb-from-source-on-linux-and-make-it-work). It didn't help.
On top of that, I've `sudo apt-get install libtbb*`ed, which also didn't help.
It seems that I now have at least 3 places where tbb resides on my system, and `cmake` still can't find it.

Have I missed something obvious? What should I do?

**Comment by ngeiswei** [comment]
I don't know about TBB support in opencog, however you shouldn't usually compile something with sudo, only install. Typically you'd do
```bash
make all
sudo make install
```

**Comment by StrangeTcy** [comment]
Yes, that's true and that's what the instructions said. Still, I don't think `sudo`ing `make all` affected anything.

**Comment by linas** [comment]
TBB is only used/needed required by some module called "AtomSpace Publisher" but no one uses that module, as far as I know. Thus, you can ignore it.

But if you want to debug, the search is done here: https://github.com/opencog/opencog/blob/master/lib/FindTBB.cmake

**Comment by StrangeTcy** [comment]
Oh. When it's not found, the configuration output is `REST AtomSpace publisher will not be built`, and I thought that a thing called a REST publisher is a must-have.
Thanks for the explanation!
