### ISSUE TITLE
Segfault caused while running the pattern miner test 

### ISSUE THREAD

**Issue by ruiting** [opencog/opencog#2584]
The pattern miner test is from:  http://wiki.opencog.org/w/Pattern_miner, i.e.

opencog> loadmodule opencog/learning/PatternMiner/libTestPatternMinerAgent.so

============================
Debug: PatternMining start! Max gram = 4, mode = Depth_First
Start thread 0 from 0 to 4294967295
100% completed in Thread 0.
Finished mining 1~4 gram patterns.

processedLinkNum = 0
Debug: PatternMiner:  done frequent pattern mining for 1 to 4gram patterns!
gram = 1: 0 patterns found! 
Debug: PatternMiner: writing  (gram = 1) frequent patterns to file FrequentPatterns_1gram.scm

gram = 2: 0 patterns found! 
Debug: PatternMiner: writing  (gram = 2) frequent patterns to file FrequentPatterns_2gram.scm

gram = 3: 0 patterns found! 
Debug: PatternMiner: writing  (gram = 3) frequent patterns to file FrequentPatterns_3gram.scm

gram = 4: 0 patterns found! 
Debug: PatternMiner: writing  (gram = 4) frequent patterns to file FrequentPatterns_4gram.scm

Calculating interestingness for 2 gram patterns by evaluating surprisingness
100% completed.Debug: PatternMiner:  done (gram = 2) interestingness evaluation!0 patterns found! Outputting to file ... 
Debug: PatternMiner: writing (gram = 2) interesting patterns to file SurprisingnessI_2gram.scm

Debug: PatternMiner: writing (gram = 2) interesting patterns to file SurprisingnessII_2gram.scm

Debug: PatternMiner: writing  (gram = 2) pattern statics to csv file PatternStatics_2gram.csv
[2017-01-11 08:54:56:460] [ERROR] Caught signal 11 (Segmentation fault) on thread 139790070507584
	Stack Trace:
	2: ./opencog/cogserver/server/cogserver (opencog::Logger::Base::~Base() +0x5e) [0x407fbe]
	3: ./opencog/cogserver/server/cogserver (sighand(int) +0x266) [0x4074b6]
	4: /lib/x86_64-linux-gnu/libc.so.6 (sighand(int) +0x36d40) [0x7f23684a0d40]
	5: /home/ruiting/hansonrobotics/opencog/opencog/build/opencog/learning/PatternMiner/libPatternMiner.so (opencog::PatternMining::PatternMiner::runPatternMiner(unsigned int) +0xa73) [0x7f235a75cc33]
	6: opencog/learning/PatternMiner/libTestPatternMinerAgent.so (opencog::TestPatternMinerAgent::run() +0x25) [0x7f235a9d5715]
	7: /home/ruiting/hansonrobotics/opencog/opencog/build/opencog/cogserver/server/libserver.so (opencog::AgentRunnerBase::run_agent(std::shared_ptr<opencog::Agent>) +0x91) [0x7f23693e4701]
	8: /home/ruiting/hansonrobotics/opencog/opencog/build/opencog/cogserver/server/libserver.so (opencog::SimpleRunner::process_agents() +0xae) [0x7f23693e493e]
	9: /home/ruiting/hansonrobotics/opencog/opencog/build/opencog/cogserver/server/libserver.so (opencog::CogServer::runLoopStep() +0x137) [0x7f23693e7cf7]
	10: /home/ruiting/hansonrobotics/opencog/opencog/build/opencog/cogserver/server/libserver.so (opencog::CogServer::serverLoop() +0xfd) [0x7f23693e7b5d]
	11: ./opencog/cogserver/server/cogserver (���h# +0x7f0) [0x406b30]
	12: /lib/x86_64-linux-gnu/libc.so.6 (���h# +0xf5) [0x7f236848bec5]
	13: ./opencog/cogserver/server/cogserver() [0x40718c]

**Comment by linas** [comment]
This looks wrong: 
```
Start thread 0 from 0 to 4294967295
```
are you really trying to start 4 billion threads?  Because this error message is garbage:
```
Caught signal 11 (Segmentation fault) on thread 139790070507584
```
thread numbers rarely go above about 1000.

**Comment by bgoertzel** [comment]
Huh ... thing is, this pattern miner demo example used to work fine, and the pattern miner code has not been changed.   So maybe this new crash is due to some change in the cogserver.  (Either a new cogserver bug; or a cogserver change exposing some design infelicity in the pattern miner... I dunno...)

**Comment by bgoertzel** [comment]
When the pattern miner was run before the output looked more like

Listening on port 17001
Debug: PatternMining start! Max gram = 4, mode = Depth_First
Start thread 0 from 0 to 119
51.6667% completed in Thread 0.

(see https://github.com/opencog/opencog/issues/2477)

... so whatever is making it create billions of threads is a new problem, probably (at least partly ) rooted elsewhere than in the pattern miner code

**Comment by bgoertzel** [comment]
I started poking in the code to see where 4294967295 is obtained from, and it doesn't look that hard , it;s variable end_index in https://github.com/opencog/opencog/blob/master/opencog/learning/PatternMiner/PatternMinerDF.cc ... but then I realized I have a lot of other crap to do so I'd better leave this to someone else even though debugging the pattern miner would be more fun than writing a bunch of proposals and summaries which is what's on my plate tonight ;p

**Comment by bgoertzel** [comment]
Actually it seems that what

Start thread 0 from 0 to 4294967295

means is that thread 0 is dealing with links 0 thru 4294967295

so it's not 4294967295 threads, just 4294967295 links

which is still too many though, there are not that many links in the test atomspace

**Comment by yantrabuddhi** [comment]
Seems like an int overflow error to me.
2^32-1 = 4294967295

Regards,
Mandeep

**Comment by ngeiswei** [comment]
The problem is that `end_index` is null and so, as @yantrabuddhi noticed, `end_index - 1` is printed as 2^32-1. So at that point nothing occurs, and then at line https://github.com/opencog/opencog/blob/master/opencog/learning/PatternMiner/PatternMiner.cc#L2438 it crash because this vector is either empty (or filled with unallocated pointers).

I guess the priority is to find out why `end_index` is null rather making line 2438 more robust. Looking into that...

**Comment by ngeiswei** [comment]
The kb was loaded. I've updated http://wiki.opencog.org/w/Pattern_miner#Steps_to_run_a_non-distributed_pattern_miner_test accordingly.

I've also wrapped it in a unit test `tests/learning/PatternMiner/PatternMinerUTest.cxxtest` (note that it doesn't test whether the result is correct, just that it doesn't crash).

**Comment by ngeiswei** [comment]
Feel free to close if you consider the issue is resolved, otherwise let me know.

**Comment by ruiting** [comment]
it works for me now, thanks

Ruiting Lian
