### ISSUE TITLE
Cannot enter the Python shell after exiting the Scheme shell

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2595]
To reproduce, start the cogserver:
```
opencog/build/opencog/cogserver/server/cogserver
```

telnet to the cogserver `rlwrap telnet localhost 17001`, and do:
```
opencog> scm
guile> .
opencog> py
```

It hangs here -- actually the same happens when re-entering the scm shell as well

**Comment by linas** [comment]
seems to work, now, right?

**Comment by leungmanhin** [comment]
Fixed by https://github.com/opencog/atomspace/pull/1085
