### ISSUE TITLE
REST API - Unable to start it

### ISSUE THREAD

**Issue by Matrioshka** [opencog/opencog#2597]
I have exported the paths (as depicted in the WIKI page): http://wiki.opencog.org/w/The_REST_API

Here is the command I used to run the python file: python ./opencog/opencog/examples/restapi/start_restapi.py

Output: Error msg:
```
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "./opencog/opencog/examples/restapi/start_restapi.py", line 1, in <module>
    from web.api.apimain import RESTAPI
  File "/home/adam/opencog/opencog/opencog/python/web/api/apimain.py", line 6, in <module>
    from apiatomcollection import *
  File "/home/adam/opencog/opencog/opencog/python/web/api/apiatomcollection.py", line 5, in <module>
    import opencog.cogserver
  File "atomspace.pxd", line 148, in init opencog.cogserver (/home/hr/hansonrobotics/opencog/opencog/build/opencog/cython/opencog/cogserver.cpp:1831)
ImportError: /usr/local/share/opencog/python/opencog/atomspace.so: undefined symbol: _ZN7opencog4Atom13getTruthValueEv

```

**Comment by mjsduncan** [comment]
have you tried starting it through the python shell in the cogserver?  see [this page.](http://wiki.opencog.org/w/REST_API#Configuration)

**Comment by linas** [comment]
I believe that you have an out-of-date atomspace installed  there should not be any directory called `/usr/local/share/opencog/python/opencog` or any files in it. If there is, the remove it by hand.  That should fix it.  That file is now installed in `/usr/local/lib/python2.7/dist-packages/opencog/`  which is the official place for python extensions to get installed into.

If that doesn't fix it, then you need to monkey with your python config. Unfortunately, python is .. well, its flakey, and its hard to get it to work right. There's a huge amount of variability between different peoples installs, and it won't work unless configured just-so.

A fresh git pull, make, install won't hurt.

**Comment by inflector** [comment]
@Matrioshka Did you ever get the REST API to work?

**Comment by Matrioshka** [comment]
Hi, I don't have much background as to its implementation at OpenCog - so
not sure why it's not working atm, the most I did was clean up and
contribute to the 'hands on' tutorial on using the REST API:
http://wiki.opencog.org/w/Using_the_REST_API

There is more documentation on it here: http://wiki.opencog.org/w/REST_API

Kind regards,

Adam A. Ford
HK Mob +852 95893014 <+852%209589%203014>
AU Mob +61 421 979977 <0421%20979%20977>
Chair - Science, Technology & the Future <http://scifuture.org>,
Director - Future
Day <http://future-day.org>

* Science, Technology & the Future <http://scifuture.org>* (Meetup
<http://www.meetup.com/Science-Technology-and-the-Future> / Facebook
<https://www.facebook.com/groups/ScienceTechnologyFuture> / YouTube
<http://youtube.com/subscription_center?add_user=TheRationalFuture>)

*Future Day <http://future-day.org> - "Join the conversation on Future Day
March 1st to explore the possibilities about how the future is transforming
us. You can celebrate Future Day however you like, the ball is in your
court!"*

SciFuture <http://scifuture.org> | H+ Australia
<http://hplusconf.com.au> | Singularity
Summit Australia <http://singularitysummit.com.au> | Twitter
<http://twitter.com/adam_ford> | YouTube
<http://youtube.com/TheRationalFuture> | Future Day <http://Future-Day.org>

"A new type of thinking is essential if mankind is to survive and move
toward higher levels." ("Atomic Education Urged by Albert Einstein", New
York Times, 25 May 1946)

Please consider the environment before printing this email
<http://hplusconf.com.au/wp-content/uploads/2012/03/H+logo_mauve_embossed_dropshadow_trans.png>

**Comment by linas** [comment]
closing, this bug is stale.
