### ISSUE TITLE
Only executes the first line of the scm code when doing 'cat'?

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2602]
For example if we have these in a file called `test`:
```scheme
scm
(ConceptNode "A")
(ConceptNode "B")
(ConceptNode "C")
```

and when we do:
```
cat test | telnet localhost 17001
```

to a cogserver, only `(ConceptNode "A")` gets into the atomspace

**Comment by linas** [comment]
wow. that's insane. ... and I can reproduce it. very disheartening.

**Comment by linas** [comment]
pull req #2603 should fix this.  I'm running this script to test:
```
#! /bin/bash

for i in `seq 1 100`;
do
    echo duude start iter $i | tee -a shellutest.log
    date | tee -a shellutest.log
    time ./tests/server/ShellUTest |tee -a shellutest.log
done    

echo duude finieshed >> shellutest.log
```

so far its done 22 iterations without error.

**Comment by linas** [comment]
Above shell-script has completed 100 iterations without error

**Comment by leungmanhin** [comment]
thanks!
