### ISSUE TITLE
parse-lojban raises opencog::InvalidParamException

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#2652]
Caused on 
opencog-sha =  c7cb4b37c37190f04d2a16f72b0c5665ad786c02
atomspac-sha = 408e2d4e3f202c5c52b1b6c3165cf8e50185af5a

![parse-lojban-crash](https://cloud.githubusercontent.com/assets/2135577/24347934/93b36546-130c-11e7-953f-92d319428be9.png)

**Comment by AmeBel** [comment]
The above is caused following https://github.com/opencog/opencog/blob/master/opencog/nlp/lojban/README.md

**Comment by rTreutlein** [comment]
The issue is the change to TruthValues which are now represented using ProtoAtoms. This broke the HaskellBinding. I am already working on this.
