### ISSUE TITLE
PatternMiner setup problem

### ISSUE THREAD

**Issue by yantrabuddhi** [opencog/opencog#2676]
hi @shujingke ,
 I am building opencog embedded, and during this I found that you have linked libssl and libcrypto with patternminer. Are these required in future? I ask this because cmake does not check for these dependencies and causes compile time error if these are not present. However removing these from cmake does not cause any problem (so then its not being used right now).
Please let me know.

**Comment by shujingke** [comment]
Hi, @yantrabuddhi @ngeiswei 
I don't know why they are there. I checked the history of this cmakelist file, it seems Nil added them.
https://github.com/opencog/opencog/commit/313103a1fc0c029443840f435f01876d812a8ac3

**Comment by ngeiswei** [comment]
It compiles and the tests pass without so I removed them. I have no idea why I added these dependencies back then, I assume I inadvertently pasted them from somewhere else, sorry about that.
