### ISSUE TITLE
no code for module (opencog nlp chatbot)

### ISSUE THREAD

**Issue by vishnuu** [opencog/opencog#2693]
Hello All,
My .guile has
(use-modules (ice-9 readline)) (activate-readline)
(add-to-load-path "/usr/local/share/opencog/scm")
(add-to-load-path ".")
(use-modules (opencog))
(use-modules (opencog nlp))
(use-modules (opencog nlp chatbot))
(use-modules (opencog nlp relex2logic))
(use-modules (opencog rule-engine))
(use-modules (opencog query))
(use-modules (opencog exec))

When i import modules in guile, i get this Error  "no code for module (opencog nlp chatbot)".

![no_codefor_mopdule](https://cloud.githubusercontent.com/assets/5689982/25121192/2778c8c8-2421-11e7-8136-94517aefa368.png)
When i also start,  guile -l ../opencog/nlp/chatbot/run-chatbot.scm under opencog build directory, i get the same error.

Thanks,
Vishnu

**Comment by linas** [comment]
did you `sudo make install` first?

**Comment by vishnuu** [comment]
yeah. I did Linas.
