### ISSUE TITLE
atomspace example

### ISSUE THREAD

**Issue by bringoo** [opencog/opencog#2697]
hi,
I build opencog and now trying to do examples but atomspace example link is not working.
https://github.com/opencog/atomspace/example

**Comment by ngeiswei** [comment]
Hi,

I don't were you got that link but the following works

https://github.com/opencog/atomspace/tree/master/examples

if it's from the wiki, please fix it (I don't know if you can have the 
permission though), or at the very least tell us where you got it so we 
can fix it.

Thanks,
Nil

**Comment by bringoo** [comment]
thanks,
I didn't remember from where I got this link. and neither I am permitted to
make a change in wiki.

**Comment by linas** [comment]
wiki permsissions are grantable to humans -- we have a problem with robots. Ask on the mailing list, I think Amen manages these.
