### ISSUE TITLE
Security: Possible Race Condition in gtk-visualizer/AtomTypes.cpp

### ISSUE THREAD

**Issue by Shinkurt** [opencog/opencog#2698]
In opencog/opencog/visualization/gtk-visualizer/AtomTypes.cpp:31

`ssize_t i = readlink("/proc/self/exe", buffer, 500);`

readlink is used badly: This accepts filename arguments; if an attacker can move those files or change the link content, a race condition results. Also, it does not terminate with ASCII NUL. I think reconsidering approch here would be nice. :) 

Thanks,

**Comment by linas** [comment]
Not a bug. Attacker cannot move that file.
