### ISSUE TITLE
Security: Possible format string vulnerability in IRC.cc

### ISSUE THREAD

**Issue by Shinkurt** [opencog/opencog#2700]
opencog/opencog/nlp/irc/IRC.cc:808 accepts arguments from user and adds them to vfprintf, causing Information Disclosure at minimum (helpful with #2699 to leak memory address) -- and a format string vulnerability with other potential issues.

`808: vfprintf(dataout, va_arg(argp, char*), argp);`

Suggestion: Use a constant for the format specification.

Thanks,

**Comment by linas** [comment]
Huh? There is no information to disclose. This is IRC, there is exactly zero security involved in any of this.  Why did you open this bug?

**Comment by Shinkurt** [comment]
information diclosure about the system, not the bot. by sending %n , %d... 

refer to this youtube video explaining what I mean: https://www.youtube.com/watch?v=0WvrSfcdq1I  (shows almost exact scenario)
