### ISSUE TITLE
obsolete: usleep maybe tamped with

### ISSUE THREAD

**Issue by Shinkurt** [opencog/opencog#2705]
opencog/opencog/cogserver/server/SleepRequest.cc, 

`211: usleep((unsigned int) delta);`

C routine this as an obsolete (as opposed to the shell command by the same name). The interaction of this function with SIGALRM and other timer functions such as sleep(), alarm(), setitimer(), and nanosleep() is unspecified, low priority but with time possibly can make the system go to a denial of service offline timing. using setitimer() or nanosleep() would be so much better

**Comment by linas** [comment]
It's not obsolete. What makes you think this?

**Comment by linas** [comment]
Anyway, SleepRequest is broken.  I'm removing that code now.

**Comment by linas** [comment]
Removed this code in pull req #2708
