### ISSUE TITLE
related project, WIP developer tools collection that may be of use to opencog

### ISSUE THREAD

**Issue by stephenbhope** [opencog/opencog#2710]
I am working on stephenbhope/Revised-CommAI-env and as part of the process assembling a unified end user & developer tool box highlighting outstanding examples of opensource apps. Are there any wish list items from contributors here for either finding the right tool or to automate a tedious bit? I want to make the tool box a stop when developers are looking for something different to their current tools, or empty spots in their set.

I'd be happy to assist with setting up the webhooks to link this repo to any of github's testing, linting apps if it's wanted.

**Comment by linas** [comment]
Heh. I desperately need a tool to manage a large collection of text files and database dumps -- approx 100GB of data, maybe a million text files, and dozens of large database dumps,   Its a real nightmare to keep juggling these through a data processing pipeline.

Anyway, closing, as this has nothing to do with opencog.
