### ISSUE TITLE
Build error: no matching function for call to define_scheme_primitive

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/opencog#2716]
Hi @linas, it looks like something committed to the atomspace on 5/6/17 https://github.com/opencog/atomspace/commits/master may be causing a build error in opencog:
```
[ 98%] [ 98%] [100%] Building CXX object opencog/cython/opencog/CMakeFiles/spacetime_cython.dir/spacetime.cpp.o
Building CXX object opencog/timeoctomap/pointmemory/CMakeFiles/point_memory.dir/PointMemorySCM.cc.o
Building CXX object opencog/cython/opencog/CMakeFiles/spatial_cython.dir/spatial.cpp.o
/home/eddie/hansonrobotics/opencog/opencog/opencog/timeoctomap/pointmemory/PointMemorySCM.cc: In member function ‘void opencog::PointMemorySCM::init()’:
/home/eddie/hansonrobotics/opencog/opencog/opencog/timeoctomap/pointmemory/PointMemorySCM.cc:194:83: error: no matching function for call to ‘define_scheme_primitive(const char [8], opencog::Handle (opencog::PointMemorySCM::*)(opencog::Handle, opencog::Handle, opencog::Handle), opencog::PointMemorySCM* const, const char [13])’
  define_scheme_primitive("map-ato", &PointMemorySCM::map_ato, this, "ato pointmem");// b_shddd
<snip> ---------
make[2]: *** [opencog/timeoctomap/pointmemory/CMakeFiles/point_memory.dir/PointMemorySCM.cc.o] Error 1
make[1]: *** [opencog/timeoctomap/pointmemory/CMakeFiles/point_memory.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/eddie/hansonrobotics/opencog/opencog/build/opencog/cython/opencog/spatial.cpp:4681:18: warning: ‘PyObject* __pyx_convert_string_to_py_(const string&)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_convert_string_to_py_(const std::string &__pyx_v_s) {
                  ^
Linking CXX shared library spatial.so
Linking CXX shared library spacetime.so
[100%] Built target spatial_cython
[100%] Built target spacetime_cython
make: *** [all] Error 2
```
Rolling back the May 6 atomspace commits makes the opencog build error go away.

**Comment by yantrabuddhi** [comment]
i am getting the same error during build

**Comment by AmeBel** [comment]
It seems some of the api signatures used by `ato pointmem` module were removed in https://github.com/opencog/atomspace/pull/1199 but it seems https://github.com/opencog/atomspace/pull/1222 causes the failure. I didn't investigate why this failure wasn't triggered earlier though.

git-shas of repos that are causing failure.
```
cogutils : 43d7f2e Merge pull request #76 from ngeiswei/measure-runtime-script                            
atomspace : a2f4eb7 Merge pull request #1222 from linas/cu                                                 
opencog : e942f2c Merge pull request #2717 from rTreutlein/UpstreamMaster                                
```

**Comment by AmeBel** [comment]
quick fix for getting to build opencog, do the following in the atomspace clone
```bash
git pull upstream master
git reset --hard fee966bd1be1a7ed01871782ec3472ea06b871f6
cd build
cmake ..
make -j$(nproc)
sudo make install
```

**Comment by linas** [comment]
Sorry,  I was trying to clean-up the dumping ground of bad scheme bindings, and accidentally removed the ones that the spacetime map needed.  I've not been checking the spacetime bindings because they are too old, and no longer build on my machine.   I'll try to see if I can port them into the modern world.

**Comment by linas** [comment]
This is frustrating. The code is a turdball,  written by people who aren't software engineers.  There are no version numbers anywhere to be found in any of the header files, so its impossible to know which version you have.  The different versions are not API compatible.  The obsolete versions had a getChild() method, the new one does not, and gives no hint about how to make up for this.

**Comment by linas** [comment]
Regarding pull #1199 -- from what I can tell, the reason those API's were removed is because the time-map scheme API was un-needed and thus removed. No existing code needs this API.  The correct fix is to not build the pointmen subdirectory at all, I think.

**Comment by linas** [comment]
I am guessing that #2721 should fix things...

**Comment by linas** [comment]
Hmm Looks like more fixes are needed. Working on them now.

**Comment by linas** [comment]
One needed fix is opencog/atomspace/pull/1224

**Comment by linas** [comment]
and finally, pull req #2722 is needed.

**Comment by bgoertzel** [comment]
Mandeep,  is this timemap scheme API Linas is referring to your work, or
something older?



On May 10, 2017 02:39, "Linas Vepštas" <notifications@github.com> wrote:

Regarding pull #1199 <https://github.com/opencog/opencog/issues/1199> --
from what I can tell, the reason those API's were removed is because the
time-map scheme API was un-needed and thus removed. No existing code needs
this API. The correct fix is to not build the pointmen subdirectory at all,
I think.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opencog/opencog/issues/2716#issuecomment-300262606>,
or mute
the thread

**Comment by linas** [comment]
My comment below was completely wrong.  I was mislead by the comments and
structure of that code, which suggested that it was dead code; its not, its
very much alive and in use (and the misleading comments now removed)

--linas

**Comment by linas** [comment]
fixed
