### ISSUE TITLE
Language Learning Instructions Incomplete - Guile 2.2 Link Problems

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#2741]
I had a rather time-consuming issue with the CogServer while trying to get the language learning pipeline working. It came from the wrong version of guile being linked when I had both the 2.0 and 2.2 libraries present.

Both of the outer layer CMakeLists.txt for OpenCog and AtomSpace repositories do not require Guile 2.2. They require only version 2.0:

https://github.com/opencog/opencog/blob/master/CMakeLists.txt#L249
https://github.com/opencog/atomspace/blob/master/CMakeLists.txt#L237

If I follow the instructions for installing the tools required for language learning found here:

https://github.com/opencog/opencog/blob/master/opencog/nlp/learn/README#L164

this results in the wrong library being linked to the CogServer.
 
If I run guile from the command line after installing the 2.2 from the git repository, I get:

```
prompt> guile -v
guile (GNU Guile) 2.2.2
Copyright (C) 2017 Free Software Foundation, Inc.

License LGPLv3+: GNU LGPL 3 or later <http://gnu.org/licenses/lgpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

So, I was getting the new interpreter, but this is not the version of Guile that loaded / linked dynamically into the CogServer. There are two problems that come up that appear to be indicative of a bad library link to the old version of guile. After fixing this issue, these problems went away.

First, and most important, I got the hanging bug referenced in the language learning install instructions when running step 10:
`
guile> (observe-text "this is a test")`

Second, I got a weird unbound variable problem when trying to run the Scheme interpreter via the CogServer if I startup the CogServer outside of the scheme shell. This appeared to be caused by use of a built-in that is not present in the 2.0 version of scheme.

To verify the library problem, I dumped the linked objects for CogServer which shows:

```
prompt> ldd ./opencog/cogserver/server/cogserver
 
 libguile-2.0.so.22 => /usr/lib/libguile-2.0.so.22
```

So the link was picking up my original Guile 2.0 library which came from the default dependencies installed using apt-get as part of the normal OpenCog install.

Make install of 2.2.2 from git places the library in:

`/usr/local/lib`

CMake is picking up the wrong library by default. The reason appears to be because FindGuile.cmake finds the 2.0 version and then stops searching. The relevant code is here:

https://github.com/opencog/opencog/blob/master/lib/FindGuile.cmake#L34-L38

```
 FIND_LIBRARY(GUILE_LIBRARY NAMES guile-2.2 guile-2.0 guile PATHS
    /usr/lib
     /usr/local/lib
     /opt/local/lib
 )

```

CMake appears to be traversing the directories and looking for any of the names, rather than traversing the names and looking in the directories.

Now, since the` CMakeLists.txt` for both OpenCog and AtomSpace require only 2.0 for Guile, the /usr/lib directory finds a valid 2.0 library in `/usr/lib` and the search ends there. This means that even though I have a 2.2, it won't link unless I require 2.2 in `CMakeLists.txt` as well.

Since there is no obvious solution that doesn't involve at least some tradeoff, I decided to file an issue here. Some solutions are:

1) Require Guile 2.2 - this has the major disadvantage of making OpenCog installs more difficult since once can't just get Guile 2.2 from a debian package via apt-get.

2) Update the instructions - which leaves open the question of what we want to do to resolve this? Do we suggest removing old Guile versions before installing 2.2? Might that cause some other problems? How backward compatible is 2.2 with 2.0 code? What if you have some code that requires 2.0 or 1.8?

3) Change `FindGuile.cmake` to force a search for 2.2 in all the directories, then a search for 2.0, then 1.8 etc. bypassing the current CMake dependent ordering which does the wrong thing.

**Comment by linas** [comment]
Sounds like one big user error. You failed to remove guile-2.0-dev when you installed guile-2.2-dev.  It is always illegal to install more than one development environment.  Its always illegal to not make-clean and cmake, from scratch, when changing devleopment environments. There's nothing that can be done to help that.

Opencog will compile and run with guile-1.8 guile-2.0 or guile-2.2.  Ordinary users should not be forced into contortions.  This is a devel problem only.
