### ISSUE TITLE
build fail DimEmbedModule through SchemePrimitive.h

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2772]
[ 96%] Building CXX object opencog/learning/dimensionalembedding/CMakeFiles/dimensionalembedding.dir/DimEmbedModule.cc.o
/home/biocog/hansonrobotics/opencog/opencog/opencog/learning/dimensionalembedding/DimEmbedModule.cc: In member function ‘virtual void opencog::DimEmbedModule::init()’:
/home/biocog/hansonrobotics/opencog/opencog/opencog/learning/dimensionalembedding/DimEmbedModule.cc:95:33: error: no matching function for call to ‘define_scheme_primitive(const char [11], <unresolved overloaded function type>, opencog::DimEmbedModule* const)’
                             this);
                                 ^
/home/biocog/hansonrobotics/opencog/opencog/opencog/learning/dimensionalembedding/DimEmbedModule.cc:95:33: note: candidate is:
In file included from /home/biocog/hansonrobotics/opencog/opencog/opencog/learning/dimensionalembedding/DimEmbedModule.cc:36:0:
/usr/local/include/opencog/guile/SchemePrimitive.h:662:13: note: template<class T, class M> void opencog::define_scheme_primitive(const char*, M, T*, const char*)
 inline void define_scheme_primitive(const char *name, M method, T *data, const char* module = "extension")
             ^
/usr/local/include/opencog/guile/SchemePrimitive.h:662:13: note:   template argument deduction/substitution failed:
/home/biocog/hansonrobotics/opencog/opencog/opencog/learning/dimensionalembedding/DimEmbedModule.cc:95:33: note:   couldn't deduce template parameter ‘M’
                             this);
                                 ^
make[3]: *** [opencog/learning/dimensionalembedding/CMakeFiles/dimensionalembedding.dir/DimEmbedModule.cc.o] Error 1
make[2]: *** [opencog/learning/dimensionalembedding/CMakeFiles/dimensionalembedding.dir/all] Error 2
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2

**Comment by eddiemonroe** [comment]
I think this is a consequence of this change in the atomspace https://github.com/opencog/atomspace/pull/1273

temporary workaround, in atomspace: 
atomspace/build$ git reset --hard 111c9885c8c  (and then sudo make install)

A commit in one repo causing a build fail in another is a recurring problem and can be tricky to track down. I think it would be a really good idea to also include build tests for all repos that depend on the repo with the pull request, which would catch problems like this and save lots of time.

**Comment by ngeiswei** [comment]
I'm confident it's fixed, but please test and close if if so.

**Comment by eddiemonroe** [comment]
Confirmed the fix and closing.
