### ISSUE TITLE
Is the build still failing?

### ISSUE THREAD

**Issue by morrissowards** [opencog/opencog#2778]
A few weeks ago we tried to build the open cog repository with no luck. I am wondering if the build is still failing, or if the page has just not been updated? Thank you.

**Comment by linas** [comment]
?? Should never happen. I build opencog daily, it works great. It is sometimes the case that you need updates to both the atomspace and to opencog repos (and maybe to cogutils repo) and if you don't pull the latest on all three, you will get build errors.

All of the unit tests on cogutils should pass. All the unit tests on the atomspace should pass, except maybe BackwardChainerUTest.  Many of the unit tests on the opencog repo will fail.  Unfortunately, this is "normal" at this time; there are some rapid changes, and no one has circled back to fix some of the old/obsolete function.
