### ISSUE TITLE
Don't redefine PatternLink!

### ISSUE THREAD

**Issue by linas** [opencog/opencog#2800]
Bug here:

https://github.com/opencog/opencog/blob/master/opencog/learning/PatternMiner/types/atom_types.script#L4

PatternLink already exists in the base, its a kind-of ScopeLink.  Two fixes are needed:

* PatternMiner should not define it.
* class server should throw an error if its already defined.

**Comment by linas** [comment]
Adding check for such accidental redefines in pull req opencog/atomspace#1290

**Comment by shujingke** [comment]
Fixed. Changed into MinedPatternLink.

**Comment by linas** [comment]
Thanks!
