### ISSUE TITLE
build fail:  PatternMiner.cc and PatternMinerDF.cc include "embodiment/atom_types.h"

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2818]
i replaced the embodiment path with "bioscience/types/atom_types.h" since i want to use GeneNodes and ProteinNodes and it builds successfully, but i haven't tested if these nodes are mine-able.  the PatternMinerUTest still fails but it was failing for me before.
is embodiment going to be included in github/opencog/opencog ?
maybe discrepancies between github/hansenrobotics/opencog and github/opencog/opencog are why other tests are failing for some people and not others?

**Comment by linas** [comment]
try git pull and rebuilding. The `embodiment/atom_types.h` was removed a week or two ago.

**Comment by linas** [comment]
PatternMinerUTest is still failing. Nil and Shujing are working to fix it, but its not yet fixed.

github/hansonrobotics/opencog is NOT the official repository. You should NOT be using it, unless you are doing robot work.

**Comment by linas** [comment]
actually, I think PatternMineurTest might pass, it seems to pass, but then crashes at the end, probably due to a cogserver module issue.

**Comment by mjsduncan** [comment]
linus, the line including embodiment/atom_types.h is still in PatternMiner.cc and PatternMinerDF.cc.  you're not checking this on a clean opencog/opencog code base.

**Comment by mjsduncan** [comment]
also, the bioscience atom types won't be included in the patternminer binary as is.

**Comment by linas** [comment]
Oh. I see. Eww.  I will remove those includes in a jiffy.  

The bioscience types do not need to be explicitly included in the pattern miner code, because the C++ code never actually would need access to those types.  The pattern miner only uses maybe half-a-dozen types, that's all. 

The pattern miner can still mine for the bioscience types. It can still manipulate them, it can still print them out.  But as long as it never explictly says `if(atom->getType() == GENE_NODE)` then it does not need to ever include the header file.

**Comment by mjsduncan** [comment]
thanks!

**Comment by linas** [comment]
OK, I just pushed a fix for embodiment types, but several other bugs persist.

**Comment by linas** [comment]
OK seems to build, now.

**Comment by mjsduncan** [comment]
so if i do include `bioscience/types/atom_types.h` in the appropriate files will `if(atom->getType() == GENE_NODE)` work?

**Comment by linas** [comment]
Yes. But if you are pattern mining, you should probably never explicitly access atom types in C++ code. So I'm confused by that question.  Most of the time, most code should not require knowing what the atom types are. It should work generically, for any atom types.
