### ISSUE TITLE
ERROR: no code for module (opencog)

### ISSUE THREAD

**Issue by mikiasw** [opencog/opencog#2830]
hi 
i have got an error while i am loading modules in to the scheme environment , 
 @linas how can i solve this problem 
`scheme@(guile-user)> (use-modules (opencog))                       
While compiling expression:
ERROR: no code for module (opencog)
`

`

**Comment by linas** [comment]
(add-to-load-path "/usr/local/share/opencog/scm")

**Comment by mikiasw** [comment]
it doesn't work in that way but i have reinstall atomspace,cogults and opencog , i think it is working well
