### ISSUE TITLE
cogita doesn't get/send result from chatbot on Debian sid

### ISSUE THREAD

**Issue by mhatta** [opencog/opencog#2870]
cogita doesn't work on Debian sid.

See discussion at https://groups.google.com/forum/#!topic/opencog/IxQQkRKzUdU

Possibly socket or guile-2.0 issue.

**Comment by linas** [comment]
I am trying to reproduce this, but I see other errors. I get a cascade of errors on `opencog/nlp/microplanning/main.scm`  which suggests that the microplanner is abandon-ware.

Also, relex2logic is abandonware: it crashes hard with 
```
Backtrace:
           3 (primitive-load-path "opencog/nlp/relex2logic/loader/ge…")
In opencog/nlp/relex2logic/loader/gen-r2l-en-rulebase.scm:
     22:0  2 (_)
In opencog/rule-engine/rule-engine-utils.scm:
   102:12  1 (ure-define-add-rule _ _ _ . _)
In unknown file:
           0 (cog-new-link 21 1 (DefinedSchemaNode "advmod")
 #)

ERROR: In procedure cog-new-link:
ERROR: In procedure cog-new-link: Wrong type argument in position 2 (expecting opencog atom): 1
```
and so opencog crashes before the cogserver is even started, for me. :-(

**Comment by linas** [comment]
If I stub out relex2logic, so that it doesn't run, I still get the error
```
;;; compiling /usr/local/share/opencog/scm/opencog/nlp/sureal/surface-realization.scm
;;; WARNING: compilation of /usr/local/share/opencog/scm/opencog/nlp/sureal/surface-realization.scm failed:
;;; ERROR: In procedure cog-new-link: Wrong type argument in position 2 (expecting opencog atom): 1
```
so it seems the both microplanning and sureal are broken, somehow.

**Comment by linas** [comment]
OK. Boost sucks. Boost should be lynched.  I have never ever every seen any boost code that actually worked correctly.  We should banish boost from opencog.  It's junk created by morons.

Step one:  commenting out the line 88 of `whirr-sockets.cc` the one that says `shutdown (sock, SHUT_WR);` allows a reply to be returned.  Which tells me that boost cannot correctly handle half-closed sockets. Unfortunately, this now leads to a hang in the receive loop, ten lines later, because the socket never gets closed, and so an end-of-socket never gets transmitted.

This is all code that used to work perfectly.

I REALLY HATE BOOST!

**Comment by linas** [comment]
Please test and close if the problem has gone away.

**Comment by linas** [comment]
I did some more testing, private chat works too, as long as you don't ask "how are you".  If you ask this, then the chatbot goes off and does a lot of thinking of some kind, and fails to respond.  Specifically, after 3 inutes of CPU time, it is still stuck in sureal, trying to generate a reply.  My guess is that sureal is just broken; that needs to be handled with a distinct bug report.

**Comment by linas** [comment]
After about 5 minutes of thinking, it spews the following error message.
```
<linas> how now brown cow
<cogita-bot> Hello linas, you said: "how now brown cow"
<cogita-bot> You made a Declarative SpeechAct
<linas> how are you
<cogita-bot> Hello linas, you said: "how are you"
<cogita-bot> You made an Interrogative SpeechAct
<cogita-bot> Backtrace:
<cogita-bot>           19 (apply-smob/1 #<catch-closure 55bd28ed24a0>)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>    2316:4 18 (save-module-excursion _)
<cogita-bot> In ice-9/eval-string.scm:
<cogita-bot>      38:6 17 (read-and-eval #<input: string 55bd288afe70> #:lang _)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>     849:4 16 (with-throw-handler _ _ _)
<cogita-bot> In opencog/nlp/chatbot/bot-api.scm:
<cogita-bot>     19:17 15 (wh_query_process _)
<cogita-bot> In opencog/nlp/fuzzy.scm:
<cogita-bot>    197:48 14 (get-fuzzy-answers _ #:do-microplanning _)
<cogita-bot> In srfi/srfi-1.scm:
<cogita-bot>    679:15 13 (append-map _ _ . _)
<cogita-bot>    592:17 12 (map1 (#))
<cogita-bot> In opencog/nlp/fuzzy.scm:
<cogita-bot>     80:27 11 (_ _)
<cogita-bot> In opencog/nlp/microplanning/main.scm:
<cogita-bot>    114:23 10 (microplanning-main _ _ _ #f)
<cogita-bot>     205:8  9 (make-sentence-chunks _ _ _)
<cogita-bot> In srfi/srfi-1.scm:
<cogita-bot>     640:9  8 (for-each #<procedure sub-helper (ut)> ("imperative"))
<cogita-bot> In opencog/nlp/microplanning/main.scm:
<cogita-bot>    149:32  7 (sub-helper "imperative")
<cogita-bot>    276:32  6 (make-sentence _ _ "imperative" #<<chunks-option> 55bd28cf5c60>)
<cogita-bot>    530:37  5 (check-chunk _ _ _)
<cogita-bot> In opencog/nlp/sureal/surface-realization.scm:
<cogita-bot>     145:4  4 (create-sentence # #t)
<cogita-bot> In ice-9/threads.scm:
<cogita-bot>    289:22  3 (loop _)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>    759:25  2 (dispatch-exception 0 wrong-type-arg ("cog-extract" "Wrong t…" …))
<cogita-bot> In opencog/nlp/chatbot/bot-api.scm:
<cogita-bot>     83:12  1 (_ . _)
<cogita-bot> In unknown file:
<cogita-bot>            0 (backtrace #<undefined>)
<cogita-bot> Sorry, I caught an exception
<cogita-bot> Backtrace:
<cogita-bot>           19 (apply-smob/1 #<catch-closure 55bd28ed24a0>)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>    2316:4 18 (save-module-excursion _)
<cogita-bot> In ice-9/eval-string.scm:
<cogita-bot>      38:6 17 (read-and-eval #<input: string 55bd288afe70> #:lang _)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>     849:4 16 (with-throw-handler _ _ _)
<cogita-bot> In opencog/nlp/chatbot/bot-api.scm:
<cogita-bot>     19:17 15 (wh_query_process _)
<cogita-bot> In opencog/nlp/fuzzy.scm:
<cogita-bot>    197:48 14 (get-fuzzy-answers _ #:do-microplanning _)
<cogita-bot> In srfi/srfi-1.scm:
<cogita-bot>    679:15 13 (append-map _ _ . _)
<cogita-bot>    592:17 12 (map1 (#))
<cogita-bot> In opencog/nlp/fuzzy.scm:
<cogita-bot>     80:27 11 (_ _)
<cogita-bot> In opencog/nlp/microplanning/main.scm:
<cogita-bot>    114:23 10 (microplanning-main _ _ _ #f)
<cogita-bot>     205:8  9 (make-sentence-chunks _ _ _)
<cogita-bot> In srfi/srfi-1.scm:
<cogita-bot>     640:9  8 (for-each #<procedure sub-helper (ut)> ("imperative"))
<cogita-bot> In opencog/nlp/microplanning/main.scm:
<cogita-bot>    149:32  7 (sub-helper "imperative")
<cogita-bot>    276:32  6 (make-sentence _ _ "imperative" #<<chunks-option> 55bd28cf5c60>)
<cogita-bot>    530:37  5 (check-chunk _ _ _)
<cogita-bot> In opencog/nlp/sureal/surface-realization.scm:
<cogita-bot>     145:4  4 (create-sentence # #t)
<cogita-bot> In ice-9/threads.scm:
<cogita-bot>    289:22  3 (loop _)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>    760:25  2 (dispatch-exception _ _ _)
<cogita-bot>    759:25  1 (dispatch-exception 1 wrong-type-arg ("cog-extract" "Wrong t…" …))
<cogita-bot> In unknown file:
<cogita-bot>            0 (apply-smob/1 #<catch-closure 55bd28ed2460> wrong-type-arg "co…" …)
<cogita-bot> ERROR: In procedure apply-smob/1:
<cogita-bot> ERROR: In procedure cog-extract: Wrong type argument in position 1 (expecting opencog atom): #<Invalid handle>
<cogita-bot> ABORT: wrong-type-arg
```

**Comment by leungmanhin** [comment]
Not sure how the `#<Invalid handle>` get to `cog-extract`, maybe it was in a different atomspace https://github.com/opencog/atomspace/issues/1336#issuecomment-323509182, just a quick guess

**Comment by linas** [comment]
@leungmanhin yes, something like that.  The hacky work-around is to test for a null list, before accessing an atom. The non-hacky fix is to figure out why this is happening (and why its so incredibly slow to respond).

**Comment by mhatta** [comment]
@linas You cogita fix works! thanks!  Closes #2878 

BTW, somehow "how are you" works on my environment.

```
05:48 (cogita-bot) ola
05:48 (cogita-bot) here we are
05:48 (mhatta) cogita-bot: Hello
05:48 (cogita-bot) Hello mhatta, you said: " Hello"
05:48 (cogita-bot) You made a Declarative SpeechAct
05:48 (mhatta) cogita-bot: How are you?
05:48 (cogita-bot) Hello mhatta, you said: " How are you?"
05:48 (cogita-bot) You made an Interrogative SpeechAct
05:48 (cogita-bot) Sorry, I don't know the answer.
05:48 (mhatta) cogita-bot: How are you
05:48 (cogita-bot) Hello mhatta, you said: " How are you"
05:48 (cogita-bot) You made an Interrogative SpeechAct
05:48 (cogita-bot) Sorry, I don't know the answer.
05:52 (mhatta) cogita-bot: how are you
05:52 (cogita-bot) Hello mhatta, you said: " how are you"
05:52 (cogita-bot) You made an Interrogative SpeechAct
05:52 (cogita-bot) Sorry, I don't know the answer.
```
I put cogita-bot in #opencog@freenode for a while, so you may test if you want.

**Comment by mhatta** [comment]
closes #2870

**Comment by linas** [comment]
Sure, but I think the default is to remember the conversation, and try to respond based on that.  So if you first say "This red dress is so you"  and then ask "how are you?" it might try to say something like "I am this red dress" or something like that.  However, it cannot create response sentences until it has previously heard a collection of other, similar sentences, from which to create a template for the answer.  This works very imperfectly, but it's the general idea.   So try again, saying "how new brown cow", first.

**Comment by linas** [comment]
The long-term goal is to pre-fill the chatbot with a collection of template example sentences, from which it can model responses, and to also provide a collection of common-sense statements, so that it can answer some basic questions. The current implementation for the collection of examples is a bit hacky; work is underway to improve it but progress is very slow.

**Comment by mhatta** [comment]
@linas I'm not familiar with the internal of nlp/chatbot, but bot-api.scm contains:
```
(define (wh_query_process query)
"
  Process wh-question using the fuzzy hypergraph Matcher
  QUERY should be a SentenceNode.

  Wrapper around get-fuzzy-answers provided by (opencog nlp fuzzy)
"
    (define temp (get-fuzzy-answers query))
    (cond
        ((equal? '() temp) "Sorry, I don't know the answer.")
        ; Return all of them, for now
        (else temp)
))
```
So I guess currently chatbot answers to all questions "Sorry I don't know the answer".  Is my understanding correct?

**Comment by linas** [comment]
it only answers "Sorry I don't know" if  `(get-fuzzy-answers query)` returns null. The fuzzy matcher looks for approximately similar patterns. If it can find them, then they are returned. But first, the atomspace has to contain some collection of patterns, which you can add by talking to the robot.
Next, the fuzzy matcher has to not be broken.  I don't know if the fuzzy matcher works or not. It used to work.

**Comment by mhatta** [comment]
Seems cogita is broken again.  The last time it was a Boost issue in cogserver socket handling, but seems Boost has been removed from cogserver.  I'm stuck.

**Comment by linas** [comment]
I get the error below; is that what you get?
```

-cogita-bot/#opencog- ola
<cogita-bot> here we are
<linas> cogita-bot: Hello
<cogita-bot> Backtrace:
<cogita-bot>            8 (apply-smob/1 #<catch-closure 5625b642e8c0>)
<cogita-bot>            7 (apply-smob/1 #<catch-closure 5625b6080e80>)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>    2316:4  6 (save-module-excursion #<procedure 5625b6070500 at ice-9/eval-string.scm:66:9…>)
<cogita-bot> In ice-9/eval-string.scm:
<cogita-bot>      38:6  5 (read-and-eval #<input: string 5625b62f0c40> #:lang _)
<cogita-bot> In ice-9/eval.scm:
<cogita-bot>    196:27  4 (_ #f)
<cogita-bot>    223:20  3 (proc #<directory (guile-user) 5625b5855140>)
<cogita-bot> In unknown file:
<cogita-bot>            2 (%resolve-variable (7 . process-query) #<directory (guile-user) 5625b5855140>)
<cogita-bot> In ice-9/boot-9.scm:
<cogita-bot>    759:25  1 (dispatch-exception 0 unbound-variable (#f "Unbound variable: ~S" (#) #f))
<cogita-bot> In unknown file:
<cogita-bot>            0 (apply-smob/1 #<catch-closure 5625b6081fc0> unbound-variable #f "Unbound var…" …)
<cogita-bot> ERROR: In procedure apply-smob/1:
<cogita-bot> ERROR: Unbound variable: process-query
<cogita-bot> ABORT: unbound-variable
```

**Comment by linas** [comment]
oh never mind, my mistake. Deleting last comment. Investigating.

**Comment by linas** [comment]
@mhatta please explain how its broken; better yet, do it in a new issue, so as not to confuse what happened here.   I just tried it, and "hello world" works.
