### ISSUE TITLE
MOSES builds but unit test "metapopulationUTest" doesn't

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2889]
this is on up-to-date ubuntu 16.04
opencog/$ git branch -v
 * master 644d1a2 Merge pull request #50 from ngeiswei/rename-bound-to-clamp
cogutils/$ git branch -v
 * master d4a8464 Fix typos, adjust wording.
```
[ 93%] Building CXX object tests/moses/CMakeFiles/metapopulationUTest.dir/metapopulationUTest.cpp.o
In file included from /home/mjsd/oc/moses/build/tests/moses/metapopulationUTest.cpp:23:0:
/home/mjsd/oc/moses/build/tests/moses/../../../tests/moses/metapopulationUTest.cxxtest: In member function ‘void metapopulationUTest::test_merge_nondominated_rec()’:
/home/mjsd/oc/moses/build/tests/moses/../../../tests/moses/metapopulationUTest.cxxtest:145:46: error: conversion from ‘void’ to non-scalar type ‘opencog::moses::scored_combo_tree_set {aka
 std::unordered_set<opencog::moses::scored_combo_tree, opencog::moses::scored_combo_tree_hash, opencog::moses::scored_combo_tree_equal>}’ requested
         scored_combo_tree_set res = set_union(res_p.first, res_p.second);
                                              ^
tests/moses/CMakeFiles/metapopulationUTest.dir/build.make:66: recipe for target 'tests/moses/CMakeFiles/metapopulationUTest.dir/metapopulationUTest.cpp.o' failed
make[3]: *** [tests/moses/CMakeFiles/metapopulationUTest.dir/metapopulationUTest.cpp.o] Error 1
CMakeFiles/Makefile2:3083: recipe for target 'tests/moses/CMakeFiles/metapopulationUTest.dir/all' failed
make[2]: *** [tests/moses/CMakeFiles/metapopulationUTest.dir/all] Error 2
CMakeFiles/Makefile2:138: recipe for target 'CMakeFiles/test.dir/rule' failed
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
Makefile:210: recipe for target 'test' failed

```

**Comment by linas** [comment]
Hey Mike, you should open moses bugs against moses, and not against opencog.

**Comment by linas** [comment]
I'm looking at this now, looks like a bug in cogutils code.

**Comment by linas** [comment]
Mike, I am closing this; fixed in https://github.com/opencog/cogutils/commit/bdb07281e70233a05f8208a46952108e87f47f1b -- in C++ all polymorphic functions must have the same return value, and somehow, that was not the case.

Note: you have to pull cogutils first, then make;make install, and then rebuild moses

**Comment by ngeiswei** [comment]
Apologies, it was me testing gcc disambiguation capabilities to the limit, it turns out it's not able to do it well so I have renamed set_union to set_insertion (for inplace union).

**Comment by ngeiswei** [comment]
Linas said "in C++ all polymorphic functions must have the same return value" ah OK, I didn't know this was C++ standard.

**Comment by linas** [comment]
Hi Nil, Yes, its part of the standard.  It has something to do with the confusion of implicit casting.

**Comment by mjsduncan** [comment]
thanks guys!  sorry for posting in the wrong repo
