### ISSUE TITLE
Unable to update face locations in opencog's octomap

### ISSUE THREAD

**Issue by misgeatgit** [opencog/opencog#2913]
I tried to manually replicate the message sent in the [ros-behavior-scripting]
(https://github.com/opencog/ros-behavior-scripting/blob/master/sensors/face_track.py#L146) code in an effort to understand why the data was not visible in the atomspace and got the following error message while doing so.

```scm
 (use-modules (opencog pointmem))
 (map-ato "faces" (NumberNode "2963" (av 5 0 0)) 0.713286099884 0.0560207790733 -0.146352373313)
```

```log
Backtrace:
           8 (apply-smob/1 #<catch-closure 1161e00>)
           7 (apply-smob/1 #<catch-closure 1161d60>)
In ice-9/boot-9.scm:
   2316:4  6 (save-module-excursion #<procedure 10735e0 at ice-9/eva…>)
In ice-9/eval-string.scm:
     38:6  5 (read-and-eval #<input: string 1982cb0> #:lang _)
In ice-9/eval.scm:
   213:21  4 (_ #f)
   223:20  3 (proc #<directory (guile-user) 11850a0>)
In unknown file:
           2 (%resolve-variable (7 . map-ato) #<directory (guile-use…>)
In ice-9/boot-9.scm:
   759:25  1 (dispatch-exception 0 unbound-variable (#f "Unbound …" …))
In unknown file:
           0 (apply-smob/1 #<catch-closure 1161d20> unbound-variable …)

ERROR: In procedure apply-smob/1:
ERROR: Unbound variable: map-ato
ABORT: unbound-variable
```

**Comment by leungmanhin** [comment]
I think it has been renamed to `cog-pointmem-map-atom`

**Comment by misgeatgit** [comment]
Just checked it. All the associated scheme bindings are prefixed with cog-pointmem as you said. The other issue almost all of functions signatures have been changed to accept Handles only. These changes haven't been reflected in the python code. Thanks.
