### ISSUE TITLE
Swap order arguments of `AtTimeLink`

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#2939]
## Objective

Swap arguments order of `AtTimeLink`, i.e.

```
AtTimeLink
  T
  A
```
becomes
```
AtTimeLink
  A
  T
```

## Rational

The current `AtTimeLink` argument order is inconsistent with both natural language and `AtLocationLink`. Indeed, `A` occurs at time `T`, is represented as
```
AtTimeLink
  T
  A
```
Furthermore, `A` is located at space map `M` and coordinates `XYZ`, is represented as
```
AtLocationLink
 A
 ListLink
   M
   XYZ
```

## Poll

What do you guys say?

Nil: :+1:

**Comment by linas** [comment]
OK w/ me.  I would like to swap the order for MemberLink. I don't want to clog this issue explaining why... but thought I should mention it.

**Comment by ngeiswei** [comment]
+ updated wiki
