### ISSUE TITLE
PointMemory invalid handle values

### ISSUE THREAD

**Issue by DeborggraeveR** [opencog/opencog#2983]
Create point-mem maps in SCM using decimals results in an exception.
Seems the decimal places are lost.

`(cog-pointmem-create-map facemap (ListLink (Number 0.01) (Number 66) (Number 150)))`

```
ERROR: In procedure cog-pointmem-create-map: Expecting positive spatial resolution (/home/randy/workspace/opencog/opencog/opencog/spacetime/pointmemory/PointMemorySCM.cc:238)
Function args:
((SpaceMapNode "faces")
 (ListLink
   (NumberNode "0.000000")
   (NumberNode "66.000000")
   (NumberNode "150.000000")
)
)
ABORT: C++-EXCEPTION
```

**Comment by linas** [comment]
Yeah, there's an obvious bug in that code.

**Comment by linas** [comment]
Pull req #2990 fixes this issue. Note however, that code is still not passing it's unit test.

That subsystem is not complex: its small, simple, and straight-foreward.  It also does not have any maintainers - the original author is not around, and no one else has picked it up. Could you possibly look into the unit test failure, debug that, and fix it?

**Comment by DeborggraeveR** [comment]
Din't have much time last 2 days to continue searching where the values
from the scm file are parsed/loaded. Bit difficult as i don't know much yet
about guile. Hopefully i can track the bug and fix.

Op 25 jan. 2018 20:14 schreef "Linas Vepštas" <notifications@github.com>:

Yeah, there's an obvious bug in that code.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/opencog/opencog/issues/2983#issuecomment-360569734>,
or mute
the thread

**Comment by linas** [comment]
OK, you mis-understood me. I already fixed the bug that you reported. It was an easy fix - its in pull req #2990. Look at it.

What I am saying is that there are also *other* bugs in this code.  What are you using the spacetime server for? Why are you interested in it?

**Comment by DeborggraeveR** [comment]
Yes, i posted my last answer before i saw your message that it's already fixed.
I had this issue when trying to run ghost or chatbot-psi.
See: https://groups.google.com/forum/#!topic/opencog/ZKDUWBC9VmA

But i'm also trying to explore the many parts of opencog and use it for my ROS project.
So my first goal is to have my ROS speech recognition node communicate to opencog, receive an answer and have the result processed by my text-to-speech ROS node.

I know about the HEAD, EVA, ros-behavior, ... projects, but want to try a different approach, full c++ (not a python fan ;))
Was also thinking about trying to run the opencog server as a ROS node itself, so still trying to get deeper in the code and see what are the possibilities.

So best way to learn code is debug, develop on it, so i will be have to be able to contribute

**Comment by linas** [comment]
OK.  Several comments then:

1) the space-time server is meant to be a fast-path for storing spatial locations, and using them to reason about. But its only used very minimally, and is not much thought out.

2) The python API to the atomspace is kind-of rough, and is not well maintained. Also, python is single-threaded (it emulates multiple threads) so, yeah, its awkward all-around.

3) a "ROS node" for opencog is .. an interesting idea. ROS nodes tend to provide specific functions, opencog is general. So maybe a "ROS node for opencog chatbot" makes sense, or something like that.

4) Try to avoid using the cogserver. The cogserver does provide a network API for executing scheme and python (you can pipe snippets of python over a socket, and it will execute it) ... but its kind of icky and olde-fashioned and problematic.
