### ISSUE TITLE
Can't find cpprest if the minor version is 2 digits

### ISSUE THREAD

**Issue by mhatta** [opencog/opencog#3030]
opencog/lib/Findcpprest.cmake assumes cpprest's minor version is always 1 digit.  The current cpprest version is 2.10.2, and CMake thinks it's 2.1.  So the version check fails.

A fix is something like:

            STRING(REGEX MATCH "#define CPPREST_VERSION_MINOR ([0-9])" _MATCH " ${_CPPREST_VERSION_H_CONTENTS}")

should be

            STRING(REGEX MATCH "#define CPPREST_VERSION_MINOR ([0-9]+)" _MATCH "${_CPPREST_VERSION_H_CONTENTS}")

**Comment by ngeiswei** [comment]
Thanks for the report!

It looks like `FindZMQ.cmake` would have potentially the same problem.

Do you think you can create a PR yourself? Otherwise I'll handle it, just let me know.

**Comment by mhatta** [comment]
Ok, I'll create a PR for this.

**Comment by mhatta** [comment]
It can be closed now.
