### ISSUE TITLE
Ghost - issue with apostraphe in rules

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/opencog#3050]
It seems ghost is having some issues matching rule patterns that have a word with an apostrophe.

E.g., this works:
scheme@(guile-user)> (ghost-parse "u: (I am hungry) 'me too")
[2018-04-12 05:04:03:784] [WARN] [GHOST] Did you forget to link a goal to the rule?
$1 = #t
scheme@(guile-user)> (test-ghost "I am hungry")
[2018-04-12 05:04:08:029] [INFO] [GHOST] Say: "me too" 

But not this:
scheme@(guile-user)> (ghost-parse "u: (I'm hungry) 'me too")
[2018-04-12 05:04:19:070] [WARN] [GHOST] Did you forget to link a goal to the rule?
$2 = #t
scheme@(guile-user)> (test-ghost "I'm hungry")
scheme@(guile-user)> 

Happens with wildcards too.
This works:
scheme@(guile-user)> (ghost-parse "u: (I am _*) 'I am _0 too")
$10 = #t
scheme@(guile-user)> (test-ghost "I am hungry")
[2018-04-12 04:40:54:109] [INFO] [GHOST] Say: "I am hungry too"

But this doesn't:
scheme@(guile-user)> (ghost-parse "u: (I'm _*) 'I am _0 too")
$11 = #t
scheme@(guile-user)> (test-ghost "I'm hungry")
scheme@(guile-user)> 

FWIW, this works (when there are no words to match the wildcard):
scheme@(guile-user)> (ghost-parse "u: (I'm _*) 'I am _0 too")
$12 = #t
scheme@(guile-user)> (test-ghost "I'm")
[2018-04-12 04:46:58:609] [INFO] [GHOST] Say: "I am too"

**Comment by leungmanhin** [comment]
Should be fixed by https://github.com/opencog/opencog/pull/3109
