### ISSUE TITLE
sql-open not available on cogserver command line / how to use password auth?

### ISSUE THREAD

**Issue by fm444fm** [opencog/opencog#3058]
I managed to use the sql persist via postgres by following https://github.com/opencog/atomspace/blob/master/opencog/persist/sql/README.md after having removed odbc drivers and cleaned/rebuild/reinstalled (following comment by mjsduncan on issue #3041)

Nevertheless, no sql-open sql-store... commands are available on cogserver command line (as shown in the wiki and as shown in the previously mentioned README). 

```
opencog> sql-open 
command "sql-open" not found
```
How to enable sql- persist commands on cogserver command line?

Another note: currently the system appears to only allow peer authentication and hence only if the user running the cogserver is the same user defined as database owner (and it has to be a unix local user, i.e. by default the opencog_tester). How to allow the password auth so that if the cogserver is launched by another user it will be possible to use the specified password?

When I attempt (sql-open "postgres:///DATABASE?user=USER&password=PASSWORD") it throws exception:
```
 In procedure sql-open: Cannot connect to database: FATAL:  Peer authentication failed for user "USER"
ABORT: C++-EXCEPTION
```

I.e. it seems it can only connect via peer mode and hence only if the user running the cogserver is the same user defined in the configuration file as
>  STORAGE_USERNAME      = "opencog"

My  /etc/postgresql/9.5/main/pg_hba.conf contains
```
local   all             all                                     peer
local   all             all                                     md5
```

Thank you very much

**Comment by glicerico** [comment]
You need parenthesis surrounding your guile commands, i.e. (sql-open ARGS).
If they're missing in the documentation, you can fix it and do a Pull
Request :)

About the user problem, I can only ask if you did what's stated in the
README in Database Setup:

If you get an error message FATAL: role "<user>" does not exist, then try
doing this, replacing 'alex' with your username.

   $ sudo su - postgres
   $ psql template1
   template1=# CREATE ROLE alex WITH SUPERUSER;
   template1=# ALTER ROLE alex WITH LOGIN;


Probably others might be better to help out if that doesn't work.

a.

**Comment by linas** [comment]
What Andres says seems right.

There is no cogserver sql module any more; anything that talk about it should be edited, and all mentions removed.  If you follow the instructions precisely, it should work; otherwise, there's fiddling with `hba.conf` and other files that is needed.  I've gotten it to work in not just peer mode, but also in other modes, but it requires fiddling and googling the postgres docs.

**Comment by linas** [comment]
The pull req opencog/atomspace#1635 updates the README, and removes the references to the obsolete cogserver module.

**Comment by fm444fm** [comment]
Ok first of all thank you for clarifying that it is not possible to do it from opencog telnet command line. I was getting really nuts trying to find what I was doing wrong... 

On scm/guile I use the commands with (), i.e.:
```
(use-modules (opencog) (opencog persist) (opencog persist-sql))
(sql-open "postgres:///DATABASE?user=USER&password=PASSWORD")
```
The result is always 
> FATAL:  Peer authentication failed for user "opencog"
(opencog is what I used as USER instead of opencog_tester)

And yes, I followed the readme and yes I defined the template and also the pg_hba.conf as mentioned above. The error messages do not mention "role".

My template1 \dg reads:
```
 MYUNIXUSER        | Superuser                                                  | {}
 opencog   | Superuser                                                  | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```
...which is probably overkill for what should be needed.

Anyway the only way I found to make it work is by using a unix user "opencog" which starts the cogserver and then connecting to cogserver from my unix user, going to guile prompt and opening the database without the password (i.e. with peer authentication) as 
`(sql-open "postgres:///atomspace?user=opencog")`

To me this is not really ideal.. I would have preferred not to have to create a dedicated "opencog" unix user running the cogserver and instead simply have  a **DBuser** opencog and rely on STORAGE_USERNAME and the other two config variables to access the storage.

**Comment by linas** [comment]
Sounds to me like you need to read the postgres documentation, paying close attention to what "peer" authentication really means, and how to alter `hba.conf` to handle different kinds of authentication.

I have gotten ALL of the different kinds of postgres authentication styles to work, including md5, password, and ssh.  On of these requires installing and configuring an `ident` server .. perhaps peer requires that ??? I don't recall.  The ident server provides the needed unix-user identities to postgres. The other authentication methods do NOT require the ident server.  ... The ident server is really old, ancient .. prehistoric internet technology, dating to the 1970's or something like that.  Anyway, it takes a lot of fiddling to get the various different postgres auth methods to work ... read the postgres documentation very carefully.  Its confusing at first, and then confusing at second, and third ... but it is possible to make it work.

**Comment by fm444fm** [comment]
> Its confusing at first, and then confusing at second, and third ... but it is possible to make it work.

Super!! :)
Ok I will try, thank  you.

Anyway from what I understood peer is working ok, i.e. it takes opencog (in my case; it'd be 
opencog_tester if using the defaults of the readme) as the user and since it is both the owner of the db and the unix user running cogserver and furthermore it connects locally, it does not need a password, using peer auth. 

But I'll try to understand more and see if I can get the password method to work, i.e. with a unix user and db user being different. Thank you.
