### ISSUE TITLE
Ghost - rejoinder after ^reuse() not working

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/opencog#3076]
For example:

    s: Rule1 (-)  Do you like ice cream?
        a: Rejoinder1 (yes) ....
    s: Rule2 (cake) ^reuse(Rule1)

If Rule2 is triggered, responding "yes" to the Rule1 question does not trigger Rejoinder1

**Comment by leungmanhin** [comment]
https://github.com/opencog/opencog/pull/3078 should fix this problem

**Comment by elggem** [comment]
Hey, just tried with this rulebase:

```
urge:(testGoal=1.0)

goal: (testGoal=1.0)
 u: RULE1 (*) do you like icecream?
    a: REJOI1 (yes) uh lala nice me too
    a: REJOI2 (no)  who doesnt like icecream?

 u: RULE2 (cake) ^reuse(RULE1) ^keep()
```

Unfortunately not the expected output, rejoinders are not being reused and can only trigger once even when RULE2 is triggered.

**Comment by eddiemonroe** [comment]
It would be good to make sure the desired behavior is clear, as there are a
few different things going on here:

1) Should RULE1 whose actions are called by ^reuse from RULE2 be marked as
already triggered? (IOW matching RULE1 pattern will or will not trigger
rule after it has been called by ^reuse. I think CS does not mark the rule
triggered in this case, but CS also separately tracks whether a particular
output can be repeated.)
2) Should RULE1 actions be able to be called by ^reuse from other rules
multiple times? (CS defaults to yes for this question and allows a "once"
parameter to specify that RULE1 actions should only be executed by ^reuse
once)
3) Seems that whenever ^reuse successfully calls RULE1 with rejoinders in
the action, the rejoinders should always get set

**Comment by eddiemonroe** [comment]
@elggem @leungmanhin I agree that addressing the questions above is something that can be deferred until the 2nd sprint. 

It looks to me that the original problem in this issue is fixed.

Also, the rejoinders can be used again by adding ^keep() to the action. IMO, we might want to make the default that if an action with rejoinders is called, that the rejoinders are automatically enabled (like with an implicit keep() for the rejoinders), as that seems like it would be the intention of the author, and it would be easy for an author to forget adding ^keep()'s to all the rejoinders.

**Comment by leungmanhin** [comment]
@eddiemonroe

> make the default that if an action with rejoinders is called, that the rejoinders are automatically enabled (like with an implicit keep() for the rejoinders), as that seems like it would be the intention of the author, and it would be easy for an author to forget adding ^keep()'s to all the rejoinders

Yes I agree, and I think it wouldn't be too difficult to implement. If I do it for this sprint, would this breaks any existing rules?

**Comment by leungmanhin** [comment]
@eddiemonroe @elggem, should be fixed by https://github.com/opencog/opencog/pull/3165

**Comment by elggem** [comment]
Tested and works!
