### ISSUE TITLE
Ghost - Lemma inside phrases not working

### ISSUE THREAD

**Issue by Eskender-B** [opencog/opencog#3106]
When I enter Lemma of a word inside a phrase, the words corresponding to the lemmas are not being properly matched. For example:

```
scheme@(guile-user)> (ghost-parse "topic: ~SOMETOPIC keep []")
$1 = #t
scheme@(guile-user)> (ghost-parse "concept: ~HI [hi hello \"how be you\"]")
$2 = #t
scheme@(guile-user)> (ghost-parse "u: (~HI) hello")
$3 = #t
scheme@(guile-user)> (test-ghost "how be you")
[2018-05-11 10:22:43:019] [INFO] [GHOST] Say: "hello"
scheme@(guile-user)> (test-ghost "how are you")
scheme@(guile-user)> (ghost-parse "u: (how be you) I am good")
$4 = #t
scheme@(guile-user)> (test-ghost "how are you")
[2018-05-11 10:24:45:746] [INFO] [GHOST] Say: "I am good"
scheme@(guile-user)> (test-ghost "how are you")
[2018-05-11 10:24:49:207] [INFO] [GHOST] Say: "I am good"

```
In Concept ~HI there is a phrase "how be you". When I use the concept inside a pattern it won't match the input "how are you". It only matches to its exact form "How be you". It on the other hand works fine when I use  "how be you" directly inside the pattern.

**Comment by leungmanhin** [comment]
Things will be matched literally if they are quoted like `"how be you"`. You can instead use another "sequence" if you want to match in lemma form, i.e.
```
(ghost-parse "concept: ~HI [hi hello (how be you)]")
```

I don't remember how much does these kind of nested "sequence" cover in terms of functionality, but as least it will work for the above test case.

**Comment by leungmanhin** [comment]
I believe this is no longer an issue, let me know if that's not the case.
