### ISSUE TITLE
relex2logic got broke in recent refactorings

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#3197]
scheme@(guile-user)> (use-modules (opencog) (opencog nlp relex2logic))
While compiling expression:
In procedure dynamic-link: file: "libspacetime-types", message: "file not found"

**Comment by linas** [comment]
`libspacetime-types` is still being built and installed, I believe. So this is probably a variant of the `liblogger not found` error, which is very obscure, having something to do with missing shared library symbols. 

But first, can you verify something more basic: that, in the build directory, you see `libspacetime-types.so` e.g. when listing
```
ls -la ./opencog/spacetime/atom-types/
```
and that the build date is recent (last few days)? Similarly, 
```
ls -la /usr/local/lib/opencog
```
should also list it, with the same size and date.   Finally, 
```
ldd -r /usr/local/lib/opencog/libspacetime-types.so
```
should not results in any error or warning messages being printed. (if there are errors, they're always printed last)

**Comment by mjsduncan** [comment]
it's current  (june 5) in both places but `ldd -r /usr/local/lib/opencog/libspacetime-types.so` gives:
```
undefined symbol: _ZN7opencog11NUMBER_NODEE     (/usr/local/lib/opencog/libspacetime-types.so)
undefined symbol: _ZN7opencog4NODEE     (/usr/local/lib/opencog/libspacetime-types.so)
undefined symbol: _ZN7opencog12ORDERED_LINKE    (/usr/local/lib/opencog/libspacetime-types.so)
undefined symbol: _ZN7opencog19SEQUENTIAL_AND_LINKE     (/usr/local/lib/opencog/libspacetime-types.so)
undefined symbol: _ZN7opencog10nameserverEv     (/usr/local/lib/opencog/libspacetime-types.so)
undefined symbol: _ZN7opencog10NameServer14beginTypeDeclsEPKc   (/usr/local/lib/opencog/libspacetime-types.so)
undefined symbol: _ZN7opencog10NameServer8declTypeEtRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE      (/usr/local/lib/opencog/libspacetime-types.so)
undefined symbol: _ZN7opencog10NameServer12endTypeDeclsEv       (/usr/local/lib/opencog/libspacetime-types.so)
```
and similarly for this library:
scheme@(guile-user)> (use-modules (opencog eva-behavior))
While compiling expression:
In procedure dynamic-link: file: "libattention-types", message: "file not found"

ldd -r /usr/local/lib/opencog/libattention-types.so
```undefined symbol: _ZN7opencog14UNORDERED_LINKE  (/usr/local/lib/opencog/libattention-types.so)
undefined symbol: _ZN7opencog4LINKE     (/usr/local/lib/opencog/libattention-types.so)
undefined symbol: _ZN7opencog12ORDERED_LINKE    (/usr/local/lib/opencog/libattention-types.so)
undefined symbol: _ZN7opencog10nameserverEv     (/usr/local/lib/opencog/libattention-types.so)
undefined symbol: _ZN7opencog10NameServer14beginTypeDeclsEPKc   (/usr/local/lib/opencog/libattention-types.so)
undefined symbol: _ZN7opencog10NameServer8declTypeEtRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE      (/usr/local/lib/opencog/libattention-types.so)
undefined symbol: _ZN7opencog10NameServer12endTypeDeclsEv       (/usr/local/lib/opencog/libattention-types.so)
```

**Comment by linas** [comment]
pull req #3199 is my best-guess fix for this. Your linker behaves differently from my linker, and I don't know why. 

You may need to apply a similar fix to the agi-bio code -- it seems likely that your agi-bio atom types file will also have the same missing symbols.

**Comment by mjsduncan** [comment]
seems to work now, thanks!
