### ISSUE TITLE
installation of atomspace + error in guile

### ISSUE THREAD

**Issue by kumkumsharma** [opencog/opencog#3217]
Hello,

I am new to opencog and atomspace and trying to install it on my ubuntu (in virtual box):

root@ubuntu-VirtualBox:~/opencog/atomspace/lib# uname -a
Linux ubuntu-VirtualBox 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

But I am getting following error while running cmake in atomspace.

root@ubuntu-VirtualBox:~/opencog/atomspace/build# cmake ..
-- Build type: Release
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Boost version 105800 found.
-- Found CogUtil version 2.0.2 at /usr/local/lib/libcogutil.so
-- CogUtil found.
-- CxxTest found.
-- Gearman found.
-- Guile ( >= 2.0.9) was not found. Make sure GUILE_LIBRARY and GUILE_INCLUDE_DIR are set.
CMake Error at CMakeLists.txt:249 (MESSAGE):
  Guile was not found; the scheme shell will not be built.

  To over-ride, make sure GUILE_LIBRARIES and GUILE_INCLUDE_DIRS are set.

-- Configuring incomplete, errors occurred!
See also "/root/opencog/atomspace/build/CMakeFiles/CMakeOutput.log".
See also "/root/opencog/atomspace/build/CMakeFiles/CMakeError.log".

As far as i understand i have alreday installed guile as
root@ubuntu-VirtualBox:~/opencog/atomspace/lib# guile --version
guile (GNU Guile) 2.0.11
Packaged by Debian (2.0.11-deb+1-10)
Copyright (C) 2014 Free Software Foundation, Inc.

License LGPLv3+: GNU LGPL 3 or later <http://gnu.org/licenses/lgpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

But as per the error. version.h is actually not there. I am not getting what to do now.I tried to look occurence of all folder where guile could possibly go with the intention to fid its version.h.But i couldnot find it. Also I tried removing previous version and installing fresh one.But i am getting following error:
root@ubuntu-VirtualBox:~# apt-get remove guile
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Virtual packages like 'guile' can't be removed
0 upgraded, 0 newly installed, 0 to remove and 170 not upgraded.

**Please help me in resolving this error.**

Here is the code snippet from my opncog/atomspace/build/CMakeCache.txt
//Path to a file.
COGUTIL_INCLUDE_DIR:PATH=/usr/local/include

//Path to a library.
COGUTIL_LIBRARY:FILEPATH=/usr/local/lib/libcogutil.so

//CxxTest binary filepath
CXXTEST_GEN:FILEPATH=/usr/bin/cxxtestgen

//Where is cxxtest located?
CXXTEST_PYTHON_BIN_DIR:PATH=/usr/bin

//Path to a file.
GEARMAN_INCLUDE_DIR:PATH=/usr/include/libgearman

//Path to a library.
GEARMAN_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libgearman.so

//Path to a file.
GMP_INCLUDE_DIR:PATH=/usr/include/x86_64-linux-gnu

//Path to a library.
GMP_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libgmp.so

**//Path to a file.
GUILE_INCLUDE_DIR:PATH=GUILE_INCLUDE_DIR-NOTFOUND

//Path to a library.
GUILE_LIBRARY:FILEPATH=GUILE_LIBRARY-NOTFOUND**

//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python

//Value Computed by CMake
atomspace_BINARY_DIR:STATIC=/root/opencog/atomspace/build

//Value Computed by CMake
atomspace_SOURCE_DIR:STATIC=/root/opencog/atomspace

and using "find" command i could foung "guile" word at these areas:
/var/lib/dpkg/alternatives/guile
/usr/share/guile
/usr/bin/guile
/usr/lib/x86_64-linux-gnu/guile-2.0/bin/guile
/usr/lib/x86_64-linux-gnu/guile
/usr/lib/x86_64-linux-gnu/aisleriot/guile
/usr/lib/x86_64-linux-gnu/libguilereadline-v-18.so

Do i need to put something in CMakeCache.txt in "GUILE_INCLUDE_DIR" and "GUILE_LIBRARY" to make it work? If yes, what? I am really confused as i didn't find version.h related to guile anywhere in whole system.

**Comment by ngeiswei** [comment]
Thanks for your report @kumkumsharma, the requirement of guile has gone up to 2.2.2 or newer. I've updated CMake config file of opencog accordingly. To upgrade your version of guile I'm afraid you're gonna have to compile/install it from source, which you may find here https://ftp.gnu.org/gnu/guile/.

**Comment by kumkumsharma** [comment]
Ohh ok..?thanks for the response @ngeiswei . I am trying doing that now.

**Comment by kumkumsharma** [comment]
Yes, it is working now.Thanks.
Now, it is complaining about absence of hypertable, pythontest and haskell.Hopefully those all i would have to install manually.

**Comment by vsbogd** [comment]
Hi @kumkumsharma,

BTW, it is not required to install all of things cmake searches. You can
start without hypertable, pythontest and haskell and add them later if you
need additional functionality.

Best regards,
  Vitaly

2018-06-22 14:31 GMT+03:00 kumkumsharma <notifications@github.com>:

**Comment by kumkumsharma** [comment]
Yeah..Got it. Thanks. :)
