### ISSUE TITLE
Ghost - Getting result in ghost

### ISSUE THREAD

**Issue by Eskender-B** [opencog/opencog#3251]
When running `test-ghost` or `ghost` the resulting speech output is printed by logger.
Is it possible to get the result as a return value or something else?

This would be very convenient specially when trying to give the result directly to TTS.
Another possible convenience is while writing tutorial for ghost in jupyter notebook where the result is only displayed to the console not as a return value to be captured inside the notebook.

`ghost-get-result` approximately achieves what is needed but if a certain input does not match any rules the function returns the previous matched input's result instead of empty list. 

Is it possible to make the function return empty list instead of previous outdated result when there is no match?

**Comment by leungmanhin** [comment]
I understand how this can be useful, especially if Ghost is used as a pure text-based chatbot. I think something like that can be done, clearing the `ghost-get-result` when a new input arrives is also possible. I can look into this to see what's the best way of doing it.

**Comment by Eskender-B** [comment]
Thanks that will simplify things!

**Comment by leungmanhin** [comment]
As done in https://github.com/opencog/opencog/pull/3307, please use `(ghost-get-result)` to get the result.
