### ISSUE TITLE
Migrating from GitHub to one_of(GitLab, BitBucket, ...)

### ISSUE THREAD

**Issue by SomeUserName1** [opencog/opencog#3257]
As Microsoft bought GitHub some weeks ago, it might be worth considering to change to e.g a self-hosted GitLab instance (OpenSource software & full control over VCS/DevOps).
[GitLab in git documentation](https://git-scm.com/book/en/v2/Git-on-the-Server-GitLab)
[Comprehensive comparison](https://medium.com/flow-ci/github-vs-bitbucket-vs-gitlab-vs-coding-7cf2b43888a1)

**Comment by pennachin** [comment]
The main value of GitHub isn't the feature set, it's the large and vibrant community of users. Should that community move elsewhere we should look into it.
