### ISSUE TITLE
Sentence splitter doesn't detect underscore as beginning of sentence

### ISSUE THREAD

**Issue by glicerico** [opencog/opencog#3282]
Sentence splitter at opencog/opencog/nlp/learn/run/split-sentences.pl doesn't split if new sentence begins with underscore, which is commonly used as emphasis indication in texts.
Examples:

> Normal sentence. \_Emphasized sentence\_.
> Another normal. \_\_2nd example\_\_.

**Comment by linas** [comment]
Fixed by #3335 I'm closing; if this is still plaguing you, please re-open.
