### ISSUE TITLE
Opencog won't build with Ubuntu 14.04 (missing PythonEval)

### ISSUE THREAD

**Issue by linas** [opencog/opencog#3298]
After upgrading to the latest, and installing cmake3 (issue opencog/atomspace#1857) I can build and install the atomspace. However, now opencog does not build. I get:
```
[  4%] Building CXX object opencog/cogserver/server/CMakeFiles/server.dir/SystemActivityTable.cc.o
[  5%] Linking CXX shared library libserver.so
/usr/bin/ld: cannot find -lPythonEval
collect2: error: ld returned 1 exit status
make[2]: *** [opencog/cogserver/server/libserver.so] Error 1
make[1]: *** [opencog/cogserver/server/CMakeFiles/server.dir/all] Error 2
make: *** [all] Error 2
```
I can see it  here:
```
$ cd /usr/local/lib/opencog; ls -la
-rw-r--r--  1 root root  7626926 Jul 11 05:14 libPatternMiner.so
-rw-r--r--  1 root root   188321 Jul 11 05:14 libpatternminer-types.so
-rw-r--r--  1 root root   125076 Aug 20 12:49 libpersist-pg.so
-rw-r--r--  1 root root   748664 Aug 20 12:49 libpersist.so
-rw-r--r--  1 root root  5950138 Aug 20 12:51 libpersist-sql.so
-rw-r--r--  1 root root  2379597 Jul 11 05:14 libpoint_memory.so
-rw-r--r--  1 root root  1736000 Mar 22 10:52 libPythonEval.so
-rw-r--r--  1 root root   793499 Mar 22 10:52 libPythonSCM.so
-rw-r--r--  1 root root  9499583 Aug 20 12:47 libquery.so
-rw-r--r--  1 root root   651175 Aug 20 12:54 librandgen.so
-rw-r--r--  1 root root 14526757 Aug 20 12:54 libruleengine.so
```
So -- all of the libraries with datestamp `20 Aug 12:54` are from the atomspace, built and installed today.  All of the libraries with the datestamp `11 Jul 05:14` are opencog libs, from the last time I built opencog.  Note that `libPythonEval.so` is there, but it has some very out-of-date timestamp of `22 Mar`.  Not sure why; I have `python-dev` installed.   Looks like atomspace isn't building it.

At any rate, this is a distinct issue: if opencog actually does need PythonEval as a dependency, it should check for it.   More generally .. why does the cogserver depend on python? ??? Is this really needed?  Or is this an accidental dependency?

**Comment by Dagiopia** [comment]
could it be that ubuntu 14 has cython version less than the required one for atomspace on apt and pythoneval isn't build if the version isn't correct. but since opencog asks for a lesser version it goes to linking the server with python because of the python shell in there. 
atomspace asks for cython [version 0.23](https://github.com/opencog/atomspace/blob/18ca1e8343c658d799d60bef41c82d88906d1d48/CMakeLists.txt#L361) whereas opencog asks for [version 0.19](https://github.com/opencog/opencog/blob/8e4499a80839a0f0c0322752644ba5258104f7a2/CMakeLists.txt#L377)

**Comment by ngeiswei** [comment]
I'm not python/cython expert but I think it could be the reason. And requiring different versions of cython in atomspace and opencog is asking for troubles. @Dagiopia could you create a pull request for it?

**Comment by Dagiopia** [comment]
sure thing

**Comment by bulidiriba** [comment]
Hello I faced the same error missing PythonEval  after upgrading to the latest opencog on ubuntu 14.04. even after I install Cython 0.28.5 the error still arise

//usr/bin/ld: cannot find -lPythonEval
collect2: error: ld returned 1 exit status
usr/bin/ld: cannot find -lPythonEval
collect2: error: ld returned 1 exit status
make[2]: *** [opencog/learning/miner/libminer.so] Error 1
make[1]: *** [opencog/learning/miner/CMakeFiles/miner.dir/all] Error 2
make[1]: make[2]: *** [opencog/nlp/types/libnlp-types.so] Error 1
*** Waiting for unfinished jobs....
make[1]: *** [opencog/nlp/types/CMakeFiles/nlp-types.dir/all] Error 2
[ 18%] Linking CXX shared library libspacetime-types.so
[ 18%] Built target spacetime-types
/home/aman/OPENCOGS/opencog/opencog/cogserver/server/CogServer.cc:49:39: fatal error: opencog/cython/PythonEval.h: No such file or directory
 #include <opencog/cython/PythonEval.h>
                                       ^
compilation terminated.
make[2]: *** [opencog/cogserver/server/CMakeFiles/server.dir/CogServer.cc.o] Error 1
make[1]: *** [opencog/cogserver/server/CMakeFiles/server.dir/all] Error 2
make: *** [all] Error 2

**Comment by linas** [comment]
Maybe it is time to abandon ubuntu 14.04? Its now 4.5 years old ... even ubuntu is dropping support for it real soon now .. in April, next year.

**Comment by ngeiswei** [comment]
I'm OK with dropping support for 14.04, personally.

**Comment by Radivarig** [comment]
This happened to me now while building opencog with nix, it depends on atomspace which I built without errors with bare python. The error was gone after adding cython as atomspace dependency

**Comment by linas** [comment]
I think that maybe pull req opencog/atomspace#1932 fixes this. I cannot test, as it appears that I no longer have any containers with Ubuntu 14.04 on them, and I am too lazy to create a new one.  Its not an issue with Debian unstable.

**Comment by linas** [comment]
anyway, thanks @Radivarig it never occured to me to look for a broken cython dependency.
