### ISSUE TITLE
ghost with ecan infinite loop

### ISSUE THREAD

**Issue by Dagiopia** [opencog/opencog#3300]
input with function `ghost TXT` loops forever if the pattern is not found causing the scm shell in cogserver to stuck
https://github.com/opencog/opencog/blob/13e7923371b2bdf8b1c34a82e0d6bfd21b7de3bc/opencog/ghost/ghost.scm#L288
`test-ghost` is nice which returns even if the pattern isn't found.

**Comment by leungmanhin** [comment]
It's related to a request #3251, and unlike `test-ghost`, this ecan based approach wouldn't know if there is no rule in the system that can satisfy the current context, or it just hasn't popped up in the attentional focus yet. I prefer what it used to be though, as getting stuck like this is undesirable.

**Comment by leungmanhin** [comment]
https://github.com/opencog/opencog/pull/3307 removed it

**Comment by Dagiopia** [comment]
that's great!
