### ISSUE TITLE
atomspacepublisher mis-handling of atoms results in crash

### ISSUE THREAD

**Issue by Dagiopia** [opencog/opencog#3303]
the cogserver crashes with the following message in the log when the attention module is loaded after loading the atomspacepublisher
```
[2018-09-13 15:18:14:695] [INFO] Loading module "/usr/local/lib/opencog/modules/libatomspacepublishermodule.so"
[2018-09-13 15:18:14:702] [INFO] [AtomSpacePublisherModule] constructor
[2018-09-13 15:18:14:702] [INFO] Initializing AtomSpacePublisherModule.
[2018-09-13 15:18:16:102] [INFO] Loading module "/usr/local/lib/opencog/libattention.so"
[2018-09-13 15:18:16:129] [ERROR] Not a node! (/home/dagim/opencog/atomspace/opencog/atoms/base/Atom.h:240)
	Stack Trace:
	2: Logger.cc:512	  opencog::Logger::logva(opencog::Logger::Level, char const*, __va_list_tag*)
	3: Logger.cc:524	  opencog::Logger::Error::operator()(char const*, ...)
	4: exceptions.cc:55	  opencog::StandardException::parse_error_message(char const*, __va_list_tag*, bool)
	5: exceptions.cc:82	  opencog::StandardException::parse_error_message(char const*, char const*, __va_list_tag*, bool)
	6: exceptions.cc:142	  opencog::RuntimeException::RuntimeException(char const*, char const*, ...)
	7: Atom.h:240	  opencog::Atom::get_name[abi:cxx11]() const
	8: basic_string.h:109	  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&)
	9: AtomSpacePublisherModule.cc:254	operator()()
	10: [0x26fdd] ??() ??:0
	11: [0x200dc] ??() ??:0
	12: [0x1efd3] ??() ??:0
	13: [0x1aa91] ??() ??:0
	14: [0x1acf9] ??() ??:0
	15: [0x76ba] ??() ??:0
	16: [0x10741d] ??() ??:0
```

I was experimenting with the publisher module so I just went in there to print the message it pushes to the queue and saw the following message:

```
BFD: /usr/lib/x86_64-linux-gnu/libtbb.so.2: warning: loop in section dependencies detected
BFD: /usr/local/lib/opencog/modules/libatomspacepublishermodule.so: warning: loop in section dependencies detected
*** Error in `cogserver': free(): invalid next size (fast): 0x00007ffb30000d90 ***
```

don't understand how it became a bfd issue, checked libatomspacepublisher.so by itself and ~~works fine~~ doesn't work fine. Publishes newly added atoms until a link is added in which case it crashes with a message exactly as the first one above in the log. So publishing Links is what's doing this. 

running ubuntu 16.04
does this happen on anyone else's system?

**Comment by Dagiopia** [comment]
it seems that the problem is when the atomspace publisher module [calls get_name](https://github.com/opencog/opencog/blob/b23078cb47f7109ffe944a7b82832043ea8d0249/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc#L315).

since links don't have a name but a link is just as much an atom as a node, the get_name function returns an exception. 
https://github.com/opencog/atomspace/blob/e965598be2cc44fdcfd7d583a73989a4d3b647e1/opencog/atoms/base/Atom.h#L240

so what should be done here? 
a function called get_name in Link.h that overrides get_name in Atom.h that just returns some constant like the name of the link type?

**Comment by Dagiopia** [comment]
edited the title because the main problem is not being unable to load both atomspacepublisher and attention modules into the cogserver but the fact that atomspacepublisher calls get_name for any Atom type whereas that function only responds to Nodes

**Comment by linas** [comment]
atomspacepublisher is buggy in several different ways. Specifically:

1) It calls functions that throw exceptions, but it fails to catch those exceptions. This is a bug.

2) It should not call `get_name()` on Links. This is just a pointless and stupid thing to do. Links don't have a name.

**Comment by linas** [comment]
The primary issue is that the atomspacepublisher is abandon-ware -- no one uses it for anything, there are no maintainers for it, and so it has fallen into a  state of disrepair.  Do you actually need it for anything, or are you just goofing around with it?  If you actually need it, you will have to invest some time to fix the above two bugs ... and there are probably more bugs than that.

**Comment by Dagiopia** [comment]
> The primary issue is that the atomspacepublisher is abandon-ware -- no one uses it for anything, there are no maintainers for it, and so it has fallen into a state of disrepair. Do you actually need it for anything, or are you just goofing around with it? 

I haven't yet grasped any useful picture of how opencog is built so I'm just browsing around everything till I get something. 

> If you actually need it, you will have to invest some time to fix the above two bugs ... and there are probably more bugs than that.

Didn't know if there was any other module that listened to the signal from the atomtable and exported it to json. If there is another way, I don't need the atomspacepublishermodule to work but if there isn't, I could try

**Comment by Dagiopia** [comment]
> Re: grasping what opencog is: start by reading the wiki about atoms, the atomspace, and the pattern matcher.

Not what is but how it is built. Just needed to know how it was engineered. 

> Re: listening to signals from the atomtable: I really really hate those signals. They have a huge performance overhead. It is best to avoid them.

so they may be removed in the future? 

> Re: json... why? Why is using json somehow better than using scheme? Why would you want to do that?

no particular reason, but was looking at the atoms the attention agents and ghost creates and thought of using the visualizer because seeing them listed there in text wasn't pretty enough so at first attempt, I fell into this bug.

So do you wanna keep the publisher, the signals and the weird json_spirit library sitting  in lib/ or do you want to remove it?  if the latter, this issue needs to be closed.

**Comment by Dagiopia** [comment]
okay, then you don't worry about the publisher... will give it some time next week if I can just so that a non-functional module isn't sitting in there.

**Comment by linas** [comment]
So pull req #3310 actually fixed this bug? I did not see where.

**Comment by Dagiopia** [comment]
just a check for the atom type before calling get_name
https://github.com/opencog/opencog/blob/638a204030decf9109805d7457e65cc306d1d148/opencog/cogserver/modules/events/AtomSpacePublisherModule.cc#L314

**Comment by linas** [comment]
OK. Thanks. With all the tab/space changes, I simply did not notice that one.
