### ISSUE TITLE
libexample_agent.so doesn't exist

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#3325]
[The agents example README](https://github.com/opencog/opencog/tree/master/examples/agents/) asks me to  `opencog> loadmodule examples/agents/libexample_agent.so`, but it turns out that my system has no file with that name (the search didn't find any, in any case).

Am I doing something wrong, or is that particular example obsolete?

**Comment by linas** [comment]
The README should say something like `make examples` first, to make the examples.

Caution: the current agents API is poorly thought out; it needs re-architecting.

**Comment by StrangeTcy** [comment]
That was it, thanks.
