### ISSUE TITLE
Add Python dependencies during ocpkg setup and then check for them during unit test invocation

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#337]
* What method should we use to add additional Python dependencies to ocpkg? (apt-get, pip, virtual environment...)

* What is a good way to confirm that required Python dependencies are installed before CMake causes the associated Python unit tests to be ran?

Previous discussion, quoted from #336:
@cosmoharrigan:
>In regards to new dependencies: I was thinking about Python dependencies recently while working on a separate task, and I was wondering: if we start using the tests/python directory again and re-enable AllPythonModuleTests in tests/python/CMakeLists.txt - what is a good way to confirm that required Python dependencies are installed before CMake causes the associated Python unit tests to be ran?

@keyvan-m-sadeghi: 
>I'm pretty sure that the code in tests/python is obsolete, but it certainly makes sense to have someone update them. I'm not sure how CMake comes into play, but I said in a thread earlier that it may make sense to have a C++ UTest call to Python tests, we could also introduce new flags like test-python or so.

>Regarding the Python dependencies, there are two approaches:

>-- Have OCPKG install python requirements with a flag like --python

>-- create a virtual environment and have it install requirements.txt (included in this patch, but should be refactored to use >= instead of ==)

>Lots to be done in the python-dev section, we're just starting...

**Comment by AmeBel** [comment]
@cosmoharrigan https://github.com/opencog/opencog/pull/1577 and https://github.com/opencog/opencog/pull/1579 replaced the installation of python packges using pip instead of apt. 

@inflector are there means of checking for python packges in cmake?

**Comment by inflector** [comment]
@AmeBel This way:

https://cmake.org/pipermail/cmake/2011-January/041666.html

can probably be adapted to your needs. What are you trying to check in cmake?

**Comment by AmeBel** [comment]
For checking whether a package exists before trying to run a test. Thanks for the pointer, will look at it.

**Comment by linas** [comment]
closing opencog/ocpkg code has moved, I have opened opencog/ocpkg#55 to continue tracking this issue.
