### ISSUE TITLE
monitor_changes blocks CogServer cycle in Embodiment

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#340]
Currently, the OAC portion of Embodiment loads a Python MindAgent called monitor_changes:
https://github.com/opencog/opencog/blob/master/opencog/embodiment/Control/OperationalAvatarController/OAC.cc#L370

And then monitor_changes blocks for 2 to 5 seconds every time it runs:
https://github.com/opencog/opencog/blob/master/opencog/python/monitor_changes.py#L97

Since the current CogServer design does not support multithreaded MindAgents, this will block the CogServer cycle and keep other agents from getting time.

This MindAgent shouldn't behave in that greedy way.

**Comment by linas** [comment]
closing, this code has been removed, and the bug report is no longer applicable
