### ISSUE TITLE
make: *** No rule to make target 'test'. 

### ISSUE THREAD

**Issue by vishal3410** [opencog/opencog#3427]
Hii,
I am trying to build and install opencog from instructions given here:
https://github.com/opencog/opencog,
but after compiling opencog when i am trying to perform unit test using
command `make test`, it gave me the following error:
`make: *** No rule to make target 'test'.`
It also occurs in cogutil, atomspace and moses,
i am using ubuntu 18.04

**Comment by ngeiswei** [comment]
Hi @vishal3410 , maybe you don't have cxxtest installed, can you paste the output of `cmake ..`?

**Comment by vishal3410** [comment]
yeah you are right i do not have cxxtest
and here is output of cmake

`-- Build type: Release
-- CogUtil found.
-- AtomSpace found.
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Boost version 106501 found.
-- cpprest was not found; Distributed version of PatternMiner will not be built.
To over-ride, make sure that the environment variable cpprest_LIBRARY is set.
Installation instructions: https://casablanca.codeplex.com/
-- Cxxtest was not found. Make sure CXXTEST_BIN_DIR is set.
-- CxxTest missing: needed for unit tests.
-- GHC was found.
-- Stack was not found. Haskell bindings will not be built.
-- The Haskell Tool Stack not found.
-- Guile (2.2.3 >= 2.2.2) was found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- link-grammar( >= 5.4.0) was not found. Make sure LINK_GRAMMAR_LIBRARY, LINK_GRAMMAR_INCLUDE_DIR and LINK_GRAMMAR_DATA_DIR are set.
-- Link Grammar missing: needed for NLP.
-- Could NOT find UUID (missing: UUID_LIBRARY UUID_INCLUDE_DIR) 
-- UUID library missing: needed for NLP.
-- Find octomap lib OCTOMAP_LIBRARY-NOTFOUND
-- Find octomath lib OCTOMAP_OCTOMATH_LIBRARY-NOTFOUND
-- Octomap not found
-- Python 3.6.8 interpreter found.
-- Python 3.6.3 libraries found.
-- Cython ( 0.29.3 >= 0.23.0) found.
-- Python install dir: /usr/local/lib/python3.6/dist-packages/opencog
-- Valgrind Prefix: 
-- VALGRIND was found.
-- VALGRIND devel headers found.
-- Checking for module 'jsoncpp'
--   No package 'jsoncpp' found
-- JsonCPP was not found; the AtomSpace Publisher Module needs JsonCPP to publish events in JSON.
If you need to receive AtomSpace events in JSON, install JsonCPP using your package manager 
such as apt or build from source: https://github.com/open-source-parsers/jsoncpp/wiki/Building
-- Looked for Threading Building Blocks in /opt/intel/tbb;/usr/local/include;/usr/include
-- Intel TBB (Threaded Building Blocks) was not found; the AtomSpace Publisher module will not be built. Installation instructions: https://www.threadingbuildingblocks.org/download
-- Required version of ZeroMQ was not found. Make sure the ZMQ_LIBRARY environment variable is set.
-- ZeroMQ was not found; the AtomSpace Publisher module, and the message system used by GUI monitor for OAC will not be built.
To over-ride, make sure that the environment variable ZMQ_LIBRARY is set.
Installation instructions: http://zeromq.org/intro:get-the-software
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Doxygen not found, you won't be able to generate API documentation.

Building for Ubuntu 18.04.1 LTS

The following components will be built:
-----------------------------------------------
   Attention        - Agents for attention allocation dynamics.
   Blopex           - BLOPEX block eigenvalue solver.
   Cython bindings  - Cython (python) bindings.
   Dim. Embedding   - Compute dimensional embedding of the AtomSpace.
   GTK Visualizer   - GTK3-based Atomspace Visualizer.
   Server           - The CogServer.
   PatternMiner     - Pattern Miner.

The following components WILL NOT be built:
-----------------------------------------------
   Doxygen          - Code documentation.
   Python tests     - Python bindings nose tests.
   REST Events      - REST Atomspace Event Publisher module.
   SpaceTime        - 3D Space-Time object tracker.
   Unit tests       - Unit tests.
   NLP              - Natural Language Processing.
   Haskell codes    - Logic via Lojban.

-- Configuring done
-- Generating done
`

**Comment by ngeiswei** [comment]
Unit tests are mentioned in the list of components not to build, so I suppose it is a non-issue. Of course if you think you have a better way to handle that situation your contribution is welcome, but as of now I am gonna consider it solved and close it. Thanks.
