### ISSUE TITLE
contraposition formula is brocken

### ISSUE THREAD

**Issue by noskill** [opencog/opencog#3465]
contraposition rule doesn't work, i think due to use of GroundedSchema instead of GroundedPredicate here: https://github.com/opencog/opencog/blob/8720e19540b0860524082c05503e2be1da454b5c/opencog/pln/rules/propositional/contraposition.scm#L43

```scheme
(use-modules (opencog) (opencog query) (opencog exec))
(use-modules (opencog rule-engine))

(define NBNA
(ImplicationLink
  (NotLink
    (PredicateNode "B" (stv 1.000000 1.000000))
  )
  (NotLink
    (PredicateNode "A" (stv 1.000000 1.000000)) 
  )))

(ImplicationLink (stv 1.000000 1.000000)
  (PredicateNode "A" (stv 1.000000 1.000000)) 
  (PredicateNode "B" (stv 1.000000 1.000000))
)


(define rbs (ConceptNode "URE"))

(ure-set-num-parameter rbs "URE:maximum-iterations" 20)

(cog-bc rbs NBNA)
$3 = (SetLink
   (ImplicationLink
      (NotLink
         (PredicateNode "B" (stv 1 1))
      )
      (NotLink
         (PredicateNode "A" (stv 1 1))
      )
   )
)
```

**Comment by ngeiswei** [comment]
Thanks @noskill.

Indeed that must be the problem. Do you think you can create a PR for it (including a unit test in https://github.com/opencog/opencog/blob/master/tests/pln/rules/PLNRulesUTest.cxxtest)?

If you'd rather not do it, cause say you're too busy with something else, I'm happy to do it, just let me know.

**Comment by ngeiswei** [comment]
Nevermind, @noskill, I'm on it, while it's warm...
