### ISSUE TITLE
Current Captcha to something more meaningful?

### ISSUE THREAD

**Issue by LWFlouisa** [opencog/opencog#3475]
How is anybody suppose to know what you mean by "Knowledge Store", if there is no evidence of a "Knowledge Store" on the website. So I'm left to just kind of assume you mean some programming concept in OpenCog.

Which I could probably find out, if I could actually sign up for the community. There are more valid ways of doing captcha that actually work, and don't piss off otherwise legitimate programmers that otherwise want to contribute.

I even had a fairly meaningful programming question, but never mind that! I'm not even tempted until that issue gets addressed.

Knowledge Store could mean anything from Atomspace, AGI, Artificial Intelligence in general (not AGI), Agora (not something that really has to do with OpenCog, and I'm not even sure why that be the answer.

Don't call it open, if it's a Cottage Industry.

Again I'd ask my questions on the community, if I could even sign up.

It could also mean Array (from the programming concept), but again not intuitive.

**Comment by LWFlouisa** [comment]
I mean is it something where I buy goods and services (like mug), or do you mean a programming concept? It's so vaguely worded, it's nonsensical.

**Comment by linas** [comment]
Yes, we desperately need a better way to explain what opencog is, what it's good for and how to use it. 

By "knowledge store" it is meant:  https://en.wikipedia.org/wiki/Knowledge_base and it applies only to the atomspace.

Examples of which include  https://en.wikipedia.org/wiki/Graph_database although the atomspace is kind-of more general, and also has an unusual structure, compared to things like e.g. grakn.ai

See also https://en.wikipedia.org/wiki/Outline_of_databases and note that the atomspace has aspects of several different kinds of these things. 

I don't know how to explain it more easily than that, and I wish we had someone on the project, someone creative who could figure out how to do this.

The community is primarily mailing-list driven. Join the mailing list.

**Comment by linas** [comment]
"store" as in "storage" not "shop".

**Comment by LWFlouisa** [comment]
Thanks, sorry stressed out a bit.

**Comment by linas** [comment]
> Thanks, sorry stressed out a bit.

So we have a lot in common.
