### ISSUE TITLE
What do I do to join the group?

### ISSUE THREAD

**Issue by LWFlouisa** [opencog/opencog#3476]
Obviously I can't add an additional post indicating I also want to do join. I'm trying to explain my project here.

Some kind of introductory post?

There doesn't seem to be a post in google groups explaining how to do it, is there is a better way of going about it?

I realize I'm largely self-taught, but that shouldn't make a difference in my ability to join.

I'm not getting why rules aren't posted.

**Comment by linas** [comment]
Looks like you joined, but your first three messages were marked as spam. I don't know why.

**Comment by linas** [comment]
Yes, introduce yourself, explain what you think you want to do, etc.

**Comment by LWFlouisa** [comment]
Ah ok that's why. Thanks for the followup!
