### ISSUE TITLE
Module deprecation causes the chatbot to stop working

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#3511]
Try to run `guile run-chatbot.scm` results in the following error message:
>Deprecated module for backward compatibility only, use 'ure' instead

I could probably re-write the relevant parts of the code, but I don't really understand which particular modules is deprecated.

**Comment by linas** [comment]
```
 $ grep -r "backward compatibility on" *
scm/opencog/rule-engine.scm:(display "Deprecated module for backward compatibility only, use 'ure' instead\n")
```
Hmm OK, so
```
grep -r "rule-engine" *
```
I get nothing.  No one seems to actually be using this deprecated code.

When is the last time you did a git pull?

**Comment by ngeiswei** [comment]
To be clear using `rule-engine` instead of `ure` will not break your code, it was just a shorter and more consistent name (python bindings and other functions).

**Comment by StrangeTcy** [comment]
- The sequence was like this: I pulled the code, built opencog, tried to run the chatbot, got a deprecation warning, pulled it again, re-built it, and then it worked. Make of it what you will.

**Comment by linas** [comment]
@StrangeTcy  both the atomspace and opencog experience occasional spurts of development and reorganization and cleanup.  One such spurt has been happening the last few weeks.  I think that explains what you saw.

@ngeiswei FYI, I've been running guile-2.9.2 (master branch) for almost two weeks, and it seems almost(?) twice as fast (for things where atomspace is not the bottleneck) and it survived 10K repetitions of MultiUserUTest over 48 hours with zero errors.  I'm crossing my fingers that it will have better paralleism, too, will see later today. Anyway, that's just FYI if you like to play with such things.
