### ISSUE TITLE
Cython build broken if you don't enable SpaceTime component

### ISSUE THREAD

**Issue by ferrouswheel** [opencog/opencog#3513]
The file `opencog/cython/opencog/cogserver_type_constructors.pyx` assumes that `opencog/spacetime/octomap/octomap_types.pyx` is generated [here](https://github.com/opencog/opencog/blob/master/opencog/cython/opencog/cogserver_type_constructors.pyx#L21).

But this isn't generated when the SpaceTime component is disabled.

Either cython bindings need to be disabled when SpaceTime component is disabled, or some flag needs to be passed to this file to avoid importing the missing file. It wasn't immediately obvious how to pass cmake flags to pyx files, but I'm happy to try to fix it if someone points me in the right direction.

**Comment by linas** [comment]
Does `#ifdef` work with pyx files?  I suppose not, but it's worth a try.

There are two other solutions: 
* generate octomap types, even if spacetime is disabled
* generate  an empty ampty types file if spacetime is disables (i.e. generate octomap_types file from an **empty** `atom_types.script` file.)

Either of the last two seem reasonable. It's presumably easier than trying to figure out how to add conditional compile statement to pyx.

**Comment by linas** [comment]
A third solution -- the long-run solution, is to split out space-time into it's own repo, per issue #3391  

The only reason that the cogserver is loading spacetime types is that it was an "easy hack" back in the day.  Extracting spacetime into it's own stand-alone component would help makke the code more modular.  Of course, this is a larger task than the above fix suggestions...

**Comment by ferrouswheel** [comment]
Opted for the second option as I couldn't find any info about passing a macro definition to influence pyx includes.

**Comment by vsbogd** [comment]
I would just move spacetime server into separate library and export octomap types from it instead of cogserver_types, but leave it in opencog repository.
