### ISSUE TITLE
Use Python 3.6 in Circle CI build

### ISSUE THREAD

**Issue by stellarspot** [opencog/opencog#3532]
Circle CI build uses Python 3.5.

OpenPsiCythonTest requires Python 3.6 where issue [PyGILState_Ensure on non-Python thread causes fatal error](https://bugs.python.org/issue20891) is fixed.
See discussion in https://github.com/opencog/opencog/pull/3517 

OpenCog docker uses Ubuntu:16.04 
https://github.com/opencog/docker/blob/master/opencog/base/Dockerfile

It may require to upgrade the Ubuntu version in docker to 18.04.

**Comment by ferrouswheel** [comment]
I agree that we should upgrade, but we we will run into issues with the default cython version (0.26.1) for Ubuntu 18.04 as explored here: opencog/atomspace#2213 - basically, as I understand it, we are doing stuff cpython and cython don't actually support by repeatedly reinitializing the python interpreter.

**Comment by ferrouswheel** [comment]
The CI docker image has been updated to 3.6 thanks to @AmeBel - :tada:

**Comment by linas** [comment]
closing - comment above suggests this is fixed.
