### ISSUE TITLE
IPython shell doesn't work

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#354]
The IPython shell doesn't work. Execute ```pyshell.shell``` in the CogServer shell and view the output in the CogServer stdout:

```
In [1]: 
Do you really want to exit ([y]/n)? 

'NoneType' object is not callable
```

IPython changed the API for embedded shells:
https://github.com/ipython/ipython/wiki/Cookbook%3a-Updating-code-for-use-with-IPython-0.11-and-later#wiki-Starting_IPython

But even when trying with the new API it fails to stay in the shell.

**Comment by inflector** [comment]
Is this bug still open?

**Comment by inflector** [comment]
So this seems to work for me. The behavior isn't what I'd have expected but it seems to work fine.

Shell 1
```
./opencog/server/cogserver -c ../lib/opencog.conf 
```

If I open a shell in and telnet into the CogServer then do:

Shell 2
```
cogserver> loadpy pyshell
No subclasses of opencog.cogserver.MindAgent found.
Python Requests found: shell.
cogserver>pyshell.shell
```
that causes Shell 1 (aka the CogServer shell) to open an IPython shell where I can:
```
In [2]: atomspace.add_node(types.ConceptNode, "Hello world")
Out[2]: 
(ConceptNode "Hello world" (av 0 0 0) (stv 1.000000 0.000000)) ; [57]
```
Which is what I'd expect it to do with the exception that I was expecting the shell to open in my telnet shell like the "py" and "scm" shells do.

**Comment by inflector** [comment]
I should note that I ran:
```
sudo apt-get install python
```
first to get python installed on Ubuntu 14.04 LTS

**Comment by inflector** [comment]
@cosmoharrigan Can you please try this again and close this if it works for you? And please verify that the shell popping up on the CogServer is the expected behavior?

https://github.com/opencog/opencog/blob/master/opencog/python/pyshell.py#L8 says:
```
# NOTE: it uses the CogServer input/output, not the telnet shell
```
So I imagine the above behavior is what was meant by "uses the CogServer input/output"

**Comment by cosmoharrigan** [comment]
Thanks @inflector, the functionality works for me now.
