### ISSUE TITLE
MicroplanningUTest and SuRealUTest fail

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#3544]
From the test log, looks like SuReal fails to even generate a very simple sentence, and it fails when it's trying to match the disjuncts between two words, e.g. he <-> she, runs <-> eats as in the first test, which is very strange... and it has started failing when I switch to using Link Grammar 5.6.1.

@linas is there any change in 5.6.1 that may give words a different set of disjuncts or something like that?

BTW since the Microplanner uses SuReal, I believe fixing SuRealUTest will also "fix" the MicroplanningUTest.

**Comment by linas** [comment]
Link-grammar gets dictionary updates pretty much every release.  h/she runs/eats is pretty basic, so it is hard to imagine what would have changed that ... the fixes tend to be fore rather rare, obscure, arcane sentence constructions.

**Comment by stellarspot** [comment]
Here is the sureal example, which works with link-grammar-5.6.0 and does not work with the link-grammar-5.6.1:

```scheme
(use-modules
 (opencog)
 (opencog nlp)
 (opencog nlp sureal)
 (opencog nlp chatbot)
 (opencog nlp relex2logic))

(nlp-parse "He eats.")
(nlp-parse "She eats quickly.")
(nlp-parse "Nobody drank it.")
(nlp-parse "It drinks water.")

(display
 (sureal
  (SetLink
   (EvaluationLink
    (PredicateNode "drink")
    (ListLink (ConceptNode "she"))))))

(newline)

(display
 (sureal
  (SetLink
   (EvaluationLink
    (PredicateNode "drink")
    (ListLink (ConceptNode "she")))
   (InheritanceLink
    (PredicateNode "drink")
    (DefinedLinguisticConceptNode "past")))))
```
The output with the link-grammar-5.6.0:
```
((she drinks .))
((she drank it .))
```

The output with the link-grammar-5.6.1:
```
()
()
```

**Comment by stellarspot** [comment]
I run the SuRealUTest::test_basic(void) and printed `(cog-incoming-by-type WORD 'LgDisjunct)` in the `lg-dict-entry` method for words `eats` and `she` for  link-grammar-5.6.0 and link-grammar-5.6.1.

The output is quite different.
The shortest  `LgDisjunct` links for word `she` for  link-grammar-5.6.0
```
 (LgDisjunct
   (WordNode "she")
   (LgConnector
      (LgConnectorNode "SJls")
      (LgConnDirNode "+")
   )
)
 (LgDisjunct
   (WordNode "she")
   (LgConnector
      (LgConnectorNode "Ss")
      (LgConnDirNode "+")
   )
)
 (LgDisjunct
   (WordNode "she")
   (LgConnector
      (LgConnectorNode "SIs")
      (LgConnDirNode "-")
   )
)
```
The shortest  `LgDisjunct` links for word `she` for  link-grammar-5.6.1

```
 (LgDisjunct
   (WordNode "she")
   (LgConnector
      (LgConnectorNode "SIs")
      (LgConnDirNode "-")
   )
)
 (LgDisjunct
   (WordNode "she")
   (LgConnector
      (LgConnectorNode "Ss")
      (LgConnDirNode "+")
   )
)
```

The output for word `she` for  link-grammar-5.6.1  contains much less `LgDisjunct` links than the output for  link-grammar-5.6.0.

**Comment by linas** [comment]
So:
```
link-parser ./link-grammar-5.6.1/data/en/4.0.dict
link-grammar: Info: Dictionary version 5.6.1, locale en_US.UTF-8
linkparser> !!she
Token "she" matches:
    she                              44  disjuncts


Token "she" expressions:
    she                        {[[R+ & Bs+]]} & (({MXs+} & Ss+ & {({@hCOd-} & (C- or ((RJrc- or RJlc+)))) or ({@hCO-} & Wd-) or [Rn-]}) or SIs- or SJls+)
```
and if I do this for 5.6.0, I get exactly the same thing. And for version 5.5.1, and I have to go back to 5.4.3 to get something smaller:
```
Token "she" expressions:
    she                        {[[R+ & Bs+]]} & ((Ss+ & {({@COd-} & (C- or ((RJrc- or RJlc+)))) or ({@CO-} & Wd-) or [Rn-]}) or SIs- or SJls+)
```
There are two differences: the `MX+` which allows the parse of "she, angry at Fred, turned away" which the earlier dictionaries failed on.

The other difference is the head/tail indicator on `CO`.

Both have S, SI and SJ.  Hard to see how this makes a difference.

**Comment by linas** [comment]
Also, drink, drinks, drank, eats, it, nobody and water are the same. "quickly" differs. The newer quickly has more disjuncts.

**Comment by linas** [comment]
Even if I explicitly enter `(nlp-parse "She drinks")` and `(nlp-parse "She drank it")` it still doesn't work. By explicitly adding these two sentences, everything needed to satisfy the relations would seem to be in place ...

**Comment by leungmanhin** [comment]
As @stellarspot noted, when doing `(lg-dict-entry (Word "she"))`:
```
 (LgDisjunct
   (WordNode "she")
   (LgConnector
      (LgConnectorNode "SJls")
      (LgConnDirNode "+")
   )
)
```
is really missing when 5.6.1 is used.

Meanwhile as @linas noted, when doing `!!she` in link-parser 5.6.1 it gives:
```
Token "she" expressions:
    she                        {[[R+ & Bs+]]} & (({MXs+} & Ss+ & {({@hCOd-} & (C- or ((RJrc- or RJlc+)))) or ({@hCO-} & Wd-) or [Rn-]}) or SIs- or SJls+)
```
which does contain `SJls+`, so it means the dictionary entry is not correctly loaded?

**Comment by stellarspot** [comment]
The "she" expression looks the same for the 
link-grammar-5.6.0:
```
<clause-conjoin>: RJrc- or RJlc+;
<CLAUSE>:   {({@hCOd-} & (C- or <clause-conjoin>)) or ({@hCO-} & Wd-) or [Rn-]};
she he:
  {[[R+ & Bs+]]} & (({MXs+} & Ss+ & <CLAUSE>) or SIs- or SJls+);
```
and link-grammar-5.6.1:
```
<clause-conjoin>: RJrc- or RJlc+;
<CLAUSE>:   {({@hCOd-} & (C- or <clause-conjoin>)) or ({@hCO-} & Wd-) or [Rn-]};
she he:
  {[[R+ & Bs+]]} & (({MXs+} & Ss+ & <CLAUSE>) or SIs- or SJls+);
```

I printed the Exp_struct  string and direction from the LGDictExpContainer constructor and got:
link-grammar-5.6.0:
```
opencog::getDictEntry word: she
LGDictExpContainer::LGDictExpContainer expression: R+
LGDictExpContainer::LGDictExpContainer expression: Bs+
LGDictExpContainer::LGDictExpContainer expression: MXs+
LGDictExpContainer::LGDictExpContainer expression: Ss+
LGDictExpContainer::LGDictExpContainer expression: hCOd-
LGDictExpContainer::LGDictExpContainer expression: C-
LGDictExpContainer::LGDictExpContainer expression: RJrc-
LGDictExpContainer::LGDictExpContainer expression: RJlc+
LGDictExpContainer::LGDictExpContainer expression: hCO-
LGDictExpContainer::LGDictExpContainer expression: Wd-
LGDictExpContainer::LGDictExpContainer expression: Rn-
LGDictExpContainer::LGDictExpContainer expression: SIs-
LGDictExpContainer::LGDictExpContainer expression: SJls+
((she eats .))
```

link-grammar-5.6.1:
```
opencog::getDictEntry word: she
LGDictExpContainer::LGDictExpContainer expression: R+
LGDictExpContainer::LGDictExpContainer expression: Bs+
LGDictExpContainer::LGDictExpContainer expression: MXs+
LGDictExpContainer::LGDictExpContainer expression: Ss+
LGDictExpContainer::LGDictExpContainer expression: SIs-
()
```

It seems that the expressions from the `<CLAUSE>` and `SJls+` are not put to LGDictExpContainer for some reason.

**Comment by stellarspot** [comment]
This is the result of printing the expression tree in the way how the `LGDictExpContainer lg_exp_to_container(Exp* exp)` method parses it:
link-grammar-5.6.0:
```
AND
 OR
  AND
  AND
   CONNECTOR  R+
   CONNECTOR  Bs+
 OR
  AND
   OR
    AND
    CONNECTOR  MXs+
   CONNECTOR  Ss+
   OR
    AND
    AND
     OR
      AND
      CONNECTOR  hCOd-
     OR
      CONNECTOR  C-
      AND
       OR
        CONNECTOR  RJrc-
        CONNECTOR  RJlc+
    AND
     OR
      AND
      CONNECTOR  hCO-
     CONNECTOR  Wd-
    CONNECTOR  Rn-
  CONNECTOR  SIs-
  CONNECTOR  SJls+
```

link-grammar-5.6.1:
```
AND
 OR
  AND
  AND
   CONNECTOR  R+
   CONNECTOR  Bs+
 OR
  AND
   OR
    AND
    CONNECTOR  MXs+
   CONNECTOR  Ss+
  CONNECTOR  SIs-
```

**Comment by linas** [comment]
LG exports a function to print expressions. So:
```
--- a/opencog/nlp/lg-dict/LGDictReader.cc
+++ b/opencog/nlp/lg-dict/LGDictReader.cc
@@ -38,6 +38,7 @@ using namespace opencog;
  */
 static LGDictExpContainer lg_exp_to_container(Exp* exp)
 {
+printf("got this %s\n", expression_stringify(exp));
     if (CONNECTOR_type == exp->type)
         return LGDictExpContainer(CONNECTOR_type, exp);

```
prints this:
```

scheme@(guile-user)> (use-modules (opencog) (opencog nlp) (opencog nlp lg-dict))
scheme@(guile-user)>    (use-modules (opencog exec))scheme@(guile-user)> (cog-execute! (LgDictEntry (WordNode "she")(LgDictNode "en")))
got this {[[R+ & Bs+]]} & (({MXs+} & Ss+ & {({@hCOd-} & (C- or ((RJrc- or RJlc+)))) or ({@hCO-} & Wd-) or [Rn-]}) or SIs- or SJls+)
got this {[[R+ & Bs+]]}
got this ()
got this [[R+ & Bs+]]
got this R+
got this Bs+
got this ({MXs+} & Ss+ & {({@hCOd-} & (C- or ((RJrc- or RJlc+)))) or ({@hCO-} & Wd-) or [Rn-]}) or SIs- or SJls+
got this {MXs+} & Ss+ & {({@hCOd-} & (C- or ((RJrc- or RJlc+)))) or ({@hCO-} & Wd-) or [Rn-]}
got this {MXs+}
got this ()
got this MXs+
got this Ss+
got this SIs-
$1 = (WordNode "she")
```
so there is some kind of recursion happening, but its incomplete.

**Comment by linas** [comment]
I don't think LG changed. I think the opencog code was always broken, and unrelated LG changes exposed the opencog bug.

**Comment by linas** [comment]
FYI I've got a fix. The fix is to simplify `lg_exp_to_container` to its bare minimum.
