### ISSUE TITLE
Manipulating Atoms in Python3   import satisfying_set error

### ISSUE THREAD

**Issue by hanimunir** [opencog/opencog#3558]
getting this error in Pattern matching in python

from opencog.bindlink import satisfying_set
ImportError: cannot import name satisfying_set

help needed

**Comment by linas** [comment]
I'm guessing that `satisfying_set` is obsolete. I'm guessing you need to say `execute_atom(... getlink...)`

`GetLink`  is used to specify a pattern, and when you execute it, if finds everything that satisfies that pattern.

If ther's documentation talking about a python `satsifying_set` it needs to be removed/updated.

**Comment by hanimunir** [comment]
i trying code from this link:  https://wiki.opencog.org/w/Manipulating_Atoms_in_Python
code:
#Create a pattern to look for color nodes
In [30]: varlink = TypedVariableLink(VariableNode("$xcol"), TypeNode("ConceptNode"))
In [31]: pattern = InheritanceLink(VariableNode("$xcol"), color)
In [32]: colornodes = GetLink(varlink, pattern)

#Now run the function to find all color nodes
In [33]:  satisfying_set(atsp, colornodes)

**Comment by linas** [comment]
try using `execute_atom` and see if that makes it work.

**Comment by AlucardNosferatu** [comment]
It works.
Thanks.
> try using `execute_atom` and see if that makes it work.

**Comment by linas** [comment]
I fixed the wiki. Closing
