### ISSUE TITLE
paternminer dead code still in tree

### ISSUE THREAD

**Issue by linas** [opencog/opencog#3588]
The `tests/miner` directory is non-empty, but probably should not exist, right @ngeiswei

**Comment by ngeiswei** [comment]
Indeed, thanks.

**Comment by linas** [comment]
Wait, there's more!  the `opencog/miner` directory, too!

**Comment by ngeiswei** [comment]
What gives you the right to insinua... Oh, you're right, thanks.

**Comment by ngeiswei** [comment]
I think it's all gone now.
