### ISSUE TITLE
Is the code in python dir abaondoned?

### ISSUE THREAD

**Issue by linas** [opencog/opencog#3599]
I'm not sure, but  believe that all of the code in the directory `opencog/python` is abandoned; is that correct?  Can it be removed? Any objections to that?

This is in regards to general janitorial cleanup per issue #3391

**Comment by AmeBel** [comment]
I know https://github.com/opencog/opencog/tree/master/opencog/python/web/api is used.

**Comment by linas** [comment]
Never mind. About half the directories there look interesting, the other half seem to be undocumented snapshots of stuff. I moved it all to an `attic` directory, with #3600 (all except the web api, which I left as-is). The attic allows anyone to browse the code, and revive it if it seems interesting, but otherwise gets it out of the way and minimizes the mental effort to grok what's in opencog.
