### ISSUE TITLE
Opencog build fails when CogServer is not installed

### ISSUE THREAD

**Issue by AlucardNosferatu** [opencog/opencog#3611]
While running make -j4:
CogServer.h: no such file or directory
I will append further information later

**Comment by AlucardNosferatu** [comment]
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_attentionbank
Scanning dependencies of target SCM_CONFIG
Scanning dependencies of target attention_atom_types
Scanning dependencies of target neighbors
[  0%] Built target SCM_CONFIG
[  2%] Generating opencog types
[  2%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_attentionbank
Scanning dependencies of target cogita
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_scm
-- Atom type name: AttentionValue AttentionValue
-- Atom type name: HebbianLink Hebbian
-- Atom type name: AsymmetricHebbianLink AsymmetricHebbian
-- Atom type name: SymmetricHebbianLink SymmetricHebbian
-- Atom type name: InverseHebbianLink InverseHebbian
-- Atom type name: SymmetricInverseHebbianLink SymmetricInverseHebbian
[  2%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_scm
[  2%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/CogitaConfig.cc.o
[  4%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/IRC.cc.o
[  4%] Built target attention_atom_types
[  6%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/go-irc.cc.o
[  6%] Building CXX object opencog/neighbors/CMakeFiles/neighbors.dir/GetPredicates.cc.o
[  6%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/whirr-sockets.cc.o
[  8%] Building CXX object opencog/neighbors/CMakeFiles/neighbors.dir/Neighbors.cc.o
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_sentiment
[  8%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_sentiment
[ 10%] Linking CXX executable cogita
Scanning dependencies of target nlp_atom_types
[ 12%] Generating opencog types
-- Atom type name: WordNode Word
-- Atom type name: AnyNode Any
-- Atom type name: WordClassNode WordClass
-- Atom type name: ReferenceLink Reference
-- Atom type name: ActionLink Action
-- Atom type name: DocumentNode Document
-- Atom type name: SentenceNode Sentence
-- Atom type name: SentenceLink Sentence
-- Atom type name: ParseNode Parse
-- Atom type name: ParseLink Parse
-- Atom type name: WordInstanceNode WordInstance
-- Atom type name: WordInstanceLink WordInstance
-- Atom type name: UtteranceNode Utterance
-- Atom type name: DialogNode Dialog
-- Atom type name: PhraseNode Phrase
-- Atom type name: AtTimeLink AtTime
-- Atom type name: TimeNode Time
-- Atom type name: SequenceLink Sequence
-- Atom type name: WordSequenceLink WordSequence
-- Atom type name: SentenceSequenceLink SentenceSequence
-- Atom type name: DocumentSequenceLink DocumentSequence
-- Atom type name: FeatureNode Feature
-- Atom type name: FeatureLink Feature
-- Atom type name: LinkGrammarRelationshipNode LinkGrammarRelationship
-- Atom type name: DefinedLinguisticConceptNode DefinedLinguisticConcept
-- Atom type name: DefinedLinguisticPredicateNode DefinedLinguisticPredicate
-- Atom type name: DefinedLinguisticRelationshipNode DefinedLinguisticRelationship
-- Atom type name: PrepositionalRelationshipNode PrepositionalRelationship
-- Atom type name: WordSenseNode WordSense
-- Atom type name: WordSenseLink WordSense
-- Atom type name: PartOfSpeechNode PartOfSpeech
-- Atom type name: PartOfSpeechLink PartOfSpeech
-- Atom type name: LemmaNode Lemma
-- Atom type name: LemmaLink Lemma
-- Atom type name: HolonymLink Holonym
-- Atom type name: TenseNode Tense
-- Atom type name: TenseLink Tense
-- Atom type name: CosenseLink Cosense
-- Atom type name: SemeNode Seme
-- Atom type name: SemanticRelationNode SemanticRelation
-- Atom type name: InterpretationNode Interpretation
-- Atom type name: InterpretationLink Interpretation
-- Atom type name: SpecificEntityNode SpecificEntity
-- Atom type name: LgDictNode LgDict
-- Atom type name: LgHaveDictEntry LgHaveDictEntry
-- Atom type name: LgDictEntry LgDictEntry
-- Atom type name: LgParseLink LgParse
-- Atom type name: LgParseMinimal LgParseMinimal
-- Atom type name: LgConnectorNode LgConnector
-- Atom type name: LgConnMultiNode LgConnMulti
-- Atom type name: LgConnDirNode LgConnDir
-- Atom type name: LgConnector LgConnector
-- Atom type name: LgSeq LgSeq
-- Atom type name: LgAnd LgAnd
-- Atom type name: LgOr LgOr
-- Atom type name: LgWordCset LgWordCset
-- Atom type name: LgDisjunct LgDisjunct
-- Atom type name: LgLinkInstanceNode LgLinkInstance
-- Atom type name: LgLinkInstanceLink LgLinkInstance
-- Atom type name: SetTypeLink SetType
-- Atom type name: SetSizeLink SetSize
-- Atom type name: MyNotLink MyNot
-- Atom type name: MyOrLink MyOr
[ 12%] Built target nlp_atom_types
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_aiml
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_aiml
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_chatbot
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_chatbot
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_chatbot-psi
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_chatbot-psi
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_fuzzy
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_fuzzy
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_lg-dict
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_lg-dict
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_lg-parse
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_lg-parse
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_microplanning
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_microplanning
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_relex2logic
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_relex2logic
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_relex2logic_loader
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_relex2logic_loader
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_relex2logic_rules
[ 12%] Built target cogita
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_sureal
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_sureal
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_eva_behavior
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_eva_behavior
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_eva_model
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_eva_model
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_eva_chatbot-eva
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_eva_chatbot-eva
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_openpsi
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_openpsi
Scanning dependencies of target openpsi
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_relex2logic_rules
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_openpsi_dynamics
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_openpsi_dynamics
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_ghost
[ 12%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_ghost
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_ghost_procedures
[ 14%] Building CXX object opencog/openpsi/CMakeFiles/openpsi.dir/OpenPsiSatisfier.cc.o
[ 14%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_ghost_procedures
[ 16%] Building CXX object opencog/openpsi/CMakeFiles/openpsi.dir/OpenPsiImplicator.cc.o
[ 20%] Building CXX object opencog/openpsi/CMakeFiles/openpsi.dir/OpenPsiRules.cc.o
[ 20%] Linking CXX static library libneighbors.a
[ 20%] Building CXX object opencog/openpsi/CMakeFiles/openpsi.dir/OpenPsiSCM.cc.o
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln
[ 20%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_propositional
[ 20%] Built target neighbors
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_term
[ 20%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_propositional
[ 20%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_term
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_predicate
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_wip
[ 20%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_predicate
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_meta-rules_predicate
[ 20%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_meta-rules_predicate
Scanning dependencies of target attention-types
[ 20%] Building CXX object opencog/attentionbank/types/CMakeFiles/attention-types.dir/atom_types_init.cc.o
[ 22%] Linking CXX shared library libattention-types.so
[ 22%] Built target attention-types
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_attentionbank_types
[ 22%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_attentionbank_types
[ 22%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_pln_rules_wip
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_types
Scanning dependencies of target nlp-types
[ 22%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__home_scrooge_opencog_opencog_nlp_types
[ 22%] Building CXX object opencog/nlp/types/CMakeFiles/nlp-types.dir/NLPTypes.cc.o
Scanning dependencies of target attentionval
[ 26%] Building CXX object opencog/attentionbank/avalue/CMakeFiles/attentionval.dir/AttentionValueOfLink.cc.o
[ 26%] Building CXX object opencog/attentionbank/avalue/CMakeFiles/attentionval.dir/AttentionValue.cc.o
[ 28%] Linking CXX shared library libopenpsi.so
[ 28%] Built target openpsi
[ 30%] Linking CXX shared library libnlp-types.so
[ 32%] Cythonizing openpsi.pyx
[ 34%] Built target nlp-types
Scanning dependencies of target wsd
[ 34%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o
Scanning dependencies of target lg-dict-entry
[ 36%] Building CXX object opencog/nlp/lg-dict/CMakeFiles/lg-dict-entry.dir/LGDictExpContainer.cc.o
[ 36%] Linking CXX shared library libattentionval.so
[ 36%] Built target attentionval
[ 36%] Building CXX object opencog/nlp/lg-dict/CMakeFiles/lg-dict-entry.dir/LGDictReader.cc.o
[ 38%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeUtils.cc.o
Scanning dependencies of target openpsi_cython
[ 38%] Building CXX object opencog/cython/opencog/CMakeFiles/openpsi_cython.dir/openpsi.cpp.o
[ 40%] Building CXX object opencog/nlp/lg-dict/CMakeFiles/lg-dict-entry.dir/LGDictUtils.cc.o
[ 42%] Building CXX object opencog/nlp/lg-dict/CMakeFiles/lg-dict-entry.dir/LGDictNode.cc.o
[ 44%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/Mihalcea.cc.o
[ 46%] Building CXX object opencog/nlp/lg-dict/CMakeFiles/lg-dict-entry.dir/LGDictEntry.cc.o
[ 48%] Linking CXX shared library openpsi.so
[ 48%] Built target openpsi_cython
Scanning dependencies of target attentionbonk
[ 48%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/MihalceaEdge.cc.o
[ 48%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/AFImplicator.cc.o
[ 50%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/MihalceaLabel.cc.o
[ 50%] Linking CXX shared library liblg-dict-entry.so
[ 50%] Built target lg-dict-entry
Scanning dependencies of target lg-dict
[ 50%] Building CXX object opencog/nlp/lg-dict/CMakeFiles/lg-dict.dir/LGDictSCM.cc.o
[ 52%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/AtomBins.cc.o
[ 54%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/NNAdjust.cc.o
[ 56%] Linking CXX shared library liblg-dict.so
[ 56%] Built target lg-dict
Scanning dependencies of target lg-parse
[ 58%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/ParseRank.cc.o
[ 60%] Building CXX object opencog/nlp/lg-parse/CMakeFiles/lg-parse.dir/LGParseLink.cc.o
[ 62%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/AttentionalFocusCB.cc.o
[ 62%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/ReportRank.cc.o
[ 64%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseCache.cc.o
[ 66%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/AttentionBank.cc.o
[ 68%] Linking CXX shared library liblg-parse.so
[ 68%] Built target lg-parse
[ 68%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/AttentionSCM.cc.o
Scanning dependencies of target sureal
[ 70%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseRank.cc.o
[ 72%] Building CXX object opencog/nlp/sureal/CMakeFiles/sureal.dir/SuRealCache.cc.o
/home/scrooge/opencog/opencog/nlp/wsd/SenseRank.cc:20:48: fatal error: opencog/cogserver/server/CogServer.h: No such file or directory
compilation terminated.
opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:278: recipe for target 'opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseRank.cc.o' failed
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/SenseRank.cc.o] Error 1
CMakeFiles/Makefile2:1145: recipe for target 'opencog/nlp/wsd/CMakeFiles/wsd.dir/all' failed
make[1]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 72%] Building CXX object opencog/nlp/sureal/CMakeFiles/sureal.dir/SuRealSCM.cc.o
[ 74%] Building CXX object opencog/nlp/sureal/CMakeFiles/sureal.dir/SuRealPMCB.cc.o
[ 76%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/AVUtils.cc.o
[ 78%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/ImportanceIndex.cc.o
[ 78%] Building CXX object opencog/attentionbank/bank/CMakeFiles/attentionbonk.dir/StochasticImportanceDiffusion.cc.o
[ 80%] Linking CXX shared library libattentionbonk.so
[ 80%] Built target attentionbonk
[ 82%] Linking CXX shared library libsureal.so
[ 82%] Built target sureal
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AlucardNosferatu** [comment]
Ok,Now I know the CogServer is a deprecated module in another repo:
[https://github.com/opencog/cogserver/tree/master/opencog](url)
I will try copy and paste the source code files of this directory and retry, if it is ok, I will close this issue.

**Comment by AlucardNosferatu** [comment]
Building is successful with pasted source code files.

**Comment by vsbogd** [comment]
Issue makes sense anyway, opencog cmake script checks that CogServer is present: https://github.com/opencog/opencog/blob/1bad174817335c8c1be43461c1858cb4ef23ee9d/CMakeLists.txt#L171-L178
So it should also exclude from build parts which require CogServer when CogServer is absent.

**Comment by AlucardNosferatu** [comment]
> Issue makes sense anyway, opencog cmake script checks that CogServer is present:
> 
> https://github.com/opencog/opencog/blob/1bad174817335c8c1be43461c1858cb4ef23ee9d/CMakeLists.txt#L171-L178
> 
> 
> So it should also exclude from build parts which require CogServer when CogServer is absent.

You are right, this can solve the problem once and for all

**Comment by linas** [comment]
Yeah, I had failed to test what happens if cogserver was not installed.

Pull req #3612 should fix this.

The cogserver is NOT deprecated!  It is very much alive and well, and often quite useful to have around.  It was split out to make the project more modular, less spaghetti-code-ified. It also allows for competing, alternative servers to be developed.

**Comment by AlucardNosferatu** [comment]
> Yeah, I had failed to test what happens if cogserver was not installed.
> 
> Pull req #3612 should fix this.
> 
> The cogserver is NOT deprecated! It is very much alive and well, and often quite useful to have around. It was split out to make the project more modular, less spaghetti-code-ified. It also allows for competing, alternative servers to be developed.

https://wiki.opencog.org/w/CogServer

![Screenshot from 2019-09-13 23-04-51](https://user-images.githubusercontent.com/10172485/64873076-f10c9a80-d67a-11e9-8126-1ec270796314.png)

Sorry, maybe I misunderstood the first line of this wiki page...

**Comment by AlucardNosferatu** [comment]
> Yeah, I had failed to test what happens if cogserver was not installed.
> 
> Pull req #3612 should fix this.
> 
> The cogserver is NOT deprecated! It is very much alive and well, and often quite useful to have around. It was split out to make the project more modular, less spaghetti-code-ified. It also allows for competing, alternative servers to be developed.

Thx for the pull request, Thank you.

**Comment by linas** [comment]
Oh I wrote that wiki page. Maybe I should review it.

Turns out that the network server provide by the cogserver is faster, more efficient, more scalable than the toy server you can get with guile. (And I haven't found a server for python, but did not look).

The "mind-agents" part of it is ... crap, and needs a total overhaul.

**Comment by linas** [comment]
Closing, both the fix and the wiki page have been updated.
