### ISSUE TITLE
Conflict between `cogserver` and `opencog` repos

### ISSUE THREAD

**Issue by glicerico** [opencog/opencog#3615]
There is a conflict between the building and installation of the `opencog` and `cogserver` repos.
If cogserver is built+installed first and `opencog` later, then one cannot call the `cogserver`:
> Unbound variable: start-cogserver

If `cogserver` is built+installed after `opencog`, `cogserver` works fine, but there's a problem with the lg parser:
> opencog/nlp/lg-parse.scm:8:0: In procedure module-lookup: Unbound variable: opencog-ext-path-lg-parse

**Comment by glicerico** [comment]
Potential fix at: https://github.com/opencog/cogserver/compare/master...glicerico:oc-config_conflict?expand=1

**Comment by linas** [comment]
merged; doe sit fix it?

**Comment by glicerico** [comment]
Yes
