### ISSUE TITLE
PLNRulesUTest fails

### ISSUE THREAD

**Issue by vsbogd** [opencog/opencog#3619]
After merge variable renaming into `opencog/atomspace/master` `PLNRulesUTest` failed, see build results: https://circleci.com/gh/opencog/atomspace/3722
[test.log](https://github.com/opencog/opencog/files/3850903/test.log)

**Comment by linas** [comment]
?? after merge of what?  The last two merges opencog/atomspace#2368 and opencog/atomspace#2367 both pass ...

**Comment by ngeiswei** [comment]
It passes on my system.

**Comment by vsbogd** [comment]
> ?? after merge of what? The last two merges opencog/atomspace#2368 and opencog/atomspace#2367 both pass ...

I am not sure it is a consequence of specific merge. It may be sporadic failure or failure under specific conditions.

> It passes on my system.

@ngeiswei , have you tried to run it in infinite loop? Sometimes it fails after few successful passes.

**Comment by ngeiswei** [comment]
Out of 150 it failed once, unfortunately I didn't save the log. Will try some more, meanwhile, @vsbogd if you happen to have the log feel free to post it here.

**Comment by vsbogd** [comment]
@ngeiswei , I have added link to the log from CircleCI job at the issue description see https://github.com/opencog/opencog/files/3850903/test.log. Not sure if you meant this log. 

Unfortunately I didn't have time to try reproducing it so far, I just started receiving e-mails from CircleCI about build failures and raised the issue.

**Comment by ngeiswei** [comment]
Interesting, it looks like it is a manifestation if that issue https://github.com/opencog/atomspace/issues/2371

**Comment by vsbogd** [comment]
I see that `atomspace/master` is green since https://github.com/opencog/atomspace/pull/2366
@ngeiswei , do you have explanation why it is dup of https://github.com/opencog/atomspace/issues/2371 ? If so we can close it as duplicate.

**Comment by ngeiswei** [comment]
It's not exactly a duplicate but I guess the PLN rule being tested is using a similar query. The output clearly looked like some permutation was missing. So I think yes we can close.
