### ISSUE TITLE
cannot find -lBoost::filesystem

### ISSUE THREAD

**Issue by Haylemicheal** [opencog/opencog#3629]
/usr/bin/ld: cannot find -lBoost::filesystem
/usr/bin/ld: cannot find -lBoost::system
collect2: error: ld returned 1 exit status
opencog/nlp/types/CMakeFiles/nlp-types.dir/build.make:118: recipe for target 'opencog/nlp/types/libnlp-types.so' failed
make[2]: *** [opencog/nlp/types/libnlp-types.so] Error 1
CMakeFiles/Makefile2:873: recipe for target 'opencog/nlp/types/CMakeFiles/nlp-types.dir/all' failed
make[1]: *** [opencog/nlp/types/CMakeFiles/nlp-types.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

I got the above error while i was building opencog manually. I tried by installing libboost-all-dev using apt-get and I tried by compiling it from the source but it couldn't solve the problem.

**Comment by linas** [comment]
Try starting again, cleanly. So `rm -r` the build dir. 

There are two problems: First, `Boost::filesystem` is not the name of a library, so the linker flag `-lBoost::filesystem` is insane. Which means that line 118 of `opencog/nlp/types/CMakeFiles/nlp-types.dir/build.make` is insanely wrong... so somehow, cmake generated a broken makefile.  How did that happen? I don't know.

The second problem is that `libnlp-types.so` does not depend on boost in any  way, for any reason. 

Boost is used only two places: to read config files, and in the python code. Almost nothing uses config files any more, except for the cogserver and some unit tests.  And there's no python code in the nlp side of things.

**Comment by Haylemicheal** [comment]
Thank you for your response, I tried it but the error still exist!

**Comment by linas** [comment]
There are other people in iCog labs that know how to build opencog; try working with them? 

The other possibility is to debug it yourself... why is the contents of the makefile so obvoiusly broken?  Did you change something? Do you have current version of cmake, or are you on some old system?  Look at the makefile, and see why the libraries are wrong ... is there a missing quotation? Missing whitespace?   Where there any earlier errors or warnings that you ignored?  All of the earlier parts should build and install without any errors or warnings.

**Comment by ngeiswei** [comment]
@Haylemicheal what is your system? OS, cmake, gcc and boost versions?

**Comment by Haylemicheal** [comment]
I am using Ubuntu 18.04. The cmake version is 3.15.7. I have a gcc version of 7.4.0 and I have 1.65 boost version

**Comment by Haylemicheal** [comment]
Thank you very much, It works!
