### ISSUE TITLE
Wrong type of atoms returned when using 'get_atoms_by_type' in Python

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#3644]
To reproduce:

```python
from opencog.atomspace import AtomSpace, types
from opencog.type_constructors import *
from opencog.utilities import initialize_opencog

atomspace = AtomSpace()
initialize_opencog(atomspace)

a = ConceptNode("A")
b = ConceptNode("B")
InheritanceLink(a, b)
SubsetLink(a, b)

atomspace.get_atoms_by_type(types.InheritanceLink)
```

I would expect only `InheritanceLink` is returned but I got `SubsetLink` as well:
```
[(InheritanceLink
  (ConceptNode "A") ; [60d59ca6ac01b2bb][1]
  (ConceptNode "B") ; [35af63e46de76d9][1]
) ; [f8e5cdd55c493426][1], (SubsetLink
  (ConceptNode "A") ; [60d59ca6ac01b2bb][1]
  (ConceptNode "B") ; [35af63e46de76d9][1]
) ; [ebc63a8bc4478577][1]]
```

**Comment by noskill** [comment]
SubsetLink is a InheritanceLink. If you don't want subtypes run get_atoms_by_type with  subtype=False

**Comment by linas** [comment]
Closing, this seems to be not-a-bug, per last comment.

**Comment by leungmanhin** [comment]
Just to add one comment, there is also a Scheme version of this function (`cog-get-atoms`) and by default it doesn't return any subtypes of the atom type being queried (and it seems more intuitive that way). It would be better if we have consistent APIs across different bindings?

**Comment by linas** [comment]
> t would be better if we have consistent API

Yes, it would be. I'd happily merge such a pull req, if @noskill has no objections.

**Comment by noskill** [comment]
@linas Sure, i have no objection to changing scheme api.

**Comment by linas** [comment]
No we are not changing the scheme API. There is too much code that uses it as it is. No one uses the Python API for anything .. change the python.
