### ISSUE TITLE
wont compile will these errors

### ISSUE THREAD

**Issue by manisabri** [opencog/opencog#3667]
opencog/opencog/nlp/lg-dict/LGDictReader.cc:57:39: error: invalid conversion from ‘const Exp*’ {aka ‘const Exp_struct*’} to ‘Exp*’ {aka ‘Exp_struct*’} [-fpermissive]
   57 |     Exp* subexp = lg_exp_operand_first(exp);
      |                   ~~~~~~~~~~~~~~~~~~~~^~~~~
      |                                       |
      |                                       const Exp* {aka const Exp_struct*}
/opencog/opencog/nlp/lg-dict/LGDictReader.cc:61:37: error: invalid conversion from ‘const Exp*’ {aka ‘const Exp_struct*’} to ‘Exp*’ {aka ‘Exp_struct*’} [-fpermissive]
   61 |         subexp = lg_exp_operand_next(subexp);
      |                  ~~~~~~~~~~~~~~~~~~~^~~~~~~~
      |                                     |
      |                                     const Exp* {aka const Exp_struct*}

**Comment by linas** [comment]
Closing, fixed in #3668

**Comment by linas** [comment]
Thanks for reporting this. Yesterday, I split out this entire subsystem; I needed it for an unrelated project. Now, the only thing left in the opencog repo are the chatbots.  To build opencog, though, there is one more step: you need to checkout and build https://github.com/opencog/lg-atomese
