### ISSUE TITLE
opencog/nlp/types/atom_types.h: No such file or directory

### ISSUE THREAD

**Issue by piekey1994** [opencog/opencog#3672]
According to the steps described in https://wiki.opencog.org/w/Building_OpenCog_(Hands_On), an error is reported when executing to make -j4.

make -j4
Scanning dependencies of target SCM_CONFIG
Scanning dependencies of target neighbors
Scanning dependencies of target cogita
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_nlp_scm
[  0%] Built target SCM_CONFIG
[  3%] Building CXX object opencog/neighbors/CMakeFiles/neighbors.dir/GetPredicates.cc.o
[  6%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/CogitaConfig.cc.o
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_nlp_sentiment
[  6%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_nlp_sentiment
Scanning dependencies of target nlp_oc_atom_types
[ 10%] Generating opencog types
[ 10%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_nlp_scm
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_eva_behavior
-- Atom type name: ActionLink Action
-- Atom type name: UtteranceNode Utterance
-- Atom type name: DialogNode Dialog
-- Atom type name: FeatureNode Feature
-- Atom type name: FeatureLink Feature
-- Atom type name: DefinedLinguisticConceptNode DefinedLinguisticConcept
-- Atom type name: DefinedLinguisticPredicateNode DefinedLinguisticPredicate
-- Atom type name: DefinedLinguisticRelationshipNode DefinedLinguisticRelationship
-- Atom type name: PrepositionalRelationshipNode PrepositionalRelationship
-- Atom type name: WordSenseNode WordSense
-- Atom type name: WordSenseLink WordSense
-- Atom type name: PartOfSpeechNode PartOfSpeech
-- Atom type name: PartOfSpeechLink PartOfSpeech
-- Atom type name: LemmaNode Lemma
-- Atom type name: LemmaLink Lemma
-- Atom type name: HolonymLink Holonym
[ 13%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/IRC.cc.o
-- Atom type name: TenseNode Tense
-- Atom type name: TenseLink Tense
-- Atom type name: CosenseLink Cosense
-- Atom type name: SemeNode Seme
-- Atom type name: SemanticRelationNode SemanticRelation
-- Atom type name: InterpretationNode Interpretation
-- Atom type name: InterpretationLink Interpretation
-- Atom type name: SpecificEntityNode SpecificEntity
-- Atom type name: SetTypeLink SetType
-- Atom type name: SetSizeLink SetSize
-- Atom type name: MyNotLink MyNot
-- Atom type name: MyOrLink MyOr
[ 17%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/go-irc.cc.o
[ 17%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_eva_behavior
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_eva_model
[ 17%] Built target nlp_oc_atom_types
[ 20%] Building CXX object opencog/neighbors/CMakeFiles/neighbors.dir/Neighbors.cc.o
[ 24%] Building CXX object opencog/nlp/irc/CMakeFiles/cogita.dir/whirr-sockets.cc.o
[ 24%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_eva_model
Scanning dependencies of target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_nlp_oc-types
Scanning dependencies of target nlp-oc-types
[ 27%] Building CXX object opencog/nlp/oc-types/CMakeFiles/nlp-oc-types.dir/NLPOCTypes.cc.o
[ 27%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__mnt_c_Users_xiaos_Desktop_opencog_opencog_opencog_nlp_oc-types
Scanning dependencies of target wsd
[ 31%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o
[ 34%] Linking CXX executable cogita
[ 34%] Built target cogita
[ 37%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeUtils.cc.o
[ 41%] Linking CXX shared library libnlp-oc-types.so
In file included from /mnt/c/Users/xiaos/Desktop/opencog/opencog/opencog/nlp/wsd/EdgeThin.cc:12:
/mnt/c/Users/xiaos/Desktop/opencog/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:63: opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 44%] Built target nlp-oc-types
[ 48%] Cythonizing nlp_oc_types.pyx
In file included from /mnt/c/Users/xiaos/Desktop/opencog/opencog/opencog/nlp/wsd/EdgeUtils.cc:10:
/mnt/c/Users/xiaos/Desktop/opencog/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:76: opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeUtils.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:815: opencog/nlp/wsd/CMakeFiles/wsd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 51%] Linking CXX static library libneighbors.a
Scanning dependencies of target nlp_oc_types_cython
[ 55%] Building CXX object opencog/cython/opencog/CMakeFiles/nlp_oc_types_cython.dir/nlp_oc_types.cpp.o
[ 55%] Built target neighbors
[ 58%] Linking CXX shared library nlp_oc_types.so
[ 58%] Built target nlp_oc_types_cython
make: *** [Makefile:152: all] Error 2

**Comment by linas** [comment]
You need to build and install https://github.com/opencog/lg-atomese first.  I will update the out-of-date wiki page to say this.

**Comment by linas** [comment]
Oh, huh. The octool thing is out of date, that needs to be fixed.

**Comment by linas** [comment]
... and looks like octool does install this dependency. Are you working with the latest octool? Perhaps what you have is out of date?

**Comment by linas** [comment]
If you are using octool, then please open issues at https://github.com/opencog/ocpkg/  which manages this stuff.  I'm hoping @AmeBel is there to assist...
