### ISSUE TITLE
fatal error: opencog/nlp/types/atom_types.h: No such file or directory

### ISSUE THREAD

**Issue by mumar2496** [opencog/opencog#3675]
Hi , i am installing opencog into ubuntu , and i have installed every single dependencies , on last step while running these commands i am getting following error 

Commands:
cd opencog
mkdir build
cd build
cmake ..
make -j6

Error :
In file included from /root/OPENCOG/opencog/opencog/nlp/wsd/EdgeThin.cc:12:
/root/OPENCOG/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:63: opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/root/OPENCOG/opencog/opencog/nlp/wsd/MihalceaEdge.cc:24:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   24 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:102: opencog/nlp/wsd/CMakeFiles/wsd.dir/MihalceaEdge.cc.o] Error 1
In file included from /root/OPENCOG/opencog/opencog/nlp/wsd/EdgeUtils.cc:10:
/root/OPENCOG/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:76: opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeUtils.cc.o] Error 1
In file included from /root/OPENCOG/opencog/opencog/nlp/wsd/MihalceaLabel.cc:21:
/root/OPENCOG/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/root/OPENCOG/opencog/opencog/nlp/wsd/Mihalcea.cc:14:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   14 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:115: opencog/nlp/wsd/CMakeFiles/wsd.dir/MihalceaLabel.cc.o] Error 1
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:89: opencog/nlp/wsd/CMakeFiles/wsd.dir/Mihalcea.cc.o] Error 1
In file included from /root/OPENCOG/opencog/opencog/nlp/wsd/NNAdjust.cc:19:
/root/OPENCOG/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:128: opencog/nlp/wsd/CMakeFiles/wsd.dir/NNAdjust.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:815: opencog/nlp/wsd/CMakeFiles/wsd.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
(dev3.8) root@ubuntu4:~/OPENCOG/opencog/build# octool -cal
/usr/local/bin/octool: option requires an argument -- l
Usage: octool OPTION
 -r Add software repositories
 -d Install base/system build dependencies
 -p Install python build dependencies
 -s Install haskell build dependencies in user space. Don't use sudo
 -i Install build-job artifacts
 -c Install Cogutil
 -a Install AtomSpace
 -f Install from opencog github repo. Pass the name of the repo as an argument
 -o Install OpenCog
 -n Install notebook
 -l {default|java} For installing Link Grammar with java binding '-l java' else '-l default'
 -m Install MOSES
 -g Install Guile 3.0.7
 -b Build source code in git worktree found @ /root/OPENCOG/opencog/build
 -e Build examples in git worktree found @ /root/OPENCOG/opencog/build
 -t Run tests of source code in git worktree found @ /root/OPENCOG/opencog/build
 -j [jobs] override number of auto-detected make jobs
 -w download data for the opencog repo
 -v Verbose output for 'apt-get' commands
 -h This help message
(dev3.8) root@ubuntu4:~/OPENCOG/opencog/build# octool -cal -- l
/usr/local/bin/octool: line 398: message: command not found
(dev3.8) root@ubuntu4:~/OPENCOG/opencog/build# cd build
-bash: cd: build: No such file or directory
(dev3.8) root@ubuntu4:~/OPENCOG/opencog/build# cmake ..
CMake Deprecation Warning at CMakeLists.txt:19 (CMAKE_POLICY):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Build type: Release
-- CogUtil found.
-- AtomSpace found.
-- Could NOT find CogServer (missing: CogServer_DIR)
-- CogServer was not found.
-- Could NOT find AttentionBank (missing: AttentionBank_DIR)
-- AttentionBank was not found. OpenPsi and Ghost will not be built.
-- Could NOT find URE (missing: URE_DIR)
-- URE was not found. OpenPsi will not be built.
-- Could NOT find PLN (missing: PLN_DIR)
-- PLN was not found. Ghost will not be built.
-- Could NOT find LGAtomese (missing: LGAtomese_DIR)
-- LGAtomese was not found. Ghost will not be built.
-- GHC was found.
-- Stack found.
-- The Haskell Tool Stack found.
-- Guile (3.0.7 >= 2.2.2) was found.
-- Python 3.8.10 interpreter found.
-- Python 3.8.10 libraries found.
-- Cython ( 0.29.2 >= 0.24.0) found.
-- Python destination dir found: /root/dev3.8/lib/python3.8/site-packages
-- Python install dir: /root/dev3.8/lib/python3.8/site-packages/opencog
-- nosetests not found: needed for python tests
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing: VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- VALGRIND missing: needed for thread debugging.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Doxygen not found, you won't be able to generate API documentation.

Building for Ubuntu 20.04.3 LTS

The following components will be built:
-----------------------------------------------
   Cython bindings  - Cython (python) bindings.
   Unit tests       - Unit tests.

The following components WILL NOT be built:
-----------------------------------------------
   Doxygen          - Code documentation.
   OpenPsi          - MicroPsi OpenCog implementation.
   Ghost            - Ghost chatbot.
   Haskell codes    - Logic via Lojban.

-- Configuring done
-- Generating done
-- Build files have been written to: /root/OPENCOG/opencog/build
(dev3.8) root@ubuntu4:~/OPENCOG/opencog/build# make -j$(nproc)
[ 10%] Built target neighbors
[ 10%] Built target SCM_CONFIG
[ 27%] Built target cogita
[ 27%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_nlp_scm
[ 27%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_nlp_sentiment
[ 31%] Built target nlp_oc_atom_types
[ 31%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_nlp_oc-types
[ 31%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_eva_model
[ 41%] Built target nlp-oc-types
[ 44%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o
[ 44%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_eva_behavior
[ 55%] Built target nlp_oc_types_cython
[ 58%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeUtils.cc.o
In file included from /root/OPENCOG/opencog/opencog/nlp/wsd/EdgeUtils.cc:10:
/root/OPENCOG/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:76: opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeUtils.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /root/OPENCOG/opencog/opencog/nlp/wsd/EdgeThin.cc:12:
/root/OPENCOG/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:63: opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:815: opencog/nlp/wsd/CMakeFiles/wsd.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
(dev3.8) root@ubuntu4:~/OPENCOG/opencog/build# sudo make install
[  0%] Built target SCM_CONFIG
[ 10%] Built target neighbors
[ 27%] Built target cogita
[ 27%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_nlp_scm
[ 27%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_nlp_sentiment
[ 27%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__root_OPENCOG_opencog_opencog_nlp_oc-types
[ 31%] Built target nlp_oc_atom_types
[ 41%] Built target nlp-oc-types
[ 44%] Building CXX object opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o
In file included from /root/OPENCOG/opencog/opencog/nlp/wsd/EdgeThin.cc:12:
/root/OPENCOG/opencog/opencog/nlp/wsd/ForeachWord.h:23:10: fatal error: opencog/nlp/types/atom_types.h: No such file or directory
   23 | #include <opencog/nlp/types/atom_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make:63: opencog/nlp/wsd/CMakeFiles/wsd.dir/EdgeThin.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:815: opencog/nlp/wsd/CMakeFiles/wsd.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

i also installed lg-atomese library . please help me to fix this issue as soon as possible .

**Comment by ngeiswei** [comment]
It looks like it's a problem with `lg-atomese`, double check if you have it really installed.  Also, I think cmake should have prevented you to compile anything at all but apparently it hasn't.

But may I ask you why you want to compile the `opencog` repo.  Maybe what you want is in another repo.  For instance PLN reasoning is on the `pln` repo, etc.  What do you want to achieve with opencog?

**Comment by mumar2496** [comment]
First of all, thank you very much for your response .

well i want to work on artificial intelligence , i see that framework is
very useful , for right now i am trying to build a conversation application
.

yes i double checked ,i installed lg-atomse  .

Well I am following the guide that you have provided on wiki. I followed
every single step , but on the last step I started getting this error ,
how can I solve this problem ?

Here is the reference link that i am following :
https://wiki.opencog.org/w/Installing_OpenCog_for_Noobs

**Comment by linas** [comment]
The reference that you are following clearly states, at the very top, that it is obsolete. That page is just ... wrong. At the very top, it also says "see here instead", which takes you to more accurate instructions.
