### ISSUE TITLE
Add basic Embodiment + Unity3D integration test

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#401]
This issue involves this repository as well as the https://github.com/opencog/unity3d-opencog-game repository. The following automated tests should be added to the project to allow further development on the embodiment framework:

Add the simplest possible integration test for OpenCog and Unity3D that proves that 
1) the connection was established successfully between Embodiment and Unity3D, and 
2) PerceiveTerrain and PerceiveWorld data were successfully added to the AtomSpace
3) A combo action command was successfully sent to the agent and executed

- [ ] Decide how to structure integration testing alongside our existing cxxtest and Unity test frameworks

- [ ] Define test contents of the Unity world (using TestScene2 or TestScene3)

- [ ] Setup embodiment after building OpenCog
(currently: cd ~/opencog/scripts/embodiment, ./make_distribution - would be better to integrate this into the rest of the cmake process)

- [ ] Run embodiment (currently: cd ~/opencog/build/dist/embodiment, ./start_embodiment.sh - would be better to integrate this into the rest of the cmake process)

- [ ] Run the Unity player. Detect and pass IP address of Embodiment to the Unity player using the command line parameter ROUTER_IP

- [ ] Issue the command to initiate the connection

- [ ] Assert whether the test contents of the Unity world has been created in the AtomSpace as expected by comparing the actual atomspace contents to an atomspace loaded from a reference Scheme atomspace export

- [ ] Issue a combo action command to move the agent

- [ ] Assert that the action was completed

- [ ] Setup the test to run on all the different published players

Related to http://wiki.opencog.org/w/Unity_Integration_Testing

**Comment by linas** [comment]
closing, the embodiment code has been removed and this bug is no longer appplicable
