### ISSUE TITLE
OpenPsi feelings states stuck on 'Waiting for feeling update'

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#488]
Run embodiment and connect to it from Unity using the default TestScene2.

It connects, but the "AGI_Robot's Psi States Panel" gets stuck on "Waiting for feeling update..." and does not display any feelings.

@shujingke @Nemquae can you see if you can reproduce this also?

**Comment by linas** [comment]
Closing, the embodiment code has been removed, this issue no longer applicable.
