### ISSUE TITLE
PLN revisionFormula issue with count

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#587]
While running PLN, I noticed that the count attribute of some truth values was growing very large.

PLN is using a **revisionFormula**:
https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/formulas.py#L483

which is called in **chainers.py** here:
https://github.com/opencog/opencog/blob/master/opencog/python/pln/chainers.py#L726

It sets the new count to be the old count plus the new count:
https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/formulas.py#L479
```n = x.count+y.count```

I think that will cause the count to grow very large.

I suspect this may not be correct.

In the PLN book on page 116, it mentions:
```
We may also heuristically form a count rule
such as n = n1 + n2 – c min(n1, n2), where the parameter c indicates an 
assumption about the level of interdependency between the bases of 
information corresponding to the two premises. The value c=1 denotes 
the assumption that the two sets of evidence are completely redundant; 
the value c=0 denotes the assumption that the two sets of evidence are 
totally distinct. Intermediate values denote intermediate assumptions.
```

in this simple case, my guess is that the sets of evidence are closer to being redundant, which would mean the c value was close to 1, causing the new truth value count to approach the max of either n1 or n2, rather than the sum of both of them.

Furthermore, isn't truth value revision currently implemented as the responsibility of the C++ **TruthValue::merge** class? Shouldn't it be encapsulated once, in one place, whether that's in PLN or in the TruthValue class, rather than doing it two different ways?

@jadeoneill what are your thoughts?

**Comment by linas** [comment]
Closing; this appears to be based on the now-obsolete python-PLN codebase
