### ISSUE TITLE
confidenceToCount 

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#588]
The maximum value that `SimpleTruthValue::confidenceToCount` will return is 4473923584:
https://github.com/opencog/opencog/blob/master/opencog/atomspace/SimpleTruthValue.cc#L110

but `SimpleTruthValue` stores `count` as a double:
https://github.com/opencog/opencog/blob/master/opencog/atomspace/SimpleTruthValue.h#L50
https://github.com/opencog/opencog/blob/186f25f8731e6fd912ceb915057d83997c3d3c8e/opencog/atomspace/TruthValue.h#L53
which can have a very large value.

this seems confusing, because if you tried to convert back and forth between them, you would lose information; for example, if the count were very large, and you used countToConfidence and then confidenceToCount, the number would reduce dramatically. 

How should this actually be implemented?

**Comment by linas** [comment]
closing, stale bug report
