### ISSUE TITLE
PLN modusPonensRule output TruthValue has incorrect strength and confidence

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#598]
Note the confidence value of the output "Anna has cancer": it is **0.001**, even though the EvaluationLink for "Anna smokes" and the ImplicationLink for "If X smokes, then X has cancer" both have strength 1 and confidence 1. That seems to be an issue.

```
-- Output:
(EvaluationLink (stv 1 0.001248)
  (PredicateNode "cancer")
  (ListLink (stv 1 0)
    (ConceptNode "Anna")))

-- using production rule: ModusPonensRule

-- based on this input:
[(ImplicationLink (stv 1 1)
  (EvaluationLink (stv 1 0)
    (PredicateNode "smokes" (stv 1 0))
    (ListLink (stv 1 0)
      (VariableNode "$X" (stv 1 0))))
  (EvaluationLink (stv 1 0)
    (PredicateNode "cancer" (stv 1 0))
    (ListLink (stv 1 0)
      (VariableNode "$X" (stv 1 0)))))
, (EvaluationLink (stv 1 1)
  (PredicateNode "smokes" (stv 1 0))
  (ListLink (stv 1 0)
    (ConceptNode "Anna" (stv 1 0))))]
```

I looked at the modusPonensFormula:
https://github.com/opencog/opencog/blob/b4af7b039b20ceeb78cbe8e81fe40370aafdec6f/opencog/python/pln/rules/formulas.py#L93

it contains the following calculation:

```
NotAB = TruthValue(0.2, 1)
return preciseModusPonensFormula([AB, NotAB, A])
```

There are two problems with the expression ```TruthValue(0.2, 1)```:

1. For strength, what does the arbitrary value "0.2" represent?
2. A count value of 1 represents a confidence of nearly 0; is this supposed to be TruthValue().confidence_to_count(1) instead?

**Comment by linas** [comment]
Closing; I think this concerns the now-obsolete python-PLN codebase.
