### ISSUE TITLE
GeneralEvaluationToMemberRule needs complete output format

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#601]
[GeneralEvaluationToMemberRule](https://github.com/opencog/opencog/blob/master/opencog/python/pln/rules/direct_evaluation_rules.py#L334)

To be able to apply PLN rules effectively on an expression like this:
```
(EvaluationLink
  (PredicateNode "breathe")
  (ListLink
    (ConceptNode "man")
    (ConceptNode "air")))
```

We need a revision to the GeneralEvaluationToMemberRule, so that the output would be:

```
(MemberLink
  (ConceptNode "man")
  (SatisfyingSetLink
    (VariableNode ("$X")
    (EvaluationLink
      (PredicateNode "breathe")
      (ListLink
        (VariableNode "$X")
        (ConceptNode "air"))))))
```

instead of the current output:

```
(MemberLink
  (ConceptNode "man")
  (ConceptNode "SatisfyingSet(breathe _ air:ConceptNode)"))
```

Note that the current output doesn't actually produce the needed atoms; it just encodes the information in a string for the name. All of the atoms need to actually be produced.

Reproduce this issue with the following test case:

https://github.com/opencog/opencog/blob/master/opencog/python/pln/examples/relex2logic/evaluation_to_member_example.py

**Comment by linas** [comment]
closing; I think this concerns the obsolete python-PLN codebase.
