### ISSUE TITLE
Enhance the MemberToEvaluationRule

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#603]
Once the ```GeneralEvaluationToMemberRule``` output is enhanced, we will require a ```SatisfyingSetMembershipRule``` for #601 and #602:

From the message from @bgoertzel [in this thread](https://groups.google.com/d/msg/opencog/Fp3MsPkJAUc/Aomj9eUD93QJ):
```
One then needs a SatisfyingSetMembershipRule (basically the definition
of satisfyingset), which has INPUT

     Member
         $Y
         SatisfyingSet
              $X
              F($X)  // any expression involving $X

and OUTPUT

  F($Y)
```

**Comment by linas** [comment]
closing; I think this issue concerns the now-obsolete python-PLN codebase.
