### ISSUE TITLE
PLN revisionFormula produces truth value strength > 1.0

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#646]
The current implementation of revisionFormula sometimes produces truth value strengths that are greater than 1.0. That is outside of the allowed range of 0.0 to 1.0 by definition.

https://github.com/opencog/opencog/blob/4373456ea49a61c1125104803437bab7f3cb83df/opencog/python/pln/rules/formulas.py#L483

For example, I created a breakpoint to watch the value of the variables at the end of that function call when it was returning a strength of **1.26041666402**:
```
s: 1.26041666402
x.mean: 1.0
y.mean: 1.0
x.count: 4473923584.0
y.count: 3150650368.0
weight_1: 0.739583335978
weight_2: 0.520833328043
```

Current implementation:
```
x, y = tvs
n = x.count + y.count - REVISION_REDUNDANCY_FACTOR * min(x.count, y.count)  
weight_1 = x.count * 1.0 / n
weight_2 = y.count * 1.0 / n
s = (weight_1 * x.mean + weight_2 * y.mean)
return TruthValue(s, n)
```
fyi @jadeoneill

**Comment by linas** [comment]
closing; I think this concerns the now-obsolete python-PLN codebase
