### ISSUE TITLE
Slow performance in ImportanceDiffusionAgent::makeConnectionMatrix

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#666]
I noticed in ```/tmp/cogserver.log``` that ```opencog::ImportanceDiffusionAgent``` was taking tens of minutes to complete one cycle. Meanwhile, all other mind agents, including PLN, were blocked.

In the test, there were approximately 2000 atoms in ```diffusionAtomsMap```.

I then found that [this code segment](https://github.com/opencog/opencog/blob/9e45737a17463c6ef9c0a001593c46e5d713ae47/opencog/dynamics/attention/ImportanceDiffusionAgent.cc#L321) in ```ImportanceDiffusionAgent::makeConnectionMatrix``` (when the condition evaluates to True) takes approximately 0.7 seconds to execute, and was executed hundreds of times:
```
        if (sumProb > maxSpreadPercentage) {
            for (unsigned int i = 0; i < connections.size1(); i++) {
                connections(i,j) = connections(i,j)
                        / (sumProb/maxSpreadPercentage) ;
            }
            sumProb = maxSpreadPercentage;
        }
```

**Comment by linas** [comment]
Can this be closed because ECAN has been redesigned, or is this still an issue?

**Comment by linas** [comment]
Closing, ECAN is in the process of being redesigned.
