### ISSUE TITLE
fundsSTI oscillating to extreme negative and positive values

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#670]
Examples from log:
```[2014-03-31 00:54:16:526] [DEBUG] AVChanged: fundsSTI = -7725007```

```[2014-03-31 00:56:05:071] [DEBUG] AVChanged: fundsSTI = 330854```

```[2014-03-31 01:03:01:849] [DEBUG] AVChanged: fundsSTI = -13761194```

This may be related to negative atom STI values. Atoms are being assigned STI values of negative several thousand, and atoms are also receiving STI adjustments that increase their STI value by positive several thousand.

**Comment by linas** [comment]
Can this be closed because ECAN has been redesigned, or is this still an issue?

**Comment by linas** [comment]
Closing, ECAN is in the process of being redesigned.
