### ISSUE TITLE
AtomSpace::getMaxSTI and getMinSTI returning inaccurate values for attention allocation

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#673]
**ImportanceDiffusionAgent** relies on **AtomSpace::getMaxSTI** and **AtomSpace::getMinSTI**.

**AttentionBank::getMaxSTI** and **AttentionBank::getMinSTI** store the value inside a data structure of type ```recent_val```. Note that the value is **stored** -- it is not calculated when the function is called.

However, when the **AtomSpace::setSTI** function is called and the **AttentionBank::AVChanged** callback runs, it **does not** update this stored value. Therefore, the value is not accurate when obtained by **ImportanceDiffusionAgent**.

Either **AttentionBank::getMinSTI** and **AttentionBank::getMaxSTI** should calculate the value whenever they are called, or the stored value should be updated in the **AttentionBank::AVChanged** callback.

**Comment by linas** [comment]
Can this be closed because ECAN has been redesigned, or is this still an issue?

**Comment by linas** [comment]
Closing, ECAN is in the process of being redesigned.
