### ISSUE TITLE
STI int type for attention allocation causes information loss

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#676]
Using an integer value type for AttentionValue sti_t and lti_t causes strange results to occur in attention allocation when there are highly connected graphs, because for each element in the diffusion matrix, the scaled STI value (of type float, ranging from 0 to 1) is rescaled to the [minSTI, maxSTI] interval, and then cast to an integer (which truncates the value -- [example](https://github.com/opencog/opencog/blob/master/opencog/dynamics/attention/ImportanceDiffusionAgent.cc#L436)). This can cause a lot of STI to be "lost" and can also cause no attention spreading to occur between atoms in cases where a small amount of attention spreading would have occurred.

What if we were to make sti_t and lti_t a float or double type instead?

**Comment by linas** [comment]
Can this be closed because ECAN has been redesigned, or is this still an issue?

**Comment by linas** [comment]
Closing, ECAN is in the process of being redesigned.
