### ISSUE TITLE
PLN Examples cause CogServer to crash

### ISSUE THREAD

**Issue by Alex-van-der-Peet** [opencog/opencog#684]
Running the PLN Examples according to the instructions at the top of 

https://github.com/opencog/opencog/blob/master/tests/python/test_pln/pln_examples.py

Gives:

[2014-04-14 08:56:57:761] [ERROR] Caught signal 11 (Segmentation fault) on thread 140427848054528
	Stack Trace:
	2: /lib/x86_64-linux-gnu/libc.so.6 (x +0x364a0) [0x7fb80404e4a0]

[2014-04-14 08:57:00:817] [INFO] [PythonModule] destructor
Exception KeyError: KeyError(140427848054528,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
[2014-04-14 08:57:00:825] [INFO] Terminating BenchmarkModule.

And causes the CogServer to shut down.

**Comment by inflector** [comment]
After #1292, the above PLN examples no longer cause a crash. The test cases listed by @cosmoharrigan do work:

```
opencog> py-eval from opencog.atomspace import *
opencog> py-eval print "Hello"
Hello
opencog> 
```
The example from the top of the pln_examples.py file, however now reports a runtime error in the Python interpreter:
```
opencog> loadpy pln_examples
No subclasses of opencog.cogserver.MindAgent found.
No subclasses of opencog.cogserver.Request found.
opencog> py
Entering python shell; use ^D or a single . on a line by itself to exit.
py> from pln_examples import *
py> pln_examples = PLNExamples(ATOMSPACE)
py> pln_examples.run_pln_example('../tests/python/test_pln/scm/specific_rules/DeductionRule.scm')
../tests/python/test_pln/scm/specific_rules/DeductionRule.scm
[(InheritanceLink (av 0 0 0) (stv 1.000000 0.000000)
  (ConceptNode "A" (av 0 0 0) (stv 0.800000 0.800000)) ; [58]
  (ConceptNode "C" (av 0 0 0) (stv 0.470000 0.820000)) ; [60]
) ; [63]
]
[(ConceptNode "DeductionRule<InheritanceLink>" (av 0 0 0) (stv 1.000000 0.000000)) ; [68]
]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../tests/python/test_pln/pln_examples.py", line 112, in run_pln_example
    all_rules = AllRules(self.atomspace, chainer)
  File "../tests/python/test_pln/pln_examples.py", line 208, in __init__
    self.member_rules = [GeneralEvaluationToMemberRule(self.chainer),
TypeError: __init__() takes exactly 4 arguments (2 given)
py> 
```
Are pln_examples.py and the sample scheme scripts it references known to work correctly?

**Comment by inflector** [comment]
@Alex-van-der-Peet Do you understand pln_examples.py well enough to know if the above is a real bug or if this bug can be closed?

**Comment by Alex-van-der-Peet** [comment]
Hi Curtis,

I mainly worked around that issue, so I would say no :)

Alex

**Comment by linas** [comment]
Perhaps @misgeatgit or maybe @AmeBel  can tell us if the examples are still relevant, or if they are outdated.  If they are outdated, they should be removed, or at least marked as outdated.

**Comment by AmeBel** [comment]
IntensionalInheritanceLink not defined as a link type so some of the atoms from scm files aren't loaded.
Final result
```
['ModusPonensRule<ImplicationLink>']
Passed 20 out of 22 tests
Failed tests:
../tests/python/test_pln/scm/sumo/living-organism-inversion.scm
../tests/python/test_pln/scm/sumo/railway3.scm
Total time: 896.258343935
```

**Comment by linas** [comment]
```
grep -r INTENS

reasoning/pln/atom_types.script:INTENSIONAL_SIMILARITY_LINK <- UNORDERED_LINK
reasoning/pln/atom_types.script:INTENSIONAL_INHERITANCE_LINK <- ORDERED_LINK
```

**Comment by linas** [comment]
maybe opencog/reasoning/pln/atom-types.scm is not being loaded ?

**Comment by cosmoharrigan** [comment]
Since #1494 was merged due to this version of PLN being deprecated, I believe this issue is obsolete; and the examples remain in the codebase as a template for porting them to the replacement implementation, after which they should be removed from the codebase. @misgeatgit please correct me if that is not the case.
