### ISSUE TITLE
Failed to load Python Helper module while running Unity Embodiement on 64bit Ubuntu

### ISSUE THREAD

**Issue by cfsterpka** [opencog/opencog#700]
I followed the tutorial on setting up Unity Embodiment, and while running it I get the following error message in opencog.log:

[2014-04-23 23:49:48:742] [ERROR] [PythonModule] Failed to load helper python module
	Stack Trace:
	2: PythonModule.cc:170	  opencog::PythonModule::init()
	3: CogServer.cc:541	  opencog::CogServer::loadModule(std::string const&)
	4: CogServer.cc:665	  opencog::CogServer::loadModules(char const**)
	5: OACExecutable.cc:90	main()
	6: libc-start.c:258	__libc_start_main()
	7: ??:0	_start()

I think I've traced this to line 33 within agent_finder_api.h: 
py_module = PyImport_Import(py_name)

It looks like PyImport_Import fails, but I'm by no means expert at this.

In addition to the above error, the following message is produced on the command line: 
ImportError: libopencog-atomspace-python.so: cannot open shared object file: No such file or directory

I haven't noticed either of these error messages happening on my laptop which is currently running 32bit Ubuntu.

Best and much appreciation,

-Chris

**Comment by inflector** [comment]
@cfsterpka It's been more almost a year with no further comments. Is this problem still open for you? If not, would you please close this issue. I'm working through all the issues marked with Python in an effort to fix any Python-specific issues.

**Comment by cosmoharrigan** [comment]
Closing. Please open a new/updated issue for anything else.
