### ISSUE TITLE
Remove repository cloning from ocpkg script

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#720]
[ocpkg](https://github.com/opencog/opencog/blob/master/scripts/ocpkg) puts the repository root here:
```
~/opencog/src
```

and the build directory here:
```
~/opencog/build
```

but this doesn't work properly right now, as @williampma and @sebastianruder have encountered this week when using the ocpkg script to obtain the repository. It causes some files to not be found when running OpenCog.

What does work properly right now is putting the repository root here:
```
~/opencog
```
and the build directory here:
```
~/opencog/build
```

so that you can run:
```
cd ~/opencog/build
cmake ..
make
```

Can we just remove the functionality that clones the repository from the ocpkg script, since the ocpkg script is already part of the repository? Then users could just be instructed to do something like this:

-------------------
**Installing OpenCog on Ubuntu**
```
cd ~
git clone https://github.com/opencog/opencog.git
./opencog/scripts/install-dependencies-trusty
cd opencog
mkdir build
cd build
cmake ..
make
make test
```
-------------------
which is already essentially what is recommended in the project README.

@githart what do you think?

**Comment by linas** [comment]
Closing .. this code has been moved to opencog/ocpkg and I've cloned to issue opencog/ocpkg#54
