### ISSUE TITLE
Incorrect input set occurs during deduction on output of MemberToInheritanceRule

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#733]
This issue is in reference to #637.

Running the example in #732 produces:

Output # 8:
https://gist.github.com/cosmoharrigan/acd36f94e451dd1b81b7#file-gistfile1-scm-L337

which includes a duplicate result of output # 7:
https://gist.github.com/cosmoharrigan/acd36f94e451dd1b81b7#file-gistfile1-scm-L288

There is one strange difference in the input sets. 

Here, the SatisfyingSetLink that is embedded in the InheritanceLink (input # 2) is identical to the SatisfyingSetLink listed by itself (input # 4):
https://gist.github.com/cosmoharrigan/acd36f94e451dd1b81b7#file-gistfile1-scm-L306

However, here, the SatisfyingSetLink listed by itself (input # 4) is different than the SatisfyingSetLink that is embedded in the InheritanceLink (input # 2):
https://gist.github.com/cosmoharrigan/acd36f94e451dd1b81b7#file-gistfile1-scm-L355

That seems incorrect -- those two SatisfyingSetLinks should definitely be identical based on the definition of deduction. So, this would need to be debugged.

**Comment by linas** [comment]
closig as stale, PLN has been completely redesigned since this bug was first reported.
