### ISSUE TITLE
Invalid SatisfyingSetLink syntax produced as output of deduction using output of MemberToInheritanceRule 

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#734]
This issue is in reference to #637 and may have a related cause as issue #733.

Running the example in #732 produces:

Output # 9:
https://gist.github.com/cosmoharrigan/acd36f94e451dd1b81b7#file-gistfile1-scm-L386

this is incorrect (for two reasons: first, the reason already described in #733 -- the SatisfyingSetLink in input # 2 is not the same as the SatisfyingSetLink in input # 4)

Second, the DeductionRule produces an output that attempts to bind a constant inside a SatisfyingSetLink, which is an invalid syntax, here:
https://gist.github.com/cosmoharrigan/acd36f94e451dd1b81b7#file-gistfile1-scm-L391
```
(InheritanceLink (stv 1.000000 1.000000)
  (ConceptNode "Socrates") ; [1]
  (SatisfyingSetLink (stv 1.000000 0.000000)
    (ConceptNode "man") ; [2]
    (EvaluationLink (stv 1.000000 0.000000)
      (PredicateNode "breathe") ; [5]
      (ListLink (stv 1.000000 0.000000)
        (ConceptNode "man") ; [2]
        (VariableNode "$X0") ; [91]
      ) ; [101]
    ) ; [102]
  ) ; [1492]
) ; [1493]
```
This needs to be debugged.

**Comment by linas** [comment]
closing, I think this is dead, the PLN infrastructure has been completely redesigned.
