### ISSUE TITLE
PLN AtomSpaceBasedInferenceHistory uses incorrect ExecutionLink syntax

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#758]
The syntax of an ExecutionLink used to record a schema application as documented [here](http://wiki.opencog.org/w/ExecutionLink) states that the correct syntax is:
```
ExecutionLink
    schema
    ListLink
        input1
        input2
        ...
    output
```
but this was implemented using the syntax
```
ExecutionLink
    schema
    ListLink
        ListLink
            input1
            input2
            ...
        ListLink
            output
```
which doesn't match the defined syntax.

The areas that are affected are:
https://github.com/opencog/opencog/blob/master/opencog/python/pln/chainers.py#L349
https://github.com/opencog/opencog/blob/master/opencog/python/pln/chainers.py#L392
and the associated documentation in
https://github.com/opencog/opencog/blob/master/opencog/python/pln/README.md#inference-history

**Comment by linas** [comment]
closing this is a bug referring to code that has been removed.
