### ISSUE TITLE
ImportanceUpdatingAgent::adjustSTIFunds taxes atoms regardless of wealth

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#869]
[ImportanceUpdatingAgent::adjustSTIFunds](https://github.com/opencog/opencog/blob/03cdc0bb2f59b06bae8450548947621460b54770/opencog/dynamics/attention/ImportanceUpdatingAgent.cc#L332) is called if atomspace STI funds go out of bounds.

The current code then proceeds to tax atoms equally, regardless of their wealth. It even taxes atoms with no wealth. For example:

```
Atom 474 STI 0. Tax 106. After tax -106.
Atom 524 STI 0. Tax 106. After tax -106.
Atom 477 STI 55. Tax 106. After tax -51.
Atom 525 STI 0. Tax 106. After tax -106.
```

This causes atoms to have negative STI, which would be nice to avoid, so that it is easier to reason about the dynamics of the system.

@bgoertzel is that the behavior that you had in mind, or would it be okay to prevent an atom's STI from going below 0 as a result of taxation?

Also, rather than applying an equal tax across all atoms, wouldn't it make sense to apply a tax to atoms in proportion to their STI amount compared to the total STI amount?

**Comment by linas** [comment]
Is this still an issue, or can this be closed because ECAN has been redesigned?

**Comment by linas** [comment]
Closing, ECAN is in the process of being redesigned.
